### ISSUE TITLE
Support for Postgres ?| operator (do any of these array strings exist as top-level keys)

### ISSUE THREAD

**Issue by soanvig** [kysely-org/kysely#1002]
Postgres supports `?|` operator https://www.postgresql.org/docs/9.5/functions-json.html
however Kysely does not:

```
invalid operator "?|"
      at parseOperator (../node_modules/.pnpm/kysely@0.27.3/node_modules/kysely/dist/cjs/parser/binary-operation-parser.js:69:11)
```

is that intended thing to not support, or is it an overlook?

**Comment by koskimas** [comment]
Just an oversight. We can add it
