### ISSUE TITLE
Failures during migration do not create errors

### ISSUE THREAD

**Issue by Sleepful** [kysely-org/kysely#1008]
Simple example:

Adding a new column with `(col) => col.setNotNull(),` to a table that already has rows will fail, because the existing rows will have null values. This is OK.

However, the failure does not create any kind of error, it just fails silently, which makes it difficult to debug.

My migrations are ran with `await migrator.migrateToLatest();`

**Comment by koskimas** [comment]
Tried it. Worked for me. Also, we have tests.

**Comment by Sleepful** [comment]
@koskimas What should the error look like on the terminal? 

I am running on Deno with PostgresJS driver, I noticed even failure to connect to DB was not creating an error with a stack trace, it was just terminating the process.

This is without putting try/catch around the code. 

I don't see tests that cover this scenario though.

**Comment by igalklebanov** [comment]
Hey 👋 

By design.
https://github.com/kysely-org/kysely/blob/master/src/migration/migrator.ts#L241-L257

Check the result object for `error` prop.

**Comment by Sleepful** [comment]
@igalklebanov thank you! I must have missed this bit.

I was just going to comment how the error can be caught inside the migration file itself but not outside. 

Got it!

**Comment by igalklebanov** [comment]
Btw, we have a new CLI in the works. https://github.com/kysely-org/kysely-ctl

Try it out.

**Comment by koskimas** [comment]
> I must have missed this bit.

It's the first thing we mention in the docs. You can also just hover over the function to see the docs.

<img width="847" alt="Screenshot 2024-05-27 at 12 53 34" src="https://github.com/kysely-org/kysely/assets/846508/2d752697-cef2-481f-84c3-f98b9dfbdff9">

**Comment by Sleepful** [comment]
Yeah it's my bad guys, sorry 😅 
In part because I was rewriting the code to work well with Deno so I was a little distracted.
I want to push a PR for docs with my Deno code soon to make it up to you both.
