### ISSUE TITLE
Multi-statement queries causes wrong result interpretation

### ISSUE THREAD

**Issue by matis-dk** [kysely-org/kysely#1014]
Executing a multi-statement raw sql query towards PostgreSQL, doesn't seem to be supported currently.  For example:

```
const result = await sql.raw(`
    BEGIN;
    
    DO $$
    BEGIN
      PERFORM "hello_world"();
    END $$;
    
    SELECT current_user;
    
    COMMIT; 
  `)
  .execute(client);
```

The issue seems to be that the [`executeQuery`](https://github.com/kysely-org/kysely/blob/f4f26cb1117195f1fff21b323782234d63c58723/src/dialect/postgres/postgres-driver.ts#L105) inside the `postgres-driver` always expects an object return type from the `this.#client.query`, when in fact, it could be either an object, or a list of objects. This causes the return evaluation to swallow the result by returning an empty array [```return { rows: result.rows ?? []};``` ](https://github.com/kysely-org/kysely/blob/f4f26cb1117195f1fff21b323782234d63c58723/src/dialect/postgres/postgres-driver.ts#L126).

This behavior is [documented here ](https://github.com/brianc/node-postgres/blob/e25428c8dceb86eb4277af90155295fd0188abce/packages/pg/lib/query.js#L58) inside the `pg` package, but unfortunately, the ts type signature for `pg`, seems to get this wrong as well.

I'm unsure about which type of solution you would prefer moving forward - and which implication it might have. Currently, I'm patching this package with `Array.isArray` check of the result, but this might not be doable as a whole.

**Comment by koskimas** [comment]
Unfortunately we can't support this. We'd need to change the output for every query since we can't detect compile-time if the query would return an array or multiple arrays. Adding a separate method is not an option either since we'd need to modify the driver interface, which is used by all third party dialects.

**Comment by matis-dk** [comment]
Would expanding [`QueryResult` ](https://github.com/kysely-org/kysely/blob/f4f26cb1117195f1fff21b323782234d63c58723/src/driver/database-connection.ts#L43) type be an option? Exposing the raw response from the `pg` client inside the `QueryResult` payload. 

This comment ` The rows returned by the query. This is always defined and is empty if the query returned no rows.` for the `rows` property is misleading, because the response from `pg` actually have rows.

**Comment by matis-dk** [comment]
Alternatively, exposing an optional selector function, would give the developer an option to pick the correct Result response inside the list. For the query defined above, the Result response would look something like this 

```
Result {
    command: 'BEGIN',
    rowCount: null,
    oid: null,
    rows: [],
    fields: [],
    _parsers: undefined,
    _types: TypeOverrides { _types: [Object], text: {}, binary: {} },
    RowCtor: null,
    rowAsArray: false,
    _prebuiltEmptyResultObject: null
  },
  Result {
    command: 'DO',
    rowCount: null,
    oid: null,
    rows: [],
    fields: [],
    _parsers: undefined,
    _types: undefined,
    RowCtor: null,
    rowAsArray: false,
    _prebuiltEmptyResultObject: null
  },
  Result {
    command: 'SELECT',
    rowCount: 1,
    oid: null,
    rows: [ [Object] ],
    fields: [ [Field] ],
    _parsers: [ [Function: noParse] ],
    _types: undefined,
    RowCtor: null,
    rowAsArray: false,
    _prebuiltEmptyResultObject: { current_user: null }
  },
  Result {
    command: 'COMMIT',
    rowCount: null,
    oid: null,
    rows: [],
    fields: [],
    _parsers: undefined,
    _types: undefined,
    RowCtor: null,
    rowAsArray: false,
    _prebuiltEmptyResultObject: null
  }
  ```
