### ISSUE TITLE
Kysely mssql dialect support for bun improved

### ISSUE THREAD

**Issue by Singha360** [kysely-org/kysely#1015]
Hey I am writing this on my Mac machine therefore I can not test if this works now or not since they seem to have [fixed the issue of connecting to mssql using the Bun runtime](https://github.com/oven-sh/bun/issues/10215#issuecomment-2125567337)

If someone can test this in the next few days to confirm this, it would be awesome but otherwise I can test it when I'll be free and have my hands on a Windows machine to confirm if there's any issue.

[The docs should also reflect the status of this issue if it changes](https://kysely.dev/docs/getting-started?dialect=mssql&package-manager=bun#dialects)

**Comment by igalklebanov** [comment]
Hey 👋 

Thanks for the heads up. Tested locally, seems to work now.
