### ISSUE TITLE
SELECT ARRAY function?

### ISSUE THREAD

**Issue by boehs** [kysely-org/kysely#1016]
Hello! These two should be functionally equivalent:

```sql
SELECT ARRAY(SELECT id FROM mytable)
```

Or:

```sql
SELECT array_agg(id) FROM mytable
```

The former should be more performant, but as far as I can tell its not implemented. I have a query like

```ts
      .select((e) =>
        e
          .selectFrom("entitytags")
          .select("tag")
          .whereRef("user_entity", "=", "userentities.id")
          .as("tags")
      )
```

but as far as I can tell I can't wrap this (or I could use the sql template string but that'd be no fun)!

```js
    .select((e) =>
      sql<string[]>`array(${e
        .selectFrom("entitytags")
        .select("tag")
        .whereRef("user_entity", "=", "userentities.id")})`.as("tags")
    );
```

**Comment by koskimas** [comment]
This seems to work https://kyse.link/we2xz

What's the issue?

**Comment by koskimas** [comment]
You can create a helper function like this so that you don't need to explicitly give the output type: https://kyse.link/Rip3y
