### ISSUE TITLE
Select columns as NULL or as placeholder

### ISSUE THREAD

**Issue by MaxosHadj** [kysely-org/kysely#1020]
Trying to do the following:

`SELECT
 value_a,
 value_b,
 null AS c
FROM table`

or 

`SELECT
 value_a,
 value_b,
 'myValue' AS c
FROM table`

I tried to use raw SQL without success
![image](https://github.com/kysely-org/kysely/assets/82805662/de8c27f3-c3ff-4487-b952-b6a895a0cb06)

Any idea?

**Comment by igalklebanov** [comment]
Hey 👋 

`sql` template tag has the `lit` method for this use-case.

```ts
import { sql } from "kysely";

await db
  .selectFrom("table")
  .select([
    "value_a",
    "value_b",
    sql.lit(null).as("c"),
    sql.lit("myValue").as("d"),
  ])
  .execute();
```
https://kyse.link/qjh24
