### ISSUE TITLE
Pronunciation help is wrong

### ISSUE THREAD

**Issue by borbware** [kysely-org/kysely#1027]
It's not key-seh-lee (..."kiiselii"? Kiisseli?), it's more closer to kew-seh-lew.

Source: I'm Finnish

Yes I know this is very important lmao.

**Comment by koskimas** [comment]
Yes I know. I'm Finnish. But there's no way to get people pronounce it the correct way. We just need to have some way for people to refer to this thing. Finnish people (the only ones with an issue with this) can pronounce it correctly.

**Comment by thelinuxlich** [comment]
Let's forget this issue exists and amuse ourselves with a Finnish game called Noita

**Comment by borbware** [comment]
my disappointment is immeasurable and my day is ruined 😔
