### ISSUE TITLE
 QueryCompilerError: Could not serialize value causes Kysely instance to fail later

### ISSUE THREAD

**Issue by mdnorman** [kysely-org/kysely#1028]
The following code will cause an error and then break the DB connection for further updates.

```typescript
const DB = new Kysely<Database>(...);

const someIds = [undefined]; // oops!
const otherId = 1234;

try {
  await db.selectFrom("a").where("id", "in", someIds).execute(),
} catch(e) {
  // e is "QueryCompilerError: Could not serialize value" because of the undefined

  await db.updateTable("b").where("id", "=", otherId).set({ status: "error" }).execute();
  // line above throws another error because the generated SQL is 
  // "(update "b" set "status" = :0 where "id" = :1)"
  // notice the parentheses around the generated SQL
}
```

I confirmed that restarting the service and running the update call works fine because the generated SQL does _not_ have the surrounding parentheses. I confirmed the presence of the parentheses with `query.compile().sql`.

**Comment by koskimas** [comment]
Ouch, thanks for opening an issue! We don't clear the `OperationNodeVisitor.nodeStack` at the beginning of compilation. The stack is left behind from that interrupted compilation.

But that query wouldn't pass typescript checks if you used types. Now the array is `any[]` and typescript checks are bypassed.

https://kyse.link/z6OPT

**Comment by mdnorman** [comment]
Yep, you're absolutely right about the types. This was a simple repro, but in the real case, the undefined sneakily got in there from a much earlier part of the pipeline.
