### ISSUE TITLE
Feature request: Feedback possibility during Migration

### ISSUE THREAD

**Issue by jbouduin** [kysely-org/kysely#1030]
In my (Electron) App, I am Showing a splash screen at startup. During this startup, migrations are performed.
While executing, I can not show any progress to the user in case the migrations take some time as `migrator.migrateToLatest()` is not providing me any feedback.

It would be nice if:

- there was a possibility to pass a callback to migrateToLatest, which could be as simple as `(name: string) => void`
- there was a possibility to ask the migrator for the number of migrations to be executed, before calling `migrateToLatest()`

thx for considering my proposals
Johan

**Comment by koskimas** [comment]
You can get the executed and new migrations using [migrator.getMigrations()](https://kysely-org.github.io/kysely-apidoc/classes/Migrator.html#getMigrations). Then you can migrate up/down one migration at a time using [migrator.migrateUp()](https://kysely-org.github.io/kysely-apidoc/classes/Migrator.html#migrateUp) or [migrator.migrateDown()](https://kysely-org.github.io/kysely-apidoc/classes/Migrator.html#migrateDown).
