### ISSUE TITLE
How to handle "empty" column selections?

### ISSUE THREAD

**Issue by waji-io** [kysely-org/kysely#1038]
Hi,

Is there a way to make use the "returning" clause in a conditional way?

*Use Case 1: List of columns provided*  
Use *returning* together with list of columns to return and all works.

```ts
    const result = await this.db
      .withSchema(DB_SCHEMA)
      .insertInto(TableNameEnum.USER)
      .values(body.payload)
      .returning(['_id'])
      .executeTakeFirst();
```

*Use Case 2a: List of columns NOT provided*  
Provide empty array. I tried this but this didn't work. 
Maybe this could be a useful feature to support: If no columns are provided, completely ignore *returning*.

```ts
    const result = await this.db
      .withSchema(DB_SCHEMA)
      .insertInto(TableNameEnum.USER)
      .values(body.payload)
      .returning([])
      .executeTakeFirst();
```

*Use Case 2b: List of columns NOT provided*  
Omit *returning*. Here I am not sure how include or exclude *returning* within the query builder statement.

```ts
    const result = await this.db
      .withSchema(DB_SCHEMA)
      .insertInto(TableNameEnum.USER)
      .values(body.payload)
      .executeTakeFirst();
```

**Comment by igalklebanov** [comment]
Hey 👋 

Yes. See [$if](https://kysely-org.github.io/kysely-apidoc/classes/InsertQueryBuilder.html#_if).
