### ISSUE TITLE
The type of `eb` in `selectFrom(eb => ...)` is wrong 

### ISSUE THREAD

**Issue by koskimas** [kysely-org/kysely#1039]
Reprodution https://kyse.link/HqeCE

I think `eb` should be `ExpressionBuilder<Database, never>` but instead it's `ExpressionBuilder<Database, keyof Database>`.

I might be brainfarting here but `ExpressionBuilder<Database, keyof Database>` is saying "we've joined every table in the database to this query. Go nuts!".

The reproduction fails because there are two tables with different `id` type "joined" to the query.

**Comment by jdpt0** [comment]
Hi @koskimas, I've just tried upgrading to 0.27.4, and this update seems to have broken the [`jsonObjectFrom` functionality documented in the documentation](https://kysely.dev/docs/examples/select/nested-object)

Can you confirm?

**Comment by igalklebanov** [comment]
Hey 👋 

> I've just tried upgrading to 0.27.4, and this update seems to have broken the [jsonObjectFrom functionality documented in the documentation](https://kysely.dev/docs/examples/select/nested-object)

In what ways? what are you seeing?

**Comment by jdpt0** [comment]
My apologies, false alarm. On closer inspection, it was just a query that was using an `ExpressionBuilder` out of its proper scope, which has been found because of this update.
