### ISSUE TITLE
fn.agg doesn't type-check

### ISSUE THREAD

**Issue by mb21** [kysely-org/kysely#1046]
The following query ([playground Link](https://old.kyse.link/?p=b&i=haFkqHBvc3RncmVzoXamMC4yNy4yoXPaAaJpbXBvcnQgeyBHZW5lcmF0ZWQgfSBmcm9tICdreXNlbHknCgpkZWNsYXJlIGdsb2JhbCB7CiAgaW50ZXJmYWNlIERCIHsKICAgIHBlcnNvbjogUGVyc29uVGFibGUKICAgIHBldDogUGV0VGFibGUKICB9CgogIGludGVyZmFjZSBQZXJzb25UYWJsZSB7CiAgICBpZDogR2VuZXJhdGVkPHN0cmluZz4KICAgIGZpcnN0X25hbWU6IHN0cmluZwogICAgbGFzdF9uYW1lOiBzdHJpbmcgfCBudWxsCiAgICBjcmVhdGVkX2F0OiBHZW5lcmF0ZWQ8RGF0ZT4KICAgIGFnZTogbnVtYmVyCiAgfQoKICBpbnRlcmZhY2UgUGV0VGFibGUgewogICAgaWQ6IEdlbmVyYXRlZDxzdHJpbmc-CiAgICBuYW1lOiBzdHJpbmcKICAgIG93bmVyX2lkOiBzdHJpbmcKICAgIHNwZWNpZXM6ICdjYXQnIHwgJ2RvZycKICAgIGlzX2Zhdm9yaXRlOiBib29sZWFuCiAgfQp9oXHZkmNvbnN0IHJlc3VsdCA9IGF3YWl0IGRiLnNlbGVjdEZyb20oJ3BlcnNvbicpCiAgICAgLnNlbGVjdCgoeyBmbiB9KSA9PiBmbi5hZ2c8c3RyaW5nW10-KCdhcnJheV9hZ2cnLCAnZmlyc3RfbmFtZScpLmFzKCdpbWFnZU5hbWVzJykpCiAgICAuZXhlY3V0ZSgpoWPD)):

```ts
const result = await db.selectFrom('person')
  .select(({ fn }) => fn.agg<string[]>('array_agg', 'first_name').as('imageNames'))
  .execute()
```

executes fine in PostgreSQL, but TypeScript complains on `'first_name'` with:

```
Argument of type 'string' is not assignable to parameter of type 'readonly ReferenceExpression<DB, "person">[]'.
```

Not exactly sure whether I'm doing something wrong or it's just a bug?

**Comment by igalklebanov** [comment]
Hey 👋 

The 2nd argument is expected to be an array.

```ts
const result = await db.selectFrom('person')
  .select(({ fn }) => fn.agg<string[]>('array_agg', ['first_name']).as('imageNames'))
  .execute()
```

**Comment by mb21** [comment]
Thanks for the quick reply! Ah okay, confusing that the generated JavaScript actually still executes correctly.

Now, in my actual code the example is a bit more contrived. Here's a minimal example that still doesn't type-check even with an array. [Playground Link](https://old.kyse.link/?p=b&i=haFkqHBvc3RncmVzoXamMC4yNy4yoXPaAaJpbXBvcnQgeyBHZW5lcmF0ZWQgfSBmcm9tICdreXNlbHknCgpkZWNsYXJlIGdsb2JhbCB7CiAgaW50ZXJmYWNlIERCIHsKICAgIHBlcnNvbjogUGVyc29uVGFibGUKICAgIHBldDogUGV0VGFibGUKICB9CgogIGludGVyZmFjZSBQZXJzb25UYWJsZSB7CiAgICBpZDogR2VuZXJhdGVkPHN0cmluZz4KICAgIGZpcnN0X25hbWU6IHN0cmluZwogICAgbGFzdF9uYW1lOiBzdHJpbmcgfCBudWxsCiAgICBjcmVhdGVkX2F0OiBHZW5lcmF0ZWQ8RGF0ZT4KICAgIGFnZTogbnVtYmVyCiAgfQoKICBpbnRlcmZhY2UgUGV0VGFibGUgewogICAgaWQ6IEdlbmVyYXRlZDxzdHJpbmc-CiAgICBuYW1lOiBzdHJpbmcKICAgIG93bmVyX2lkOiBzdHJpbmcKICAgIHNwZWNpZXM6ICdjYXQnIHwgJ2RvZycKICAgIGlzX2Zhdm9yaXRlOiBib29sZWFuCiAgfQp9oXHaATdjb25zdCByZXN1bHQgPSBhd2FpdCBkYgogICAgLnNlbGVjdEZyb20oJ3BlcnNvbicpCiAgICAubGVmdEpvaW4oCiAgICAgICh7IGViLCBmbiB9KSA9PiBlYi5zZWxlY3RGcm9tKCdwZXQnKQogICAgICAgIC5zZWxlY3QoWydvd25lcl9pZCcsIGZuLmFnZzxzdHJpbmdbXT4oJ2FycmF5X2FnZycsIFsnbmFtZSddKS5hcygnbmFtZXMnKV0pCiAgICAgICAgLmdyb3VwQnkoJ293bmVyX2lkJykKICAgICAgICAuYXMoJ3BldHMnKSwKICAgICAgam9pbiA9PiBqb2luLm9uUmVmKCdpZCcsICc9JywgJ293bmVyX2lkJyksCiAgICApCiAgICAuZXhlY3V0ZSgpCqFjww==)

```ts
const result = await db
    .selectFrom('person')
    .leftJoin(
      ({ eb, fn }) => eb.selectFrom('pet')
        .select(['owner_id', fn.agg<string[]>('array_agg', ['name']).as('names')])
        .groupBy('owner_id')
        .as('pets'),
      join => join.onRef('id', '=', 'owner_id'),
    )
    .execute()
```

**Comment by igalklebanov** [comment]
The `fn` you're using doesn't have "pet" in context.

```ts
const result = await db
  .selectFrom("person")
  .leftJoin(
    (x) =>
      x
        .selectFrom("pet")
        .select([
          "owner_id",
          (x2) => x2.fn.agg<string[]>("array_agg", ["name"]).as("names"),
        ])
        .groupBy("owner_id")
        .as("pets"),
    (join) => join.onRef("id", "=", "owner_id"),
  )
  .execute()
```
https://old.kyse.link/?p=s&i=2lDvcgcbos21HqwleQwJ

**Comment by mb21** [comment]
Thanks a lot, that did the trick!

Not sure whether you've considered this approach already: since the TypeScript errors often get unwieldly, perhaps it would make sense to additionally have hints emitted during runtime? Like here: "Got string, expected array in [stack trace]"

**Comment by igalklebanov** [comment]
Adding anything excessive at runtime would slow everyone down. 

We could try adding `KyselyError<'blah blah blah'>` in more places to try and make errors friendlier.

**Comment by mb21** [comment]
[KyselyTypeError](https://github.com/kysely-org/kysely/blob/master/src/util/type-error.ts) ? Ah yes, that sounds like a good idea.
