### ISSUE TITLE
"Extending kysely" example doesn't compile 

### ISSUE THREAD

**Issue by Andrey36652** [kysely-org/kysely#1052]
Example https://kysely.dev/docs/recipes/extending-kysely#a-more-complex-example does not compile with error
```
src/db/kysely-helpers.ts:30:5 - error TS2322: Type 'AliasedRawBuilder<unknown, A>' is not assignable to type 'AliasedRawBuilder<R, A>'.
  Type 'unknown' is not assignable to type 'R'.
    'R' could be instantiated with an arbitrary type which could be unrelated to 'unknown'.

30     return sql`(values ${values})`.as<A>(aliasSql)
```
kysely 0.27.3
typescript 5.4.4
ts-node 10.9.2

This error can be fixed by replacing string ```return sql`(values ${values})`.as<A>(aliasSql)``` with ```return sql`(values ${values})`.as<A>(aliasSql) as as AliasedRawBuilder<R, A>```

**Comment by igalklebanov** [comment]
Hey 👋 

This is resolved with `sql<R>` instead of `sql`.

**Comment by Andrey36652** [comment]
@igalklebanov can docs be fixed?

**Comment by igalklebanov** [comment]
Yeah, should be resolved now.
