### ISSUE TITLE
Unsupported MySQL DataTypes

### ISSUE THREAD

**Issue by rentalhost** [kysely-org/kysely#1053]
Hello, I noticed that some DataType types are currently not supported for MySQL.

- MEDIUMINT (something like "int3")
- BIT(x)
- ENUM / SET
- TINYTEXT / TINYBLOB
- MEDIUMTEXT / MEDIUMBLOB
- LONGTEXT / LONGBLOB
- INET4 / INET6
- YEAR
- Spatials, in general:
  - POINT / MULTIPOINT
  - LINESTRING / MULTILINESTRING
  - POLYGON / MULTIPOLYGON
  - GEOMETRY / GEOMETRYCOLLECTION

There is also no way to `addColumn()` with a custom type. Is there any reason for this? I understand that Kysely works for multiple DBs, but customizing the type would be interesting.

**Comment by rentalhost** [comment]
Alright, I just found out about `sql ...`, which allows customization. However, it still remains to know why this is not a part of Kysely directly (at least `int3`, for example).

**Comment by koskimas** [comment]
> it still remains to know why this is not a part of Kysely directly 

Just an oversight. Your blaming attitude does not make me want to fix this for you. In fact, I would've fixed it right away if you asked nicely. But now, fix it yourself or GTFO.
