### ISSUE TITLE
Construct standalone SQL Snippets

### ISSUE THREAD

**Issue by waji-io** [kysely-org/kysely#1054]
Hi,

I am trying to build small SQL snippets/fragments following one of the example from the [docs](https://kysely-org.github.io/kysely-apidoc/functions/sql-1.html) but I seem to be missing something.

**Example**
```ts
const example = sql`concat(first_name, ' ', last_name)`;

console.log(JSON.stringify(example));
```

The resulting output is an empty object...

What I am trying to achieve is to dynamically generate a list of SQL fragments based on some input and apply them later to the actual query.

**Comment by koskimas** [comment]
It's not an empty object. It's an instance of a class with with private properties. Stringifying it will not show anything but an empty object.
