### ISSUE TITLE
<statement expected> got .... instead when using sql function

### ISSUE THREAD

**Issue by Mathieu-R** [kysely-org/kysely#1066]
Hi !

Using Kysely `0.27.3` , I have the following error when using the `sql` function:

```
<statement expected> got .... instead
```
with ... is the string I pass between the backticks to the sql function.

For example, running a migration and trying to set a **default value** for a `created_at` column:

```ts
await db.schema
    .createTable('users')
    // other columns definition
    // ...
    .addColumn('created_at', 'timestamp', (col) => col.notNull().defaultTo(sql`CURRENT_TIMESTAMP`))
    .execute()
```

The error is then `<statement expected> got 'CURRENT_TIMESTAMP' instead`.

Note that despite my editor crying this error, the migration is still running correctly though.

**Comment by KazimirPodolski** [comment]
@koskimas why is this closed? I'm experiencing the same issue with the latest version.

**Comment by KazimirPodolski** [comment]
Hmmm strangely enough I **cannot** repro it in the playground: https://kyse.link/pOy91, while it complains in my own code:

<img width="1617" height="568" alt="Image" src="https://github.com/user-attachments/assets/803b5f3f-c507-4618-95e6-8c326fad0d5f" />
