### ISSUE TITLE
Idea: query.toString() could be an alias for query.compile()

### ISSUE THREAD

**Issue by mb21** [kysely-org/kysely#1071]
I often want to look at the sql generated for a certain query and I keep forgetting that the way to do that is to call `query.compile()` and then I try to find the docs on that for like two minutes. Maybe I'm the only one, but for me it would be great if I could just do `console.log(query)` to debug things.

**Comment by koskimas** [comment]
`toString` should always return a string.

**Comment by mb21** [comment]
Ah right, in that case `query.compile().toString()`, which is what I'm usually after when quickly debugging something. Hey, it could even be pretty-printed!
