### ISSUE TITLE
Add range column types to the schema api

### ISSUE THREAD

**Issue by kansson** [kysely-org/kysely#1072]
https://www.postgresql.org/docs/current/rangetypes.html

**Comment by kansson** [comment]
Hi! Was this implemented? Can't see anything in the commit history.

**Comment by koskimas** [comment]
No it wasn't.

**Comment by koskimas** [comment]
If you want other people to do free stuff for you, vomiting a command is probably not the way to get that done.

**Comment by kansson** [comment]
> If you want other people to do free stuff for you, vomiting a command is probably not the way to get that done.

That was not my intention, sorry if it came off that way. This issue was intended to track the addition of range column types to the schema api.

**Comment by kansson** [comment]
Can this issue be reopended or should I create a new one?
