### ISSUE TITLE
mysql2 `createPoolCluster` support

### ISSUE THREAD

**Issue by JayJamieson** [kysely-org/kysely#1075]
Hi team,

Have been using your library in production and finding really easy to work with. Right now I'm using `createPoool` and creating two instance for Primary and Replica database instances to separate read and write workloads.

It's a but rough around the edges If I want to add more replicas. I'm wondering if there would be a lot of effort to add support for mysql2 `createPoolCluster` and have a similar api through kysely to "select" the database to run queries against?

**Comment by koskimas** [comment]
You need to create a custom dialect for that. You can use the built-in MysqlDialect as the starting point and make the needed changes.
