### ISSUE TITLE
Coalesce is limited to only 5 arguments

### ISSUE THREAD

**Issue by razsightfull** [kysely-org/kysely#1076]
Hey team!

I've just upgraded Kysely's version to the latest and noticed that there was a change in the coalesce parser, which used to receive unlimited number of arguments, and now it is limited to maximum 5.

There are some parts in my code in which I'm using spread in order to pass the arguments, because the array of them is in a dynamic length --> Meaning it is breaking my code.

**Comment by igalklebanov** [comment]
Hey 👋 

The limitation only exists at the type-level. The old recursive type was too expensive compile-time performance-wise.

I'm surprised it worked for you before. It was not designed to be used dynamically. Beats it's purpose.

You can switch to `eb.fn<RT>('coalesce', references)` as a workaround.

**Comment by koskimas** [comment]
Without ignoring types, I don't see how an arbitrary length array could make sense. The whole purpose of coalesce is to have N null able arguments followed by a non-null one. You can't encode those types in an array type.
