### ISSUE TITLE
Syntax error at the end of input when using onConflict and empty values

### ISSUE THREAD

**Issue by sfratini** [kysely-org/kysely#1090]
Hello! It seems like internally kysely strips undefined or empty values and that breaks the SQL syntax. 

Using this (simulating an upSert):

```
let data = await kysely.insertInto('table')
          .values({
            unique: 'value
            value1: input.value1,
            value2: input.value2,
          })
          .onConflict(oc => {
              return oc.column('unique')
              .doUpdateSet({
                value1: input.value1,
                value2: input.value2,
              })
          })
          .executeTakeFirst();
```

If value1 and value2 are undefined, will generate this SQL:

`insert into "table" ("table") values ($1) on conflict on column 'unique' do update set
`

The do update set is incomplete and will trigger the error in the subject. The workaround is simple enough, just making sure that at least one of the empty values is an empty string will generate the right SQL however I think this should be handled by kysely

This works:

```
let data = await kysely.insertInto('table')
          .values({
            unique: 'value
            value1: input.value1,
            value2: input.value2,
          })
          .onConflict(oc => {
              return oc.column('unique')
              .doUpdateSet({
                value1: input.value1 || '', //See empty value as default
                value2: input.value2,
              })
          })
          .executeTakeFirst();
```

The LogEvent shows parameters as an empty array

**Comment by koskimas** [comment]
An empty default value is not an acceptable fix. There's nothing a query builder can do here. An ORM could do some opinionated shit, but we can't. Just make sure you write valid queries.

**Comment by sfratini** [comment]
@koskimas I disagree since you are allowing undefined values in the doUpdateSet object, but then stripping them as if they were not allowed in the final query which causes this issue. 

I understand what you are saying, that you cannot assume what I meant by the undefined, but then why not forcing the types to not allow it? Otherwise you are indeed making an opinion, which is that you allow undefined values but then don't use them. 

In the end, it is your library, you do you, but I was not expecting an undefined value to be stripped and the query is not logged in this case so it took longer to debug. In my use case adding an empty value so the update query has at least one value works and that is enough of a workaround. I just submitted since I thought it could be improved. 

Cheers

**Comment by koskimas** [comment]
If we didn't strip undefined values, what would we use?

**Comment by sfratini** [comment]
@koskimas When did I bitch about it? You are reading my tone incorrectly. You are the one that is acting "not my problem" and using words like "shit, bitching, and write valid queries". All I did was brought up one particular behaviour which I did not believe was either right or was trying to understand how it works. 

A simple explanation would have sufficed. It took me longer to understand this behaviour as the log option "query" does not log this particular scenario so it just throws the exception and you cannot even see the query that is missing all the values. The only way to see the full query is to check the LogEvent which has the SQL property. 

Sometimes, you can have a full table with all optional columns (like mine) and you just want to pass an entire object without having to validate and sanitise every single property. I could do it, of course, but I just felt like the library can know right before making the on update set that the syntax will be wrong (parameters array is empty) and perhaps throw a more clear warning to the user or an exception we can catch and do our own alternative. 

Don't get me wrong, this is a great library and you guys did great work. Just was not expecting all of you to be so defensive about a question. I will stop this thread now. Thanks and good luck.

**Comment by mertalev** [comment]
I'm in the process of porting queries from TypeORM to Kysely and encountered this as well. This could ideally be prevented with typing, but if this is impossible, then I think it'd be better for Kysely itself to throw an error rather than sending the malformed query to the DB. It would be more helpful in understanding what went wrong and avoid the network request.
