### ISSUE TITLE
Add option to use "=" in order by

### ISSUE THREAD

**Issue by leegunwoo98** [kysely-org/kysely#1093]
In my work scenario, where we are pulling multiple users from a table, it is import that the current user stays on the top. As a result, we use 
```
`order by u.id=${userId}`
```
in order to make the current user stay on the top of the list.

I believe that this use case is also prevalent in many applications, so it would be useful to have it implemented natively instead of using raw sql.

**Comment by koskimas** [comment]
Already possible

https://kyse.link/UcHtx
