### ISSUE TITLE
Invalid parameter serialization when using array operators (@>, <@, &&)

### ISSUE THREAD

**Issue by ghalle** [kysely-org/kysely#1096]
Calling `where` with an array operator like `<@` will result in the following errors:

If the array has a single element:
`malformed array literal`

If the array has multiple elements:
`operator does not exist: text[] <@ record`

Manually building an array literal works but results in a typescript error.

Playground repro: https://kyse.link/v7Pzu

**Comment by koskimas** [comment]
That's error comes from the DB and has nothing to do with Kysely.

**Comment by ghalle** [comment]
You can see from the playground link that I am using an array and it is generating sql like `($1, $2)` which is not valid with the `<@` operator.

**Comment by ghalle** [comment]
@koskimas Can you take another look, I think there may have been a misunderstanding.

I'll inline everything in this comment to make it easy.

As you can see an array `pets` is used with the `<@` operator:
```typescript
const pets = ["hamster", "dog"];

const rows = await db
  .selectFrom("person")
  .where("pets", "<@", pets)
```
The sql generated is:
`select from "person" where "pets" <@ ($1, $2)`
And the parameters are:
`$1 = hamster, $2 = dog`

Trying to run that sql will result in:
`operator does not exist: text[] <@ record`

That is because `($1, $2)` is not a valid format for `<@` which expects an array.

**Comment by vmaubert** [comment]
Hi @ghalle ,

You can use this syntax =>

https://github.com/kysely-org/kysely/blob/3c2d268b765909fd97af1bbe34f1de31670afdda/src/raw-builder/sql.ts#L57
