### ISSUE TITLE
Migrations with custom provider don't work properly if Migrations are instances of classes, implementing Migration interface.

### ISSUE THREAD

**Issue by HerrRomich** [kysely-org/kysely#1099]
Hey, Why are you closing all the the time the issues to the the obvious problem #1098?

If you declares an interface for migration: [Migration](https://github.com/kysely-org/kysely/blob/bb0867793aa63e9969c50b48fbb5adbd603ba56a/src/migration/migrator.ts#L16), be ready, that once a migration comes as an instance of a class. And be ready, that the [spread operator](https://github.com/kysely-org/kysely/blob/bb0867793aa63e9969c50b48fbb5adbd603ba56a/src/migration/migrator.ts#L501) won't copy the method of this class but just skips it.

P.S. And regarding the over-engineering... It's a common practice to use Inverse of control in such big projects, like we do have. InversifyJS in this case is a good tool to realise dependency injection.

**Comment by HerrRomich** [comment]
I would really appreciate, if we could discuss the problem and may be find a good solution.

**Comment by igalklebanov** [comment]
Hey 👋 

We're not responsible for JavaScript skill issues once you over-engineer and apply patterns where they don't make sense.

Sincerely, the team.
