### ISSUE TITLE
How to manipulate RootOperationNode ?

### ISSUE THREAD

**Issue by HendrixString** [kysely-org/kysely#1105]
Hi,

Given this Query Builder
```
const qb = db.updateTable("person").set("gender", "male");
```
Then, 

Why this works ? 

```
sql`${qb}`.execute(db);

```

But this Not ? (The `RootOperationNode`)
```
sql`${qb.compile().query}`.execute(db);

```

Suppose, that all I have is `RootOperationNode` and I need to manipulate it with `sql` function,
how do I manipulate it without instantiating QueryBuilders all over the place ?

**Comment by koskimas** [comment]
You can't pass query nodes to the SQL template tag. It doesn't work because it's not supposed to work and nowhere does it say that it would work.
