### ISSUE TITLE
Type inferration error on dynamic selection

### ISSUE THREAD

**Issue by dotMortis** [kysely-org/kysely#1115]
Typescript v5.4 - v5.5 (have not tested older versions)

tsconfig.json
```json
{
    "compilerOptions": {
        "allowSyntheticDefaultImports": true,
        "strictPropertyInitialization": true,
        "esModuleInterop": true,
        "skipLibCheck": true,
        "forceConsistentCasingInFileNames": true,
        "importHelpers": true,
        "sourceMap": true,
        "noImplicitAny": true,
        "declaration": false,
        "noFallthroughCasesInSwitch": true,
        "noImplicitReturns": true,
        "pretty": true,
        "strict": true,
        "strictNullChecks": true,
        "target": "ES2022",
        "module": "NodeNext",
        "lib": ["ES2022"],
        "resolveJsonModule": true,
        "outDir": "./dist",
        "declaration": true
    },
    "ts-node": {
        "esm": true
    }
}
```

The most important setting ist `"decleration": true"` otherwise the error wont show.

```typescript
import { Generated, Kysely, SelectExpression } from 'kysely';

type DB = {
    test: {
        id: Generated<number>;
        type: 'a' | 'b';
        updatedAt: number;
        createdAt: number;
    };
};

export class WorkflowTypeRepository {
    private readonly _db: Kysely<DB>;

    constructor(db: Kysely<DB>) {
        this._db = db;
    }

    all<SE extends SelectExpression<DB, 'test'>>(selections: ReadonlyArray<SE>) {
        return this._db.selectFrom('test').select(selections).execute();
    }
}
```

The goal is to create a function that allows me to select only fields I really need.
In the screenshots below its shown that the generic selection has been inferred correctly, but tsc can't build declerations for it.
It's necessary for me to be able to build the .d.ts files since it's a package in a monorepo.

Errors:
- The inferred type of 'all' cannot be named without a reference to '../../node_modules/kysely/dist/esm/dynamic/dynamic-reference-builder.js'. This is likely not portable. A type annotation is necessary.ts(2742)
- The inferred type of 'all' cannot be named without a reference to '../../node_modules/kysely/dist/esm/util/type-utils.js'. This is likely not portable. A type annotation is necessary.ts(2742)

![Screenshot 2024-08-12 203208](https://github.com/user-attachments/assets/f173d71e-72f9-40d0-bed4-ae9e9e02c558)
![Screenshot 2024-08-12 203246](https://github.com/user-attachments/assets/9c1bac7b-b991-4650-b3c5-24273f893fbd)
![Screenshot 2024-08-12 203220](https://github.com/user-attachments/assets/d1d20951-3e07-45d9-8d1f-bfe5f6636a0c)

**Comment by dotMortis** [comment]
@koskimas Is the problem already fixed in the next version or whats about the issue?

**Comment by dotMortis** [comment]
@koskimas You added the invalid label.
I would be very grateful if you could explain why you classified it that way.
Sorry if I'm being a bit more intrusive, but I'm a bit surprised.

**Comment by vyshnavsdeepak** [comment]
This feels valid to me as well. I ran into the same issue today.

**Comment by igalklebanov** [comment]
Hey 👋

Provide a reproduction repository please.

**Comment by dotMortis** [comment]
@igalklebanov 
https://github.com/dotMortis/kysely_bugreport_1115

Most basic example.
npm install
npm run build

**Comment by jonaskello** [comment]
I ran into the same issue today. Above I can see a reproduction of the issue and a PR to fix it but no resolution. Is there a reason this issue is closed or can it be opened again?

**Comment by jonaskello** [comment]
For reference, using pnpm you can place this file in `patches/kysely@0.27.4.patch` to resolve the issue:

```
diff --git a/dist/esm/dynamic/dynamic.d.ts b/dist/esm/dynamic/dynamic.d.ts
index 859b6fe28d022f2bbc3c485d58ca822c30359dc9..4c8d16407ea5325c2723207d1d47992830af32b3 100644
--- a/dist/esm/dynamic/dynamic.d.ts
+++ b/dist/esm/dynamic/dynamic.d.ts
@@ -1,3 +1,4 @@
+export { DynamicReferenceBuilder } from './dynamic-reference-builder.js';
 import { DynamicReferenceBuilder } from './dynamic-reference-builder.js';
 export declare class DynamicModule {
     /**
diff --git a/dist/esm/dynamic/dynamic.js b/dist/esm/dynamic/dynamic.js
index 9bf1f543f84b76ab9c258731bc2741404edc4f38..35d97edcd0be051e4ee42c8c333995c092fd823f 100644
--- a/dist/esm/dynamic/dynamic.js
+++ b/dist/esm/dynamic/dynamic.js
@@ -1,4 +1,5 @@
 /// <reference types="./dynamic.d.ts" />
+export { DynamicReferenceBuilder } from './dynamic-reference-builder.js';
 import { DynamicReferenceBuilder } from './dynamic-reference-builder.js';
 export class DynamicModule {
     /**
diff --git a/dist/esm/index.d.ts b/dist/esm/index.d.ts
index d556ad76e2a23d600e3ee3024bad9d7dd8beccf7..4da2297c71bce9d6aeec652734640642a1333f4d 100644
--- a/dist/esm/index.d.ts
+++ b/dist/esm/index.d.ts
@@ -209,3 +209,5 @@ export { OrderByExpression, OrderByDirectionExpression, } from './parser/order-b
 export { ComparisonOperatorExpression, OperandValueExpression, OperandValueExpressionOrList, FilterObject, } from './parser/binary-operation-parser.js';
 export { ExistsExpression } from './parser/unary-operation-parser.js';
 export { OperandExpression, ExpressionOrFactory, } from './parser/expression-parser.js';
+export * from './util/type-utils.js'
+export * from './util/type-error.js'
diff --git a/dist/esm/index.js b/dist/esm/index.js
index c85949e9080a6e78f1aef5561ed050cb6d924b15..6b801028eb30c1fdb406d4b2ee06530b12b69a66 100644
--- a/dist/esm/index.js
+++ b/dist/esm/index.js
@@ -198,3 +198,5 @@ export * from './util/streamable.js';
 export * from './util/log.js';
 export * from './util/infer-result.js';
 export { logOnce } from './util/log-once.js';
+export * from './util/type-utils.js'
+export * from './util/type-error.js'
```

@koskimas Could you elaborate on why the issue is closed or should we perhaps go ahead and open a new issue?

**Comment by eqqe** [comment]
I am running into the same issue

**Comment by yss14** [comment]
Can confirm this issue.
The `index.ts` has 

```typescript
export {
  AnyAliasedColumn,
  AnyAliasedColumnWithTable,
  AnyColumn,
  AnyColumnWithTable,
  Equals,
  UnknownRow,
  Simplify,
  SqlBool,
  Nullable,
  NotNull,
} from './util/type-utils.js'
```
which seems to be insufficient, since `export * from ./util/type-utils.js'` fixes the compiler error.
Couldn't find out the missing type export, though.

**Comment by juanrgm** [comment]
The problem exists, and it's very easy to fix.

If you have type declaration enabled in tsconfig.json (required if you use composite projects) and you export an object in any file that uses a type not exported in the kysely index file:

> The inferred type of '?' cannot be named without a reference to '../../node_modules/kysely/dist/esm/util/type-utils.js'. This is likely not portable. A type annotation is necessary.

In my case, it's because I'm using the `jsonObjectFrom` function, which in turn uses the `ExtractColumnType` type, which is not exported by kysely.

Solution? Export all types from `./util/type-utils.js` in the kysely index file. Otherwise, kysely cannot be used in TypeScript composite projects that export kysely objects.

**Comment by igalklebanov** [comment]
Try https://github.com/kysely-org/kysely/releases/tag/v0.28.10.

If you're still having issues, please submit a new issue with the error message, a minimal example, `tsconfig.json`, etc.
