### ISSUE TITLE
Is there any API that  can compile a  multi count and DISTINCT count query?

### ISSUE THREAD

**Issue by iceleo-com** [kysely-org/kysely#1116]
Hi There,

I can't seem to find any examples that can do a simple count query like the one below

```
SELECT COUNT(*) AS `total_users`, COUNT(DISTINCT `position`) as `total_positions` FROM `tbl_user`;
```
May anyone help me with an example?
Thank you so much for helping!

**Comment by koskimas** [comment]
There's no built-in way to build that query currently, but you can easily create your own helper https://kyse.link/3Ca1J

**Comment by igalklebanov** [comment]
Hey 👋 

We actually do have a built-in way to build it:

```ts
await db
  .selectFrom("tbl_user")
  .select(({ fn }) => [
    fn.countAll().as("total_users"),
    fn.count("position").distinct().as("total_positions"),
  ])
  .execute();
```
https://kyse.link/oo181

**Comment by koskimas** [comment]
Oh, my bad 😅
