### ISSUE TITLE
Investigate generating types instead of relying on third party packages.

### ISSUE THREAD

**Issue by seivan** [kysely-org/kysely#1120]
I really think this should be part of this library, and there are other reasons for it other than just making queries. 
In order to offer feature parity with other query builders and even dare I say, ORMS like Active RecordL 

Kysely should be a complete go-to for any db work, but it needs to be feature complete for that. The strong type checking makes it the best library out there, so it's a shame it doesn't have it. 

Another problem it would solve is old migrations.

With Active Record for instance, after every successful invocation of a `dev` migration, a `schema.rb` file is updated that reflects the current state of the database. 

Not just for compile time checks but also run-time meta-data. 

The reason for this is because after a project has been on-going after a while, you don't want to run the 80 migration files in order to get started for a new dev, you just use the `schema.rb` to get up to speed. 

One way to do it, is that if there is no `migrations_table` and there is a `schema.ts` file, it should apply it **with** explicit user confirmation as it's only useful for dev as I said earlier. 

I'm urging to merge in https://github.com/RobinBlomberg/kysely-codegen into the code base and make it first class support.

**Comment by koskimas** [comment]
Easy to urge and demand when you're not the one doing any of the work.

**Comment by seivan** [comment]
I’m not demanding, I’m asking, if you’re ok with it or if you had other plans. Get the stick out.
