### ISSUE TITLE
Suggestion: ReadOnlyKysely type

### ISSUE THREAD

**Issue by jake-nz** [kysely-org/kysely#1123]
I'm using Kysely on a master database and a read replica. I'd like to see TS errors when I try to use the read instance for write operations. For example `databaseReadOnly.insertInto('table')...` <- Type Error!

I'm currently using this type to catch the most common write operations:
```ts
type ReadOnlyKysely<DB> = Omit<Kysely<DB>, 'insertInto' | 'updateTable' | 'deleteFrom'>
export const databaseReadOnly: ReadOnlyKysely<DB> = new Kysely<DB>({...
```

It would be great to have a `ReadOnlyKysely` out of the box that's more thorough.

**Comment by igalklebanov** [comment]
Hey 👋 

We've looked into this and decided it will be too demanding to maintain.
See https://github.com/kysely-org/kysely/pull/218.
