### ISSUE TITLE
typescript error when using output on insertInto

### ISSUE THREAD

**Issue by zivni** [kysely-org/kysely#1129]
using mssql, when adding `output` on the `updateTable` it works great. When using it on `insertInto` there is typescript error. commenting the `output ` with `//@ts-ignore` the results are getting as needed by the of course the returned type is wrong. 

Works:
```typescript
this.db.updateTable("tableName")
.set(dataToUpdate)
.output("inserted.fieldName")
.execute();
```

Doesn't work:
```typescript
this.db.insertInto("tableName")
.values(dataToInsert)
.output("inserted.fieldName") //ts-ignore this line returns the correct results
.execute();
```

**Comment by igalklebanov** [comment]
Hey 👋 

Can you provide a reproduction repository?

**Comment by zivni** [comment]
Sorry. my mistake~

Iin the insert I put the table name into a constant with a type  `keyof Database` so it didn't work. I forgot that I hade the same problem when trying to use it in the update and changed it to a regular string.
