### ISSUE TITLE
Improvement of lateral support

### ISSUE THREAD

**Issue by Bessonov** [kysely-org/kysely#1131]
#983 was closed without any comment mistakenly.

Thank you again for the amazing query builder! It would be nice if the following query were supported:

```sql
-- mysql
select *
from customer c,
lateral (select 6371 * distance_formula) as distance
where longitude is not null;
```

This means:
- Supporting `fromLateral`.
- Supporting `selectNoFrom` in laterals.

Currently, I am using the following workaround. Please also pay attention to ```sql`dual` as any``` to overcome typings.

```typescript
.innerJoinLateral(({ selectFrom, val, ref }) =>
	selectFrom(sql`dual` as any)
		.select(sql`(6371 * distance_formula)`.as('distance'))
		.as('distance'),
	join => join.onTrue()
)
```

**Comment by Bessonov** [comment]
Hey @koskimas , any comment?

**Comment by mshick** [comment]
I'm also curious. I would find `fromLateral` useful as well.
