### ISSUE TITLE
TraversedJSONPathBuilder.$castTo and .$notNull should return TraversedJSONPathBuilder instead of JSONPathBuilder?

### ISSUE THREAD

**Issue by cassus** [kysely-org/kysely#1138]
Hi,

#### `TraversedJSONPathBuilder.as` typechecks correctly:

```ts
eb
  .ref("healthScaleStepJson.healthScaleStepJson", "->>")
  .key("id")
  .as("formComponentId"),
```

#### `TraversedJSONPathBuilder.$castTo` typechecks correctly:

```ts
eb
  .ref("healthScaleStepJson.healthScaleStepJson", "->>")
  .key("id")
  .$castTo<FormComponentId>()
```

#### But when `.$castTo` and `.as` is combined it's a type error
```ts
eb
  .ref("healthScaleStepJson.healthScaleStepJson", "->>")
  .key("id")
  .$castTo<FormComponentId>()
  .as("formComponentId"), // <--- Property 'as' does not exist on type 'JSONPathBuilder
```

My guess is that this could be fixed if `TraversedJSONPathBuilder`.`$castTo` (and .`$notNull` which is very similar) returned `TraversedJSONPathBuilder` instead of `JSONPathBuilder`.

**Comment by igalklebanov** [comment]
Hey 👋

Yeah, your assumption seems correct.
