### ISSUE TITLE
Support "returning" functionality for MySQL dialect

### ISSUE THREAD

**Issue by kiryasolod** [kysely-org/kysely#1140]
Hi everyone! Thanks for such a great library!
Could you please add "returning" functionality for MySQL? MySQL supports it from version 8.0.27
Thanks!

**Comment by koskimas** [comment]
Yep, let's do this.

For now you should be able to enable it by overriding one property of `MysqlAdapter` https://kyse.link/MYZCF.

**Comment by thelinuxlich** [comment]
Where is the source on this? Can you provide a link to the docs?

**Comment by thelinuxlich** [comment]
No mention of RETURNING here: https://dev.mysql.com/doc/refman/8.4/en/insert.html

**Comment by igalklebanov** [comment]
No such thing in MySQL.
https://dev.mysql.com/doc/relnotes/mysql/8.0/en/news-8-0-27.html

**Comment by christiannaths** [comment]
Sorry to raise an old thread, but using a mysql adapter and chaining a `returning` or `returningAll` method, it seems as though Kysely [produces invalid SQL](https://kyse.link/#cN4IgpgJglgLg9gJwM4gFyhgTwA5jSKAW20RgAJgAdAOzLIHExqwEBDGSAGhroGUwANmADGMVgCMh3WmQCq2COzASpPMgElqSFmMlhpAXzIAzBHEJlKIANaZtAzFYDcNGmAAeJBOSjUOCY1ZhMDIAEXYJVm0KNVxkOGpUMgAFFiQEgBUVMBcZXBgk1JgsvVyDV2ZPUjJff0DglLTM7JiZKAgkxmY2DggAHmoAV0JxFgA+XLpjKGQYAH1qVkIwJKQYBF8Ac0myASj5xeXV9a2yAB8yIYEBHc2mCBZO+5Yyio8vHz8WepCikqFWnR2k9ukp+kMRuMdocVmQ1htqNs1HAAO7dObAy7DUYIHZIXDCKBgJBJXgEolIV7UNxVbxkLC4BjPBBkAC8lhAhFYQis5w5xjAXJ5ID5VjgMAAFixnDSPvScCEySIKWyORA4JteRcrMJ2FqORKlmtpSBcrLqgzfk1aOz+EJRNk+ql4tR-mAJua6ZayAA5MAo53pG0aLQ6R2B5p6D2VOXeiPUeSKDiqxNKcPWt3Rz3kONgci2wQiXRCJ15zO5d4WhW+-1FVWabTedPFbLRyte6tFVPJ9nd5R6UstqO5ECcEAAR0GLEw+FYKNYsDIEHEagAdL5GzBNPAABRWfJWACUa4Abtyp0gd1QZHQYUkrAAxASDYzGRyjtR0VHozEARmkdB0PiyrEveICGoQxoIFYAFkAYx4yKuCB5oMCDUFsACC1w7ghdCrh4IiDBwWTWGAD4zGsADyCAZBKZgojhI4GGO0DckW+CEHY44CKONh2IIM7oCAlr4GImy8TC+AAAyrgATAA7KuACsIAGAYQA)

input
```typescript
await db
  .insertInto("pet")
  .values({
    name: "Fluffy",
    owner_id: 1,
    species: "hamster",
  })
  .returningAll()
  .executeTakeFirstOrThrow();
```

output
```sql
INSERT INTO
  `pet` (`name`, `owner_id`, `species`)
VALUES
  (?, ?, ?) returning *
```

AFAICT there are no versions of mysql which support `RETURNING`, so I would expect, at the very least, for this to raise a type error.

I'm running MySQL 8.4.3 and the above SQL query returns the following error:

```
Query 1 ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'returning *' at line 4
```

Just wanted to double check before opening a new issue, I rarely work with mysql so my knowledge may be inaccurate.

**Comment by igalklebanov** [comment]
Hey @christiannaths 👋

Kysely outputs what you want it to. WYSIWYG and Bring Your Own SQL Knowledge are core principles.

**Comment by christiannaths** [comment]
@igalklebanov Ok, got it. Thanks for the reply :)
