### ISSUE TITLE
? Character is not escaped in `sql` function

### ISSUE THREAD

**Issue by kujo205** [kysely-org/kysely#1141]
I stumbled upon a problem with using `kysely` with mysql.

I try to use `sql` function like this in order to construct a link

```ts
 .select([
      (eb) => {
        const foo = eb.ref('table1.foo');
        const bar = eb.ref('table2.id');
        const baz = eb.ref('table3.id');

        const link = sql<string>`concat('/some/url/', ${foo}, '/', ${bar}, '?query=', ${baz})`;
        return link.as('link');
      },
```

The issue appears to in the line below, specifically with `?` character, `mysql` seems to be recognising this as a place where to insert substituted value, however I want to escape this character, how do I do this

```ts
const link = sql<string>`concat('/hiring/profiles/', ${foo}, '/', ${bar}, '?query=', ${baz})`;
```

**Comment by koskimas** [comment]
It's up to you to build valid SQL when you use the `sql` tag.
