### ISSUE TITLE
Is it possible to throw a type error when list could possibly be empty in "where... in" clauses

### ISSUE THREAD

**Issue by imtixz** [kysely-org/kysely#1145]
Im not an expert with typescript but is it possible to suggest the possibility of an error when a (possibly empty) array is passed into a query builder for a "where ... in ... " clause. So for example:

```js
const bills = await this.db
        .selectFrom('bills')
        .select([
          'bills.id',
        ])
        .where(
          'bills.forProperty',
          'in',
          properties.map((t) => t.propertyId),
        )
        .execute();
```

This threw an error during runtime because properties was an empty array. One of the big reasons for using kysely is that I dont have to worry about making mistakes like this because of it's incredible typesafety. Would it be possible to handle situations like this where if I havent't made sure the length is at least 1, this throws a type error?

**Comment by koskimas** [comment]
Unfortunately this can't be fixed in the types.
