### ISSUE TITLE
Can't use "begin immediate" in Sqlite

### ISSUE THREAD

**Issue by leononame** [kysely-org/kysely#1152]
As it stands, when using kysely, it seems impossible to use "BEGIN IMMEDIATE" in sqlite3, as the beginTransaction hook just ignores TransactionSetings and emits a normal begin (https://github.com/kysely-org/kysely/blob/c34093ec7afa36296023d28d1789bd6a4b644ade/src/dialect/sqlite/sqlite-driver.ts#L42). Is there another way to start an immediate transaction in sqlite3?

**Comment by koskimas** [comment]
Nope.
