### ISSUE TITLE
`preventAwait` cannot handle `Effect.runSync`

### ISSUE THREAD

**Issue by guillempuche** [kysely-org/kysely#1158]
Kysely is helping me a lot with SQLite (local-first) and Postgres (server).

I'm encountering a problem in my project (I can give access to the Kysely's authors if they want) using Kysely-PowerSync-Effect.

```ts
// runtime.ts
...
const MainLayer = Layer.mergeAll(
	PowerSyncClientLive,
	PowerSyncConnectorLive,
	ReposLive,
	SupabaseLive,
	WebClientLive,
).pipe(Layer.provide(ViteConfigProviderLayer))

export const RuntimeClient = ManagedRuntime.make(MainLayer)

// repo.ts
getMe: () => kysely.selectFrom(TableLibraryNames.creators).selectAll().limit(1)
```

// react_page.tsx
```tsx
import { useQuery } from '@powersync/react'
import { RuntimeClient } from '...'

export const PageSettings = () => {
	const { data: creators, isLoading: isLoadingCreators } = useQuery(
		RuntimeClient.runSync(RepoCreator.getMe()) // <-- Error here
	)
...
}
```

_More about PowerSync's useQuery here [powersync-ja/powersync-js@944ee93/demos/react-supabase-todolist/src/components/widgets/TodoListsWidget.tsx#L20](https://github.com/powersync-ja/powersync-js/blob/944ee938e6596e9819cb5572897c03614c7a7741/demos/react-supabase-todolist/src/components/widgets/TodoListsWidget.tsx#L20) and [powersync-ja/powersync-js@944ee93/demos/react-supabase-todolist/src/app/views/todo-lists/edit/page.tsx#L37](https://github.com/powersync-ja/powersync-js/blob/944ee938e6596e9819cb5572897c03614c7a7741/demos/react-supabase-todolist/src/app/views/todo-lists/edit/page.tsx#L37)._

No compile error, but this runtime error:

![imatge](https://github.com/user-attachments/assets/1255592b-e954-4ec7-a0c7-2d8552f00fc3)

It works when I refactor `getMe` to:

```ts
	getMe: () => {
		const query = kysely
			.selectFrom(TableLibraryNames.creators)
			.selectAll()
			.limit(1)

		return {
			execute: () => query.execute(),
			compile: () => query.compile(),
		}
	}
```

[PowerSync's team](https://discord.com/channels/1138230179878154300/1288468904984711209/1288486749894479884), a developer, and I consider there's something wrong detecting async logic.

Could it be caused by this? https://github.com/kysely-org/kysely/blob/14dc94af7ed2fb75004f02e616ab9ac255acbf8a/src/query-builder/select-query-builder.ts#L2430-L2433

What do you think can be the cause?

**Comment by koskimas** [comment]
https://github.com/kysely-org/kysely/pull/748

**Comment by guillempuche** [comment]
Thanks Sami for considering it.
