### ISSUE TITLE
Feature Request (MSSQL): Allow VarChar type for string parameters

### ISSUE THREAD

**Issue by drew-marsh** [kysely-org/kysely#1161]
I'm working with a database which uses varchar instead of nvarchar columns.
Searches can be very slow because string parameters are of type nvarchar, so sql server cannot use the varchar indexes.
An optional MssqlDialectOptions property to use varchar globally would be awesome :)
Happy to put in a PR

**Comment by belgattitude** [comment]
Had the same issue not long ago… have you tried to manually cast nvarchar into varchar in your queries ?

**Comment by drew-marsh** [comment]
@belgattitude the parameter itself has to be converted to varchar. you can cast the parameter in a raw sql query but not in for example a .where()
If this feature doesn't get added then a Kysely middleware that casts to varchar might be the solution :)

**Comment by igalklebanov** [comment]
Hey 👋

`MssqlDialect` expects `tedious` data types in its config. Try swapping the `NVarChar` value with the `VarChar` value.

**Comment by drew-marsh** [comment]
Thank you for the workaround! This does solve the problem.
```typescript
const dialect = new MssqlDialect({
    tedious: {
      ...Tedious,
      TYPES: { ...Tedious.TYPES, NVarChar: Tedious.TYPES.VarChar },
}});
```

**Comment by belgattitude** [comment]
@igalklebanov @drew-marsh 

Thank you for the workaround. I was wondering if there’s drawbacks when passing utf8 parameters in where clauses that are nvarchar ?

the solution above seems to be global… that’s why I’m asking

**Comment by igalklebanov** [comment]
Opened https://github.com/kysely-org/kysely/issues/1164 as a possible solution.
