### ISSUE TITLE
Postgres 17 `mergeInto` with `returning`

### ISSUE THREAD

**Issue by asterikx** [kysely-org/kysely#1169]
Postgres 17 now supports `MERGE INTO` with `RETURNING` (which is very handy to streamline queries and upsert records without writing multiple queries).

```sql
MERGE INTO heroes AS h
USING (VALUES ('Wade', 'Wilson', 'Deadpool')) AS v(first_name, last_name, hero_name)
ON h.hero_name = v.hero_name
WHEN MATCHED THEN
  UPDATE SET first_name = v.first_name, last_name = v.last_name
WHEN NOT MATCHED THEN
  INSERT (first_name, last_name, hero_name)
  VALUES (v.first_name, v.last_name, v.hero_name)
RETURNING merge_action(), *;
```

Is it possible to create the preceding query (taken from the [Neon release note](https://neon.tech/blog/postgres-17#simplifying-queries-using-merge-with-returning)) with Kysely?

**Comment by igalklebanov** [comment]
Hey 👋

Not yet.
