### ISSUE TITLE
MYSQL: kysely converting the datetime field to UTC while fetching data from database

### ISSUE THREAD

**Issue by stuvan** [kysely-org/kysely#1172]
This is my query
```js
 const query = sql`select id, registration_start_time, registration_end_time, timezone from \`scrim\``;
      const records = await query.execute(this.db);
```

the returned result
![image](https://github.com/user-attachments/assets/5c8c6e8c-835d-447b-a30b-86a327d5739d)

only column in my table
![image](https://github.com/user-attachments/assets/9f5f85c5-acd5-4390-b777-8c513749c7ce)

The data from mysql cli
![image](https://github.com/user-attachments/assets/5729ce3f-06c4-40d4-bcf7-3fa6daecbb45)

Look like kysely converting my date to UTC while fetching result and also on inserting or updating data

AS I reside in the land of +05:30 kysely subtracting the 5 hours and 30 minutes.

Any workaround for now?

**Comment by koskimas** [comment]
Kysely doesn't touch the data in any way. This is done by the mysql2 driver.

**Comment by stuvan** [comment]
> This is done by the mysql2 driver

In the enchanted realm of data management, it’s the mysql2 driver that handles this task. For future adventurers seeking guidance, remember to set your timezone properly. As I was converting my datetime to UTC before storing it in the database.

Here’s the solution that worked for mr:
```js
 new MysqlDialect({
        pool: createPool({
          uri: process.env.DATABASE_URL,
          database: process.env.DATABASE_NAME,
          timezone: 'Z', // <---- Set default timezone, in my case UTC
        }),
      }),
```
This way, your data will flow smoothly through time!
