### ISSUE TITLE
How to change website from dark to light?

### ISSUE THREAD

**Issue by ivorobioff** [kysely-org/kysely#1176]
my monitor doesn't work well with dark theme, and I can't find how to switch from dark to light. Please let me know how to do that.

**Comment by igalklebanov** [comment]
Hey 👋 

Light mode is not implemented in the docs site.

**Comment by igalklebanov** [comment]
You should be able to switch between light and dark mode now.

![image](https://github.com/user-attachments/assets/7fa37f1b-786b-4778-a144-1bdb11cb4943)
