### ISSUE TITLE
Missing types of core functionality

### ISSUE THREAD

**Issue by xpr0gamers** [kysely-org/kysely#1180]
Hello @koskimas,

first of all, i think this is an incredibly query builder!
But sadly, it's only a query builder. 
I will try to build an orm around this lovely library like [TypeOrm](https://typeorm.io/) or [MikroOrm](https://mikro-orm.io/).
For that, i need core types and functionality.

**Comment by koskimas** [comment]
Unfortunately we can't export all of that. It's not exported for a reason: the internal types and utilities can change at any given moment. If we exported them, we'd need to keep them backwards compatible. That'd slow down development significantly.
