### ISSUE TITLE
Loop over array of strings column to find if ID is present

### ISSUE THREAD

**Issue by MariuzM** [kysely-org/kysely#1184]
Sorry guys for posting this here not sure where else to go 

I have `r.service_groups` that is array of strings, then i have `c.category_group_pid` that i want to match agains them and return if match.

I found that either this works

```
.where(sql`c.category_group_pid = ANY(r.service_groups)`)
```

or this works

```
.where((e) => e(e.ref('c.category_group_pid'), '=', e.fn.any('r.service_groups')))
```

But with those i get error TS and i just don’t know how to make TS happy :(
<img width="1066" alt="image" src="https://github.com/user-attachments/assets/3bbf5e66-6ddf-49fa-acd7-9677c4406469">
<img width="840" alt="image" src="https://github.com/user-attachments/assets/41cb6955-df4c-49b4-aa4f-3c2ee8d4c6bf">

I have also tried these 
```
	.where('c.category_group_pid', 'in', 'r.service_groups')
		.where('c.category_group_pid', '@>', 'r.service_groups')
```
But i could not get them to work so something i wrote is incorrect

Here is bigger picture of my query 
<img width="625" alt="image" src="https://github.com/user-attachments/assets/2873bfab-ece9-4d20-8c12-ea240734af4c">

**Comment by koskimas** [comment]
Read the error message. The type of `r.service_groups` must be `string[]`.

**Comment by MariuzM** [comment]
@koskimas where does it say that? because looking at the error its just noise hard to make out that it needs to be string[]

This is Drizzle schema of the table, here i can see `string[]`
<img width="402" alt="image" src="https://github.com/user-attachments/assets/489f629a-8da0-4149-99a0-755518eb0a6b">

**Comment by MariuzM** [comment]
Here also is the types generated with `kysely-codegen` 
<img width="375" alt="image" src="https://github.com/user-attachments/assets/8cd5ad91-4287-4de1-a26e-ee89724c2f70">

**Comment by MariuzM** [comment]
The schema in Drizzle I'm taking from doc's https://orm.drizzle.team/docs/guides/empty-array-default-value
I have also tried 
```
	serviceGroups: varchar('service_groups').$type<string[]>().array(),
```
But it keeps adding the Generated generic, without it works but its either this specific kysely function does not know how to handle Generated type or kysely code gen is adding this when it should not? 

I have also tried `Kyselify` and just directly do `recipients: Kyselify<typeof RecipientsTable>` still same issue

**Comment by igalklebanov** [comment]
Hey 👋 

Can you provide a kyse.link instead of these screenshots?

**Comment by MariuzM** [comment]
@igalklebanov hopefully this will help 

https://kyse.link/ZQ6Q3

**Comment by igalklebanov** [comment]
You're getting the following error:

```
Argument of type 'KyselyTypeError<"any(expr) call failed: expr must be an array">' is not assignable to parameter of type 'OperandValueExpressionOrList<Database & { r: Recipients; } & { cg: Nullable<CategoriesGroups>; }, "r" | "cg", "cg.pid">'.
```

As @koskimas mentioned, it states in the beginning, `KyselyTypeError<"any(expr) call failed: expr must be an array">`, meaning that anything you put inside `any` must be an array expression.

`"r.serviceGroups"` is a reference to a column of type `string[] | null` which means, that sometimes it's not an array - thus doesn't fit inside an `any` safely.

In order to solve this, you need to coalesce your nullable reference to resolve as an array expression at all times.

Something like:

```ts
import { sql } from "kysely";

await db
  .selectFrom("recipients as r")
  .leftJoin("category_groups as cg", "cg.name", "r.name")
  .where(({ eb, fn }) =>
    eb(
      "cg.pid",
      "=",
      fn.any(fn.coalesce("r.serviceGroups", sql<[]>`'{}'`)),
    ),
  )
  .select(["r.name"])
  .execute();
```
https://kyse.link/ydQTh

**Comment by MariuzM** [comment]
Super thank you its because of the null, i have tested with another column that is not null and then it just generates string[] type without Generator. 

Also i did found this worked for me when i had type also with null 
```
.where((e) => sql`${e.ref('c.category_group_pid')} = ANY(${e.ref('r.service_groups')})`)
```
