### ISSUE TITLE
get runtime db dialect type

### ISSUE THREAD

**Issue by aslushnikov** [kysely-org/kysely#1191]
TL;DR: how do I get SQL dialect in my migrations, so that I can adapt queries accordingly?

---

Hi folks!

First of all, thank you for the awesome Kysely lib. It's a pleasure to work with.

I'm using Kysely in an app that has to work against both MySQL and Postgres.
Consider the following migration that adds an index:

```ts
// 012_add_index.ts

import { Kysely } from 'kysely';

export async function up(db: Kysely<any>): Promise<void> {
  await db.schema
    .createIndex('idx__projects__projects_token')
    .on('projects')
    .columns(['projects_token'])
    .execute();
}

export async function down(db: Kysely<any>): Promise<void> {
  await db.schema.dropIndex('idx__projects__projects_token').execute();
}
```

Now the `down` function will work in postgres but will throw in MySQL.
MySQL requires the following:

```ts
export async function down(db: Kysely<any>): Promise<void> {
  await db.schema
    .dropIndex('idx__projects__projects_token')
    .on('projects')
    .execute();
}
```

How do I check in migration which dialect `db` uses to adapt accordingly? Any workarounds? 

Thanks,
Andrey

**Comment by igalklebanov** [comment]
Hey 👋

You can't, by design.

Use an environment variable.

**Comment by igalklebanov** [comment]
You can then use `$call` as follows:

```ts
await db.schema
  .dropIndex('idx__projects__projects_token')
  .$call((ib) => isMySQL(db) ? ib.on('projects') : ib)
  .execute()
```
https://kyse.link/YvYol

**Comment by aslushnikov** [comment]
Awesome, thank you for the recommendations!
