### ISSUE TITLE
My DB Needs & A little confusion about kysley

### ISSUE THREAD

**Issue by gunslingor** [kysely-org/kysely#1195]
It seems kysley has changed over the years, I haven't used it in a while and I'm rusty. The main reason I appreciated it is that it allowed me to define my DB as code in objects. One serious issue with relying entirely on discrete migrations is that it becomes impossible to see the entire DB design, and if no one person can see it all your guaranteed to have relationality issues (the 10k foot view, not every step it took to get there).

Thus, over 20 years I have only identified 2 approaches to 'actually' managing a database 'design' in a completely flawless and inherently extensible manner, but note this does assume the developer knows his stuff really well on relationality.
-  A database diagram (that actually saves the layout for you and uses isometric lines). Only MySQL workbench seems to save and sync correctly, after all these years. But alas, it stores as a binary so this is not ideal for GIT tracking.
- An ORM system where my 'DB AS CODE' objects are able to be synced back and forth, but where I can still define the folder structures to mimic the relationality (e.g. objects in separate files, hierarchical organization of primary relationality which is typically all I allow). Kesley seemed to do this at one point if I am not mistaken, but now entirely relies on the approach of other frameworks like prisma and flyaway? The migration approach?

What I am trying to avoid in my new app? When I start a job and ask to see the DB design, I am often provided with:
- a 20k line CREATE script (that has horrible relationality flaws)
- a 200k line single file automatically generated ORM model from a product DB (that has horrible relationality flaws)
- a rats nest diagram that takes 20 minutes to load, 2 minutes to scroll and 5 minutes to zoom... or something more peace meal that routes automatically and fast but doesn't show the 10k foot view, only the relationships to a few tables and saving layouts isn't a thing.

In other words, what I am typically provided in terms of the actual design of the database is not actually ever even adequate to do the job. 

Thus, can I still use Kysley as my source of truth? A production DB is the source of DATA truth I agree, but it should never be the source of DB DESIGN truth... as soon as a DB DESIGN error makes its way to production you have lost your source of INTENDED DESIGN truth,  (and seems to happen with DBs more than code for reasons stated or alluded to herein).

So, is Kysley still the right tool to document design truth? Is there a walkthru? I was doing the getting started again and saw this: "For production apps, it is recommended to automatically generate your Database interface by introspecting your production database or Prisma schemas. "

I'm really confused because I thought Prisma and Kysley do the same thing, but kysley does it better in typescript instead of something proprietary.

Thanks in advance

**Comment by igalklebanov** [comment]
Hey 👋 

Kysely is a type-safe query builder. 

You *can* define your database and tables representations in TypeScript interfaces/types, OR you *can* an external tool to generate these for you (e.g. Prisma [ORM as source-of-types] via `prisma-kysely` or straight from the database schema via `kysely-codegen` or `kanel-kysely` [database as source-of-types]), and then pass these to the `Kysely` constructor's generic argument.

There is a programmatic schema manipulation module designed for up/down migrations (which Kysely also provides primitives for running and managing). But unlike ORMs, such as Prisma or TypeORM, there is no way to declare your schema and have it be the source-of-types.

**Comment by gunslingor** [comment]
I think I understand. I can create my own kysley models and migrate production to match them manually, or I can go the other way automatically. I'll give both a try, in the end I kinda feel both ways are needed.
