### ISSUE TITLE
How to access "message" OR "code" in my code

### ISSUE THREAD

**Issue by patrickReiis** [kysely-org/kysely#1196]
Take for example the following query (it returns an empty array):

```ts
await kysely.selectFrom('nostr_events').select('id').where('search', '@@', sql`phraseto_tsquery('what')`).execute()
```

Since `what` is a stop word and it's the only only word, Postgres ignores this query (which is ok).

When I run the query mentioned I see this in my logs:
```
{
  severity_local: "NOTICE",
  severity: "NOTICE",
  code: "00000",
  message: "text-search query contains only stop words or doesn't contain lexemes, ignored",
  file: "tsquery_cleanup.c",
  line: "406",
  routine: "cleanup_tsquery_stopwords"
}
```

I would like to be able to get the `code` or `message` before or after executing, so I can throw an error in my code so the frontend can handle it. Thanks.

**Comment by koskimas** [comment]
That's logged by the `pg` driver. There's no way to access it.
