### ISSUE TITLE
Support `join` parenthesis.

### ISSUE THREAD

**Issue by igalklebanov** [kysely-org/kysely#1198]
Hey 👋 

Kysely currently produces `join`s without parenthesis, and engines process this from left to right.
This can produce unwanted results in some cases.
e.g. `left join` followed by an `inner join`, in which you want to keep t1's rows regardless of `inner join` between t2 and t3.

You can wrap joins in parenthesis to group joins and break out of the regular processing order:

```sql
select *
from "t1"
left join (
  "t2"
  inner join "t3" on "t2"."c" = "t3"."c"
) on "t1"."c" = "t2"."c"
```

SQLite might require aliasing the parenthesis before the `on` clause.

**Comment by spearmootz** [comment]
for the record if anyone has the issue. here is how i got around this

```


query
  .leftJoin(
    // @ts-expect-error this is needed because typescript complains but it does work
    ({ parens }) => parens(sql`("table1"
                  INNER JOIN "table2" ON "table2"."id" = "table1"."table2_id")`),
    "table1.id",
    "previousTableFoundInQuery.table1_id"
  )
  // @ts-expect-error this is required because the raw causes typescript not to infer the type
  .orderBy("table.id", `asc NULLS LAST`);

```

**Comment by koskimas** [comment]
Wouldn't this be equivalent to

```sql
select *
from "t1"
left join (
  select "t2".*
  from "t2"
  inner join "t3" on "t2"."c" = "t3"."c"
  as "t2"
) on "t1"."c" = "t2"."c"
```

?

The query optimizer will most likely turn that into exactly the same query plan as the original example. Only a really dumb optimizer would materialize the inner query in this case.

This query you can already build using kysely:

```ts
db.selectFrom("t1")
  .leftJoin(
    db.selectFrom("t2").innerJoin("t2", "t2.c", "t3.c").selectAll("t2").as("t2"),
    "t1.c",
    "t2.c",
  )
  .selectAll()
```

This is the very first time during my 15 year career that I see the syntax in the original message. Do we really want to rewrite our join builder and logic to support this case?

**Comment by igalklebanov** [comment]
Agree with @koskimas, not much added value in adding this - it'll be complex and the DX is not guaranteed to be great.

Closing this for now.
