### ISSUE TITLE
Support for `Set<>` and other kinds of iterables.

### ISSUE THREAD

**Issue by arthurfiorette** [kysely-org/kysely#1204]
Not always data is organized in an array form and even currently it appears work with `Set<>`, TS type checker gets mad and only allows arrays.

```ts
db
  .selectFrom('Table')
  .select('field')
  .where('id', 'in', mySet) // breaks typings!
  .execute()
```

Which leads to having to write many `.where('id', 'in', Array.from(mySet))` calls which could be avoided.

Best approach would be to allow all kinds of objects that extends `Iterable<T, void, void>` in parameters.

**Comment by koskimas** [comment]
They still would get turned into arrays internally. It's better to be explicit.
