### ISSUE TITLE
Nested array doesn't work on MySQL 5.7.44

### ISSUE THREAD

**Issue by tobe-continued** [kysely-org/kysely#1212]
Hello, i'm working on MySQL 5.7 in my office, and when i want use nested array, it doesn't work.

This : 
  ```javascript
import { jsonArrayFrom } from 'kysely/helpers/postgres'

const result = await db
  .selectFrom('person')
  .select((eb) => [
    'id',
    jsonArrayFrom(
      eb.selectFrom('pet')
        .select(['pet.id as pet_id', 'pet.name'])
        .whereRef('pet.owner_id', '=', 'person.id')
        .orderBy('pet.name')
    ).as('pets')
  ])
  .execute()
```

return : 
  ```text
sqlMessage: "Unknown column 'person.id' in 'where clause'",
```

Anyone has solution for this ?

See you later !

**Comment by koskimas** [comment]
You're importing the `jsonArrayFrom` helper from Postgres.

**Comment by kangwuyi** [comment]
> You're importing the `jsonArrayFrom` helper from Postgres.

I encountered the same problem. when use *import { jsonArrayFrom } from 'kysely/helpers/mysql'*
