### ISSUE TITLE
Is nested writes a thing?

### ISSUE THREAD

**Issue by Serpentarius13** [kysely-org/kysely#1213]
In prisma, it is possible to insert multiple child records when inserting a parent record in transaction. Can I do it in Kysely?

**Comment by igalklebanov** [comment]
Hey 👋

Such nesting doesn't exist in SQL and since Kysely is a query builder,vand not an ORM, it will never find it's way to Kysely's design. To achieve this, Prisma performs multiple queries and does things on the rust engine side.

You could achieve something close with the use of CTEs in PostgreSQL since it supports writes there and the `returning` clause (getting id's and default values that can be used in nwxt dependant writes).

**Comment by Serpentarius13** [comment]
> Hey 👋
> 
> Such nesting doesn't exist in SQL and since Kysely is a query builder, and not an ORM, it will never find it's way to Kysely's design. To achieve this, Prisma performs multiple queries under the hood, and does things on the query engine side, based on a schema definition that includes relations.
> 
> You could achieve something close with the use of CTEs in PostgreSQL since it supports writes there and the `returning` clause (getting id's and default values that can be used in next dependant writes).
> 
> You could also do it within the scope of a transaction, executing multiple queries.

Thank you for quick response! Yeah, well, I've came to the same conclusion after reading multiple posts and documentation, but I could not make it work. The problem arised when I wanted to insert it all inside a transition, however, since the parent rows are in transition themselves, I found it impossible to reference them with foreign keys in child rows. I also tried CTE's and I didn't really get how to reference rows from the first `with` clause if I return many of them, so here's my attempt:

```ts
await tx
          .with("nested", (db) =>
            db
              .insertInto("DevprofileExperience")
              .values(
                input.experiences.map((e) => {
                  const now = dayjs();
                  const from = now
                    .set("year", e.fromYear)
                    .set("month", e.fromMonth)
                    .toISOString();
                  const to = now
                    .set("year", e.toYear)
                    .set("month", e.toMonth)
                    .toISOString();

                  return {
                    profileId: ctx.devprofile.id,
                    companyName: e.name,
                    description: e.description,
                    to,
                    from,
                  };
                }),
              )
              .returningAll(),
          )
          .with("next", (db) =>
            db
              .insertInto('DevprofileExperienceTechs').values( e => {
                const experiences =  e.selectFrom('nested').select(['id']).as('id_table')
                // I have an array up top, which I wanted to match with returning ids by index, yeah, baka
                return [
                 
                ]
              }))
           
              }),
          )
```

Would you please write a small example how can I achieve nesting insert of an array of parent rows with a child property of an array of child rows, like so?

```ts
interface Parent {
  children: Id[]
}

type Payload = Parent[]
```
