### ISSUE TITLE
NO documentation about error handling!!!!

### ISSUE THREAD

**Issue by mohrazzak** [kysely-org/kysely#1217]
I am really confused that the docs doesnt have anything about error handling 
ex: user already exsits 
violating constaints 
this is a mandataory things to add!!

**Comment by igalklebanov** [comment]
Hey 👋 

Kysely is a lightweight query builder that passes compiled queries under the hood to 3rd party database drivers. Errors that originate from those drivers are not caught by Kysely and you should handle them according to these drivers' OR database's documentations.

Documenting these errors in Kysely doesn't make sense.
