### ISSUE TITLE
cloneWithUpdates is duplicating fields in OperationNode

### ISSUE THREAD

**Issue by noudadrichem** [kysely-org/kysely#1218]
Hi! Awesome package, loving the type inference. 

I'm creating a plugin where I need to adjust a field before it's updated. However I'm now stumbling across the thing that cloneWithUpdates is duplicating the fields and therefore throws errors. I'm wondering if this behaviour is on purpose.

code:
```ts
const updateNode = UpdateQueryNode.cloneWithUpdates(node, [updates[0]]);
```
error:
```json
{
    "statusCode": 500,
    "code": "42601",
    "error": "Internal Server Error",
    "message": "multiple assignments to same column \"updated_at\""
}
```

I'm unable to get it to work and the docs aren't that clear to me about how these nodes need to be updated. I'm trying to update the operation node with adjusted updates that are created like so:
```ts
const adjustedUpdates = node.updates?.map((update) => {
    if (ColumnUpdateNode.is(update)) {
        const column = update.column.column.name;

        if (table === "table_name" && column === "column_name") {
            return ColumnUpdateNode.create(update, {
                value: {
                    kind: "ValueNode",
                    value: 'some updated value here based on `update',
                },
            });
        }
    }
    return update;
});
```

Wondering if the duplication is on purpose or if it's a bug.

**Comment by noudadrichem** [comment]
P.S. I got it working by resetting the updates on the initial node. See:
```ts
const updateNode = UpdateQueryNode.cloneWithUpdates({ ...node, updates: [] }, modifiedUpdates);
```

But this feels very hacky.

**Comment by igalklebanov** [comment]
Hey 👋 

You're diving into the world of Kysely's internals. Don't expect these things to be fully documented, and stable, or for you to be served as a 1st class citizen. Don't immediately assume there's a bug. Anything you will do will be hacky - that's the nature of altering the AST.

If there's a way to make it better for your use case, without making it worse for regular usage AND without hurting the maintainability of the core project, or hurting other use cases - it will be considered.

**Comment by noudadrichem** [comment]
@igalklebanov Thanks for your quick response. Good to know hacky is the way to go with this AST! 

As response to
> or for you to be served as a 1st class citizen. Don't immediately assume there's a bug
I'm not doing both of these things hence why I'm creating this issue.
