### ISSUE TITLE
[Bug] Missing space when using dropNotNull and setDefault together

### ISSUE THREAD

**Issue by lucasalberto01** [kysely-org/kysely#1270]
### Description:
When using the dropNotNull and setDefault methods together, I noticed that there is a missing space between the words, resulting in the string "nulldrop". The expected behavior would be to have an appropriate space between the commands.

### Reference:
For more information on how to remove a NOT NULL constraint in PostgreSQL, please refer to this [link](https://popsql.com/learn-sql/postgresql/how-to-remove-a-not-null-constraint-in-postgresql).

Screenshots:
![image](https://github.com/user-attachments/assets/de242baf-db0b-4c13-ac75-ccb256ddeb56)
![image](https://github.com/user-attachments/assets/f6b10e13-e9ff-4e15-a0b2-2cf768fa5cc5)

### Additional Information:
- Kysely: 0.25.0
- PostgreSQL: 16.4
- Node: v20.18.0

### Steps to Reproduce:
1. Use `dropNotNull` on a column.
2. Then apply `setDefault` on the same column.
3. Observe the generated output and note the absence of space.

### Expected Behavior:
The output should include a space between the commands, resulting in a properly formatted string.

Thank you for your attention, and I hope this can be addressed in a future update!

**Comment by igalklebanov** [comment]
Hey 👋 

The [spec](https://www.postgresql.org/docs/current/sql-altertable.html) states a single change is allowed per `alter column`.
