### ISSUE TITLE
Excessively Deep Typescript Error When Passing SelectQueryBuilder to function

### ISSUE THREAD

**Issue by ppetro08** [kysely-org/kysely#1273]
I am trying to build a function to handle pagination on a `SelectQueryBuilder` that is passed to it, but I am getting the typescript error `Type instantiation is excessively deep and possibly infinite. ts(2589)`

I tried the [kysely-paginate](https://github.com/charlie-hadden/kysely-paginate) package but it results in the same error.

My project is on typescript v5.5.4.

Does anyone know any typescript type magic to resolve the error?

Here is the function in question.
```typescript
export const executeWithPagination = async <
  DB,
  O,
  TB extends keyof DB,
>(
  queryBuilder: SelectQueryBuilder<DB, TB, O>,
  opts: PaginationOpts
) => {
  queryBuilder = queryBuilder
    .offset((opts.pageNumber - 1) * opts.pageSize)
    .fetch(opts.pageSize + 1);

  const rows = await queryBuilder.execute();
  const hasPrevPage = rows.length > 0 ? opts.pageNumber > 1 : false;
  const hasNextPage = rows.length > 0 ? rows.length > opts.pageSize : false;

  if (hasNextPage) {
    rows.pop();
  }

  return {
    rows,
    pageInfo: {
      hasPrevPage,
      hasNextPage,
    },
  };
};
```

**Comment by igalklebanov** [comment]
Hey 👋 

Separate concerns, simplify generics:

```ts
function paginate(pageNumber: number, pageSize: number) {
  return <QB extends SelectQueryBuilder<any, any, any>>(qb: QB): QB => 
    qb.offset((pageNumber - 1) * pageSize)
      .fetch(pageSize + 1)
}

function processPaginatedResults<R>(results: R[], pageNumber: number, pageSize: number): {
  page: R[],
  hasNext: boolean,
  hasPrev: boolean,
} {
  const hasNext = results.length > pageSize;
  const hasPrev = pageNumber > 1 && rows.length > 0;

  return {
    page: hasNext ? page.slice(0, -1) : page,
    hasNext,
    hasPrev,
  }
}

const results = await db.selectFrom("table").selectAll().$call(paginate(2, 100)).execute()

const { page, hasNext, hasPrev } = processPaginatedResults(results, 2, 100)
```

**Comment by ppetro08** [comment]
```typescript
Argument of type '<QB extends SelectQueryBuilder<any, any, any>>(qb: QB) => QB' is not assignable to parameter of type '(qb: SelectQueryBuilder<DB, "dbo.Test", { ID: number; IsActive: boolean; IsNew: boolean; Name: string; ForeignKeyID: number; SysEndTime: Date; SysInsertedBy: string; SysInsertedDate: Date | null; SysLastUpdatedBy: string; SysStartTime: Date; }>) => SelectQueryBuilder<...>'.
  Types of parameters 'qb' and 'qb' are incompatible.
    Type 'SelectQueryBuilder<DB, "dbo.Test", { ID: number; IsActive: boolean; IsBecks: boolean; Name: string; ForeignKeyID: number; SysEndTime: Date; SysInsertedBy: string; SysInsertedDate: Date | null; SysLastUpdatedBy: string; SysStartTime: Date; }>' is not assignable to type 'SelectQueryBuilder<any, any, any>'.
      Types of property 'where' are incompatible.
        Type '{ <RE extends ReferenceExpression<DB, "dbo.Test">, VE extends OperandValueExpressionOrList<DB, "dbo.Test", RE>>(lhs: RE, op: ComparisonOperatorExpression, rhs: VE): SelectQueryBuilder<...>; <E extends ExpressionOrFactory<...>>(expression: E): SelectQueryBuilder<...>; }' is not assignable to type '{ <RE extends ReferenceExpression<any, any>, VE extends OperandValueExpressionOrList<any, any, RE>>(lhs: RE, op: ComparisonOperatorExpression, rhs: VE): SelectQueryBuilder<...>; <E extends ExpressionOrFactory<...>>(expression: E): SelectQueryBuilder<...>; }'.
          Target signature provides too few arguments. Expected 3 or more, but got 1.ts(2345)
```
Thanks for your response! I tried this out but am running into a type issue on the paginate call, I ran into this error when trying different things on my original function but couldn't figure it out.

Also since the paginate function has `any` for the QueryBuilder generics doesn't that mean `processPaginatedResults` will not be able to infer the return type?

**Comment by igalklebanov** [comment]
> I tried this out but am running into a type issue on the paginate call

My bad, provided without double-checking. Here ya go..
https://kyse.link/S6QB6

> Also since the paginate function has any for the QueryBuilder generics doesn't that mean processPaginatedResults will not be able to infer the return type?

No. It means we enforce a any `SelectQueryBuilder`, but then the exact argument type is returned as-is. This is fine because `limit` and `offset` don't affect types in any way.

**Comment by ppetro08** [comment]
I still seem to be getting the same typescript error even with those changes.

**Comment by igalklebanov** [comment]
Imma need a kyse.link that reproduces this error.

**Comment by ppetro08** [comment]
After a frustrating goose chase I realized the error was specific to our project. We have an nx repo where types and db connections were in a commonjs library and the code using it was in an esm app. This seemed to be the root of the problem because once I changed the library with the types and db connections to esm I no longer had errors with any of the solutions.

**Comment by siranweb** [comment]
I ran into the same error. My IDE tryed to import `SelectQueryBuilder` from `'kysely/dist/esm'`, which is not supported by my project. I just changed import from `'kysely/dist/esm'` to `'kysely'` and it was fixed.

I hope this helps someone
