### ISSUE TITLE
numInsertedOrUpdatedRows is not converted as an int or string (Postgresql)

### ISSUE THREAD

**Issue by MGMehdi** [kysely-org/kysely#1276]
Hello,
I was playing arround and tried this 
```js
const insertedDoor = await db
    .insertInto("doors")
    .values(door)
    .onConflict((oc) => oc.doNothing())
    .execute();
  console.log(insertedDoor);
```
It return `[ InsertResult { insertId: undefined, numInsertedOrUpdatedRows: 1n } ]` and `numInsertedOrUpdatedRows` is still a bigint despite putting this like in the documentation
```js
const int8TypeId = 20;
// Map int8 to number.
pg.types.setTypeParser(int8TypeId, (val) => {
  return parseInt(val, 10);
});
```
But if I return only the id from the insert or if I do a `count` it return correctly a number

**Comment by igalklebanov** [comment]
Hey 👋

`pg-types` handles result set value parsing. The number of affected rows returned by various databases/drivers is not part of that, and is mapped to `BigInt` by Kysely since a table can hold more than `Number.MAX_SAFE_INTEGER` records and a query can potentially affect all records.

**Comment by MGMehdi** [comment]
Oh ok thanks for explanation @igalklebanov !
