### ISSUE TITLE
`where in` with empty array produces invalid SQL

### ISSUE THREAD

**Issue by rafaelalmeidatk** [kysely-org/kysely#1284]
Related issue comment: https://github.com/kysely-org/kysely/issues/447#issuecomment-1789788846
Reproduction of the issue: https://old.kyse.link/?p=s&i=rdvxZDgcBQ7FzTmMG4Cx

When using `where('foo', 'in', [])` I would expect the query builder to not produce invalid SQL. This is the behavior with knex:

```js
const query = knex
  .select("id", "last_name")
  .from("user")
  .whereIn("last_name", [])

query.toSQL().sql
// 'select "id", "last_name" from "user" where 1 = ?'
// bindings: [ 0 ]
```

Having to check the length of the array to conditionally add the `where` clause considerably increases the complexity of the query specially in situations where you have more than a simple `where`:

```js
// The desired API
const users = await ky
  .selectFrom("users")
  .selectAll()
  .where((eb) => eb(sql`lower(email)`, "in", emails).or("phone", "in", phones))
  .execute()

// What needs to be done today
const users = await ky
  .selectFrom("users")
  .selectAll()
  .where((eb) => {
    const ors: Expression<SqlBool>[] = []

    if (emails.length) {
      ors.push(eb(sql`lower(email)`, "in", emails))
    }
    if (phones.length) {
      ors.push(eb("phone", "in", phones))
    }

    return eb.or(ors)
  })
  .execute()
```

FWIW kysely already does something similar when both conditions in the above query are `false`:

```js
const emails = []
const phones = []
const query = ky
  .selectFrom("users")
  .selectAll()
  .where((eb) => {
    const ors: Expression<SqlBool>[] = []

    if (emails.length) {
      ors.push(eb(sql`lower(email)`, "in", emails))
    }
    if (phones.length) {
      ors.push(eb("phone", "in", phones))
    }

    return eb.or(ors)
  })
  .compile()

query.sql
// 'select * from "users" where 1 = 0'
```

**Comment by rafaelalmeidatk** [comment]
Hi @koskimas first of all I appreciate the work on the library, I don't think this issue is a duplicate. The other issue I linked was related to accepting anything other than an `array` as the 3rd argument, and the comment I linked to was related to providing type errors for empty arrays which you said is not worth it and I agree.

What I am proposing here is that kysely correctly fixes the query output when an empty array is provided to `where in` because it is a cognitive overload to always be aware of empty arrays when using `where` (which is almost aways possible when doing some filtering). Let me know if you still think this is not common enough and should be handled on the user side

**Comment by igalklebanov** [comment]
Hey 👋

This is a duplicate. There's even a pull request with a plugin that aims to handle this.

**Comment by rafaelalmeidatk** [comment]
Hey thanks for commenting about the plugin, I found the PR :pray: Sorry for not finding the other issue (#709) before, for some reason it didn't show up the first time I searched it. Having this as a plugin would be great, for the time being I am using this:

```js
export function whereInNonEmpty<
  DB,
  TB extends keyof DB,
  RE extends ReferenceExpression<DB, TB>,
>(
  eb: ExpressionBuilder<DB, TB>,
  lhs: RE,
  rhs: ValueExpressionOrList<
    DB,
    TB,
    ExtractTypeFromReferenceExpression<DB, TB, RE>
  >,
): Expression<SqlBool> {
  if (Array.isArray(rhs) && rhs.length > 0) {
    return eb(lhs, "in", rhs)
  } else {
    return sql`false`
  }
}

// .where((eb) => whereInNonEmpty(eb, 'foo', []))
```
