### ISSUE TITLE
Use eb.fn() inside eb.and()

### ISSUE THREAD

**Issue by bbohec** [kysely-org/kysely#1287]
I would like to make the following join query part:

```sql
...
LEFT JOIN departements d 
  ON values.gps IS NOT NULL
  AND ST_Contains(d.shape, values.gps);
...
```

I'm currently facing a typescript error and `eb.and` with the following kysely query builder:
```typescript
.leftJoin("public_department_region", (join) =>
  join.on((eb) =>
    eb.and([           // TS Error
      eb("values.gps", "is not", null),
      eb.fn("ST_Contains", [
        "public_department_region.shape",
        "values.gps",
      ]),
    ]),
  ),
),
```

Using eb.fn directly in join eb seems ok but I have not tested the execution yet:
```typescript
.leftJoin("public_department_region", (join) =>
  join.on((eb) =>
   eb.fn("ST_Contains", [
      "public_department_region.shape",
      "values.gps",
    ]),
  ),
),
```

Could you confirm I can use FunctionModule inside JoinBuilder and inside OperandExpression?
Sorry if I've made mistakes about builders names.

Meanwhile I will try with the sql`` pattern.

Thanks.

**Comment by igalklebanov** [comment]
Hey 👋 

Try `eb.fn<boolean>(...)`.

**Comment by bbohec** [comment]
That's perfect thanks @igalklebanov
