### ISSUE TITLE
bug: and typescript syntax allows for arbitrary deep array structures

### ISSUE THREAD

**Issue by damienwebdev** [kysely-org/kysely#1288]
```ts
const firstName = 'Jennifer'
const maxAge = 60

const persons = await db
  .selectFrom('person')
  .selectAll('person')
  .where(({ eb, or, and, not, exists, selectFrom }) => and([]))
  .execute()
```

this is strange but valid.

```ts
const firstName = 'Jennifer'
const maxAge = 60

const persons = await db
  .selectFrom('person')
  .selectAll('person')
  .where(({ eb, or, and, not, exists, selectFrom }) => and([[[[]]]])) <--- This line.
  .execute()
```

This is strange and invalid, but passes a typescrip check.

This example is not a perfect reproduction of how I came across the issue, but this leads to the error:

```
this[#visitors][node.kind] is not a function
```

**Comment by igalklebanov** [comment]
Hey 👋 

The first example - this can be blocked at compile-time, but would come with a DX penalty, a compile-time performance hit, and more complex types to maintain - harder to contribute to the project as an outsider. At this point, we don't want to handle this at compile-time.

The second example - seems like a problem on your end as it does error in the [playground](https://kyse.link/aQKTn).
