### ISSUE TITLE
`ExpressionBuilder` allows invalid fields in update/set, causing runtime failures

### ISSUE THREAD

**Issue by johnpyp** [kysely-org/kysely#1299]
Most set/update update styles in Kysely work as expected, disallowing extraneous properties not present in the schema, as otherwise the queries will fail when executed.

Unfortunately, there's one case that is quite natural to use, which dangerously doesn't check for this: using an ExpressionBuilder function which returns an object -
```ts
await db
  .insertInto("person")
  .values({ 
    first_name: "first name", 
    last_name: "last name",
    gender: "male"
  })
  .onConflict((oc) =>
    oc.column("first_name").doUpdateSet((eb) => ({
      first_name: "asdf",
      asdf: "asdf"
    }))
  )
  .execute();
```

Full example: https://kyse.link/klyC9

In the above example in the `onConflict` clause, the `first_name` property is required, and as expected, if *no valid fields are present*, then the query fails.

However, once at least one other valid property is in the object, you can add any other extraneous properties and they won't fail typechecking. This is incorrect and will lead to runtime query failures (my team uses this pattern extensively, and were just bitten by it :cry: ).

The example above is the exact case that my team ran into, but it looks like it also applies to cases like `set((eb) => ({ ... })`. 

---

To mitigate this issue, you can pass the object directly to `doUpdateSet` instead, but you'll have to use a `(eb) =>` closure *in every field* instead, which makes it the much less appealing option (for example when doing mass `eb.ref("excluded.field"`).

**Comment by igalklebanov** [comment]
Hey 👋

This is part of a long standing TypeScript [issue](https://github.com/microsoft/TypeScript/issues/12936#issuecomment-2156717446).

**Comment by igalklebanov** [comment]
I'm afraid this won't work. `sp` is not "bound", it doesn't know what it should expect.

There are probably some [hacks](https://github.com/kysely-org/kysely/pull/229) out there, but they would hurt compile-time performance for everyone, they don't cover all cases probably, and they're not future-proof and could break with any new TypeScript version.

There is hope in catching these with `typescript-eslint` if this [proposal](https://github.com/typescript-eslint/typescript-eslint/issues/10234) gets through.

**Comment by t-unimorphic** [comment]
I ran into a similar issue, so I created a ESLint plugin to catch it https://bitbucket.org/unimorphic/eslint-plugin-no-excess-properties

**Comment by JClackett** [comment]
The Updateable type can just implement something like this:

```ts
type NoExtraPropertiesStrict<T, K extends PropertyKey = PropertyKey> = T & {
  [P in K as P extends keyof T ? never : P]?: never;
};
```

And now it only allows the exact properties
