### ISSUE TITLE
insert into fails

### ISSUE THREAD

**Issue by oscar-skillup** [kysely-org/kysely#1301]
Hey
I'm using kysely: "^0.26.3" with a postgres database
```
import { Kysely, PostgresDialect, type Transaction } from "kysely";

const dialect = new PostgresDialect({
  pool,
});

const kysely = new Kysely<any>({
  dialect,
});

...
await kysely.insertInto('some_table').values(vals).execute();
````
it fails when vals array has more than 10000 entries
after I change my code and splitting the array into chunks of 1000, I don't get any error
```
function splitArrayIntoChunks(vals: any[], chunkSize: number) {
  const chunks = [];
  for (let i = 0; i < vals.length; i += chunkSize) {
    chunks.push(vals.slice(i, i + chunkSize));
  }
  return chunks;
}

const chunks = splitArrayIntoChunks(vals, 1000);
for (const chunk of chunks) {
    await kysely.insertInto("some_table").values(chunk).execute();
}
```
This proof that there is a limit of size for the values argument.
Also in the log errors I get a insert into sql query truncated

**Comment by comphonia** [comment]
DBs have a limit on how many rows you can insert in one transaction (that might be what's happening here). So you should probably research to know what that limit is. I know it's only 1_000 for ms sql server. 

You have a good solution with splitArrayIntoChunks!

**Comment by igalklebanov** [comment]
Hey 👋 

As @comphonia suggested, not related to `kysely`.
