### ISSUE TITLE
BUG: Filter for nullable booleans SQLite not working

### ISSUE THREAD

**Issue by priska96** [kysely-org/kysely#1305]
Hey there,

I encountered a weird problem in my project while filtering for boolean fields.

I have a table `PatientTable` that has boolean fields `created, staged, deleted, archived` which can be null as well., except for `archived`. 

When I try to filter for patients that can be deleted I want to get all patients, where created and staged are not true. So being null or false is fine. Also they should be archived.

I made a little example in the play ground. I wasn't sure how to get results from the filtering, but at least you can see my queries. It's the very last function called `query`.

When I run this in my project I don't get any values which is as far as I figured out due to some of the values being null.

[playground](https://kyse.link/#cN4IgpgJglgLg9gJwM4gFyhgTwA5jSKAW20RgAJgAdAOzLIHExqwEBDGSAGhroGUwANmADGMVgCMh3WmQCq2COzASpPMgElqSFmMlhpdAFK8A8gDkAwnAEBXQtQAqOfTQC+ZAGYI4hMpRAA1pjaApj+ANw0NGAAHiQI5FDUHAgerMJgZAAi7BKs2hRqsSnUrAJIqGQAojElZQ4qYJEy2OxQTDCVAAptHQ16za7RcaRkSSlpGdW1LKUC-UKFMsWzZeoQlUgwCEkA5s10AlAAbnsAggjKFWTG5la29k64ADxbO9S7ANoAugB8g1FmCMEmNkixJpkejB2skFpkqC1esl1pttnsDmRSoQwKj3vs1MJLkoNmRxHBrMpaAAfTE2AQCDFbVi7SCVMkU1jU2n0jEQQRgDgk9lCTlkGnUOkMtSsBDCAAWJ1ZpPJIuoGIA7nAbNQIABZTnMlgoshvdFqRQca63SzWOyOZzPXWYHKW-5uQFYXBkJ0usBIMgAXiWdCZCVxZpkHiSUCQcvDH0GzRAnBAAEcbCxMPgiPFyMAyLFsJckEgoHBqAAhGxQAR8hCcE2pgRkdxeHx+QLBQRhEDNHOjfMuvIFVveXz+T1gAC0kFgiAigNY6tYsDIEHEagAdEltAlNPAABT+VrQjr+ACUW+OZQzSAPnzUdARdBfZBPMJgxv8EmEAEZ-AYr6Yqw2KVP4ZwVhYAGPi+hLKIKlTbBmgGvkyLIkmk5QuDIr58kICHcgIKEvjK8qKhhZTaMRdCatqeoGiyCBfiA-7JjBdAWn6lTWpupofFAHiYAez5ASGYhhh2ABMAAMkkACxTr+kmKQAHA4SmoNJ0madJABa0E4UBUbUDGcZSbJClKVOklqRpWk6fpbGGXQrjnsRrjESJr7vh0zE-pJBmiViOIdlkVQAGKBUBcHEohCDIexJpiOhlSYVRiV4QKSoSvS1FkKRCrHEqaXYaJtE6vqpSMcxrF5ZxVqmGYvFovxgnCYlYkyp05nyYpym-rZkk6Q5UWicZplgSAMm9VZNnqUN9laY5eWue5nmJT5yIkt+4jCAAzKNL7BZN9AABLqIddAxQRSGlUBaHFZRd24fyBE5URiUFeRqVPXl5X0VVRrbSAfKXWuSgNeYzV4gJQlefd4ndf402Wf1g3DUtYN0ONsaTSjfXWeji16WDq0wR5ajfJeMibrEIg2BwB7ns0NDCOWWxkCyMBmHAMBZK9kCBvly6ruuW4hCIMDhWOR4gJtMAXlu6pyiwYCy9dkAAR2AZa7d1N0Lx-KiGc9JM1udPCAzavM4CbNaBSm4CHAuyy8WWtczzfMCxAnzSVTLOlCL5BizTO46PucCyysCBzEgis09eth+veMHw3Q0dzH5u21YlRynB8FxXNxjXQ3ssMpyAP5a-4fIeP4VNrZT+tkLTMT04zNvUKz7PkHn5xEkL-i7AqC5d4HK7BxuNM2AoShwlHMwx5R8cG9oMDtYZfcF0S1wHmA4jnoGvyJUgTYAAYAFZIOWAD6YcJAeADkW+7IX+SPw2j8ACSfAAxN8H8yBf2AC-N+rkz6AVckrFWlwF51AEOsauIAdbJg7D+VizdW7t2tgHO2HN-qVUNDsCA-ogwPhYkgquqCa5gHrrgnuZB0yZiFgeXQQgzAgRCgEMAmA4AeGyLkcQ+QwCHwDL8YMZA8HkH3kLQsxZSzlirDWOszwhxCKomQScfDNGNA4diX4TMMT4XyqIRUJhxAX0lkgGo2BZHiFbjGGAd4YL703JyCAKdnIFnEOrIkgokEAEIUENj1puRAe8fH+AehAQJwTNHxREW5RK+9ZZfSKjE6hyDdYJKSYZBuahO50AEmQA8BCGIsCgCQgA-I7JguwYBykPvDKRZAykfBYDYuxDitjOK8Sk-wbSiGIMydQXmoItaDMYpUpAuTXyFJIqYoq5jLGiGsXELp4TPjpGhEsixVibENjaYxGx-s1BDBkJcGANgY4mJ2WAZZ+y4iJkBOuQ2QhRDSx8LLeWK8W4S2NqbTBytVYHiYQgISx4kQKxAOeTBiA6wViEqfAQl9r7UBvsUNgogDz1U-l-TcOM5SP3PBAtBSBhC-KwZbDuSYPIgygGUSW+BkWwDwCmIIIQszoBAJOfAyVkwgGCvgaSm5JIAHZNwAFYQCuFcEAA)

I hope you can recreate this issue and have som tips for me how I can achieve this filtering.

Best regards,

**Comment by igalklebanov** [comment]
Hey 👋 

The SQL you're trying to build seems off. e.g. `exists` usage seems excessive or wrong, comparison with `true`/`false` instead of `0`/`1` (might be ok in newer SQLite versions).

Try ditching the `exists` and running again.

Have you tried writing it outside Kysely and running it directly with `better-sqlite3`?

**Comment by priska96** [comment]
Hey,
Thank you for your quick answer!!
opps, sorry, I didn't see the exists in the playground. In my project I already removed it. I tried writing it in raw sql with the raw template tag, but that as well didn't give me the results I am looking for.

I'll try running it outside kysely and will get back to you shortly!

**Comment by priska96** [comment]
Hey,

I found my error.

I didn't know that but 

> SQLite evaluates this as NULL because NULL cannot be compared to 'true'. So explicitly account for NULL values in your query

So if I want to filter for 'created != true' and it is a field that can be null as well I need to check that too. So I should filter like this

`eb("created", "is", null).or("created", "!=", true)`
