### ISSUE TITLE
Support `MERGE` SQL command

### ISSUE THREAD

**Issue by rubenferreira97** [kysely-org/kysely#203]
What is `MERGE`?
"A relational database management system uses SQL MERGE (also called upsert) statements to INSERT new records or UPDATE existing records depending on whether condition matches. It was officially introduced in the SQL:2003 standard, and expanded in the SQL:2008 standard."

Some DBMSs are currently supporting the MERGE command:

PostgresSQL: https://www.postgresql.org/docs/current/sql-merge.html
SQL Server: https://learn.microsoft.com/en-us/sql/t-sql/statements/merge-transact-sql
Oracle: https://docs.oracle.com/database/121/SQLRF/statements_9017.htm

Example from PostgresSQL: 
"Attempt to insert a new stock item along with the quantity of stock. If the item already exists, instead update the stock count of the existing item. Don't allow entries that have zero stock.".
```sql
MERGE INTO wines w
USING wine_stock_changes s
ON s.winename = w.winename
WHEN NOT MATCHED AND s.stock_delta > 0 THEN
  INSERT VALUES(s.winename, s.stock_delta)
WHEN MATCHED AND w.stock + s.stock_delta > 0 THEN
  UPDATE SET stock = w.stock + s.stock_delta
WHEN MATCHED THEN
  DELETE;
```

**Comment by igalklebanov** [comment]
This one is like the mothership of mutation queries ain't it? 😆

**Comment by igalklebanov** [comment]
Now that mssql dialect is in the core, this query is the only way, I know of, to perform upserts in this engine, outside of if-else in what seems to be stored procedures.
