### ISSUE TITLE
Support custom `NoResultError`s to be passed globally.

### ISSUE THREAD

**Issue by igalklebanov** [kysely-org/kysely#216]
raised by Cristian Da Silva on discord.

Currently custom `NoResultError`s can only be passed per query execution using `.executeTakeFirstOrThrows(...)` arguments.

Allowing to pass a global custom error or its factory, perhaps in `Kysely`'s constructor parameters, could be a nice QoL enhancement.

**Comment by koskimas** [comment]
I don't think we should add this. The custom error in `executeTakeFirstOrThrows` is already a bit hacky and we should consider removing it alltogether instead of making it more complex.
