### ISSUE TITLE
Support [cte] as materialized (...)

### ISSUE THREAD

**Issue by rccoe** [kysely-org/kysely#246]
Since Postgres 12, there's now the ability to tell Postgres to MATERIALIZE a CTE, this can have significant performance benefits downstream. Something as simple as this

```
db.with("cte", (qb) => qb.selectFrom("user").select("name")).materialized()
```

Would generate
```
WITH cte AS MATERIALIZED (select name from user)
```

Likewise `.materialized(false)` could generate ` AS NOT MATERIALIZED `

**Comment by igalklebanov** [comment]
Hey 👋 

The suggested API does not fit in:

1. it modifies a previous method in the chain, out of context. Kysely API at the topmost level, only has the major clauses. Nested clauses usually end up in sub-builders passed to args.

2. `.materialized(false)` goes against Kysely's philosophy of being as close to writing sql as possible. A `notMaterialized()` is the way to go.

---

The right approach would be to either add `withMaterialized` & `withNotMaterialized` to `QueryCreator` or add a 3rd argument to `with` & `withRecursive` that is passed a `WithBuilder`-ish instance that allows to modify the `with` clause.

**Comment by koskimas** [comment]
@igalklebanov The option 4 is the best IMO. I'll implement it.
