### ISSUE TITLE
More fine-grained transaction API with savepoints?

### ISSUE THREAD

**Issue by koskimas** [kysely-org/kysely#257]
```ts
try {
  const trx = await db.begin().isolationLevel('serializable').execute()
  await trx.insertInto(...).execute()

  await trx.savepoint('foobar')
  try {
    await trx.updateTable(...).execute()
    await trx.updateTable(...).execute()
  } catch (err) {
    await trx.rollbackToSavepoint('foobar')
  }

  await trx.commit()
} catch (err) {
  await trx.rollback()
}
```

**Comment by igalklebanov** [comment]
Great idea! 💡 

- I personally prefer `.startTransaction()` over `.begin()`, clearer intent. The first is usually aliased by the latter in documentations.

- We should probably also support `.releaseSavepoint(name)`.

- It's weird that some of the methods fire immediately without `.execute()`. Let's allow compiling and executing these with the usual methods?

**Comment by koskimas** [comment]
Excellent points!

So here's the revised API:

```ts
try {
  const trx = await db.startTransaction().setIsolationLevel('serializable').execute()
  await trx.insertInto(...).execute()

  await trx.savepoint('foobar').execute()
  try {
    await trx.updateTable(...).execute()
    await trx.updateTable(...).execute()
    await trx.releaseSavepoint('foobar').execute()
  } catch (err) {
    await trx.rollbackToSavepoint('foobar').execute()
  }

  await trx.commit().execute()
} catch (err) {
  await trx.rollback().execute()
}
```

> Does this replace current API,
We could still provide the old API as a convenience. Most of the time people would probably still want to use that one.

**Comment by igalklebanov** [comment]
Another good thing about this, is that it allows compiling transactions, e.g. for display in the browser.
We had someone ask about this a while back on discord..

**Comment by koskimas** [comment]
Actually that's not the case 🤔 We have this API in the driver

```ts
  /**
   * Commits a transaction.
   */
  commitTransaction(connection: DatabaseConnection): Promise<void>

  /**
   * Rolls back a transaction.
   */
  rollbackTransaction(connection: DatabaseConnection): Promise<void>

  /**
   * Releases a connection back to the pool.
   */
  releaseConnection(connection: DatabaseConnection): Promise<void>
```

Dialects have the ability to start transactions however they want. For example the [kysely-data-api](https://github.com/serverless-stack/kysely-data-api/blob/f09b3b7a3706676e2753bc63c6b1e5b3ea8b7f28/src/data-api-driver.ts#L28) does a "start transaction" HTTP request instead of running a `BEGIN` SQL command. Same for commit and rollback.

We can't allow those to be compiled since some dialects in fact don't compile anything.

**Comment by igalklebanov** [comment]
I see, yep that wouldn't work for such dialects..

Can't we make the new API fully compilable, not requesting directly from the driver? So dialects that actually perform a sql query to begin a transaction can enjoy this..

**Comment by koskimas** [comment]
I don't see how? What would `compile` return for dialects that just call a method and don't execute any SQL?

**Comment by igalklebanov** [comment]
Not sure, maybe dummy response such as `{ sql: '', parameters: [], query: { kind: 'StartTransactionNode' }}`?

**Comment by igalklebanov** [comment]
Could we make these driver methods optional?

- If they are not implemented (which should be the case for all 3 built-in dialects), beginning a transaction (the old API) defaults to creating a `StartTransactionNode`, compiling and executing.
- If they are implemented, compilation will just return some dummy response.

If this makes sense, a rename that describes this "non-sql begin transaction method" situation would make sense.

**Comment by koskimas** [comment]
Optional driver methods could make sense. But on the other hand, jumping through too many loops to allow the user to compile things that will __always__ be the string `commit` or `rollback` doesn't seem too important.

**Comment by igalklebanov** [comment]
Yeah this is not really worth it, for just 1-2 sql statements that are very predictable. Our consumers could simply prepend them manually if they want to display them. 👍

**Comment by nikeee** [comment]
JS is set to get explicit resource management:
https://github.com/tc39/proposal-explicit-resource-management (reached stage 3).

There is also an async Version in the planning:
https://github.com/tc39/proposal-async-explicit-resource-management

I think transactions could really benefit from this. They are also listed as a use case:
```ts
async function transfer(account1, account2) {
  using await tx = transactionManager.startTransaction(account1, account2);
  await account1.debit(amount);
  await account2.credit(amount);

  // mark transaction success if we reach this point
  tx.succeeded = true;
} // await transaction commit or rollback
```

Maybe this is something you'd consider in the design of a transaction API in the future. Since the sync version of the proposal was accepted, chances are that we'll also get an async version. :)

**Comment by igalklebanov** [comment]
> JS is set to get explicit resource management: [tc39/proposal-explicit-resource-management](https://github.com/tc39/proposal-explicit-resource-management) (reached stage 3).
> 
> There is also an async version in planning: [tc39/proposal-async-explicit-resource-management](https://github.com/tc39/proposal-async-explicit-resource-management)
> 
> I think transactions could really benefit from this. They are also listed as a use case:
> 
> ```ts
> async function transfer(account1, account2) {
>   using await tx = transactionManager.startTransaction(account1, account2);
>   await account1.debit(amount);
>   await account2.credit(amount);
> 
>   // mark transaction success if we reach this point
>   tx.succeeded = true;
> } // await transaction commit or rollback
> ```
> 
> Maybe this is something what would be interesting for the design of a transaction API in the future. Since the sync version of the proposal was accepted, chances are that we'll also get an async version. :)

This feature is great for javascript, but redundant in Kysely, since the current transaction API already abstracts away commit & rollback so consumers can focus on content.

This issue's purpose is to provide consumers with a more fine-grained control over transactions. The demographic for this feature wants to call `.commit()` and `.rollback()` themselves.

> ```ts
>   tx.succeeded = true;
> ```

This is such a footgun. Hate it.

**Comment by Alex-Yakubovsky** [comment]
This would also be handy for parallelizing automated tests (each in their own transaction) that talk to the database without having them commit the data. Currently, I truncate tables so the tests have to run single order. With finer grained controls over rollbacking back I can rollback after each test.

**Comment by rdgout** [comment]
Is there any update regarding this? 
In our application we would like to use transactions but we would like to perform every query as they come into our streaming system.  
The current API would only allow us to batch a list of queries and then perform them all at once by way of
```pseudocode
kyselyClient.transaction()
    .execute(async (trx) => {
        queries.map((query) => trx.execute(query))
    });
```

However, we would prefer to be able to use the connection for the transaction to perform each query as it comes in.
This way we can validate the query is not invalid, by trying to execute it on the connection, and only need to perform the commit when we reach the threshold or a predefined time.

Some pseudocode would be:

```
class TransactionBatcher {
    addQuery(query: Query) {
        if (!this.transactionHasBegun) {
            this.kyselyClient.beginTransaction();
            this.transactionHasBegun = true;
        }

        try {
             this.kyselyClient.execute(query);
        } catch (e) {
             logger(`Found an error in query: ${query}`);
        }
    }

    commitQueries() {
         try {
             this.kyselyClient.commitTransaction();
         } catch (e) {
             logger('Could not commit query');
             this.kyselyClient.rollbackTransaction();
         }
    }
}
```

**Comment by ibnumusyaffa** [comment]
hope this is implemented soon

**Comment by koskimas** [comment]
You can achieve the same thing using the current API with a little bit of hacking.

```ts
function begin(db: Kysely<DB>) {
  const connection = new Deferred<Transaction<DB>>()
  const result = new Deferred<any>()

  db.transaction().execute(trx => {
    connection.resolve(trx)
    await result.promise;
  })

  const trx = await connection.promise;
  
  return {
    trx,
    commit() {
      result.resolve(null)
    },
    rollback() {
      result.reject(new Error('rollback'))
    }
  }
}

export class Deferred<T> {
  readonly #promise: Promise<T>

  #resolve?: (value: T | PromiseLike<T>) => void
  #reject?: (reason?: any) => void

  constructor() {
    this.#promise = new Promise<T>((resolve, reject) => {
      this.#reject = reject
      this.#resolve = resolve
    })
  }

  get promise(): Promise<T> {
    return this.#promise
  }

  resolve = (value: T | PromiseLike<T>): void => {
    if (this.#resolve) {
      this.#resolve(value)
    }
  }

  reject = (reason?: any): void => {
    if (this.#reject) {
      this.#reject(reason)
    }
  }
}
```

**Comment by codepunkt** [comment]
@koskimas Is there a way to achieve individual test cases running in transactions? This would have to support nested transactions in case the business logic that's being tested has transactions itself, probably in the form of savepoints.

**Comment by subframe7536** [comment]
crude but works in sqlite
```ts
export function createSavePoint(db: Kysely<any>, name?: string) {
  const _name = name || `sp_${new Date().getTime()}`
  return {
    save: async () => {
      await sql`savepoint ${sql.raw(_name)}`.execute(db)
    },
    release: async () => {
      await sql`release savepoint ${sql.raw(_name)}`.execute(db)
    },
    rollback: async () => {
      await sql`rollback to savepoint ${sql.raw(_name)}`.execute(db)
    },
  }
}
```

```ts
await db.transaction().execute(async (trx) => {
  const s1 = createSavePoint(trx)

  await s1.save()
  await trx.insertInto('test').values({ person: `test ${Date.now()}` }).execute()
  
  const s2 = createSavePoint(trx)

  try {
    await s2.save()
    await trx.insertInto('test').values({ person: `test ${Date.now()}` }).execute()
    await s2.rollback()
    // throw new Error('test error')
    s1.release()
  } catch (error) {
    s1.rollback()
  }
})
```

**Comment by shirakawayohane** [comment]
> Is there a way to achieve individual test cases running in transactions? This would have to support nested transactions in case the business logic that's being tested has transactions itself, probably in the form of savepoints.

I think this is a very important perspective. When testing functions that use transactions by utilizing transaction rollback, it is ideal to support nested transactions so as not to interfere with the internal transactions of the function. Therefore, supporting nested transactions, such as in the form of savepoints, seems ideal to me.

```ts

function doSomethingUsingTransaction() {
  db.transaction().execute(tx => {
    ...
  })
}

// test code
export const testTrx = async <T>(fn: (tx: Transaction<DB>) => Promise<T>) => {
  let result: T;
  try {
    await db.transaction().execute(async (tx) => {
      result = await fn(tx);
      throw new TestTrxRollback();
    });
  } catch (e) {
    if (!(e instanceof TestTrxRollback)) throw e;
  }
  return result!;
};

describe('check something', () => {
  it('should rollback', () => {
    testTrx(async (tx) => {
      doSomethingUsingTransaction(tx);
    });
  });
});
```

**Comment by shirakawayohane** [comment]
@igalklebanov  @koskimas 
Do you have any updates or feedback?

**Comment by subframe7536** [comment]
@shirakawayohane #962

**Comment by jeffreypeoples** [comment]
> @shirakawayohane #962

Curious:  are nested transactions going to be possible with that pr? Specifically for my use case I have been testing a server that has itself transactions,  but passing in a transaction into my createServer function to act as the parent db connection doesn't work since nested transactions are not allowed. I get `"calling the transaction method for a Transaction is not supported." `I want to do this so that I can just rollback any changes done while working with integration tests, both mutations performed by the test itself and mutations performed by the server being tested, some of which are themselves transactions. I'd like to just rollback everything after each test, or if the test fails. Is that something this PR will enable?  Right now Im manually clearing whatever data is mutated by the tested server.  Thx.

**Comment by igalklebanov** [comment]
@jeffreypeoples 

Yes, in the form of savepoints.

**Comment by shirakawayohane** [comment]
@igalklebanov 
While it is true that with Savepoint, we can use a transaction during testing, but roll back all the data under test at the end, savepoint perceives that it is in a transaction, which makes it difficult to abstract the process.

Do you have any answers or initiatives regarding this problem awareness?

**Comment by aq1018** [comment]
I see https://github.com/kysely-org/kysely/pull/962 is merged. 

Can we please have a new release?

**Comment by BurningEnlightenment** [comment]
Can the new API be extended to support vendor extensions like sqlite3's [`IMMEDIATE`]?

[`IMMEDIATE`]: https://www.sqlite.org/lang_transaction.html

**Comment by igalklebanov** [comment]
> Can the new API be extended to support vendor extensions like sqlite3's [`IMMEDIATE`]?
> 
> [`IMMEDIATE`]: https://www.sqlite.org/lang_transaction.html

Different issue. Probably.

**Comment by romanstetsyk** [comment]
I'm looking forward to a new release now that #962 is merged.
