### ISSUE TITLE
Allow passing in other types to `$.if`

### ISSUE THREAD

**Issue by mikewuu** [kysely-org/kysely#271]
Currently `$.if` only accepts a `boolean`. This means we're having to write a separate check, then force-cast, or set the value to an empty string to keep TS happy. Would be nice to pass other possibly `null`/`undefined` values to `$.if`, and then automatically get the non-null value back out in the callback.

```ts
$if<O2 extends O, T>(
    value: T | undefined | null,
    func: (qb: this, condition: T) => SelectQueryBuilder<DB, TB, O2>
  ): SelectQueryBuilder<DB, TB, MergePartial<O, O2>> {
    if (value) {
      return func(this, value)
    }
```

**Comment by koskimas** [comment]
I personally prefer to just use `!` in these cases

```ts
.$if(something, (qb) => qb.where('id', '=', something!))
```

but I guess we could pass in the value as the second argument. @igalklebanov any thoughts?

**Comment by mikewuu** [comment]
Me too. Though we try to avoid force-casting when possible. 

Have a PR ready. If this sounds ok, would love to have a go at contributing 🙂

**Comment by igalklebanov** [comment]
> I personally prefer to just use `!` in these cases
> 
> ```ts
> .$if(something, (qb) => qb.where('id', '=', something!))
> ```
> 
> but I guess we could pass in the value as the second argument. @igalklebanov any thoughts?

We could make 1st argument an immediate value OR a function, check for truthy, and pass the value/result to callback as its 2nd argument.

Sounds good to me.

`!` can be a problem in super strict repositories.

**Comment by koskimas** [comment]
Cool! @mikewuu a PR would be much appreciated 👍
