### ISSUE TITLE
add support for nested `with...select` when using set operations (e.g. `union`).

### ISSUE THREAD

**Issue by BlakeB415** [kysely-org/kysely#285]
I've run into a few issues with the union and unionAll functions. I’m using the Postgres dialect.

The ability to wrap the union SQL in parentheses, as using "with" inside of a union will result in a syntax error.

~It would also be great if there could also be a way to provide an array of expressions into the function so we can avoid using a for loop.~

**Comment by igalklebanov** [comment]
Hey 👋 

> The ability to wrap the union SQL in parentheses, as using "with" inside of a union will result in a syntax error.

Can you share the SQL query you're trying to build? Just so we fully understand eachother..

> It would also be great if there could also be a way to provide an array of expressions into the function so we can avoid using a for loop.

I've opened a separate issue to help track this.

**Comment by BlakeB415** [comment]
We reworked our queries to use selectFrom() subqueries instead of .with() and it works fine now. I guess we were misusing them anyway though.

with() only causes a syntax error when inside a union.

**Comment by igalklebanov** [comment]
I see, thank you for updating.

**Comment by BlakeB415** [comment]
> Hi 👋 Actually, PostgreSQL supports `with` keyword in `union` and `union all` with parentheses. For example:
> 
> ```sql
> SELECT "id" FROM "user"
> UNION ALL
> (
>   WITH "with_user" AS (
>     SELECT "id" FROM "user"
>   )
>   SELECT "id" FROM "with_user"
> )
> ```
> 
> Currently kysely do not wrap subquery with parentheses, so there is a syntax error. https://wirekang.github.io/kysely-playground/?p=h&i=eyJreXNlbHlWZXJzaW9uIjoiMC4yMy4zIiwiZGlhbGVjdCI6InBvc3RncmVzIiwidHMiOiJpbnRlcmZhY2UgREIge1xuICB1c2VyOiBVc2VyVGFibGVcbn1cblxuaW50ZXJmYWNlIFVzZXJUYWJsZSB7XG4gIGlkOiBHZW5lcmF0ZWQ8c3RyaW5nPlxuICBmaXJzdF9uYW1lOiBzdHJpbmcgfCBudWxsXG4gIGxhc3RfbmFtZTogc3RyaW5nIHwgbnVsbFxuICBjcmVhdGVkX2F0OiBHZW5lcmF0ZWQ8RGF0ZT5cbn1cblxuY29uc3Qgd2l0aFF1ZXJ5ID0ga3lzZWx5XG4gIC53aXRoKFwid2l0aF91c2VyXCIsIChxYikgPT4gcWIuc2VsZWN0RnJvbShcInVzZXJcIikuc2VsZWN0KFtcImlkXCJdKSlcbiAgLnNlbGVjdEZyb20oXCJ3aXRoX3VzZXJcIikuc2VsZWN0KFwiaWRcIik7XG5cbnJlc3VsdCA9IGt5c2VseVxuICAuc2VsZWN0RnJvbShcInVzZXJcIilcbiAgLnNlbGVjdChcImlkXCIpXG4gIC51bmlvbkFsbCh3aXRoUXVlcnkpIn0%3D
> 
> Is it worth reopening the issue?

I would say so. There is no way to get around this other than by manually wrapping it via the sql template syntax. 

We should be able to pass a parameter to .union() to tell it to wrap in parentheses. Either that or wrapping the subquery in parentheses could be the default behavior.

**Comment by igalklebanov** [comment]
Reopened. Thank you for raising this.

**Comment by metallicusdev** [comment]
Running into same issue, need a way to wrap `unionAll` call in parenthesis, otherwise it leads to duplicate order by issue

**Comment by koskimas** [comment]
Since I'm not 100% sure how union and union all work, always wrapping subqueries to parentheses seems risky. Is the result always the same with the parentheses? I think there are some differences and sometimes leaving out parentheses is preferred.

If someone can convince me it's ok to always wrap, I'll do it.

**Comment by koskimas** [comment]
Hmm.. What we could do is allow a callback in `union` and `unionAll` that would enable you to use the new `parens` function:

```ts
db.selectFrom('person)
  .select('id')
  .unionAll((eb) => eb.parens(
    eb.selectFrom('pet')
      .select('id')
  ))
```

**Comment by koskimas** [comment]
Ok, this got solved. Even the three core dialects postgres, mysql and sqlite all treat parentheses differently. I found at least these differences:

 - postgres: allows parentheses, but not around a single query. You can wrap a set operation in paretheses to control their execution order when there are more than three set operations.
 - mysql: allows parentheses everywhere
 - sqlite: doesn't seem to allow parentheses at all in set operations

So it's clear we can't automatically wrap anything. I'll add the callback syntax mentioned above and that's the best we can/should do here.
