### ISSUE TITLE
Can/should we help protect our consumers from `DELETE FROM` without a `WHERE`?

### ISSUE THREAD

**Issue by igalklebanov** [kysely-org/kysely#298]
Hey 👋 

I think a good selling point for a safety-first library is to provide good defaults to protect its consumers from destroying their production environment by accident, or allowing a malicious actor to do so with ease.

`delete from` without a `where` clause is devastating if you don't have backups, and it can be quite easy to forget or delete a line of code.

The question is, can we protect our consumers from this? and if we can, should we protect our consumers from this?

WDYT?

**Comment by zmilonas** [comment]
I think it could be a strong case for an eslint rule introduction for such a thing. This could be potentially ery beneficial for active codebases since they would notice eslint warnings but it would not break backwards compatibility. One thing to sort out though for such a scenario would be thinking how to make sure people pull your eslint-rule - https://eslint.org/docs/latest/extend/custom-rules.

**Comment by igalklebanov** [comment]
Tackling this with tooling is the wrong approach imho. Nobody will use it, nobody's protected.

If we should protect..

Compile-time protection is possible via a generic flag on `DeleteQueryBuilder<..., W = false>`. Calling any of the `where` methods will return `DeleteQueryBuilder<..., true>`. `DeleteQueryBuilder.execute` can then return `never` if the flag is still false.

Runtime protection is possible via throwing a KyselyError if root operation node is a `DeleteQueryNode` without a where prop.

This does introduce a breaking change, and we're OK with that. It means any delete queries without a where, need to add a simple `.where(sql\`true\`)`. We could suggest consimers to use a truncate query instead.

**Comment by koskimas** [comment]
I'm not sure it's our job to guard the user from this particular footgun. We'd need to do the same for update queries too if we go down this road. 

At least any solution that involves adding a new generic argument for `DeleteQueryBuilder` and `UpdateQueryBuilder` is out of the question. We'd need to carry that extra parameter around everywhere making the types even more unreadable.

We could in theory return a different type of query builder from the `where` methods. Until the first call to any `where` method, we'd have some `DeleteAllQueryBuilder` (or something) that, for example, only has an `executeDangerously()` method.

**Comment by igalklebanov** [comment]
> We'd need to do the same for update queries too if we go down this road.

Yep!

> At least any solution that involves adding a new generic argument for DeleteQueryBuilder and UpdateQueryBuilder is out of the question. We'd need to carry that extra parameter around everywhere making the types even more unreadable.

Yeah I agree. It becomes overwhelming.

> We could in theory return a different type of query builder from the where methods. Until the first call to any where method, we'd have some DeleteAllQueryBuilder (or something) that, for example, only has an executeDangerously() method for execution.

I like this approach!

We could alternatively not have any execute methods on the initial query builder, forcing consumers to explictly:

```ts
.where(sql`true`)
```

I think `.clearWhere` presents a problem, there's no explicit indication the execution is dangerous. 💣

**Comment by koskimas** [comment]
> We could alternatively not have any execute methods on the initial query builder

I fear users wouldn't understand why there are not execute methods. Having a method starting with `execute` would remove this problem. We could make that method name "really scary" 😄. Let's add 👻 emoji to the name 😛

> I think .clearWhere presents a problem, there's no explicit indication the execution is dangerous. 💣
Do we return an initial query builder instance (with accumulated node) here?

Yeah I think we could return the initial query builder from `clearWhere`.

**Comment by koskimas** [comment]
I don't think this is worth the hassle. The best solution here is to have a different query builder class until there's some sort of `where` clause. Since we can't use inheritance (for complex type reasons), this would be a huge amount of code for a (IMO) minor improvement.
