### ISSUE TITLE
Creating a Sorted Index

### ISSUE THREAD

**Issue by nikeee** [kysely-org/kysely#301]
In a migration, I write
```ts
await db.schema.createIndex("user_created_at")
    .on("user")
    .columns(["createdAt"])
    .execute();
```

To build a simple index on `createdAt`.

This doesn't help when doing a range query on `createdAt`, so I want to create a sorted index to help with that.

Looking at the source, I _think_ the following is not supported (because `"createdAt DESC"` is not a column name):
```ts
await db.schema.createIndex("user_created_at")
    .on("user")
    .columns(["createdAt DESC"])
    .execute();
```

From the docs, there is `expression`, which might help with that:
```ts
await db.schema.createIndex('user_created_at')
    .on("user")
    .expression(sql`createdAt DESC`)
    .execute();
```

Is this the way to go or is there a better solution? I'm trying to be compatible with PG, SQLite and MySQL/MariaDB, so I try to avoid raw SQL.

**Comment by koskimas** [comment]
Raw SQL is the way.

> I'm trying to be compatible with PG, SQLite and MySQL/MariaDB, so I try to avoid raw SQL.

You'll have a hard time doing that with Kysely. Kysely doesn't abstract away any of the DB features. For example, if you have a migration like this on MySQL or sqlite:

```ts
  await db.schema
    .createTable('person')
    .addColumn('id', 'integer', (col) => col.autoIncrement().primaryKey())
```

It won't work on postgres since it doesn't have the `auto increment` keyword. You need this instead:

```ts

```ts
  await db.schema
    .createTable('person')
    .addColumn('id', 'serial', (col) => col.primaryKey())
```

**Comment by nikeee** [comment]
Thanks for clarification! :)

Not part of this issue, but can I write a single migration that contains conditional code to distinguish between the supported SQL dialects? This way, it would still be possible to use Kysely's API to build the schema while using DB-specific features.
