### ISSUE TITLE
Allow `regexp` as comparison operator

### ISSUE THREAD

**Issue by twiddler** [kysely-org/kysely#338]
Hey there! :wave: Is there a reason why `regexp` is not in [`COMPARISON_OPERATORS`](https://github.com/koskimas/kysely/blob/master/src/operation-node/operator-node.ts#L4)?

**Comment by koskimas** [comment]
No, but you can already use it like this `where('foo', sql`regexp`), '[abc]')`

**Comment by twiddler** [comment]
Doing that already. 👍
