### ISSUE TITLE
CHAR datatype

### ISSUE THREAD

**Issue by armpogart** [kysely-org/kysely#339]
Is support for `CHAR` datatype (fixed-length, blank padded) omitted on purpose? Both PostgreSQL and MySQL support that type.

Is it planned or will you accept PR on that?

**Comment by anirudh1713** [comment]
Hi @armpogart Are you working on this?
If not, @koskimas @igalklebanov Can I take this on?

Thank you.

**Comment by armpogart** [comment]
Hi @anirudh1713, I haven't had a time to prepare the PR, you can do that.

**Comment by koskimas** [comment]
@anirudh1713 Yes, go ahead 👍 

While you're at it, you could also add the `regexp` type to close [this issue](https://github.com/koskimas/kysely/issues/338).

**Comment by anirudh1713** [comment]
Thanks! I'll be starting this min-next week, I hope that is fine.

**Comment by anirudh1713** [comment]
I've raised PR for this. Sorry for the delay, I've been busy with work and other stuff.

Thank you so much folks for your patience.
