### ISSUE TITLE
[feature request] support object as parameter in where()

### ISSUE THREAD

**Issue by subframe7536** [kysely-org/kysely#344]
is it possible to filter line by object? like
```ts
interface db = {
  test: TestTable
}
interface TestTable = {
  filterParam: number
}
kysely.selectFrom('test')
  .where({ filterParam: 1 })
  .selectAll()
  .execute()
```

**Comment by koskimas** [comment]
What benefit does this offer over the current API? I couldn't think of one so I left this out for simplicity. I can consider adding this if you have a use case for this (other than "I prefer the syntax")

**Comment by subframe7536** [comment]
Thanks for your timely response! 

I'm currently migrating from my project that uses Knex, and I've used this syntax in many places throughout that project.

In addition, most of the input that I receive is in the form of an object. For example, the search request from my API always uses a POST method, and all of the parameters are packaged in the ResponseBody. Getting the parsed object and using it in where() is very convient. Manually splitting up the response body to parse the conditions would produce a lot of duplicate code, which I'd like to avoid if possible.

**Comment by igalklebanov** [comment]
I understand the usability inconvenience here.
But let's balance the conversation a bit..

Objects as inputs are currently flawed in TypeScript.
Nothing stops you from using an object with keys that do not exist in the current query's context.
Kysely won't protect you from runtime errors in such cases.
TypeScript hacks exist, but the compile performance hit is not worth it.

Introducing objects to the API that are compiled to non-object sql is not aligned with Kysely's WYSIWYG philosophy.
But, then there's `InsertQueryBuilder.values`.

**Comment by koskimas** [comment]
This has been requested many times in different places. I think we need to add it.

**Comment by koskimas** [comment]
Seems like we'll need a new method name for this 😞 If we overload `where` autocompletion breaks. When you start typing `where({` the current types think you are writing the three-argument overload and offer you all method names of all objects that can be provided in the first slot (`SelectQueryBuilder`, `Expression`, etc.). If we put the `where(object)` overload first, other things break.

This also means that `where(eb => eb({ ... }))` won't work, which is even more sad.

I'm thinking it might make sense to allow this instead:

```ts
where((eb) => eb.and({ ... }))
```

That overload would work and it would be obvious how the different filters in the object get combined. What do you think? @igalklebanov

**Comment by koskimas** [comment]
We could also add

```ts
where((eb) => eb.or({ ... }))
```

**Comment by igalklebanov** [comment]
@koskimas great idea! a lot more readable than any `.whereX` we were almost forced to add.
