### ISSUE TITLE
createNotResultError instead of NoResultErrorConstructor in executeTakeFirstOrThrow()

### ISSUE THREAD

**Issue by archimag** [kysely-org/kysely#359]
I would like use executeTakeFirstOrThrow() in many places but I have some problems with producing a correct error. I belive there should be  ability to pass a specific function to create NoResultError instead of constructor. Actually, it should be a closure that return specific Error object created with params from context.

**Comment by koskimas** [comment]
This is already implemented but not released yet.

**Comment by igalklebanov** [comment]
@archimag this has been released.
