### ISSUE TITLE
Kysely and Deno & MySQL Driver

### ISSUE THREAD

**Issue by mrtornado** [kysely-org/kysely#360]
Anybody already written a MySQL driver to work with Kysely in Deno ? Or is that even needed anymore ? Sry my programming skills are bad  and I can't write it for myself :)

**Comment by mrtornado** [comment]
I managed to create one with the help of chatgpt :) for anybody who needs something like this here it goes. I don't know how good it is, but it's working for me :

`import { Client, ClientConfig } from "mysql";
import {
  CompiledQuery,
  DatabaseConnection,
  Driver,
  QueryResult,
  TransactionSettings,
} from "kysely";

type QueryArguments = unknown[];

export class MySQLDriver implements Driver {
  readonly #connectionMutex = new ConnectionMutex();

  #client?: Client;
  #connection?: DatabaseConnection;

  db_conn_info: ClientConfig; // MySQL connection info

  constructor(conn_info: ClientConfig) {
    this.db_conn_info = conn_info;
  }

  async init(): Promise<void> {
    this.#client = await new Client().connect(this.db_conn_info);
    this.#connection = new MySQLConnection(this.#client);
  }

  async acquireConnection(): Promise<DatabaseConnection> {
    await this.#connectionMutex.lock();
    return this.#connection!;
  }

  async beginTransaction(
    connection: DatabaseConnection,
    _settings: TransactionSettings,
  ): Promise<void> {
    await connection.executeQuery(CompiledQuery.raw("start transaction"));
  }

  async commitTransaction(connection: DatabaseConnection): Promise<void> {
    await connection.executeQuery(CompiledQuery.raw("commit"));
  }

  async rollbackTransaction(connection: DatabaseConnection): Promise<void> {
    await connection.executeQuery(CompiledQuery.raw("rollback"));
  }

  releaseConnection(): Promise<void> {
    this.#connectionMutex.unlock();
    return Promise.resolve();
  }

  destroy(): Promise<void> {
    this.#client?.close();
    return Promise.resolve();
  }
}

class MySQLConnection implements DatabaseConnection {
  readonly #db: Client;

  constructor(c: Client) {
    this.#db = c;
  }

  async executeQuery<R>(compiledQuery: CompiledQuery): Promise<QueryResult<R>> {
    const { sql, parameters } = compiledQuery;

    const rows = await this.#db.query(sql, parameters as QueryArguments);

    return Promise.resolve({
      rows: rows as [],
    });
  }

  async *streamQuery<R>(
    _compiledQuery: CompiledQuery,
    _chunkSize?: number,
  ): AsyncIterableIterator<QueryResult<R>> {
    // Streaming queries are not yet supported by the deno_mysql library.
    throw new Error("Streaming queries are not supported with MySQL driver.");
  }
}

class ConnectionMutex {
  #promise?: Promise<void>;
  #resolve?: () => void;

  async lock(): Promise<void> {
    while (this.#promise) {
      await this.#promise;
    }

    this.#promise = new Promise((resolve) => {
      this.#resolve = resolve;
    });
  }

  unlock(): void {
    const resolve = this.#resolve;

    this.#promise = undefined;
    this.#resolve = undefined;

    resolve?.();
  }
}
`

**Comment by koskimas** [comment]
That seems to be created from the SQLite driver, which has a single connection. Having the mutex there forces your MySQL driver to only have one connection, which will lead to bad performance once you have more than one concurrent request running.

**Comment by mrtornado** [comment]
thanks for the info, I will try to remove it.

**Comment by mrtornado** [comment]
I managed to modify it to use a connection pool, that currently has 10 max connections, but you can modify the `maxConnections: number = 10` value according to your needs and server capacity.

https://pastecode.io/s/jwfpktky

Is this one better @koskimas ?

**Comment by mrtornado** [comment]
thanks for looking into it @y12studio but I prefer my method more, seems more cleaner.

**Comment by waptik** [comment]
I'd also like to add that npm specifiers are not yet supported on deno deploy so the npm packages will not work there unless using cdns or esm.sh. So custom adapters/dialects for deno are the way to go for now for both mysql and postgres.

**Comment by alexgleason** [comment]
I would love if I could just use kysely's query builder, target a particular dialect and then get a string. I want to pass the string to the database interface myself.

**Comment by igalklebanov** [comment]
@alexgleason https://kysely.dev/docs/recipes/splitting-build-compile-and-execute-code
