### ISSUE TITLE
column references allow ambiguity at compile-time that results in errors at runtime.

### ISSUE THREAD

**Issue by igalklebanov** [kysely-org/kysely#372]
Let's start with an example:

```ts
interface Database {
  person: { id: GeneratedAlways<string> },
  pet: { id: GeneratedAlways<string> },
}

db.selectFrom(['person', 'pet'])
  .select([
    'person.id', // OK!
    'pet.id', // OK!
    'id', // runtime error, but OK at compile-time.
  ])
```

What do we have here?

Both tables have an `'id'` column, both tables exist in query context. 
`'id'` is being referred to without indicating from which table.
This passes compilation/type-checks, gets deployed and causes a runtime error.
...which means we failed as a type-safe library.

**Comment by koskimas** [comment]
| which means we failed as a type-safe library.

It doesn't. Nothing is 100% type-safe. This one is very hard to fix.

**Comment by kristiannotari** [comment]
Is there a technical reason why column references should be left without indicating from which table they come from? Apart from a better reading experience (opinionated). If not, my suggestion would be to get rid of ambiguity by not allowing direct column reference without a table specifier. That way there's no way of causing the error in the first place, right?

**Comment by igalklebanov** [comment]
> > which means we failed as a type-safe library.
> 
> It doesn't. Nothing is 100% type-safe. This one is very hard to fix.
> 

Sorry for my wording. The idea was, "Can/should we do better in this case."

Yeah, it's hard and probably not worth it with the current state of the ts compiler.

Perhaps we should warn about some of the current design's caveats in the readme/docs?

**Comment by igalklebanov** [comment]
> Is there a technical reason why column references should be left without indicating from which table they come from? Apart from a better reading experience (opinionated). If not, my suggestion would be to get rid of ambiguity by not allowing direct column reference without a table specifier. That way there's no way of causing the error in the first place, right?

In most cases, there is no ambiguity. Either there's a single table in a context, or the intersection is very small.

You don't want to hurt dx for most queries.

If we ever try and solve this, we should attempt to exclude the intersection from the references pool.

**Comment by koskimas** [comment]
>  If not, my suggestion would be to get rid of ambiguity by not allowing direct column reference without a table specifier.

That would be wayyyy too opininated. I, for example, only use table specifiers if I have to.

**Comment by koskimas** [comment]
There's really nothing we can do for this one with reasonable amount of work. This hasn't attracted any attention during the four months it has been open. Let's close this for now.

**Comment by mertalev** [comment]
How feasible would it be to require the table specifier only when there are multiple tables in the query? Or alternatively, to add a plugin that modifies the types to require table specifiers? I've run into this a few times and it'd be nice to remove an entire class of runtime errors.

**Comment by Magnuti** [comment]
Hi, any updates on this? I am a big fan og Kysely but I have been hitting runtime errors a lot due to this.

I support @mertalev suggestion with an optional plugin that requires us to write `table_name.column_name` when doing joins (or all the time). I have no issue writing `table_name.column_name` every time if this fixes my runtime issues.
