### ISSUE TITLE
Support streaming results from update queries.

### ISSUE THREAD

**Issue by daffron** [kysely-org/kysely#376]
I currently have this `knex` query that Im hoping to convert,

```ts
  return connection<Invoice>('invoice')
    .update({
      locked: true,
    })
    .whereIn('id', selectSql) // SELECT SUB QUERY
    .returning('id')
    .stream();
```
    
To be able to do the same in Kysely would be awesome

Thanks

**Comment by koskimas** [comment]
@igalklebanov already started working on this [here](https://github.com/koskimas/kysely/pull/377) 🚀
