### ISSUE TITLE
Typesafe JSON_ARRAYAGG & JSON_OBJECT helper function

### ISSUE THREAD

**Issue by isaac-scarrott** [kysely-org/kysely#394]
Is there a typesafe way to do the following query with the MySQL functions `JSON_ARRAYAGG` and `JSON_OBJECT`? I've seen issues such as https://github.com/kysely-org/kysely/issues/31, however I can't seem to find a way to make an typesafe abstraction of my raw SQL like in https://github.com/kysely-org/kysely/issues/31.

```ts
      const result = await db
        .selectFrom("Workflows")
        .select([
          "Workflows.head_commit",
          "Workflows.repository_full_name",
          "Workflows.head_commit_message",
          "Workflows.status",
          "Workflows.reason",
          "Workflows.started_at",
          "Workflows.completed_at",
          // I would like the following to be typesafe
          sql<Tasks[]>`JSON_ARRAYAGG(JSON_OBJECT(
            'id', Tasks.id,
            'head_commit', Tasks.head_commit,
            'preset', Tasks.preset,
            'status', Tasks.status,
            'output_pull_request_url', Tasks.output_pull_request_url,
            'output_commit', Tasks.output_commit,
            'output_commit_message', Tasks.output_commit_message,
            'reason', Tasks.reason,
            'started_at', Tasks.started_at,
            'completed_at', Tasks.completed_at
          ))`.as("tasks"),
        ])
        .leftJoin("Tasks", "Tasks.head_commit", "Workflows.head_commit")
        .groupBy("Workflows.head_commit")
        .execute();
```

**Comment by koskimas** [comment]
Hmm.. MySQL doesn't seem to have a way to convert row to JSON objects without specifying each column one at a time. Well you can do this:

```ts
        function jsonArrayFrom<O>(
          expr: SelectQueryBuilder<any, any, O>
        ): RawBuilder<Simplify<O>[]> {
          const node = expr.toOperationNode()

          const props = node.selections!.flatMap(({ selection: sel }) => {
            if (ReferenceNode.is(sel) && ColumnNode.is(sel.column)) {
              return [
                sql.literal(sel.column.column.name),
                sql.id('agg', sel.column.column.name),
              ]
            } else if (ColumnNode.is(sel)) {
              return [
                sql.literal(sel.column.name),
                sql.id('agg', sel.column.name),
              ]
            }
          })

          return sql`(select cast(coalesce(json_arrayagg(json_object(${sql.join(
            props
          )})), '[]') as JSON) from ${expr} as agg)`
        }
        
         const query = ctx.db
          .selectFrom('person')
          .select((eb) => [
            'first_name',

            jsonArrayFrom(
              eb
                .selectFrom('pet')
                .select(['pet.id', 'pet.name'])
                .whereRef('person.id', '=', 'pet.owner_id')
            ).as('pets'),
          ])
 ```

**Comment by isaac-scarrott** [comment]
Cheers for quick response.

Makes sense, I believe Prisma also follows a similar approach (not quite the same) of not using joins as they claim is it quicker when executing complex joins? Anyway, I'll keep an eye on this in the next version.

Thanks for the helper function as well, I had no chance of creating that alone. Also agree it is stupid that you have to specify each column...I usually use postgres but trying out Planetscale.

**Comment by koskimas** [comment]
The helper in the next version is only for postgres and it's already [in the master branch](https://github.com/kysely-org/kysely/blob/master/src/helpers/postgres.ts) if you want to take a look.

**Comment by koskimas** [comment]
By the way, this would probably work as a type-safe `JSON_OBJECT` helper:

```ts
export function jsonObject<O extends Record<string, Expression<unknown>>>(
  obj: O
): RawBuilder<
  Simplify<{
    [K in keyof O]: O[K] extends Expression<infer V> ? V : never
  }>
> {
  return sql`JSON_OBJECT(${sql.join(
    Object.keys(obj).flatMap((k) => [sql.lit(k), obj[k]])
  )})`
}
```

**Comment by isaac-scarrott** [comment]
> The helper in the next version is only for postgres and it's already [in the master branch](https://github.com/kysely-org/kysely/blob/master/src/helpers/postgres.ts) if you want to take a look.
> 
> I could consider adding a mysql version that does something similar as my doodle above.
> 
> By the way, does Planetscale return JSON columns as strings or does it `JSON.parse` them automatically?

Seems they parse them automatically, I get an object back
