### ISSUE TITLE
Support `ROW_NUMBER()`

### ISSUE THREAD

**Issue by mplibunao** [kysely-org/kysely#397]
Hi

I'm trying to create the following window function

```sql
ROW_NUMBER() OVER (PARTITION BY t.id ORDER BY num_common_tags DESC, ct.is_primary DESC) AS tag_rank,
```

I've noticed that `OVER` is supported [here](https://kysely-org.github.io/kysely/classes/AggregateFunctionBuilder.html#over) but I can't find `ROW_NUMBER()` anywhere

I've also tried using raw sql but I'm getting the following type error

```
No overload matches this call.
  Overload 1 of 2, '(selections: readonly SelectExpression<From<DB, "communityTags"> & Record<"commonTags", Selection<From<DB, "communityTags">, "communityTags" | "userInterests", "communityTags.communityId" | AliasedAggregateFunctionBuilder<...>>>, FromTables<...> | "commonTags">[]): QueryBuilderWithSelection<...>', gave the following error.
    Type 'RawBuilder<number>' is not assignable to type 'SelectExpression<From<DB, "communityTags"> & Record<"commonTags", Selection<From<DB, "communityTags">, "communityTags" | "userInterests", "communityTags.communityId" | AliasedAggregateFunctionBuilder<...>>>, FromTables<...> | "commonTags">'.
      Type 'RawBuilder<number>' is missing the following properties from type 'AliasedExpression<any, any>': expression, alias
  Overload 2 of 2, '(selection: SelectExpression<From<DB, "communityTags"> & Record<"commonTags", Selection<From<DB, "communityTags">, "communityTags" | "userInterests", "communityTags.communityId" | AliasedAggregateFunctionBuilder<...>>>, FromTables<...> | "commonTags">): QueryBuilderWithSelection<...>', gave the following error.
    Argument of type '(string | RawBuilder<number>)[]' is not assignable to parameter of type 'SelectExpression<From<DB, "communityTags"> & Record<"commonTags", Selection<From<DB, "communityTags">, "communityTags" | "userInterests", "communityTags.communityId" | AliasedAggregateFunctionBuilder<...>>>, FromTables<...> | "commonTags">'. (tsserver 2769)
```

**Comment by koskimas** [comment]
Kinda difficult to help without seeing the code that produced that error 😄

**Comment by koskimas** [comment]
You need to use the `as` method to give an alias for the raw selection. The raw SQL is not parsed as a type:

```ts
sql<number>`ROW_NUMBER() OVER (PARTITION BY tags.id ORDER BY numCommonTags DESC, communityTags.isPrimary DESC)`.as('tagRank')
```

**Comment by mplibunao** [comment]
Oh you're right. That fixed the type error. Thank you!  😄

**Comment by koskimas** [comment]
@igalklebanov Should we add a way to call arbitrary aggregate functions? Something like

```ts
fn.aggregate('over', [arg1, arg2])
```

the same way we have `fn('name', [arg1, arg2])` but it'd return an `AggregateFunctionBuilder`

**Comment by igalklebanov** [comment]
@koskimas Good idea! I just had the same idea over at the original discord [thread](https://discord.com/channels/890118421587578920/1090551639976456202).

@mplibunao Check out the playground link over there.

**Comment by igalklebanov** [comment]
> @igalklebanov Should we add a way to call arbitrary aggregate functions? Something like
> 
> ```ts
> fn.aggregate('over', [arg1, arg2])
> ```
> 
> the same way we have `fn('name', [arg1, arg2])` but it'd return an `AggregateFunctionBuilder`

Something like:

```ts
fn.agg<number>('rank').over(...) // rank() over(...)
fn.agg<string>('group_concat', ['column0']) // group_concat("column0")
```

**Comment by koskimas** [comment]
Looks good to me!

**Comment by Azarattum** [comment]
Speaking of window functions, I get that [frame spec](https://www.sqlite.org/syntax/frame-spec.html) isn't supported, right? I'm looking for something like:
```ts
fn.over(qb => 
  qb
    .partitionBy("group")
    .orderBy("order")
    .rowsBetween("UNBOUNDED PRECEDING", "UNBOUNDED FOLLOWING") // this isn't real
)
```

Since the default end of the window is `CURRENT ROW` for SQLite, I really need a way to specify `UNBOUNDED FOLLOWING` to include the entire partition. Are there any available workaround without writing an entire select as sql? Would you consider adding support for the frame spec?

**Comment by igalklebanov** [comment]
@Azarattum I think the best way to approach this is to provide `.$modifyX` methods in `AggregateFunctionBuilder`.

**Comment by koskimas** [comment]
I think we can close this now. We now have a way to create arbitrary aggregate calls.
