### ISSUE TITLE
Incrementing int field in SET (TypeScript)

### ISSUE THREAD

**Issue by mehulmpt** [kysely-org/kysely#402]
We have a use case as follows:

<img width="1264" alt="Screenshot 2023-03-30 at 19 06 25@2x" src="https://user-images.githubusercontent.com/10388889/228853907-e2845a81-251a-490f-8f86-0e5693cd1c8f.png">

Here `publicProfileViewCount` is a mandatory `Int` field. However, the error we get is:

```
Operator '+' cannot be applied to types 'ExpressionWrapper<number>' and 'number'
```

Can this be addressed on TypeScript level?

**Comment by koskimas** [comment]
See the `set` method's documentation. There's an example for this exact case.

**Comment by elitan** [comment]
@koskimas `bxp` seems to be [deprecated](https://github.com/kysely-org/kysely/blob/master/src/expression/expression-builder.ts#L720). Do you have an example of how to do it in the new way?

**Comment by igalklebanov** [comment]
Hey 👋 

@elitan The new way is to just use `eb` as a function.
