### ISSUE TITLE
Using UUIDs with MySQL

### ISSUE THREAD

**Issue by voinik** [kysely-org/kysely#406]
Hey there! First of all, great work on this library! I'm really enjoying working with it so far.
Second: excuse the long post. I'm trying to show you what my thought process is and what I've tried so far. 

On to my issue:

**TLDR; I'm generating my own UUIDv4 ids for MySQL (using kysely-planetscale), and I'm trying to find a way to automatically wrap all selects and inserts for primary/foreign keys (with a binary type) with the BIN_TO_UUID(column) and UUID_TO_BIN(uuid) MySQL functions, respectively. Do you have some insight you can share in order to find a way to do it?**

### Background
I've been trying (for a week now) to figure out a good solution to get UUIDs working with MySQL (through kysely-planetscale). After diving into it, I concluded the best way to go about that is by converting and storing the UUIDs in binary (for performance reasons). MySQL has 2 functions for that: `UUID_TO_BIN()` and `BIN_TO_UUID()`. MySQL also has a function to generate UUIDs, but those are UUIDv1s whereas I need UUIDv4s.

Additionally, I want to be able to just generate a UUID in my code and pass it along, without having to do anything else like converting it to something else.

So my journey began. I started with setting up a migration with binary column types for the primary ids, like this:
```ts
.addColumn('id', sql`BINARY(16)`, col => col.primaryKey())`)
```

Next I needed a way to convert the UUIDs from my application to something MySQL understands (hex).

### First attempt
This is what I've tried to get this working:
Generate a UUID and then convert it to hex (in my own code) for inserts, and converting received hex numbers back to string UUIDs for selects. This didn't work because I was unable to convert whatever MySQL was sending me as binary data during selects (e.g. `id: '¿\x00´ÿõ\x8AE²\x97\x83H\x96\fIë»',`. This looks like binary but if I put it in a buffer I don't get the expected data compared to if I convert my own uuid to binary). Also during inserts, I wasn't sure how to send a hex value across the wire as a hex literal. I'm not very experienced in encodings and conversions between binary/hex/buffers/strings etc., so maybe I missed something here.

(I could use something like `HEX()` and `UNHEX()` for this, but that has the same issues as the second attempt).

### Second attempt
Let the database do the conversion using its own UUID conversion methods. I did this by creating a conversion function in my code:
```ts
export const convertUuidToBin = <T>(uuid: string) => sql<T>`UUID_TO_BIN(${uuid})`;
```
And then doing something like this:
```ts
    const org = await db.insertInto('organization').values({
        id: convertUuidToBin('9000b538-59a8-4a77-8f27-12f6f5ead7da')
    }).executeTakeFirstOrThrow();
```
For inserts it's kind of ok to do it this way because I can create a function (e.g. 'makeOrganization') that uses that `convertUuidToBin` function.

The problem is with selects. Each time I'd like to select an id I would have to remember to use the `convertBinToUuid` function, which would be something like:
```ts
const selectUuidFromBin = (colName: string) => sql`BIN_TO_UUID(${sql.ref(colName)})`.as(colName);
```
And then use it like this:
```ts
const selectOrg = await db.selectFrom('organization').select(selectUuidFromBin('id')).execute();
```
If I don't use `selectUuidFromBin`, I get the strange raw binary data. 
This is very suboptimal because there's no way to use `.selectAll()` for example. Additionally, I'd have to remember to use this function every time I select.

### Third attempt
I then went on to check out if there are some options with which I can automate these conversions and ran into custom format and cast functions (kysely-planetscale docs), but alas, I can't do specific conversions for specifically primary keys. So I'd have to write a format function that parses the query, finds out which position any keys with "id" in them are positioned in the `args` array, and then replace them with `BIN_TO_UUID` or `UUID_TO_BIN`, depending on if it's a select or insert query, respectively. I don't think it's a good idea to do that myself, honestly.

## Conclusion
And now I'm here, asking you for help. Do you perhaps have any ideas how I could make this work? Would it be possible to do this conversion so that I can work with string UUIDv4s in my code without having to remember to do conversions? Or is this something that already exists, but I just missed it somehow? Or do you have some other advice perhaps?

Thank you!

**Comment by koskimas** [comment]
Have you actually measured the performance if you just use strings for the uuids compared to binary? Does the difference really matter in your application? Like, really really? What kind of difference will there be for the users? Will the users care? If performance is really __that__ critical in your application, have you considered using something other than node?

You'd save yourself a huge amount of trouble if you are able to use strings.

**Comment by voinik** [comment]
Thank you so much for taking the time to respond! And so quickly at that.

I figured this would be quite difficult to pull off. For now, it isn't worth it for me to dive further into this and I'll take your suggestion of simply using strings. It's good to know it's (mostly?) possible using a custom plugin, though. And maybe by the time I'll need a feature like this there may be a plugin for it made by the community 🙂 

Thanks again!
