### ISSUE TITLE
Simplifying where expressions

### ISSUE THREAD

**Issue by jtlapp** [kysely-org/kysely#411]
Before Kysely supported `or` and `and` compound conditionals, I had written my own filter supporting compound conditionals. I'm grateful that Kysely now provides these, because it allows me to ditch a lot of code and rely on someone else to maintain this functionality.

However, I'm a bit unhappy about one thing. My filter syntax was more concise and therefore easier to read. Consider the following v0.24 Kysely query:

```ts
    await db
      .deleteFrom("some_table")
      .where(({ or, and, cmpr }) =>
        or([
          cmpr("columnA", "=", 100),
          cmpr("columnB", ">=", 32),
          cmpr("columnC", "in", ["a", "b", "c"]),
          and([
            cmpr("columnD", ">", 0),
            cmpr("columnE", "<", 100),
            cmpr("columnF", "is", null),
          ]),
        ])
      );
```

With two syntactic changes, this could become:

```ts
    await db
      .deleteFrom("some_table")
      .where(({ or, and }) =>
        or(
          ["columnA", "=", 100],
          ["columnB", ">=", 32],
          ["columnC", "in", ["a", "b", "c"]],
          and(
            ["columnD", ">", 0],
            ["columnE", "<", 100],
            ["columnF", "is", null],
          ),
        )
      );
```

The two changes are:

1. Replace `cmpr()` with tuples.
2. Have `or` and `and` accept rest parameters instead of arrays.

This would be another breaking change, but now would be the time to do it, before too many people have converted to the new syntax.

**Comment by koskimas** [comment]
No thanks 😄

**Comment by jtlapp** [comment]
> No thanks 😄

I see you found the proposal tempting. 🤣
