### ISSUE TITLE
request failed, reason: connect ETIMEDOUT 

### ISSUE THREAD

**Issue by jahirfiquitiva** [kysely-org/kysely#415]
Hello ... I'm trying to use the library with a PlanetScale database ... but any request to it just fails with a ETIMEDOUT error

This is my configuration

```typescript
import { Kysely } from 'kysely';
import { PlanetScaleDialect } from 'kysely-planetscale';

export type ReactionName = 'likes' | 'loves' | 'awards' | 'bookmarks';

export type CountersReactions = { [Key in ReactionName]?: number };

interface CountersTable extends CountersReactions {
  slug: string;
  views?: number;
}

interface Database {
  counters: CountersTable;
}

export const queryBuilder = new Kysely<Database>({
  dialect: new PlanetScaleDialect({
    url: process.env.DATABASE_URL,
  }),
});

```

and I'm trying to get the data like:

```typescript
const slug = 'uses';
const data = await queryBuilder
      .selectFrom('counters')
      .where('slug', '=', slug)
      .select(['slug', 'likes', 'loves', 'awards', 'bookmarks'])
      .execute();
```

but the query never succeeds and it just shows the error:
`request to https://p9hawx83bcfm.us-west-2.psdb.cloud/psdb.v1alpha1.Database/Execute failed, reason: connect ETIMEDOUT 54.189.191.130:443"`

**Comment by jahirfiquitiva** [comment]
This is the database schema
<img width="333" alt="Shot 2023-04-05 at 21 57 14@2x" src="https://user-images.githubusercontent.com/10360816/230272193-17200aaf-30cb-438a-b5c3-0bc740317ebd.png">

**Comment by koskimas** [comment]
This is not related to Kysely. The Dialect takes care of everything connection related, and in this case you're using a 3rd party dialect we have no control over.

This is most likely a configuration issue, but you may get help if you open this issue in PlanetScaleDialect's repo.
