### ISSUE TITLE
[Bug] Argument of type "typename" is not assignable to parameter of type 'ReferenceExpression '.

### ISSUE THREAD

**Issue by jonluca** [kysely-org/kysely#418]
In the following query, the `cmpr` in the `where` throws a type error, even though the casted `select` is of type number.

```typescript
      const query = this.getMessageQueryByYear(year)
        .innerJoin("handle", "handle.ROWID", "message.handle_id")
        .select((e) => e.fn.count("message.ROWID").as("message_count"))
        .select("handle.id as handle_identifier")
        .select(
          sql<number>`cast(strftime('%H', DATETIME(date / 1000000000 + 978307200, 'unixepoch')) as integer)`.as("hour"),
        )
        .where(({ or, cmpr }) => or([cmpr("hour", ">", 22), cmpr("hour", "<", 5)]))
        .where("is_from_me", "=", Number(fromMe))
        .groupBy("handle_identifier")
        .orderBy("message_count", "desc");
```
<img width="980" alt="capture 2023-04-09 at 12 31 26 PM" src="https://user-images.githubusercontent.com/13029040/230792815-f74a5746-ac56-4885-a8a6-827e8b0150c0.png">

Am I formatting the query incorrectly? This code works and produces the correct sql, when inspected with `query.compile().sql`

```sql
select count("message"."ROWID")                                                              as "message_count",
       "handle"."id"                                                                         as "handle_identifier",
       cast(strftime('%H', DATETIME(date / 1000000000 + 978307200, 'unixepoch')) as integer) as "hour"
from "message"
         inner join "handle" on "handle"."ROWID" = "message"."handle_id"
where ("hour" > ? or "hour" < ?)
  and "is_from_me" = ?
group by "handle_identifier"
order by "message_count" desc
```

**Comment by igalklebanov** [comment]
Hey 👋 

A `where` clause can't reference things declared in the `select` clause, it "runs" before it.
(We know that SQLite allows it, but its such a rare case that Kysely will not support it).

As a result, `'hour'` is not part of the query context that `.where` is bound to.
You need to repeat yourself in the `where` clause for this to be valid SQL.

**Comment by igalklebanov** [comment]
This should work:
https://wirekang.github.io/kysely-playground/?p=f&i=-NSbrG-limvtuwpUJ4-B

**Comment by asfaltboy** [comment]
It looks like the playground link above is broken. I also came across the issue myself, and I think it would have been helpful if we added this explanation and example into the docs somewhere visible :pray:
