### ISSUE TITLE
Missing column type `binary(${number})` for mysql

### ISSUE THREAD

**Issue by stefankyriacou123** [kysely-org/kysely#421]
Hi,

I've been using kysely for a mysql project and noticed that I have to use `@ts-expect-error` as follows: 
```
  await db.schema
    .createTable("users")
    // @ts-expect-error "binary(16)" throws error
    .addColumn("id", "binary(16)", column => column.primaryKey().defaultTo(sql`(uuid_to_bin(uuid(), 1))`))
    .execute()
```

It looks like `type ColumnDataType` in `src/operation-node/data-type-node.ts` doesn't include the type `binary(${number})`.

I haven't put up a pr as i'm not sure what your process is, though it should be a pretty quick change?

cheers!

**Comment by igalklebanov** [comment]
Hey 👋 

You can escape it as follows:

```ts
.addColumn('id', sql`binary(16)`, column => column.primaryKey().defaultTo(sql`(uuid_to_bin(uuid(), 1))`))
```

You're welcome to submit a PR. 👌
