### ISSUE TITLE
Update result only returning number of updated rows

### ISSUE THREAD

**Issue by ahmafi** [kysely-org/kysely#428]
Is there anyway I can get the number of changed rows and matched rows? [UpdateResult](https://kysely-org.github.io/kysely/classes/UpdateResult.html) only returns `numUpdatedRows` which is the number of changed rows, I want to have the number of matched but unchanged rows as well.

**Comment by igalklebanov** [comment]
Hey 👋 

It depends on the dialect you're using.

e.g. 

> [UPDATE](https://dev.mysql.com/doc/refman/8.0/en/update.html) returns the number of rows that were actually changed. The [mysql_info()](https://dev.mysql.com/doc/c-api/8.0/en/mysql-info.html) C API function returns the number of rows that were matched and updated and the number of warnings that occurred during the [UPDATE](https://dev.mysql.com/doc/refman/8.0/en/update.html).
-mysql
https://dev.mysql.com/doc/refman/8.0/en/update.html

You'd have to make another call with MySQL to get what you need.

While..

> The optional RETURNING clause causes UPDATE to compute and return value(s) based on each row actually updated.
>
> On successful completion, an UPDATE command returns a command tag of the form
> UPDATE count
> The count is the number of rows updated, including matched rows whose values did not change.
-postgresql
https://www.postgresql.org/docs/current/sql-update.html

In PostgreSQL you won't.

**Comment by ahmafi** [comment]
Hi :wave:

Actually, [node-mysql](https://github.com/mysqljs/mysql#getting-the-number-of-affected-rows) returns both affected rows and changed rows. Since we are using this driver in kysely I suppose we should be able to get those values! Am I wrong? (Kysely uses `node-mysql2` but it has the same API as `node-mysql`).

I also don't see anything dialect specific in the [UpdateResult](https://kysely-org.github.io/kysely/classes/UpdateResult.html) class.

**Comment by scottsword** [comment]
I don't know if it's related this this issue or not, but I'm encountering some weirdness, or at least the APIs aren't seeming to function according to documentation. 

I have the following insert statement

```return await db
            .insertInto('moods')
            .values(moodItem)
            .returning('id')
            .execute()```

I need that API call to return the ID of the newly create row, but when result never respo
<img width="599" alt="Screenshot 2023-05-07 at 12 32 05 PM" src="https://user-images.githubusercontent.com/1930696/236696118-2ee5944a-6f1a-4f18-8304-6fd646cdd3a7.png">
nds with the id. I'm using the mysql2 driver w/ Maria.

**Comment by igalklebanov** [comment]
@scottsword 

> I don't know if it's related this this issue or not, but I'm encountering some weirdness, or at least the APIs aren't seeming to function according to documentation.
> 
> I have the following insert statement
> 
> ```
> return await db
>             .insertInto('moods')
>             .values(moodItem)
>             .returning('id')
>             .execute()
> ```
> 
> I need that API call to return the ID of the newly created row, but result never responds with the id. I'm using the mysql2 driver w/ Maria DB.
> 
> <img alt="Screenshot 2023-05-07 at 12 32 05 PM" width="599" src="https://user-images.githubusercontent.com/1930696/236696118-2ee5944a-6f1a-4f18-8304-6fd646cdd3a7.png">

Hey 👋

1. `returning` adds https://www.postgresql.org/docs/current/dml-returning.html / https://www.sqlite.org/lang_returning.html to the query. This clause is not supported in MySQL - so the built-in MySQL dialect doesn't support it. We might want to handle it differently, and throw.
 
2. When used with supported dialects, it returns an actual result set, and not an OK packet.
