### ISSUE TITLE
NextAuth Adapter

### ISSUE THREAD

**Issue by keeganmccallum** [kysely-org/kysely#429]
Hi there, was introduced to kysely through sst which looks cool, but was disappointed to see that there is no support for NextAuth (https://authjs.dev/reference/adapters). This would make things a lot nicer from an auth perspective, allowing integration with the db via kysely vs. needing to hack something together

**Comment by igalklebanov** [comment]
Hey 👋 

Check out this [PR](https://github.com/nextauthjs/next-auth/pull/5464) over at the NextAuth repository.
