### ISSUE TITLE
[BUG] wrong type when `.where('t.foo', 'is not', null)`

### ISSUE THREAD

**Issue by loynoir** [kysely-org/kysely#432]
```ts
await db
  .selectFrom('t')
  .selectAll()
  .where('t.foo', 'is not', null)
  .execute()
```

Actually, got type

```ts
{
    foo: bar | null;
}[]
```

Expected type 

```ts
{
    foo: bar;
}[]
```

But seems there is a runtime test.

https://github.com/kysely-org/kysely/blob/609001c5961ff805fcc244733044bb5cac1b97f6/test/node/src/where.test.ts#L79

Is there a type test?

Is that column optional?

**Comment by wirekang** [comment]
Your `DB` interface will be looks like:
```ts
interface DB {
  t: {
    foo: string | null
  }
}
```

This is not a bug.
SelectQueryBuilder returns the type as defined in `DB` regardless of condition.

The test you mentioned is for sql generation, not for type type.

**Comment by loynoir** [comment]
> SelectQueryBuilder returns the type as defined in DB regardless of condition.

Is there a workaround?

How can I get type

```ts
{
    foo: bar;
}[]
```

**Comment by wirekang** [comment]
#380 will help you but it seems not released yet.

**Comment by wirekang** [comment]
Check out [the detailed explanation](https://github.com/kysely-org/kysely/issues/335#issuecomment-1435515901)

**Comment by koskimas** [comment]
@loynoir For future reference, please learn how to write issues if you want people to help you. This one reads to me like this:

```
YOU HAVE A BUG IDIOTS!Q!11!°
FIX IT!341221
WHY ISN'T IT FIXED!"!#
I DEMAND SERVICE!"#€!"#€
```

and I wouldn't help you or consider your request even if it made sense. Next time try something like this:

```
Hi!

I've written this query

<the query>

and it seems like the `is not` where expression doesn't narrow the output type and the column is nullable in the output. I wonder if it would be possible for Kysely to narrow the type automatically?
```
