### ISSUE TITLE
Hide `returning()`/`returningAll()` when using unsupported db

### ISSUE THREAD

**Issue by ImLunaHey** [kysely-org/kysely#443]
It would be nice to have something to prevent `returning()`/`returningAll()` from showing when using MySQL for example. I wrote all my code when moving from prisma to kysely and it wasn't until I actually ran the code that I realised the mistake I had made.

Also see: https://github.com/kysely-org/kysely/issues/264

**Comment by koskimas** [comment]
This has been discussed but it's too difficult to implement cleanly. We'd basically need a copy of kysely for each dialect and that doesn't work with third party dialects.
