### ISSUE TITLE
MySQL Migration Example

### ISSUE THREAD

**Issue by ctdh** [kysely-org/kysely#445]
The [MySQL migration example in the README](https://github.com/kysely-org/kysely/tree/master#mysql-migration-example) should put the `.addForiegnKeyConstraint()` into a new execute block:

     await db.schema
    .createTable('pet')
    .addColumn('id', 'integer', (col) => col.autoIncrement().primaryKey())
    .addColumn('name', 'varchar(255)', (col) => col.notNull().unique())
    .addColumn('owner_id', 'integer', (col) => col.notNull())
    .addColumn('species', 'varchar(255)', (col) => col.notNull())
    .addForeignKeyConstraint(
      'pet_owner_id_fk', ['owner_id'], 'person', ['id'],
      (cb) => cb.onDelete('cascade')
    )
    .execute()

It would also be good to include an enum example as it demonstrates the inclusion of native sql.
Suggest it should be something like this...

    import { Kysely, sql } from 'kysely'
...

    await db.schema
    .createTable('pet')
    .addColumn('id', 'integer', (col) => col.autoIncrement().primaryKey())
    .addColumn('name', 'varchar(255)', (col) => col.notNull().unique())
    .addColumn('owner_id', 'integer', (col) => col.notNull())
    .addColumn('food', sql`enum('dry', 'tinned, 'cooked meat', 'fresh meat')`)
    .addColumn('species', 'varchar(255)', (col) => col.notNull())
    .execute()
    await db.schema
    .addForeignKeyConstraint(
      'pet_owner_id_fk', ['owner_id'], 'person', ['id'],
      (cb) => cb.onDelete('cascade')
    )
    .execute();

**Comment by koskimas** [comment]
> should put the .addForiegnKeyConstraint() into a new execute block

Why? The example is completely valid MySQL. You can add foreign key constraints as a part of a create table query.
