### ISSUE TITLE
"Where in" with non-array third argument produces invalid SQL

### ISSUE THREAD

**Issue by FINDarkside** [kysely-org/kysely#447]
You can do stuff like `.where('last_name', 'in', 'Matti')` which produces invalid SQL when the third argument is not an array.
Here's the playground link: https://kyse.link/?p=s&i=Hw6N0sRWzTStpqMl8PTE

**Comment by FINDarkside** [comment]
Seems like it works in reverse as well, you can do `.where('last_name', '=', ['Matti', 'Pekka'])` which produces invalid SQL. Not sure if I should create a seprate ticket for this or not.

https://kyse.link/?p=s&i=6l03mfQCY7yrP5fJnSfF

**Comment by koskimas** [comment]
We've been avoiding making the third argument's type depend on the second one since the types are already very complex. But now that we've dropped the amount of `where` functions to one, we could do that using overrides.

If we fix these issues, we could only allow `is` and `is not` when used with `null` (and boolean?).

**Comment by koskimas** [comment]
I don't think it's worth the type complication to do this. I'll close this for now. Let's see if people complain about this in the future and revisit this then.

@shivan-eyespace It will always be up to the user to check for an empty array.

**Comment by lsnow99** [comment]
I made this utility function for this case:

export const whereInNonEmpty =
  <
    WB extends WhereInterface<D, T>,
    RE extends ReferenceExpression<D, T>,
    D,
    T extends keyof D
  >(
    lhs: RE,
    rhs: FilterValueExpressionOrList<D, T, RE>
  ) =>
    (wb: WB) =>
      Array.isArray(rhs) && rhs.length > 0
        ? wb.where(lhs, "in", rhs)
        : wb.where(sql`false`)


I plan to deprecate the direct "in" pattern in my codebase
