### ISSUE TITLE
What is the reason behind not exposing FunctionNode node?

### ISSUE THREAD

**Issue by jsonkb3** [kysely-org/kysely#449]
I know it is marked as internal but what is the reason behind not exposing it but exposing almost any other node?

The only reason I can think of is because of the existance of the FunctionModule.

**Comment by koskimas** [comment]
Each nodes' functional API is marked with `@internal`. But since this issue is again formatted like you're angry at us, I won't answer your question.

**Comment by jsonkb3** [comment]
It was not my intention that my question came out as being angry at you or the project.

Just curious of the design decision behind it.
