### ISSUE TITLE
Add an `.upsert()` that abstracts on top of `.onConflict()` and `.onDuplicateKeyUpdate()`?

### ISSUE THREAD

**Issue by bnoctis** [kysely-org/kysely#451]
The two don't differ much in API:

```ts
await db
	.insertInto('pet')
	.values({
		name: 'Catto',
		species: 'cat',
	})
	.onConflict((oc) => oc
		.column('name')
		.doUpdateSet({ species: 'hamster' })
	)
	.execute()

await db
	.insertInto('pet')
	.values({
		name: 'Catto',
		species: 'cat',
	})
	.onDuplicateKeyUpdate({ species: 'hamster' })

```

Here's a pseudo-prototype:

```ts
class InsertQueryBuilder<Table> {
	upsert(keyColumn?: PrimaryKey<Table>, newValues: Updateable<Table>) {
		if(this.db.dialect instanceof PostgresqlDialect) {
			return this.onConflict(oc => oc
				.column(keyColumn | this.table.primaryKey)
				.doUpdateSet(newValues)
			)
		} else if(this.db.dialect instanceof MysqlDialect) {
			return this.onDuplicateKeyUpdate(newValues)
		}
	}
}
```

Of course it's oversimplified, but is this feasible?

**Comment by igalklebanov** [comment]
Hey 👋 

Kysely has a WYSIWYG design philosophy - trying to be as close as possible to writing SQL.
Your proposal doesn't align with that, and cannot be part of a builder's API.

We do have a place for QoL helper functions, and shipped some JSON helpers in recent releases.
This proposal is a good candidate for that, but we need to figure out if it can be solved for the wide enough range of cases and in a type-safe way.

**Comment by koskimas** [comment]
My problem with adding more and more ORM features in the helpers folder is that, even though they are written as "helpers" and meant as second class citizens, people will start to think of them as official parts of the library. They won't understand the distinction between the core and the helpers.

So soon we'd just have an oddly organized crappy ORM 😄

**Comment by bnoctis** [comment]
Alright, I'm fine with this "query builder and no more" mindset ;) This issue is a rather random thought, won't blame you for not considering it.
