### ISSUE TITLE
Querying on Generated<Timestamp> columns does not type check.

### ISSUE THREAD

**Issue by afg419** [kysely-org/kysely#452]
With a `Generated<Timestamp>` column (where 'Timestamp' comes from the kysely-codegen package), like `created_at`, I'm running into a type error when executing a query. I've created the query in the playground, and you can see the type issue:

<img width="1792" alt="Screenshot 2023-04-27 at 12 11 49 PM" src="https://user-images.githubusercontent.com/13969784/234954547-d7154942-e5e1-487a-918e-1c10694f15b9.png">

```
Argument of type 'Date' is not assignable to parameter of type 'OperandValueExpressionOrList<DB, "user", "user.created_at">'.
  Type 'Date' is missing the following properties from type 'readonly ValueExpression<DB, "user", Timestamp | null>[]': length, concat, join, slice, and 22 more.(2345)
```

The following type checks, but the generated sql is incorrect:

<img width="1791" alt="Screenshot 2023-04-27 at 12 11 17 PM" src="https://user-images.githubusercontent.com/13969784/234954433-aa8f52ac-1e36-42fe-a8d8-eb0f5fece571.png">

Finally, it's worth noting, that had the column not been `Generated`, things seem to work as expected:

<img width="1792" alt="Screenshot 2023-04-27 at 12 15 02 PM" src="https://user-images.githubusercontent.com/13969784/234955214-6f347eb8-fb13-4a2f-9c7c-c27c90ba0e5b.png">

**Comment by koskimas** [comment]
You can't have `ColumnType` inside `Generated` or another `ColumnType`. The types passed to `Generated` or `ColumnType` are the actual row types. kysely-codegen might be doing some other type magic to flatten the nested types.

**Comment by afg419** [comment]
Ah that's exactly right, kysely-codegen has a special definition of 'Generated' that I missed. Thank you!
