### ISSUE TITLE
[Feature]: Allow executing raw queries with a more idiomatic way

### ISSUE THREAD

**Issue by kasvith** [kysely-org/kysely#455]
Currently executing raw queries has the following structure

```ts
sql`SELECT 1 AS result`.execute(kysely)
```

It would be nice to have it the other way around as well as people naturally tend to think with the current instance first.

```ts
kysely.execute(sql`SELECT 1 AS result`)
```

or

```ts
kysely.raw(sql`SELECT 1 AS result`).execute()
```

**Comment by igalklebanov** [comment]
Hey 👋 

I think this might fit 

```ts
const { rows } = await db.executeQuery(sql`select 1 as result`)
```

**Comment by kasvith** [comment]
its also good

**Comment by capaj** [comment]
does this still work? I am trying to do 

```
          await trx.executeQuery(
            sql<any>`ALTER SCHEMA ${current.subdomain} RENAME TO ${subdomain};`
          )
```

and I keep getting `this query cannot be compiled to SQL`

**Comment by capaj** [comment]
ok this works ok 

```ts
await sql`ALTER SCHEMA "test" RENAME TO "test23"`.execute(trx)
```

but when I try to use variables in the template it throws

**Comment by capaj** [comment]
sorry for spamming. This is most likely a problem in pgPool as it has the same problem with the parameter for this query. TIL you cannot rename a schema in a stored procedure <img src="https://media0.giphy.com/media/HW0AdmHCf33KV72TX7/giphy.gif"/>

**Comment by capaj** [comment]
BTW on this note, is there a way to do raw query with plain old string literal in kysely?

**Comment by igalklebanov** [comment]
> does this still work? I am trying to do
> 
> ```
>           await trx.executeQuery(
>             sql<any>`ALTER SCHEMA ${current.subdomain} RENAME TO ${subdomain};`
>           )
> ```
> 
> and I keep getting `this query cannot be compiled to SQL`

Some engines don't support any parameters in DDL, or in some queries. Try using `sql.ref` or `sql.raw` in those interpolated positions.

**Comment by thelinuxlich** [comment]
Shouldn't this be closed?

**Comment by igalklebanov** [comment]
You can do [this](https://kyse.link/#cN4IgpgJglgLg9gJwM4gFyhgTwA5jSKAW20RgAJgAdAOzLIHExqwEBDGSAGhroGUwANmADGMVgCMh3WmQCq2COzASpPMgElqSFmMlhpAXzIAzBHEJlKIANaZtAzFYDcNGmAAeJBOSjUOCY1ZhMDIAEXYJVm0KNVxkOGpUMgAFFiQEgBUVMBcZXBgk1JgsvVyDV2ZPUjJff0DglLTM7JiZKAgkxmY2DggAHmoAV0JxFgA+XLpjKGQYAH1qVkIwJKQYBF8Ac0myASj5xeXV9a2yAB8yIYEBHc2mCBZO+5Yyio8vHz8WepCikqFWnR2k9ukp+kMRuMdocVmQ1htqNs1HAAO7dObAy7DUYIHZIXDCKBgJBJXgEolIV7UNxVbxkLC4BjPBBkAC8lhAhFYQis5w5xjAXJ5ID5VjgMAAFixnDSPvScCEySIKWyORA4JteRcrMJ2FqORKlmtpSBcrLqgzfk1aOz+EJRNk+ql4tR-mAJua6ZayAA5MAo53pG0aLQ6R2B5p6D2VOXeiPUeSKDiqxNKcPWt3Rz3kONgci2wQiXRCJ15zO5d4WhW+-1FVWabTedPFbLRyte6tFVPJ9nd5R6UstqO5ECcEAAR0GLEw+CIcuAZAAwuZsFAhBAAIpThCYMhGUzmDm2eyOU0VYQJNYUMhmFFIPeq1go1iwMgQcQAOg8IkGHC3076BdCDgJApSSABGPcxgACjUZdiDXSB-x3D82BRWCQHsIsyEgqIyGA0CwCsTgyAAbQAXQASmkSiRwMMdoG5It8BINZNgQYlRxsOxBBndAQEtfAxE2LiYXwAAGD8ACYAHYPwAFhAAwDCAA) nowadays.
