### ISSUE TITLE
Question: Should `postgres-adapter` & `mysql-adapter` implement the two-parameter `acquireMigrationLock()`?

### ISSUE THREAD

**Issue by bjornlll** [kysely-org/kysely#456]
The interface for `createAdapter()` requires a function `acquireMigrationLock()` that since a few versions back have a new signature:

* Previous interface: `acquireMigrationLock(db)`
* Current interface: `acquireMigrationLock(db, options)`

This is the commit that changed the interface ~3 months ago: https://github.com/kysely-org/kysely/commit/fbcf3e3853e6e466fc7e93ce0294d6da32554a14

Neither the [MySQL adapter](https://github.com/kysely-org/kysely/blob/af0c1fa995dfa5520880653f4ce06ce21e86aa4e/src/dialect/mysql/mysql-adapter.ts) nor the [Postgres adapter](https://github.com/kysely-org/kysely/blob/af0c1fa995dfa5520880653f4ce06ce21e86aa4e/src/dialect/postgres/postgres-adapter.ts) are implementing this interface. 

Not sure if this is an issue, so feel free to close/ disregard, but flagging since I found it odd. Discovered when I was trying to track down an [issue with SST](https://github.com/serverless-stack/sst/issues/2813) where `kysely-codegen` doesn't seem to execute.

**Comment by koskimas** [comment]
It's not an issue but we should add the parameter to the implementations to avoid confusion. The parameter won't be used for anything in those dialects though.

**Comment by bjornlll** [comment]
Got it. Thanks for getting back to me @koskimas
