### ISSUE TITLE
Selectable, Insertable & Updateable types are not generating correctly

### ISSUE THREAD

**Issue by swapnil-gawali** [kysely-org/kysely#469]
I have following schema and i am using generated types for selection, Insertion and Updation as follows:

```ts
export interface ContactTable {
    id: Generated<string>;
    number: string;
}

export type ContactRow = Selectable<ContactTable>;
export type InsertableContactRow = Insertable<ContactTable>;
export type UpdateableContactRow = Updateable<ContactTable>;
```

But it is not generating correct types:

For e.g. `Insertable` type should not contains `id` since it generated column, but id is still present in the `Insertable` :

```ts
{
    id: string;
    number: string;
}
```

instead it should be:

```ts
{
    number: string;
}
```

**Note**: I am using latest 0.24.2 version of kysely

**Comment by koskimas** [comment]
This is just not true. You can ask help in our discord channel.

**Comment by koskimas** [comment]
You can insert and update generated columns like postgres `serial` or mysql primary key. You can use the `GeneratedAlways` helper if you have a column that can't be inserted/updated.
