### ISSUE TITLE
Unable to specify PostgreSQL schema when calling schema.alterTable

### ISSUE THREAD

**Issue by hannesj** [kysely-org/kysely#470]
When calling `db.schema.alterTable`, it is not possible to give it a table name with a postgres schema name. This is possible in `db.schema.createTable` and `db.schema.dropTable`, as they call `parseTable`, when creating the node,  which returns the table identifier separated in schema and table names 

typescript:
```
db.schema
    .alterTable("schema.table")
    .addColumn("started_at", "timestamptz")
    .execute()
```

sql:
```
alter table "schema.table" add column "started_at" timestamptz
```

sql should be:
```
alter table "schema"."table" add column "started_at" timestamptz
```

**Comment by koskimas** [comment]
Hey, thanks for reporting this! We'll fix this ASAP. In the meanwhile, you should be able to do this:

```ts
db.withSchema('schema').schema
    .alterTable("table")
    .addColumn("started_at", "timestamptz")
    .execute()
```

**Comment by hannesj** [comment]
Hi, took a stab in fixing it in  #471
