### ISSUE TITLE
out of order migrations

### ISSUE THREAD

**Issue by shayaantx** [kysely-org/kysely#472]
Wanted to ask about case I've seen a few times specific to out of order migrations related to hotfixing.

Consider the following:
1. Branch A (main) - has two migrations 2023-03-30-223252-do-something.ts, 2023-04-24-223252-do-something2.ts
2. Branch B (hotfix) - has one migration 2023-04-24-223252-do-something2.ts

If i deploy the migrations for Branch B before Branch A, I get an error preventing migration when I eventually deploy Branch A

```
Error: corrupted migrations: expected previously executed migration 2023-03-30-223252-do-something to be at index 25 but 2023-04-24-223252-do-something2 was found in its place. New migrations must always have a name that comes alphabetically after the last executed migration.
```
https://github.com/kysely-org/kysely/blob/9ecf9bffa8f7629cb4ed74aff7428b4d8f385a2f/src/migration/migrator.ts#L468

The reason I would deploy branch B with later migrations is because branch B represents a hotfix branch and branch A is the normal branch that wouldn't have been released yet (branch B would be released before A for various reasons).

So I'm wondering why this would be treated as "corruption", when if the migration detects an already executed migration, why couldn't we just ignore that already executed migration? Couldn't we just treat the second block in ensureMigrationsNotCorrupted() as optional for these kind of cases. At first glance I'm not seeing any negatives from this approach, but maybe I'm missing something obvious.

**Comment by shayaantx** [comment]
@koskimas was this fixed by a particular commit?

**Comment by shayaantx** [comment]
@n7olkachev we manually fix the migration table so the subsequent migrations can succeed or we be extra careful creating migrations when hotfixes occur, both are not really ideal tbh.

**Comment by shayaantx** [comment]
I will also say this also happens without the hotfix scenario, lets say 2 developers merge into same branch (main) but created migrations of differing dates 

The first developer merges their migration with 8-18-2023......xyz.ts

The second developer merges their migration with 8-14-2023.....xyb.ts

This also triggers the corruption warning, which seems pretty common when you have multiple people committing.

**Comment by tday** [comment]
@koskimas what was the resolution to this? I'm hoping there is an option to run migrations out of order manually like [Flyway does. ](https://documentation.red-gate.com/fd/out-of-order-184127522.html)
