### ISSUE TITLE
[proposal] caching queries on `selectFrom`

### ISSUE THREAD

**Issue by mehulmpt** [kysely-org/kysely#479]
Hello
When we were on mongoose we implemented a way to cache a mongoose query with a TypeScript overload of `.cache()` on every query. If that can be built natively in kysely that would be a great addon. Here is how it could work:

- every `selectFrom()` construct in kysely provides a `cache()` after `execute()` method (i.e. `db.selectFrom('...').selectAll().execute().cache('my-key')`
- `db` somehow can be programmed to handle the cache (making the cache store generic):

```js
db.onQueryCacheSet = async (key: string, queryResult: unknown) => {
   // responsibility of the developer to cache this properly
}
```

```js
db.onQueryCacheGet = async (key: string) => {
  // responsibility of the developer to return data associated with the given key. return null/false to execute the query
}
```

`.onQueryCacheGet` and `.onQueryCacheSet` would only run if `.cache` is set on query. Inside these two methods, developers can use caching stores like Redis or in-memory if required.

**Comment by koskimas** [comment]
Kysely is a query builder, not an ORM.
