### ISSUE TITLE
Trim required if there are empty characters in select as statement

### ISSUE THREAD

**Issue by kakasoo** [kysely-org/kysely#480]
```typescript
const rows = await kysely
  .selectFrom("user")
  .select(["id", "last_name", "user.last_name as      k"])
  .execute();
```

```typescript
const rows: {
    id: string;
    last_name: string;
    "     k": string;
}[]


```

```sql
SELECT
  "id",
  "last_name",
  "user"."last_name" AS "k"
FROM
  "user"
```

I haven't tried kyselly yet. I've only touched kyselly on playground, and I've noticed the following issues. The problem is that the actual type is different from the query generated when an empty character is inserted into the kyselly select syntax.
I didn't actually call this method using kyselly, so I can't tell if the problem is with the type or query just with the playground.

**Comment by koskimas** [comment]
Yep, unfortunately kysely doesn't support whitespace in column names. You should avoid having whitespace in your column names. Kysely won't be the only tool that has problems with it.

**Comment by kakasoo** [comment]
First of all, thank you for making a great library.
I agree with you on that. So don't you think we should automatically make the key name of the type (=the name of the column) into a trim string?

**Comment by igalklebanov** [comment]
Hey 👋 

This comes with a serious degradation in compile-time performance (recursively ignoring whitespaces) that's simply not worth it at present.

**Comment by kakasoo** [comment]
I am satisfied with your answer. I know this is possible to infer at the type level but I didn't know how much of a burden it was on ts-compiler. :)
By the way, I'm a developer using typeorm but I'll be using a new ORM in my next project and I have a plan to move the whole project gradually. I think this ORM is very attractive.
Thank you again.

**Comment by igalklebanov** [comment]
> I think this ORM is very attractive.

Many confuse Kysely with an ORM, its actually a query builder. :)
