### ISSUE TITLE
Investigate excessively deep types

### ISSUE THREAD

**Issue by schusovskoy** [kysely-org/kysely#481]
In the [excessively-deep-types doc](https://github.com/kysely-org/kysely/blob/master/site/docs/recipes/excessively-deep-types.md) you wrote "I know what you're thinking: "can't this be done automatically?" No, unfortunately it can't. There's no way to do this using current TypeScript features".

Actually thats not quite right, there is one technique that can help typescript to reset instantiation depth level. Look at the example below:

```ts
type A<T> = { item: T }

type Test<T> = A<
  A<A<A<A<A<A<A<A<A<A<A<A<A<A<A<A<A<A<A<A<A<A<A<A<T>>>>>>>>>>>>>>>>>>>>>>>>
>

type Error = Test<number>
```

Here Test is a type (25 levels deep) that causes `Type instantiation is excessively deep and possibly infinite.` error. But we can force TS to calculate generic type A "in place":

```ts
type A<T> = { item: T } extends infer X ? X : never

type Test<T> = A<
  A<A<A<A<A<A<A<A<A<A<A<A<A<A<A<A<A<A<A<A<A<A<A<A<T>>>>>>>>>>>>>>>>>>>>>>>>
>

type NoError = Test<number>
```

Now everything is ok. The key idea here is to add `extends infer X ? X : never` to the innermost generic type to force TS to unwrap it.

So maybe it will help you improve inference for complex queries.

**Comment by schusovskoy** [comment]
I did it 🙂
@koskimas please review, when you have free time.

**Comment by koskimas** [comment]
Holy crap that's impressive!
