### ISSUE TITLE
jsonArrayFrom dates have Date type but are returned as a string

### ISSUE THREAD

**Issue by jvandenaardweg** [kysely-org/kysely#482]
Hi there,

Thanks for the time and effort on this library, really enjoy working with it on my current project!

I do however have a question. I notice the `Date`'s retrieved by using `jsonArrayFrom` are returned as a `string` instead of a `Date`. The types expect i should get a `Date` back, but in fact i'm getting a `string`. Is this expected behaviour?

Due to not giving away my database architecture in the open, i've reduced it down to it's most basic form below.

Typescript sees both `createdAt` with a `Date` type. But only the `createdAt` from the `jsonArrayFrom` is actually a `string`, which is not what we expect.

```typescript
const a = await kysely
  .selectFrom('a')
  .select((eb) => [
    jsonArrayFrom(
      eb
        .selectFrom('b')
        .select([
          'b.createdAt',
        ])
        .whereRef('b.aId', '=', 'a.id'),
    ).as('b'),
  ])
  .select(['a.createdAt'])
  .where('id', '=', id)
  .executeTakeFirst();

console.log(
  'typeof a?.createdAt',
  typeof a?.createdAt,
  a?.createdAt,
);
// typeof a?.createdAt object 2023-05-02T21:57:15.466Z
// This is a Date, correct!

a?.b.forEach((b) =>
  console.log('typeof b.createdAt', typeof b.createdAt, b.createdAt),
);
// typeof b.createdAt string 2023-05-11 14:16:36.483000
// This is a string, not correct
```

The types:

```typescript
export type A = {
  id: Generated<number>;
  createdAt: Generated<Timestamp>;
};

export type B = {
  id: Generated<number>;
  aId: number;
  createdAt: Generated<Timestamp>;
};
```

Some context: i'm using Kysely with the Planetscale Dialect together with `prisma-kysely` to have the correct types.

edit: can confirm `jsonObjectFrom` is also having this same behaviour.

**Comment by koskimas** [comment]
Yep, this is expected.

**Comment by jvandenaardweg** [comment]
Ok, is it something that can be fixed? Either as a fix in this library or a workaround I can use? As it's not really type-safe here, which is a bit of a bummer

**Comment by koskimas** [comment]
JSON is JSON. There's no `Date` type in JSON. There's nothing we can do. The word `JSON` is in the name of the function, so you shouldn't be that surprised.

**Comment by jvandenaardweg** [comment]
> JSON is JSON. There's no Date type in JSON. There's nothing we can do. The word JSON is in the name of the function, so you shouldn't be that surprised.

True true, but would have expected the types to pick that up too. If the method could return non-JSON types as string, I think that would already fix it?

**Comment by jtmarmon** [comment]
Here's the workaround I'm using in case it helps anyone

```ts
export type CastDatesToStrings<O> = {
    [K in keyof O]: O[K] extends Date ? string : O[K];
};

// https://github.com/kysely-org/kysely/issues/482
export function typesafeJsonArrayFrom<O>(
    expr: Expression<O>,
): RawBuilder<CastDatesToStrings<Simplify<O>>[]> {
    // @ts-expect-error #TS2322
    return jsonArrayFrom(expr);
}
```

**Comment by ptrxyz** [comment]
I also find this devilish; it makes the linter and typescript think everything's find and than -- out of nothing -- things break terribly! :smiling_imp: 

Therefore I extended the casting type from above

```
export type JSONValue =
	| string
	| number
	| boolean
	| null
	| { [x: string]: JSONValue }
	| Array<JSONValue>

export type CastDatesToStrings<O> = {
	[K in keyof O]: O[K] extends JSONValue
		? O[K] // it's a JSONValue, we are good
		: O[K] extends Date // it's a Date, we need to cast it to string
		? string
		: never // otherwise, we don't know what to do, better error out.
}
```

**Comment by koskimas** [comment]
> True true, kinda forgot it only returns JSON because the types were not representing that. Would have expected the types to pick that up too. If the method could return non-JSON types as string, I think that would already fix it?

Recursively traversing the output type and transforming all non-JSON properties to JSON would be terribly slow and it would be done for all outputs of those JSON functions, not just the problematic ones. We could destroy the typescript performance for everyone that uses those functions.

Since the typescript compiler is super slow, we need to constantly balance between type-safety and keeping the IDEs and your compilation step fast. If I fixed this for you, a bunch of other users would come here pissed off demanding the opposite fix.

**Comment by elitan** [comment]
> Here's the workaround I'm using in case it helps anyone
> 
> ```ts
> export type CastDatesToStrings<O> = {
>     [K in keyof O]: O[K] extends Date ? string : O[K];
> };
> 
> // https://github.com/kysely-org/kysely/issues/482
> export function typesafeJsonArrayFrom<O>(
>     expr: Expression<O>,
> ): RawBuilder<CastDatesToStrings<Simplify<O>>[]> {
>     // @ts-expect-error #TS2322
>     return jsonArrayFrom(expr);
> }
> ```

What's the downside of this, and why can't Kysely adopt it natively?

**Comment by hughgardiner** [comment]
> Here's the workaround I'm using in case it helps anyone
> 
> ```ts
> export type CastDatesToStrings<O> = {
>     [K in keyof O]: O[K] extends Date ? string : O[K];
> };
> 
> // https://github.com/kysely-org/kysely/issues/482
> export function typesafeJsonArrayFrom<O>(
>     expr: Expression<O>,
> ): RawBuilder<CastDatesToStrings<Simplify<O>>[]> {
>     // @ts-expect-error #TS2322
>     return jsonArrayFrom(expr);
> }
> ```


got caught by this one as well, thanks for the workaround 🫡

**Comment by NiklasPor** [comment]
FYI we got also caught by this offguard. I don't really mind working with date strings as long as it's the same everywhere. We wrote a simple plugin which rewrites all dates as date strings:

```ts
export class DateStringPlugin implements KyselyPlugin {
  transformQuery(args: PluginTransformQueryArgs): RootOperationNode {
    return args.node;
  }

  async transformResult(args: PluginTransformResultArgs): Promise<QueryResult<UnknownRow>> {
    if (args.result.rows && Array.isArray(args.result.rows)) {
      return {
        ...args.result,
        rows: this.mapRows(args.result.rows),
      };
    }

    return args.result;
  }

  private mapRows(rows: UnknownRow[]): UnknownRow[] {
    return rows.map((row) => this.mapDates(row) as UnknownRow);
  }

  private mapDates(data: unknown | unknown[]): unknown {
    if (Array.isArray(data)) {
      return data.map((d) => this.mapDates(d));
    }

    // Won't work in difference window contexts. No problem as this is only in a single node process.
    if (data instanceof Date) {
      return data.toISOString();
    }

    if (typeof data === "object" && data !== null) {
      return Object.fromEntries(
        Object.entries(data).map(([key, value]) => [key, this.mapDates(value)]),
      );
    }

    return data;
  }
}
```

Then simply search and replace your `Timestamp` (and other date definitions) with your custom `DateString` type:
```ts
export type DateString = string & {};
export type Timestamp = ColumnType<DateString, Date | string, Date | string>;
```

⬆️ This types all selects for Timestamps to return `Datestring` instead of `Date`. The conversion of the result is then done by the plugin.

**Comment by hughgardiner** [comment]
> Here's the workaround I'm using in case it helps anyone
> 
> ```ts
> export type CastDatesToStrings<O> = {
>     [K in keyof O]: O[K] extends Date ? string : O[K];
> };
> 
> // https://github.com/kysely-org/kysely/issues/482
> export function typesafeJsonArrayFrom<O>(
>     expr: Expression<O>,
> ): RawBuilder<CastDatesToStrings<Simplify<O>>[]> {
>     // @ts-expect-error #TS2322
>     return jsonArrayFrom(expr);
> }
> ```

I've updated the following to handle `Date | null`
```typescript
type CastDatesToStrings<O> = {
  [K in keyof O]: O[K] extends Date | null
    ? O[K] extends Date
      ? string
      : O[K] extends null
        ? null
        : string | null
    : O[K];
};
```

**Comment by igalklebanov** [comment]
Try version `0.28.3`, let us know how it goes.
