### ISSUE TITLE
Support for escaping identifiers and literals

### ISSUE THREAD

**Issue by RobinClowers** [kysely-org/kysely#485]
Hi there, loving this library so far, thanks for working on it!

I have a pretty strange use case, I'm building an admin console that allows users to create objects through a web UI. So I need to build a lot of DDL statements, and I want to make sure I'm escaping all user input. These users have direct privileged database access, but defense in depth, etc, I want to make sure this is as secure as possible.

What do you think about having `sql.lit` and `sql.id` replacing single and double quote with pairs, to prevent breaking out of strings? Something like:

```javascript
// in sql.id
idValue.replace('"', '""');
// in sql.lit
litValue.replace("'", "''");
```

If that seems like too much of a breaking change, maybe we could introduce separate escape functions?

**Comment by RobinClowers** [comment]
@koskimas Can you link to the change? It's not obvious to me what changed, and the docs still say these functions are not escaping the input.

**Comment by WoodyWoodsta** [comment]
Also interested. I'd like to know what I'm responsible for escaping and what I can expect kysely or the underlying drivers to escape.

**Comment by RobinClowers** [comment]
Looks like it was https://github.com/kysely-org/kysely/pull/121?

**Comment by RobinClowers** [comment]
However, if I'm not mistaken, that only covers identifiers, not literals? @koskimas can we re-open this? Or would you prefer if I open a new issue specifically about literals?

**Comment by koskimas** [comment]
As a clarification to anyone reading this, Kysely sends all user input as parameters and there is no chance of SQL injection. Parameters are never concatenated to the SQL.

> However, if I'm not mistaken, that only covers identifiers, not literals? @koskimas can we re-open this? Or would you prefer if I open a new issue specifically about literals?

This comment is about the explicit sql.lit function that allows you to concatenate string values to SQL.
