### ISSUE TITLE
Routing reads to one host, writes to another host

### ISSUE THREAD

**Issue by jpike88** [kysely-org/kysely#486]
I know this is maybe a niche situation, but I'm looking to move to kysley from knex.

The situation is that I have a pg master and a replica, and I want 

The workaround in Knex is here, it involves creating two Knex clients (one master, one replica), and then creating a third 'wrapper' client, that we monkey patch to route the query to the appropriate 'real' client.
https://github.com/knex/knex/issues/2253#issuecomment-879182892

The above solution is elegant and works fine but is not part of Knex documented capabilities.

Is there an equivalent strategy I can use with Kysley?

**Comment by kpozin** [comment]
See https://github.com/kysely-org/kysely-replication
