### ISSUE TITLE
Make 'execute' method optional

### ISSUE THREAD

**Issue by jpike88** [kysely-org/kysely#487]
Using knex I enjoyed just being able to `await` a query without the need to explicitly call `execute` on it.

Is there a way to opt out of needing to explicitly execute a query, and just the simple act of 'then'-ing it like a Promise makes it yield the correct value?

**Comment by koskimas** [comment]
Not having the execute method causes confusion about when the query gets executed. It was one of the biggest causes of confusion in objection.
