### ISSUE TITLE
Shorthand object notation for `where`

### ISSUE THREAD

**Issue by jpike88** [kysely-org/kysely#488]
Usually a `where` condition specifies equality.

It would be much easier to just provide an object of a bunch of things I want to match against like this:

```
const person = await db
  .selectFrom('person')
  .selectAll()
  .where({ first_name: 'Jennifer' })
  .executeTakeFirst()
```

This just allows for more succinct code, Knex provides this option.

**Comment by koskimas** [comment]
Nope
