### ISSUE TITLE
Query build doesn't behave in an expected way

### ISSUE THREAD

**Issue by jpike88** [kysely-org/kysely#490]
Unfortunately this is a showstopper for our migration from Knex, I hope this can be looked into.

See below code:

```
console.log(
		await kysley.selectFrom('user').where('id', '=', '1').selectAll().compile()
			.sql
	); // select * from "user" where "id" = $1
console.log(
		await kysley.selectFrom('user').where('id', '=', '1').selectAll().execute()
	); // returns correct values

const wat = kysley.selectFrom('user');
wat.where('id', '=', '1');
wat.selectAll();
console.log(wat.compile().sql); // select from "user"
const f = await wat.execute();
console.log(f); // [ {}, {}, {} ]
```

Those two queries should be outputting the same values. They are built with the same inputs and call the same methods. The second one just happens to be built in multiple calls (which is an extremely common pattern for building complex queries. But for some reason, the second query seems to be ignoring some of the commands it was provided. This is not good.

**Comment by koskimas** [comment]
Kysely is immutable. Please use discord for these questions. These are not issues.
