### ISSUE TITLE
Grouping by weekday/week/day

### ISSUE THREAD

**Issue by iduuck** [kysely-org/kysely#491]
I am currently trying to use kysely for a dashboard I am building. But I am missing the "WEEK", etc. functions. Is there any way to achieve a query like:

```sql
SELECT 
	WEEK(createdDate) as createdWeek,
	COUNT(finishedDate) as finishedCount,
	COUNT(id) as count
FROM
	Table
WHERE
	providerId = "clgz9g6gn0007a4l98chlsae9"
GROUP BY
	createdWeek
ORDER BY
	createdWeek;
```

I couldn't find any issue about this.

**Comment by koskimas** [comment]
This should do it:

```ts
db.selectFrom('Table')
  .select(({ fn }) => [
    fn<number>('WEEK', ['createdDate']).as('createdWeek'),
    fn.count('finishedDate').as('finishedCount'),
    fn.count('id').as('count')
  ])
  .where('providerId', '=', 'clgz9g6gn0007a4l98chlsae9')
  .groupBy('createdWeek')
  .orderBy('createdWeek')
```

**Comment by iduuck** [comment]
That's good to know. Didn't know about the fn argument or even a function as argument. 

Is there any place in the docs about this? Otherwise it would need to be added.

**Comment by igalklebanov** [comment]
@iduuck Kysely is fully documented in your IDE and in generated jsdocs site. We are working on a user-friendly docs site.
There's also a queries forum on our discord server with real-world examples.
