### ISSUE TITLE
Feature request: $ifElse query builder function

### ISSUE THREAD

**Issue by ethanresnick** [kysely-org/kysely#492]
Hello, I love kysely and we've been using it in production for a long time at my company. Thank you for all your hard work!

I have a small feature request for a function that I think would compliment the existing `$if` function. Here's an example:

```ts
db.selectFrom('entity_versions') 
  .$ifElse(
     requestedVersion != null, 
     qb => qb.where(version, '=', requestedVersion),
     qb => qb.where('is_current', '=', true)
  )
```

Pretty simply, the idea is that the current `$if` function lets you add to a query if a condition is true, but doesn't give any way to handle the false case, which `$ifElse` would do. This could even be an overload of the `$if` method, as in:

```ts
db.selectFrom('entity_versions') 
  .$if(
     requestedVersion != null, 
     qb => qb.where(version, '=', requestedVersion),
     qb => qb.where('is_current', '=', true)
  )
```

The best alternative I can think of today (having two `$if`s, one with the condition and one with it's negation) makes it harder to parse what's going on, I think.

**Comment by igalklebanov** [comment]
Hey 👋 

`.$if` was introduced as a way to perform optional selects. It is recommended to use native javascript control flow (e.g. if-else) for other conditionals (e.g. where). [More on that](https://github.com/kysely-org/kysely/pull/272#issuecomment-1503740228).

**Comment by ethanresnick** [comment]
Thanks for the quick response @igalklebanov! I read the thread/comment you linked, and my interpretation is that:

- `$if` was originally added with at least some idea that it could be used for purposes other than optional selects. (I'm basing that on the fact that the documentation for `SelectQueryBuilder.$if` still shows examples of using `$if` with `where()`, `innerJoin()`, etc.)

- However, it was discovered that `$if` leads to TS performance problems, so the Kysely team considers it deprecated, or not desirable for non-select use cases.

Am I understanding that right?

If so, I'm still a bit confused about the relationship between `$if`, TS performance, and this feature request.

In particular, `SelectQueryBuilder.where()` is always gonna return a new `SelectQueryBuilder` that has the same types in the type parameters as the original query builder, whereas `SelectQueryBuilder.select()` is gonna change those type parameters. Therefore, shouldn't it actually be _faster_, in terms of TS performance, to compute the return type of `$if` when then callback uses a `qb.where()`, compared to when it changes the selection?

I.e., the type looks like:

```ts
$if<O2 extends O>(condition: boolean, func: (qb: this) => SelectQueryBuilder<DB, TB, O2>): SelectQueryBuilder<DB, TB, MergePartial<O, O2>>
```
    
So, in `qb.$if(bool, (builder) => builder.where(....))`, `O` and `O2` are the same type, which seems like it should be faster to handle in `MergePartial`, than if`qb.$if(bool, builder => builder.select())` actually introduces a new type for `O2`.

If so, it seems like `$if` could at least be recommended to `.select()` and `.where()` calls – just discouraged for joins and the like. And, if I'm right about the TS performance implications of `where()` calls, then it seems like something like this use case could be supported reasonably efficiently? 

Backing up a bit, I think the reason that people are "overusing" `$if` (as @koskimas described it), and keep asking for ways to make it more powerful, is, I think, a sign that this sort of API is actually nicer to work with compared to native JS control flow, because it lets the author capture the full definition of what is logically intended to be one query, without having to do conditional variable reassignments (or, for the immutable folks, create multiple `const`s for the query at its different stages).

Given the utility of this API, I'd personally prefer an approach that involves heavily _discouraging_ the worst-performing uses of `$if` in the documentation, but still letting users run with it if they're not finding the performance to be an issue or aren't using it for any of the cases that trigger performance problems.

**Comment by koskimas** [comment]
You should just use a normal javascript `if` statement. We're thinking of removing `$if`.

**Comment by ethanresnick** [comment]
>  Based on what I've seen, most of the time people thing they have no other option but to use $if.

@koskimas That's very interesting. I won't speak for others but, just on my team, it's always been clear that we could use standard JS control flow for these cases and, in fact, that's exactly what we've done historically. We actually found `$if` very recently in our usage of kysely, and have been inclined to use it instead of standard control flow constructs, solely for the ergonomics.

To give a concrete example, we tend to code w/ minimal mutable variables and we try to keep the scope of each variable as narrow as possible, so, on our team, the example in the OP would become something like:

```ts
const entityVersionsQuery = (() => {
  const baseQuery = db
    .selectFrom('entity_versions')
    .select(['a', 'b', 'c']);

  return requestedVersion != null 
    ? baseQuery.where(version, '=', requestedVersion)
    : baseQuery.where('is_current', '=', true);
})();
```

That's honestly not horrible, but it does seem distinctly worse than:


```ts
const entityVersionsQuery = db
  .selectFrom('entity_versions')
  .select(['a', 'b', 'c']);
  .$if(
     requestedVersion != null, 
     qb => qb.where(version, '=', requestedVersion),
     qb => qb.where('is_current', '=', true)
  );
```

Again, just speaking for my team, I think we're willing to pay the TS performance overhead (esp. as we haven't actually run into the 'instantiation excessively deep' error w/ our Kysely usage) for the ergonomics benefit.

**Comment by ethanresnick** [comment]
Btw, for anyone who finds this later, this use case is well-served by the expression builder API, which I hadn't started using at the time:

```ts
db.selectFrom('entity_versions') 
  .where(({ cmpr }) => 
    requestedVersion != null 
      ? cmpr('version', '=', requestedVersion)
      :  cmpr('is_current', '=', true)
  )
