### ISSUE TITLE
How to type optional input params?

### ISSUE THREAD

**Issue by lancejpollard** [kysely-org/kysely#493]
I would like to construct the input properties to an `insertInto(table).values(input)` call, progressively. Therefore, all the possible props need to be optional type. However, when calling `.values(input)`, I am getting this error:

    No overload matches this call.
      Overload 1 of 2, '(insert: InsertObjectOrList<DB, "my_table">): InsertQueryBuilder<DB, "my_table", InsertResult>', gave the following error.
        Argument of type 'Partial<MyTable>' is not assignable to parameter of type 'InsertObjectOrList<DB, "my_table">'.
          Type 'Partial<MyTable>' is not assignable to type 'InsertObject<DB, "my_table">'.
            Type 'Partial<MyTable>' is not assignable to type '{ id: ValueExpression<DB, "my_table", string>; language_id: ValueExpression<DB, "my_table", string>; }'.
              Types of property 'id' are incompatible.
                Type 'string | undefined' is not assignable to type 'ValueExpression<DB, "my_table", string>'.
                  Type 'undefined' is not assignable to type 'ValueExpression<DB, "my_table", string>'.
      Overload 2 of 2, '(insert: InsertObjectOrListFactory<DB, "my_table">): InsertQueryBuilder<DB, "my_table", InsertResult>', gave the following error.
        Argument of type 'Partial<MyTable>' is not assignable to parameter of type 'InsertObjectOrListFactory<DB, "my_table">'.
          Type 'Partial<MyTable>' provides no match for the signature '(eb: ExpressionBuilder<DB, "my_table">): InsertObjectOrList<DB, "my_table">'.ts(2769)

```ts
const input: Partial<MyTable> = {
  id: uuid.v4(),
  some_id: params.someId,
};

if (params.something) {
  input.something_else = params.something + 10
}

await db.insertInto("my_table").values(input).execute();
```

How can I get this properly with kysely?

I am using kysely-codegen to generate the schema types from the db.

**Comment by lancejpollard** [comment]
Alright, I figured it out:

```
Insertable<MyTable>
```

**Comment by elitan** [comment]
This should be added to the docs.
