### ISSUE TITLE
Sqlite Error: No such table

### ISSUE THREAD

**Issue by hi-brylle** [kysely-org/kysely#497]
This is on Node. This is my code

```
... (tables above)

interface TouchPanelAppDB {
    experiment: ExperimentTable,
    experiment_profile: ExperimentProfileTable,
    data_snapshots: DataSnapshotsTable
}

const db = new Kysely<TouchPanelAppDB>({
    dialect: new SqliteDialect({
        database: async () => new Database(path.join(path.dirname(process.cwd()), "touch_panel_utils", "db", "touch_panel_app_db.db"))
    })
})

... (function queries below)
```

The better-sqlite3 db path I set is placed just outside the project's repo. Whenever I run this app and the server eventually crashes, I would check that the db file itself is created but it doesn't have tables in it. This is the error I get:

![image](https://github.com/kysely-org/kysely/assets/55132223/70207744-7cd6-4209-b631-8a43b82fa700)

I'm definitely missing something, but I can't see it in the docs. I already tried wrapping the new db in a promise with the async according to https://kysely-org.github.io/kysely/classes/SqliteDialect.html thinking I could just 'lazily instantiate' the db. Or do I have to create the tables myself first? Thank you.

**Comment by koskimas** [comment]
You need to run migrations.
