### ISSUE TITLE
AlterColumnBuilder - rename should not be chained with another operation

### ISSUE THREAD

**Issue by soanvig** [kysely-org/kysely#498]
Following builder produces invalid query for Postgres

```
db.schema.alterTable('X').addColumn('Y', 'int').renameColumn('Z1', 'Z2')
```

The reason is because it creates a query:

```
alter table "X" add column "Y" int, rename column "Z1" to "Z2"
```

Which according to https://www.postgresql.org/docs/current/sql-altertable.html
is invalid.

Rename (column or constraint) must be a standalone operation.

Therefore both `.renameColumn().XXX()` and `XXX().renameColumn()` must be prohibited.
I don't see a function to rename constraint, so we can skip it.

If you agree I can prepare PR

**Comment by koskimas** [comment]
That's a valid query.

**Comment by soanvig** [comment]
For other users in future:

This is literally invalid query.

![image](https://github.com/kysely-org/kysely/assets/7525286/ad74dde4-7039-493f-b951-392a8b5aeea6)

Also, postgresql clearly states that you have to choose between
1. ALTER TABLE RENAME
2. ALTER TABLE action (action: ADD, DROP, ALTER COLUMN)

However MySQL permits that (https://dev.mysql.com/doc/refman/8.0/en/alter-table.html)

SQLite doesn't permit that as well: https://www.sqlite.org/lang_altertable.html

So I guess if only MySQL supports that it's still a reason to support that on Kysely level.
