### ISSUE TITLE
How should I reset a column back to its default value when updating a table?

### ISSUE THREAD

**Issue by lucassilvas1** [kysely-org/kysely#500]
I'm trying to reset a column of a row back to its default value when I update a table, but I'm not sure how to do that, right now I'm just using ``` sql`DEFAULT` ``` as the value when updating, but I don't know what type to use for that, so, for now the type for that column is `ColumnType<Date, never, any>`, which is not ideal since `set` will accept any value for that column that way.

Basically, the only thing I want to do to that column when updating is resetting its value back to default, nothing else, how do I do that while remaining type safe?

**Comment by koskimas** [comment]
You can specify the type like this 

```ts
sql<Date>`DEFAULT`
```

You could create a helper:

```ts
function defaultDate() {
  return sql<Date>`DEFAULT`
}
```
