### ISSUE TITLE
How to dynamically build list of keys to use in a select query in `.select(keys)`?

### ISSUE THREAD

**Issue by lancejpollard** [kysely-org/kysely#501]
Not sure where to post this, I tried discord but it seems dead, and I was the first person to tag `kysely` on stackoverflow, so not sure I will get any bites there. Any help would be appreciated (and note on where I should ask future questions, I have a few for kysely).

https://stackoverflow.com/questions/76277708/how-to-properly-build-an-array-of-keys-which-match-a-types-keys-in-typescript

Thanks!

**Comment by koskimas** [comment]
If the discord seems dead you were in the wrong discord.

**Comment by koskimas** [comment]
Here's one option https://kyse.link/?p=s&i=ye5MaLka2OLLWmIBVnSC

**Comment by koskimas** [comment]
You were actaully answered 11 minutes after your question. Jesus christ 😄 That's enough for you to consider it dead?????
