### ISSUE TITLE
Typescript type errors when casting the column types on a `innerJoin`?

### ISSUE THREAD

**Issue by edgarsilva** [kysely-org/kysely#502]
@koskimas @igalklebanov how would this work on a `innerJoin`? I have this problem where I need to join a table but the columns have diff types and I keep getting this ->

![image](https://github.com/kysely-org/kysely/assets/518231/4c6c52fc-bd35-44af-9be6-2ecd6e7b05b4)

For This query ->

```ts
const purchaseOrders = await db
    .selectFrom("integration.purchase_order as po")
    .innerJoin("integration.order_data as od",
      sql<string>`od.po_ext_id::text`,
      sql<string>`po.id::text`)
    .select([
      "po.id",
      "od.id",
      "od.po_ext_id",
    ])
    .limit(5)
    .execute();
```

Which forces me to do this to bypass it -> 

```ts
const purchaseOrders = await db
    .selectFrom("integration.purchase_order as po")
    .innerJoin("integration.order_data as od",
      sql<string>`od.po_ext_id::text` as unknown as "od.po_ext_id",
      sql<string>`po.id::text` as unknown as "od.po_ext_id")
    .select([
      "po.id",
      "od.id",
      "od.po_ext_id",
    ])
    .limit(5)
    .execute();
```
is This the correct approach?

**Comment by edgarsilva** [comment]
Amazing work with this query builder BTW 👏🏽 keep up the good work!

**Comment by koskimas** [comment]
I think the problem is that the simple "two columns" shortcut version of the join methods only accepts string references. You can do something like this:

```ts
innerJoin('table', join => join.on(sql`col1::text`, '=', sql`col2::text`))
```

**Comment by edgarsilva** [comment]
Yes! thanks for the fast response, this is exactly what I meant, I was looking for something like this in the docs but couldn't find it. I'll give it a try 👍🏽

**Comment by koskimas** [comment]
That's the third example in the `innerJoin` methods's documentation. Where did you try to search it? https://kysely-org.github.io/kysely/classes/SelectQueryBuilder.html#innerJoin
