### ISSUE TITLE
Kysely does not work in combination with OpenTelemetry (using mysql dialect)

### ISSUE THREAD

**Issue by jballentine-sharpen** [kysely-org/kysely#503]
It seems something with OpenTelemetry's mysql2 instrumentation conflicts with Kysely. When I attempt to execute a query, I get an error of `TypeError: format is not a function` as well as some warnings of `Warning: Accessing non-existent property 'format' of module exports inside circular dependency`, with the error coming from `@opentelemetry/instrumentation-mysql2/src/utils.ts:105:21`. and caused by `kysely/dist/esm/dialect/mysql/mysql-driver.js:117:33`

This issue does not happen with regular connections using the mysql2 package directly, or when using connections created via Knex. It seems something Kysely-specific is causing this conflict.

Any suggestions are welcome, but I'm assuming this is just a bug that nobody has encountered before.

**Comment by igalklebanov** [comment]
Hey 👋 

Kysely will never provide opentelemetry support in its core. This is something that has to be published by opentelemetry, same as they did with [Knex](https://github.com/open-telemetry/opentelemetry-js-contrib/tree/main/plugins/node/opentelemetry-instrumentation-knex).

I'd be happy to collaborate with them.

**Comment by rhyek** [comment]
FYI, I believe it's not required for opentelemetry to publish the instrumentation. Prisma developed their own [here](https://www.npmjs.com/package/@prisma/instrumentation). However, it's not super compliant the the [otel db spec](https://opentelemetry.io/docs/specs/semconv/attributes-registry/db/). This is what brought me here, actually. Was wondering what otel support looked like.

**Comment by igalklebanov** [comment]
Prisma is:

1. a company. I imagine implementing it in-house and under the organization was faster to ship than waiting on the OTEL maintainers.
2. an ORM with a Rust engine under the hood. This, I imagine, required a Prisma-specific OTEL implementation.

![image](https://github.com/user-attachments/assets/d2dbe011-f3f3-409b-a6a0-0b8f1e8a6881)

With `kysely` you can probably just instrument the underlying drivers (e.g. `pg`, `mysql2`, etc.) with existing OTEL implementations and call it a day. Isn't it enough or am I missing something?

**Comment by rhyek** [comment]
> With `kysely` you can probably just instrument the underlying drivers (e.g. `pg`, `mysql2`, etc.) with existing OTEL implementations and call it a day. Isn't it enough or am I missing something?

This might be the case. Unsure about the kysely internals. Good to know!
