### ISSUE TITLE
How to get it working in TypeScript project?

### ISSUE THREAD

**Issue by JetLi2K** [kysely-org/kysely#506]
I have been spending a month trying to get Kysely working and random tutorial on the web aren't working correctly. There is a huge barrier to adopt Kysely in TypeScript project.

How does pg work with TypeScript?

`import { Pool } from 'pg'`

`
  CommonJS modules can always be imported via the default export, for example using:
  
  import pkg from 'pg';
  const { Pool } = pkg;
  
import { Pool } from 'pg';
         ^^^^
SyntaxError: Named export 'Pool' not found. The requested module 'pg' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from 'pg';
const { Pool } = pkg;

    at ModuleJob._instantiate (node:internal/modules/esm/module_job:124:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:190:5)
`

**Comment by JetLi2K** [comment]
It doesn't compile with

```
import pkg from 'pg';
const { Pool } = pkg;
```

**Comment by koskimas** [comment]
You are the first one having this much trouble. Our documentation is not the best but it's not that difficult. Seems like you are just frustrated and want to make us feel bad too. I suggest you try some other library that has more mature documentation and better tutorials.

**Comment by JetLi2K** [comment]
I have got it working! Thanks!
