### ISSUE TITLE
Support SQLITE's `ON CONFLICT` clause

### ISSUE THREAD

**Issue by johnpyp** [kysely-org/kysely#510]
Sqlite supports a non-standard `ON CONFLICT` clause (https://www.sqlite.org/lang_conflict.html) that determines how inserts/updates/create tables work, taking into account the entire row. Notably, this is **distinct** from sqlite's implementation of `ON CONFLICT` for use in its `upsert` clause - https://www.sqlite.org/lang_UPSERT.html.

An example usecase of this feature is a simplified upsert, that just replaces the underlying with the new row if there's a primary key or unique constraint violation of any sort, instead of having to declare every conflict resolution separate from the main insert body:

(Note the use of `OR REPLACE` instead of `ON CONFLICT REPLACE`, which is part of the syntax to be less verbose in INSERT/UPDATE statements)

```
INSERT OR REPLACE INTO subscriptions (
  id, -- The primary key, if this is conflicted, the row gets deleted and replaced with this new one
  many,
  keys,
  that,
  will,
  always,
  be,
  upserted
) VALUES ( ... )
```

**Comment by koskimas** [comment]
You can get the same result like this https://kyse.link/?p=s&i=wSDqoqqCK5mM9d5z5Ywy. Since this is trivially implemented using the current features, I don't think we should add another nonstandard method.

**Comment by enrique-lozano** [comment]
> You can get the same result like this https://kyse.link/?p=s&i=wSDqoqqCK5mM9d5z5Ywy. Since this is trivially implemented using the current features, I don't think we should add another non-standard method.

But here in your example we can not inser arrays right? If we convert the `user` object to an array we can insert this array but the `doUpdateSet` fails. Maybe we should wait for #976 to get this functionality
