### ISSUE TITLE
Pattern for create / replace function in Postgres?

### ISSUE THREAD

**Issue by theogravity** [kysely-org/kysely#514]
I'm currently using the `sql` template tag to create functions:

```ts
  await sql`
  CREATE OR REPLACE FUNCTION sb.test_fn() RETURNS TRIGGER AS $$
  DECLARE
      modelName TEXT;
  BEGIN
      SELECT model INTO modelName FROM sb.chunk WHERE id = NEW.document_id;

      INSERT INTO sb.chunk_embed (document_chunk_id, embedding)
      VALUES (NEW.id, pgml.embed(modelName, NEW.text));
      RETURN NEW;
  END;
  $$ LANGUAGE plpgsql;`.execute(db);
```

It gets a bit unwieldy to have to specify `sb.` everywhere. I do have the `WithSchemaPlugin` in use, but I figure that's only applicable to non-raw queries.

Is there a better pattern for this?

**Comment by theogravity** [comment]
It looks like as long as the function has the context of the schema, it can be simplified where you don't need the schema name in the actual definition:

```ts
  await sql`
  CREATE OR REPLACE FUNCTION sb.test_fn() RETURNS TRIGGER AS $$
  DECLARE
      modelName TEXT;
  BEGIN
      SELECT model INTO modelName FROM chunk WHERE id = NEW.document_id;

      INSERT INTO chunk_embed (document_chunk_id, embedding)
      VALUES (NEW.id, pgml.embed(modelName, NEW.text));
      RETURN NEW;
  END;
  $$ LANGUAGE plpgsql;`.execute(db);
```

**Comment by igalklebanov** [comment]
Hey 👋 

Kysely doesn't have built-in support for stored programs (functions / triggers / procedures).
Using sql template tag is the right call here. 

You could also embed query builders, be somewhat type-safe and aligned with dialect compilation detail, but it is very hacky:

```ts
import { ExpressionBuilder, sql } from "kysely"

interface NEW {
  id: string
  document_id: string
  text: string
}

interface Props {
  modelName: string
}

interface TriggerDB extends DB {
  NEW: NEW
  _props: Props // fake table to allow referring to function's props.
}

type TriggerTB<TB> = TB | "NEW" | "_props" // we use this to lie to Kysely that `NEW` and `_props` are part of query context even they're not part of `selectFrom` or `insertInto` args.

const trigger = db.withTables<{ [K in keyof TriggerDB]: TriggerDB[K] }>()

await sql`
  CREATE OR REPLACE FUNCTION sb.test_fn() RETURNS TRIGGER AS $$
  DECLARE
    ${sql.ref("modelName")} TEXT;
  BEGIN
    select * into ${sql.ref("modelName")} from ${trigger
  .selectFrom<TriggerTB<"chunk">>("chunk")
  .whereRef("id", "=", "NEW.document_id")
  .select("model")
  .as("c")};

    ${sql.raw(
      trigger
        .insertInto<TriggerTB<"chunk_embed">>("chunk_embed")
        .values(
          (eb: ExpressionBuilder<TriggerDB, TriggerTB<"chunk_embed">>) => ({
            document_chunk_id: eb.ref("NEW.id"),
            embedding: eb.fn("pgml.embed", ["modelName", "NEW.text"]),
          }),
        )
        .compile().sql,
    )};

    RETURN ${sql.ref("NEW")};
  END;
  $$ LANGUAGE plpgsql;`.execute(trigger)

```
[Playground link](https://kyse.link/?p=b&i=haFkqHBvc3RncmVzoXamMC4yNC4yoXPaARBpbXBvcnQgeyBHZW5lcmF0ZWQgfSBmcm9tICJreXNlbHkiCgpkZWNsYXJlIGdsb2JhbCB7CiAgaW50ZXJmYWNlIERCIHsKICAgIGNodW5rOiBDaHVuawogICAgY2h1bmtfZW1iZWQ6IENodW5rRW1iZWQKICB9CgogIGludGVyZmFjZSBDaHVuayB7CiAgICBpZDogR2VuZXJhdGVkPHN0cmluZz4KICAgIG1vZGVsOiBzdHJpbmcKICB9CgogIGludGVyZmFjZSBDaHVua0VtYmVkIHsKICAgIGRvY3VtZW50X2NodW5rX2lkOiBzdHJpbmcKICAgIGVtYmVkZGluZzogc3RyaW5nCiAgfQp9CqFx2gQ6aW1wb3J0IHsgRXhwcmVzc2lvbkJ1aWxkZXIsIHNxbCB9IGZyb20gImt5c2VseSIKCmludGVyZmFjZSBORVcgewogIGlkOiBzdHJpbmcKICBkb2N1bWVudF9pZDogc3RyaW5nCiAgdGV4dDogc3RyaW5nCn0KCmludGVyZmFjZSBQcm9wcyB7CiAgbW9kZWxOYW1lOiBzdHJpbmcKfQoKaW50ZXJmYWNlIFRyaWdnZXJEQiBleHRlbmRzIERCIHsKICBORVc6IE5FVwogIF9wcm9wczogUHJvcHMKfQoKdHlwZSBUcmlnZ2VyVEI8VEI-ID0gVEIgfCAiTkVXIiB8ICJfcHJvcHMiCgpjb25zdCB0cmlnZ2VyID0gZGIud2l0aFRhYmxlczx7IFtLIGluIGtleW9mIFRyaWdnZXJEQl06IFRyaWdnZXJEQltLXSB9PigpCgphd2FpdCBzcWxgCiAgQ1JFQVRFIE9SIFJFUExBQ0UgRlVOQ1RJT04gc2IudGVzdF9mbigpIFJFVFVSTlMgVFJJR0dFUiBBUyAkJAogIERFQ0xBUkUKICAgICR7c3FsLnJlZigibW9kZWxOYW1lIil9IFRFWFQ7CiAgQkVHSU4KICAgIHNlbGVjdCAqIGludG8gJHtzcWwucmVmKCJtb2RlbE5hbWUiKX0gZnJvbSAke3RyaWdnZXIKICAuc2VsZWN0RnJvbTxUcmlnZ2VyVEI8ImNodW5rIj4-KCJjaHVuayIpCiAgLndoZXJlUmVmKCJpZCIsICI9IiwgIk5FVy5kb2N1bWVudF9pZCIpCiAgLnNlbGVjdCgibW9kZWwiKQogIC5hcygiYyIpfTsKCiAgICAke3NxbC5yYXcoCiAgICAgIHRyaWdnZXIKICAgICAgICAuaW5zZXJ0SW50bzxUcmlnZ2VyVEI8ImNodW5rX2VtYmVkIj4-KCJjaHVua19lbWJlZCIpCiAgICAgICAgLnZhbHVlcygKICAgICAgICAgIChlYjogRXhwcmVzc2lvbkJ1aWxkZXI8VHJpZ2dlckRCLCBUcmlnZ2VyVEI8ImNodW5rX2VtYmVkIj4-KSA9PiAoewogICAgICAgICAgICBkb2N1bWVudF9jaHVua19pZDogZWIucmVmKCJORVcuaWQiKSwKICAgICAgICAgICAgZW1iZWRkaW5nOiBlYi5mbigicGdtbC5lbWJlZCIsIFsibW9kZWxOYW1lIiwgIk5FVy50ZXh0Il0pLAogICAgICAgICAgfSksCiAgICAgICAgKQogICAgICAgIC5jb21waWxlKCkuc3FsLAogICAgKX07CgogICAgUkVUVVJOICR7c3FsLnJlZigiTkVXIil9OwogIEVORDsKICAkJCBMQU5HVUFHRSBwbHBnc3FsO2AuZXhlY3V0ZSh0cmlnZ2VyKQqhY8M=)
