### ISSUE TITLE
Planetscale Kysely cascade delete many to many

### ISSUE THREAD

**Issue by Adam-Collier** [kysely-org/kysely#516]
I'm currently using Prisma for db migrations and Kysely for dealing with the sql query executing and type safety. I have the below schema with Bookmark and BookmarkTag having a many too many relationship

```js
export type Bookmark = {
  id: Generated<number>
  createdAt: Generated<Timestamp>
  updatedAt: Timestamp
  title: string
  url: string
  description: string | null
  favicon: string
}
export type BookmarkTag = {
  id: Generated<number>
  createdAt: Generated<Timestamp>
  updatedAt: Timestamp
  name: string
}
export type _BookmarkTags = {
  A: number
  B: number
}
```

I'm super new to writing sql queries and I've got creating a bookmark, tag and linking them working fine. However, I would like to know how I would go about deleting the relations when a bookmark is deleted? I think usually onDelete: Cascade would be used for something like this, but because Planetscale doesn't use foreign keys this doesn't seem to be possible. Any help would be appreciated and apologies if this isn't the correct location for discussing something like this 🙏

**Comment by koskimas** [comment]
If there are no foreign keys, then the only option is to use separate queries:

```
await db.deleteFrom('bookmarks').where('id', 'in', arrayOfIdsToDelete).execute()
await db.deleteFrom('_bookmarkTags').where('A', 'in', arrayOfIdsToDelete).execute()
```

don't know the names of the tables so I just guessed something here.

**Comment by igalklebanov** [comment]
Planetscale is based on MySQL, so multi-table deletes should work.

Better make sure this behaves (engine-wise) as you'd expected:

```ts
await db
  .deleteFrom(['person', 'pet', 'toy'])
  .using('person')
  .leftJoin('pet', 'pet.owner_id', 'person.id')
  .leftJoin('toy', 'toy.pet_id', 'pet.id')
  .where('toy.price', '=', 1000)
  .execute()
```

**Comment by Adam-Collier** [comment]
Perfect thanks for clarifying @koskimas and sharing how the Kysely implementation could look @igalklebanov. I appreciate you both taking the time to respond!
