### ISSUE TITLE
Should `insertInto('table').values(data).executeTakeFirst()` return a value?

### ISSUE THREAD

**Issue by mac-long** [kysely-org/kysely#523]
I have the following code to insert into a database table, the function does indeed insert into the database, however it doesn't return any data just an empty object `{}`

``` ts
const insertedRecipe = await db
    .insertInto("recipe")
    .values(recipe)
    .executeTakeFirst();
```

Is this correct? Or should it return a value?

**Comment by koskimas** [comment]
It does return a value. The properties are not enumerable, so they don't show up when you console.log the object. But the properties are there. Just try to access them.

**Comment by igalklebanov** [comment]
Agree with @koskimas. 

Also wanted to point out that if you're expecting the inserted recipe to be returned, and using PostgreSQL or SQLite, then you should add a `.returning`/`.returningAll` method invocation before `.executeTakeFirst`.

**Comment by mac-long** [comment]
For some reason my editor was saying that `.returning` didn't exist when I tried it earlier... I couldn't find any docs on it either. Seems to be working now thought.

**Comment by koskimas** [comment]
https://github.com/kysely-org/kysely/assets/846508/a3d124e9-11a1-4311-9cfc-228937439893

**Comment by koskimas** [comment]
I'm curious, where did you search the documentation?

**Comment by koskimas** [comment]
Also you can just hover over any method to get the docs and a bunch of examples:


https://github.com/kysely-org/kysely/assets/846508/a9178a9b-1024-4358-951d-e596ddf5ac48

**Comment by koskimas** [comment]
So please tell us, how could we make finding the documentation easier for you?

**Comment by mac-long** [comment]
I'm not sure I must have done so via a search engine. Might I recommend adding a returning section to this page on the [.dev](https://www.kysely.dev/docs/category/insert) url.

**Comment by igalklebanov** [comment]
> I'm not sure I must have done so via a search engine. Might I recommend adding a returning section to this page on the [.dev](https://www.kysely.dev/docs/category/insert) url.

kysely.dev is a WIP, so it might not have everything.

This is what google offers me for "kysely insert":

![image](https://github.com/kysely-org/kysely/assets/14938291/e9ec86bd-d764-4552-9d76-c333ca2837cb)

**Comment by mac-long** [comment]
Yeah unsure where I stumbled across the pages when searching, apologies for that. I understand the site is a WIP. That's where I'd put it though as Vercel etc. is linking to that site when suggesting your library.
