### ISSUE TITLE
[Feature] Migration arguments

### ISSUE THREAD

**Issue by theogravity** [kysely-org/kysely#529]
I have a scenario where I'm dynamically creating a table based on a template. The table name would be non-static.

Ideally I'd like to re-use my migrations to dynamically create the table by specifying a prefix for the name. 

It'd be nice if when I perform a migration operation(s), I can feed in external args for use with building the schema.

For example:

```ts
export async function up(db: Kysely<any>, args: Record<string, any>): Promise<void> {
```

```ts
await migrator.migrateToLatest(pathToMigrationsFolder, { ... })
```

**Comment by theogravity** [comment]
I guess I could also just do this without migrations since it uses the `db` object under the hood, but then there would be no actual tracking of this in the migrations table

**Comment by koskimas** [comment]
I don't think this is a good idea. Migrations should never be dynamic. They should be static in all possible ways.

You could simply use environment variables.

**Comment by theogravity** [comment]
Thank you for the consideration!
