### ISSUE TITLE
`col.references()` method makes the column NOT NULL automatically

### ISSUE THREAD

**Issue by 01hossein10** [kysely-org/kysely#533]
I'm using Kysely with PostgreSQL. I created a table called `roles` but when I used `references` method to create a foreign key on `invited_by` column (without using `notNull()`) it automatically makes this column `NOT NULL`. Is that a normal behaviour?

Here's my code:
```
await db.schema
  .createTable('roles')
  .addColumn('id', 'serial', col => col.primaryKey())
  .addColumn('type', sql`"RoleTypes"`, col => col.notNull())
  .addColumn('status', sql`"RoleStatus"`, col => col.notNull())
  .addColumn('user_id', 'serial', col =>
    col.references('users.id').onDelete('cascade').notNull()
  )
  .addColumn('workspace_id', 'serial', col =>
    col.references('workspaces.id').onDelete('cascade').notNull()
  )
  .addColumn('created_at', 'timestamp', col =>
    col.defaultTo(sql`now()`).notNull()
  )
  .addColumn('updated_at', 'timestamp', col =>
    col.defaultTo(sql`now()`).notNull()
  )
  .addColumn('invited_at', 'timestamp')
  .addColumn('invited_by', 'serial', col => col.references('users.id'))
  .execute();
```

So my problem is with this line: 
```.addColumn('invited_by', 'serial', col => col.references('users.id'))```
Which in this case, there is no difference with this one:
```.addColumn('invited_by', 'serial', col => col.references('users.id').notNull())```

**Comment by koskimas** [comment]
Kysely doesn't add `not null` automatically there. Something else is doing it.
