### ISSUE TITLE
Support custom limit expressions

### ISSUE THREAD

**Issue by RobinClowers** [kysely-org/kysely#534]
I'm working with a database that doesn't support parameters in the limit clause, would it be possible to add an overload that takes an expression, so I can set the limit to a raw value?

**Comment by koskimas** [comment]
Good idea! Let's add it.

**Comment by iamtope** [comment]
Hi, can I take on this issue? You can assign it to me possibly

**Comment by igalklebanov** [comment]
@iamtope 

Sure! 💪 

if you need any help, feel free to ask in contributing channel on discord..

**Comment by iamtope** [comment]
Thanks, on it
