### ISSUE TITLE
Documentation dark mode not usable.

### ISSUE THREAD

**Issue by c608345** [kysely-org/kysely#535]
https://kysely.dev/docs/installation
![09456845067](https://github.com/kysely-org/kysely/assets/37238933/c859f64d-2776-4818-9813-6634e9d7c8e2)

**Comment by koskimas** [comment]
Noted.

**Comment by koskimas** [comment]
Yes it is, and it looks nothing like the picture in this issue 😄

**Comment by igalklebanov** [comment]
> I disabled js, enable js it works fine. So the real problem is documentation didn't work without js.

We'll require javascript in the docs site if and when #521 is merged, because it does client-side stuff with query params.
