### ISSUE TITLE
Cursor Based Pagination

### ISSUE THREAD

**Issue by suchcodemuchwow** [kysely-org/kysely#544]
I have seen in the examples there is support for `pg-cursor` but couldn't see the same for mysql. Do we have to rely on custom implementation or is there any suggested way for cursor based pagination in mysql driver.

**Comment by igalklebanov** [comment]
Hey 👋 

There is no opinionated solution for pagination in the core right now.
`pg-cursor` is used for result streaming only.

There is a community project you could try: https://github.com/charlie-hadden/kysely-paginate

**Comment by cryptrr** [comment]
kysely-paginate is still WIP.

What a bummer.
