### ISSUE TITLE
instructions for mysql into readme

### ISSUE THREAD

**Issue by bazo** [kysely-org/kysely#545]
hi, can you add the instructions for mysql into readme? took me a while to find them in changelog

```ts
import { createPool } from 'mysql2'

const db = new Kysely<Database>({
  dialect: new MysqlDialect({
    pool: createPool({
      host: 'localhost',
      database: 'kysely_test'
    })
  })
})
```

**Comment by igalklebanov** [comment]
Hey 👋 

Please refer to the "Getting Started" section on our docs site:
https://kysely.dev/docs/getting-started?dialect=mysql

We'll eventually remove things from the readme and refer to the docs.
