### ISSUE TITLE
Add `.table(tableName)` to `ExpressionBuilder`.

### ISSUE THREAD

**Issue by igalklebanov** [kysely-org/kysely#546]
Hey 👋 

When building queries with a mix of `sql` template tag and `eb` (`ExpressionBuilder`) we have `eb.ref` that provides a type-safe way of referring to columns in query context, 

example:

```ts
(eb) => sql`...${eb.ref('column')}...`
(eb) => sql`...${eb.ref('table.column')}...`
```

but we have no way to refer to just table names in query context.

something like:

```ts
(eb) => sql`...${eb.table('table')}...`
```

Such functionality exists in `sql` template tag (`sql.table`) but in a non-type-safe way, you can pass any string without errors.

Implementing it in `ExpressionBuilder` should be straightforward as it has awareness of table names in query context through a generic value.

**Comment by koskimas** [comment]
Good idea!

**Comment by naorpeled** [comment]
Hey,
would love to work on this, feel free to assign me  :)

**Comment by igalklebanov** [comment]
@koskimas wasn't this added recently?

**Comment by koskimas** [comment]
Yep, done.
