### ISSUE TITLE
Support `WINDOW` clause. 

### ISSUE THREAD

**Issue by igalklebanov** [kysely-org/kysely#547]
Hey 👋 

In #153, we started supporting window functions.

[PostgreSQL](https://www.postgresql.org/docs/current/tutorial-window.html), [MySQL](https://dev.mysql.com/doc/refman/8.0/en/window-functions-named-windows.html) and [SQLite](https://www.sqlite.org/windowfunctions.html) support the `WINDOW` clause as a way to DRY up window definitions with ability to extend them.

example of possible API:

```ts
db.selectFrom('t0')
  .window('win1', (ob) => ob.orderBy('y'))
  .window('win2', (ob) => ob.partitionBy('y').orderBy('x'))
  .select((eb) => [
    'x',
    'y',
    eb.fn.agg('row_number', []).over('win1').as('row_number'),
    eb.fn.agg('rank', []).over('win2').as('rank'),
    eb.fn.avg('x').over('win1', (ob) => ob.partitionBy('x')).as('avg'), // this re-uses `win1` and extends it.
  ])
```

compiles to:

```sql
select "x", "y", 
  row_number() over "win1" as "row_number", 
  rank() over "win2" as "rank", 
  avg("x") over ("win1" partition by "x") as "avg"
from "t0"
window "win1" as (order by "y"), "win2" as (partition by "y" order by "x")
```

If we want this to be type-safe, we'd have to introduce another generic slot for window names in `SelectQueryBuilder`, `ExpressionBuilder` and `AggregateFunctionBuilder`. It will default to `never`.

**Comment by koskimas** [comment]
I don't think it's a good idea to add another generic for this. I've never seen anyone use named windows. I wonder if the whole feature is worth the complexity 🤔

**Comment by igalklebanov** [comment]
I don't have a horse in this one. Consumers could just implement helper functions or find another way to keep it DRY. I agree that adding a generic for this one is not worth it.

I think it's good that we document these and our decisions so everything's searchable.
