### ISSUE TITLE
Not working:  selectAll from multiple tables

### ISSUE THREAD

**Issue by Firebrand** [kysely-org/kysely#559]
Hi,

I'm trying to select all columns from just two tables out of the four I'm using in the joins (aliased as a & b, see image) and the raw SQL output generated by this is actually correct and it works.

However, I'm getting a type-related error because I guess selectFrom is only defining one of those tables, although if I defined both (ex. _db.selectFrom(['menuItems as a', 'menuItemRootMenuLinks as b'])..._ )  that would not generate correct raw SQL.

![image](https://github.com/kysely-org/kysely/assets/7831979/5a5024c1-40f5-4bb0-bd2e-b3aa552b6055)

**Comment by igalklebanov** [comment]
Hey 👋 

TypeScript compiler can't work backwards.
You must, at first, accumulate query context, and only then select from it.
This is also aligned with SQL's order of execution - `from->joins->where->group by->having->select->order by->limit`.

**Comment by Firebrand** [comment]
Thanks @igalklebanov , I've understood that, but what do you suggest I do in this case? How do I make it aware of the join with b before I even declare that join?

**Comment by igalklebanov** [comment]
You can't. At the very least, swap lines between `.selectAll` and first `leftJoin`.

**Comment by Firebrand** [comment]
@igalklebanov  Oh.... wow. I didn't even know you could do that. I thought the query construction had to be done in order, like a raw SQL query would be. That worked. Thanks, man... ur kind of the best.
