### ISSUE TITLE
[Question/BUG] CASE expression return type and ANY() Postgres operator

### ISSUE THREAD

**Issue by ropbastos** [kysely-org/kysely#561]
Hi guys, first, let me thank you for the awesome library! It's truly amazing.

Now, for my two questions: 

1. I'd like to know if there is support for checking if a certain string is contained in an array, using the " string = ANY(array_column)" method in Postgres.

2. Is it a bug that in the query below "read" is typed as boolean but when printed to the console it reads " 'true' " (a string)?

The query:
```ts
let query = this.db
            .selectFrom('notifications')
            .leftJoin('readReceipts', 'notifications.id', 'readReceipts.notificationId')
            .select((eb) => [
                'id',
                'oneSignalId',
                'heading',
                'body',
                'data',
                'notifications.createdAt',
                'type',
                eb.case('notificationId').when(null).then(false).else(true).end().as('read'),
            ])
            .where(sql`${username}`, '=', sql`ANY(destination_usernames)`)

if (lastId) {
    query = query.where('id', '<', lastId)
}
if (take) {
    query = query.limit(take)
}

const notifications = await query.orderBy('id', 'desc').execute()

console.log(notifications[0])

return notifications
```

A playground with it and the DB types (mostly): [Playground Link](https://kyse.link/?p=b&i=haFkqHBvc3RncmVzoXamMC4yNS4woXPaBNFpbXBvcnQgeyBHZW5lcmF0ZWQsIENvbHVtblR5cGUgfSBmcm9tICdreXNlbHknCgpleHBvcnQgdHlwZSBUaW1lc3RhbXAgPSBDb2x1bW5UeXBlPERhdGUsIERhdGUgfCBzdHJpbmcsIERhdGUgfCBzdHJpbmc-CgpkZWNsYXJlIGdsb2JhbCB7CiAgaW50ZXJmYWNlIERCIHsKICAgIGFkdmlzb3JOb3RpZmljYXRpb25QcmVmZXJlbmNlczogQWR2aXNvck5vdGlmaWNhdGlvblByZWZlcmVuY2VzCiAgICBkZWZhdWx0Tm90aWZpY2F0aW9uUHJlZmVyZW5jZXM6IERlZmF1bHROb3RpZmljYXRpb25QcmVmZXJlbmNlcwogICAgbm90aWZpY2F0aW9uczogTm90aWZpY2F0aW9ucwogICAgcmVhZFJlY2VpcHRzOiBSZWFkUmVjZWlwdHMKICB9CgogIGludGVyZmFjZSBBZHZpc29yTm90aWZpY2F0aW9uUHJlZmVyZW5jZXMgewogICAgdXNlcm5hbWU6IHN0cmluZwogICAgbm90aWZpY2F0aW9uVHlwZTogJ2FwcG9pbnRtZW50JyB8ICdiaXJ0aGRheScgfCAnbnBzJyB8ICd0ZWQnCiAgICBlbmFibGVkOiBib29sZWFuCiAgICBleHRyYVBhcmFtZXRlcnM6IFJlY29yZDxzdHJpbmcsIHN0cmluZz4gfCBudWxsCn0KCmludGVyZmFjZSBEZWZhdWx0Tm90aWZpY2F0aW9uUHJlZmVyZW5jZXMgewogICAgbm90aWZpY2F0aW9uVHlwZTogJ2FwcG9pbnRtZW50JyB8ICdiaXJ0aGRheScgfCAnbnBzJyB8ICd0ZWQnCiAgICBlbmFibGVkOiBHZW5lcmF0ZWQ8Ym9vbGVhbj4KICAgIGV4dHJhUGFyYW1ldGVyczogUmVjb3JkPHN0cmluZywgc3RyaW5nPiB8IG51bGwKfQoKaW50ZXJmYWNlIE5vdGlmaWNhdGlvbnMgewogICAgb25lU2lnbmFsSWQ6IHN0cmluZyB8IG51bGwKICAgIGNyZWF0ZWRBdDogR2VuZXJhdGVkPFRpbWVzdGFtcD4KICAgIHR5cGU6ICdhcHBvaW50bWVudCcgfCAnYmlydGhkYXknIHwgJ25wcycgfCAndGVkJwogICAgZGF0YTogUmVjb3JkPHN0cmluZywgc3RyaW5nPgogICAgYm9keTogc3RyaW5nCiAgICBoZWFkaW5nOiBzdHJpbmcgfCBudWxsCiAgICBpZDogR2VuZXJhdGVkPHN0cmluZz4KICAgIHNlbmRpbmdFcnJvcjogc3RyaW5nIHwgbnVsbAogICAgZGVzdGluYXRpb25Vc2VybmFtZXM6IHN0cmluZ1tdCiAgICBwdXNoUGF5bG9hZDogUmVjb3JkPHN0cmluZywgc3RyaW5nPiB8IG51bGwKfQoKaW50ZXJmYWNlIFJlYWRSZWNlaXB0cyB7CiAgICBub3RpZmljYXRpb25JZDogc3RyaW5nCiAgICByZWFkQnk6IHN0cmluZwogICAgY3JlYXRlZEF0OiBHZW5lcmF0ZWQ8VGltZXN0YW1wPgp9Cn2hcdoDOWltcG9ydCB7IHNxbCB9IGZyb20gImt5c2VseSIKCmxldCBsYXN0SWQgPSAiYXNkYXNkc2FkIgpsZXQgdGFrZSA9IDUKbGV0IHVzZXJuYW1lID0gInNvbWVfdXNlciIKCmxldCBxdWVyeSA9IGt5c2VseQogICAgICAgICAgICAuc2VsZWN0RnJvbSgnbm90aWZpY2F0aW9ucycpCiAgICAgICAgICAgIC5sZWZ0Sm9pbigncmVhZFJlY2VpcHRzJywgJ25vdGlmaWNhdGlvbnMuaWQnLCAncmVhZFJlY2VpcHRzLm5vdGlmaWNhdGlvbklkJykKICAgICAgICAgICAgLnNlbGVjdCgoZWIpID0-IFsKICAgICAgICAgICAgICAgICdpZCcsCiAgICAgICAgICAgICAgICAnb25lU2lnbmFsSWQnLAogICAgICAgICAgICAgICAgJ2hlYWRpbmcnLAogICAgICAgICAgICAgICAgJ2JvZHknLAogICAgICAgICAgICAgICAgJ2RhdGEnLAogICAgICAgICAgICAgICAgJ25vdGlmaWNhdGlvbnMuY3JlYXRlZEF0JywKICAgICAgICAgICAgICAgICd0eXBlJywKICAgICAgICAgICAgICAgIGViLmNhc2UoJ25vdGlmaWNhdGlvbklkJykud2hlbihudWxsKS50aGVuKGZhbHNlKS5lbHNlKHRydWUpLmVuZCgpLmFzKCdyZWFkJyksCiAgICAgICAgICAgIF0pCiAgICAgICAgICAgIC53aGVyZShzcWxgJHt1c2VybmFtZX1gLCAnPScsIHNxbGBBTlkoZGVzdGluYXRpb25fdXNlcm5hbWVzKWApCgppZiAobGFzdElkKSB7CiAgICBxdWVyeSA9IHF1ZXJ5LndoZXJlKCdpZCcsICc8JywgbGFzdElkKQp9CmlmICh0YWtlKSB7CiAgICBxdWVyeSA9IHF1ZXJ5LmxpbWl0KHRha2UpCn0KCmNvbnN0IG5vdGlmaWNhdGlvbnMgPSBhd2FpdCBxdWVyeS5vcmRlckJ5KCdpZCcsICdkZXNjJykuZXhlY3V0ZSgpO6Fjww==)

Thanks again.

**Comment by igalklebanov** [comment]
Hey 👋 

Thanks for the playground link! 👏 

1. There is no built-in support for `= any`.
2. Seems like a bug. Try using 0 and 1 for now, or sql template tag to control the return type.

Can you please submit an issue for each so we could track them?

**Comment by koskimas** [comment]
The behavior in 2 is indeed weird, but it will be very difficult to fix. The issue is that parameters don't contain any type information. The relevant part of the generated query is

```sql
when null then $1 else $2
```

The only way to fix this (while still using parameters) is to use casts

```sql
when null then cast($1 as boolean) else cast($2 as boolean)
```

and unfortunately we don't have enough information available in kysely to do that reliably.

For now you can use value literals

```ts
eb.case('notificationId').when(null).then(sql.lit(false)).else(sql.lit(true)).end().as('read'),
```

**Comment by ropbastos** [comment]
Thanks @koskimas for the heads-up with using eb.cmpr() (and now eb directly), the code is much better.

@igalklebanov Thanks for the speedy reply, I've created the separate issues as you requested:
https://github.com/kysely-org/kysely/issues/593
https://github.com/kysely-org/kysely/issues/592

Sorry for taking that long, been really busy with school and work.

I'm closing this issue now since the subject matter is better tracked in the two new separate ones :).
