### ISSUE TITLE
[Question] How to use reusable expression helpers with aliased tables

### ISSUE THREAD

**Issue by pylebecq** [kysely-org/kysely#569]
Hello 👋 

I followed the documentation [here](https://kysely.dev/docs/recipes/expressions#creating-reusable-helpers) to create some reusable helpers.

Let's supposed I have these types to represent my database:

```typescript
export interface Employees {
  id: Generated<string>;
  name: string | null;
  workspaceId: string;
}

export interface DB {
  employees: Employees
}
```

Following the documentation, I created my reusable helper like this:

```typescript
export function memberOfWorkspace(workspaceId: string) {
  return ({ cmpr }: ExpressionBuilder<DB, 'employees'>) =>
    cmpr('employees.workspaceId', '=', workspaceId);
}
```

It works fine when using the following query:

```typescript
    await db
      .selectFrom('employees')
      .where(memberOfWorkspace('0327f1a4-8817-4288-befb-dea77f355d78'))
      .execute();
```

However, if I use an alias, it does not work:

```typescript
    await db
      .selectFrom('employees as e')
      .where(memberOfWorkspace('0327f1a4-8817-4288-befb-dea77f355d78'))
      .execute();
```

This code creates a type error.

Do you know if there is a way to make these kind of reusable helpers to work with aliases tables? I have a very complex query on employees and at some point I would like to reuse this helper with an aliased table. I suppose I would need to give the alias to use as a parameter to the function, however I'm not smart enough to properly type my helper function and this alias parameter to make it work. 😅 

Here is a playground link if that helps: https://kyse.link/?p=b&i=haFkqHBvc3RncmVzoXamMC4yNS4woXPaASppbXBvcnQgeyBHZW5lcmF0ZWQsIENvbHVtblR5cGUgfSBmcm9tICdreXNlbHknCgpleHBvcnQgdHlwZSBUaW1lc3RhbXAgPSBDb2x1bW5UeXBlPERhdGUsIERhdGUgfCBzdHJpbmcsIERhdGUgfCBzdHJpbmc-CgpkZWNsYXJlIGdsb2JhbCB7CiAgaW50ZXJmYWNlIERCIHsKICAgIGVtcGxveWVlczogRW1wbG95ZWVzCiAgfQoKICBleHBvcnQgaW50ZXJmYWNlIEVtcGxveWVlcyB7CiAgICBpZDogR2VuZXJhdGVkPHN0cmluZz47CiAgICBuYW1lOiBzdHJpbmcgfCBudWxsOwogICAgd29ya3NwYWNlSWQ6IHN0cmluZzsKICB9Cn0KoXHaAaJpbXBvcnQgeyBzcWwsIEV4cHJlc3Npb25CdWlsZGVyIH0gZnJvbSAia3lzZWx5IgoKZnVuY3Rpb24gbWVtYmVyT2ZXb3Jrc3BhY2Uod29ya3NwYWNlSWQ6IHN0cmluZykgewogIHJldHVybiAoeyBjbXByIH06IEV4cHJlc3Npb25CdWlsZGVyPERCLCAnZW1wbG95ZWVzJz4pID0-CiAgICBjbXByKCdlbXBsb3llZXMud29ya3NwYWNlSWQnLCAnPScsIHdvcmtzcGFjZUlkKTsKfQoKbGV0IHF1ZXJ5ID0ga3lzZWx5CiAgICAgICAgICAgIC5zZWxlY3RGcm9tKCdlbXBsb3llZXMgYXMgZScpCiAgICAgICAgICAgIC5zZWxlY3RBbGwoKQogICAgICAgICAgICAud2hlcmUobWVtYmVyT2ZXb3Jrc3BhY2UoJzdkNGI3YWI2LWNkODctNGI0OS04NzNiLWYxZjI2MTRlZTA5NCcpKQoKY29uc3QgcmVzdWx0MiA9IGF3YWl0IHF1ZXJ5LmV4ZWN1dGUoKTsKoWPD

Any help would be much appreciated. Thanks.

**Comment by koskimas** [comment]
I don't think it's possible to create that kind of a helper in a type-safe way. You can always make it less type-safe though https://kyse.link/?p=s&i=3Vx8YLvLrhb2sF84h3yR

**Comment by pylebecq** [comment]
Thank you for your quick answer. 👍
