### ISSUE TITLE
What's the best way of doing conditional joins?

### ISSUE THREAD

**Issue by nicholasgriffintn** [kysely-org/kysely#575]
Hey,

I've found the docs on [relations](https://kysely.dev/docs/recipes/relations) that suggest to do joins like this:

```ts
const persons = await db
  .selectFrom('person')
  .selectAll('person')
  .select((eb) => [
    withPets(eb),
    withMom(eb)
  ])
  .execute()
```

I'm wondering, what would be the best way to do the joins conditionally?

Basically, I only want to join X if the matching param is provided. Sorry if that's super simple and I've missed it in the docs somewhere :)

**Comment by koskimas** [comment]
Those don't actually create joins, but subqueries. But I'm guessing by joins, you mean fetching related items as nested objects/lists? Probably the easiest way to do that conditionally is to use the `$if` method. https://kyse.link/?p=s&i=plFcR0KGGRDlhtcHpOjt

**Comment by koskimas** [comment]
There's a recipe on the subject https://kysely.dev/docs/recipes/conditional-selects.

**Comment by nicholasgriffintn** [comment]
Ahhh I see! That makes sense thanks :)
