### ISSUE TITLE
'RECURSIVE' gets lost when 'withRecursive' is used after a 'with'

### ISSUE THREAD

**Issue by nadanke** [kysely-org/kysely#579]
Hey,

please look at: [playground link](https://kyse.link/?p=b&i=haFkqHBvc3RncmVzoXamMC4yNi4woXPZymltcG9ydCB7IEdlbmVyYXRlZCB9IGZyb20gJ2t5c2VseScKCmRlY2xhcmUgZ2xvYmFsIHsKICBpbnRlcmZhY2UgREIgewogICAgdXNlcjogVXNlclRhYmxlCiAgfQoKICBpbnRlcmZhY2UgVXNlclRhYmxlIHsKICAgIGlkOiBHZW5lcmF0ZWQ8c3RyaW5nPgogICAgZmlyc3RfbmFtZTogc3RyaW5nIHwgbnVsbAogICAgbGFzdF9uYW1lOiBzdHJpbmcKICB9Cn2hcdoBQ2NvbnN0IHJvd3MgPSBhd2FpdCBreXNlbHkKICAud2l0aCgnVGVzdCcsIChxYikgPT4gcWIuc2VsZWN0RnJvbSgndXNlcicpKQogIC53aXRoUmVjdXJzaXZlKCdTaG91bEJlUmVjdXJzaXZlQnV0SXNudCcsIChxYikgPT4KCQkJcWIKCQkJCS5zZWxlY3RGcm9tKCd1c2VyJykKICAgICAgICAuc2VsZWN0KCdpZCcpCgkJCQkudW5pb25BbGwoCgkJCQkJcWIKCQkJCQkJLnNlbGVjdEZyb20oJ3VzZXInKQogICAgICAgICAgICAuc2VsZWN0KCdpZCcpCgkJCQkpLAoJCSkuc2VsZWN0RnJvbSgnU2hvdWxCZVJlY3Vyc2l2ZUJ1dElzbnQnKS5zZWxlY3RBbGwoKS5leGVjdXRlKCkKoWPD)

In the compiled query, the CTE "ShoulBeRecursiveButIsnt" should have the RECURSIVE keyword, but doesn't. If you swap the CTE declarations, the keyword is correctly there.

My guess is the problem is somewhere here: https://github.com/kysely-org/kysely/blob/d9e06ab6568de976af675df4794a49e73fe648aa/src/query-creator.ts#L483

but right now I'm unable to check it out and try it for myself.

**Comment by koskimas** [comment]
The whole `WITH` statement is either recursive or not. That's not a per CTE option. Kysely API is a bit suboptimal for this since currently the first CTE determines the recursiveness of the whole `WITH` statement. I don't know how we could improve this without complicating the API.

**Comment by nadanke** [comment]
Ohh, I see, thank you!
