### ISSUE TITLE
[BUG] Wrong type for CASE expression result

### ISSUE THREAD

**Issue by ropbastos** [kysely-org/kysely#592]
As discussed in https://github.com/kysely-org/kysely/issues/561 I'm creating this issue so that this bug may be tracked individually.

In the query below, "read" is typed as boolean, but it's actually returned as a string (I'm using Postgres + pg). It seems that the issue is that "true" and "false" are treated as parameters, which don't contain any type information - as [pointed out](https://github.com/kysely-org/kysely/issues/561#issuecomment-1620013826) by @koskimas, who also brought up a possible solution: always writing booleans, numbers and nulls as literals.

The query:
```ts
let query = this.db
            .selectFrom('notifications')
            .leftJoin('readReceipts', 'notifications.id', 'readReceipts.notificationId')
            .select((eb) => [
                'id',
                'oneSignalId',
                'heading',
                'body',
                'data',
                'notifications.createdAt',
                'type',
                eb.case('notificationId').when(null).then(false).else(true).end().as('read'),
            ])
            .where(sql`${username}`, '=', sql`ANY(destination_usernames)`)

if (lastId) {
    query = query.where('id', '<', lastId)
}
if (take) {
    query = query.limit(take)
}

const notifications = await query.orderBy('id', 'desc').execute()

console.log(notifications[0])

return notifications
```

A playground with it and the DB types (mostly): [Playground Link](https://kyse.link/?p=b&i=haFkqHBvc3RncmVzoXamMC4yNS4woXPaBNFpbXBvcnQgeyBHZW5lcmF0ZWQsIENvbHVtblR5cGUgfSBmcm9tICdreXNlbHknCgpleHBvcnQgdHlwZSBUaW1lc3RhbXAgPSBDb2x1bW5UeXBlPERhdGUsIERhdGUgfCBzdHJpbmcsIERhdGUgfCBzdHJpbmc-CgpkZWNsYXJlIGdsb2JhbCB7CiAgaW50ZXJmYWNlIERCIHsKICAgIGFkdmlzb3JOb3RpZmljYXRpb25QcmVmZXJlbmNlczogQWR2aXNvck5vdGlmaWNhdGlvblByZWZlcmVuY2VzCiAgICBkZWZhdWx0Tm90aWZpY2F0aW9uUHJlZmVyZW5jZXM6IERlZmF1bHROb3RpZmljYXRpb25QcmVmZXJlbmNlcwogICAgbm90aWZpY2F0aW9uczogTm90aWZpY2F0aW9ucwogICAgcmVhZFJlY2VpcHRzOiBSZWFkUmVjZWlwdHMKICB9CgogIGludGVyZmFjZSBBZHZpc29yTm90aWZpY2F0aW9uUHJlZmVyZW5jZXMgewogICAgdXNlcm5hbWU6IHN0cmluZwogICAgbm90aWZpY2F0aW9uVHlwZTogJ2FwcG9pbnRtZW50JyB8ICdiaXJ0aGRheScgfCAnbnBzJyB8ICd0ZWQnCiAgICBlbmFibGVkOiBib29sZWFuCiAgICBleHRyYVBhcmFtZXRlcnM6IFJlY29yZDxzdHJpbmcsIHN0cmluZz4gfCBudWxsCn0KCmludGVyZmFjZSBEZWZhdWx0Tm90aWZpY2F0aW9uUHJlZmVyZW5jZXMgewogICAgbm90aWZpY2F0aW9uVHlwZTogJ2FwcG9pbnRtZW50JyB8ICdiaXJ0aGRheScgfCAnbnBzJyB8ICd0ZWQnCiAgICBlbmFibGVkOiBHZW5lcmF0ZWQ8Ym9vbGVhbj4KICAgIGV4dHJhUGFyYW1ldGVyczogUmVjb3JkPHN0cmluZywgc3RyaW5nPiB8IG51bGwKfQoKaW50ZXJmYWNlIE5vdGlmaWNhdGlvbnMgewogICAgb25lU2lnbmFsSWQ6IHN0cmluZyB8IG51bGwKICAgIGNyZWF0ZWRBdDogR2VuZXJhdGVkPFRpbWVzdGFtcD4KICAgIHR5cGU6ICdhcHBvaW50bWVudCcgfCAnYmlydGhkYXknIHwgJ25wcycgfCAndGVkJwogICAgZGF0YTogUmVjb3JkPHN0cmluZywgc3RyaW5nPgogICAgYm9keTogc3RyaW5nCiAgICBoZWFkaW5nOiBzdHJpbmcgfCBudWxsCiAgICBpZDogR2VuZXJhdGVkPHN0cmluZz4KICAgIHNlbmRpbmdFcnJvcjogc3RyaW5nIHwgbnVsbAogICAgZGVzdGluYXRpb25Vc2VybmFtZXM6IHN0cmluZ1tdCiAgICBwdXNoUGF5bG9hZDogUmVjb3JkPHN0cmluZywgc3RyaW5nPiB8IG51bGwKfQoKaW50ZXJmYWNlIFJlYWRSZWNlaXB0cyB7CiAgICBub3RpZmljYXRpb25JZDogc3RyaW5nCiAgICByZWFkQnk6IHN0cmluZwogICAgY3JlYXRlZEF0OiBHZW5lcmF0ZWQ8VGltZXN0YW1wPgp9Cn2hcdoDOWltcG9ydCB7IHNxbCB9IGZyb20gImt5c2VseSIKCmxldCBsYXN0SWQgPSAiYXNkYXNkc2FkIgpsZXQgdGFrZSA9IDUKbGV0IHVzZXJuYW1lID0gInNvbWVfdXNlciIKCmxldCBxdWVyeSA9IGt5c2VseQogICAgICAgICAgICAuc2VsZWN0RnJvbSgnbm90aWZpY2F0aW9ucycpCiAgICAgICAgICAgIC5sZWZ0Sm9pbigncmVhZFJlY2VpcHRzJywgJ25vdGlmaWNhdGlvbnMuaWQnLCAncmVhZFJlY2VpcHRzLm5vdGlmaWNhdGlvbklkJykKICAgICAgICAgICAgLnNlbGVjdCgoZWIpID0-IFsKICAgICAgICAgICAgICAgICdpZCcsCiAgICAgICAgICAgICAgICAnb25lU2lnbmFsSWQnLAogICAgICAgICAgICAgICAgJ2hlYWRpbmcnLAogICAgICAgICAgICAgICAgJ2JvZHknLAogICAgICAgICAgICAgICAgJ2RhdGEnLAogICAgICAgICAgICAgICAgJ25vdGlmaWNhdGlvbnMuY3JlYXRlZEF0JywKICAgICAgICAgICAgICAgICd0eXBlJywKICAgICAgICAgICAgICAgIGViLmNhc2UoJ25vdGlmaWNhdGlvbklkJykud2hlbihudWxsKS50aGVuKGZhbHNlKS5lbHNlKHRydWUpLmVuZCgpLmFzKCdyZWFkJyksCiAgICAgICAgICAgIF0pCiAgICAgICAgICAgIC53aGVyZShzcWxgJHt1c2VybmFtZX1gLCAnPScsIHNxbGBBTlkoZGVzdGluYXRpb25fdXNlcm5hbWVzKWApCgppZiAobGFzdElkKSB7CiAgICBxdWVyeSA9IHF1ZXJ5LndoZXJlKCdpZCcsICc8JywgbGFzdElkKQp9CmlmICh0YWtlKSB7CiAgICBxdWVyeSA9IHF1ZXJ5LmxpbWl0KHRha2UpCn0KCmNvbnN0IG5vdGlmaWNhdGlvbnMgPSBhd2FpdCBxdWVyeS5vcmRlckJ5KCdpZCcsICdkZXNjJykuZXhlY3V0ZSgpO6Fjww==)

**Comment by koskimas** [comment]
>  who also brought up a possible solution: always writing booleans, numbers and nulls as literals.

I don't know if that's actually a good idea. It'd make the SQL very long in some cases. For example a large `where in (<10000 numbers here>)` query would be suuper long. We might hit some query length limits.

I think for now, we should fix this by making `then` use literal values for numbers, booleans and nulls.

**Comment by koskimas** [comment]
@igalklebanov We could add a `lit` method to the expression builder as you suggested BUT only allow numbers, booleans and nulls. If a string or something else is passed in, we'd show a type error informing the user that the operation is dangerous and they should use `sql.lit` instead.

I think we should still make `then(true)`, `then(1.23154)` and `then(null)` use literals by default. But the expression builder addition could be useful elsewhere? Thoughts?
