### ISSUE TITLE
Postgres jsonB Columns inserts and updates

### ISSUE THREAD

**Issue by clarknova** [kysely-org/kysely#594]
Hello I introspected my postgres db and got
```
export interface AppointmentResources {
[...]
  data: Generated<Json>;
[...]
}

export type Json = ColumnType<JsonValue, string, string>;
```
and got this type for my jsonb fields.
When i update or insert i have to provide the new value as stringified object which is annoying.
I discovered i can just pass in the original object and even make it typesave biy changing the string types to JSONValue in the ColumnType.

Am i missing something or can i just pass in the object ?!?

**Comment by koskimas** [comment]
| Am i missing something or can i just pass in the object ?!?

Didn't you just say you discovered that you can? What are you asking exactly?

If it works, it works. Some db drivers allow it, some don't. IIRC pg accepts objects, but not arrays.

**Comment by clarknova** [comment]
Yeah, it is great that is works. I was only confused because the introspection of the postgres db put the string as type for updates and inserts there. I just wanted to be sure that this doesn't cause trouble later on.
