### ISSUE TITLE
when i insert empty list i get an error 

### ISSUE THREAD

**Issue by JIM-GLITCH** [kysely-org/kysely#596]
```ts
import { pg } from "./connectDB";
pg.insertInto("data.advice")
        .values([])
        .execute()
```
when i insert empty list i get an error 
![image](https://github.com/kysely-org/kysely/assets/58733364/71693f6d-ac0c-4d8f-8f75-a3bdde629c66)

**Comment by JIM-GLITCH** [comment]
it generates invalid sql sentence

**Comment by wirekang** [comment]
What you are requesting to database is "insert nothing" via "INSERT" keyword. Check the length of input to prevent kysely from generating invalid SQL.

```ts
if (input.length === 0){
  // return or throw exception
}
pg.insertInto().values(input)

```

**Comment by koskimas** [comment]
Yep, everything works as expected here.
