### ISSUE TITLE
Insertable - All keys incorrectly optional

### ISSUE THREAD

**Issue by codebykenny** [kysely-org/kysely#607]
When using `Insertable`, all of the keys on the insertable type are optional. In the example below `name` & `weight` should be required and not optional.

This is using `kysely@0.26.1`

<img width="446" alt="Kenny- 2023-07-21 at 07 45 09" src="https://github.com/kysely-org/kysely/assets/6720728/c5509131-caa0-488c-881c-67d84978d5d7">
---

Test Code:

```ts
import {
	ColumnType,
	Generated,
	Insertable,
	Selectable,
	Updateable,
} from "kysely";

export interface PetTable {
	id: Generated<number>;
	name: string;
	weight: number;
}

export type LocalPet = Selectable<PetTable>;
export type PetUpdate = Updateable<PetTable>;
export type NewPet = Insertable<PetTable>;

```

**Comment by igalklebanov** [comment]
Hey 👋 

Can you share your `tsconfig.json`?

**Comment by codebykenny** [comment]
Sure @igalklebanov 

`tsconfig.json`

```json
{
	"compilerOptions": {
		"target": "es2015",
		"lib": ["ES2021.String", "dom", "dom.iterable"],
		"module": "commonjs",
		"outDir": "./build",
		"inlineSourceMap": true,
		"noEmitOnError": true,
		"esModuleInterop": true,
		"forceConsistentCasingInFileNames": true,
		"strict": false,
		"noFallthroughCasesInSwitch": true,
		"skipLibCheck": true,
		"moduleResolution": "node"
	},
	"include": ["src/**/*"],
	"exclude": ["node_modules", "build"]
}
```

**Comment by igalklebanov** [comment]
Kysely, and most other modern TypeScript libraries, require `strict: true` to infer types properly.

**Comment by codebykenny** [comment]
Thank you @igalklebanov works correctly with `strict: true`
