### ISSUE TITLE
[Feature]: Support CapacitorJS SQLite 

### ISSUE THREAD

**Issue by scr2em** [kysely-org/kysely#609]
is it possible to support https://github.com/capacitor-community/sqlite ?

**Comment by igalklebanov** [comment]
Hey 👋 

It is possible, just not part of the core library as we aim to maintain only the household names here. A community dialect would be awesome, and we'll gladly list it in docs & https://github.com/kysely-org/awesome-kysely.

There's a discord thread from ~3 days ago discussing this:
https://discord.com/channels/890118421587578920/1131318271916916826/1131318271916916826

> You can use kysely as a query builder only, without any driver. See this for more info https://kysely.dev/docs/recipes/splitting-build-compile-and-execute-code

> Alternatively, you could implement a custom dialect, re-using most of the pieces from the built-in SqliteDialect (adapter, introspector, query compiler) and writing your own driver that communicates with capacitor's driver
This entire repository is dedicated to various flavors of SQLite dialects you could get inspiration from https://github.com/subframe7536/kysely-sqlite-tools/tree/master/packages 
> You could also contribute to that project, or submit an issue requesting such dialect
