### ISSUE TITLE
Convert the result type of the `count` function

### ISSUE THREAD

**Issue by inktrl** [kysely-org/kysely#610]
### How can I convert a type with a library without using SQL expressions?

```ts
const result1 = await db
    .selectFrom('users')
    .select(() => sql`COUNT("users".id)::integer`.as('count'))
    .execute();

const result2 = await db
    .selectFrom('users')
    .select((eb) => eb.fn.count('id').as('count'))
    .execute();

console.log('Result 1:', result1);
console.log('Result 2:', result2);
```

```bash
Result 1: [ { count: 5 } ]
Result 2: [ { count: '5' } ]
```

**Comment by koskimas** [comment]
You can usually configure data type transformations through the db driver. Which dialect are you using?

**Comment by inktrl** [comment]
> You can usually configure data type transformations through the db driver. Which dialect are you using? If you're using the built-in `PostgresDialect` see [this](https://github.com/brianc/node-pg-types).

Thank you, I've added this and it worked, it's a shame that there's currently no way to convert types using the CAST operator through Kysely.

```diff
const pool = new Pool({ connectionString });

+ pg.types.setTypeParser(20, (val) => (val === null ? null : parseInt(val, 10))); 

export const db = new Kysely<Database>({
  dialect: new PostgresDialect({ pool }),
});
```

**Comment by koskimas** [comment]
We're thinking about adding a cast function to Kysely, but it's not that simple. There's no direct mapping between typescript types and DB datatypes. Each dialect has different defaults. If we added a cast function it'd need to take both, a type argument AND a data type. Something like this

```ts
.select(({ fn, cast }) => cast<number>(fn.count('id').as('count'), 'integer'))
```

which is not ideal.
