### ISSUE TITLE
Custom SQL query for migration

### ISSUE THREAD

**Issue by Trystan-SA** [kysely-org/kysely#613]
Maybe i'm missing something, but is it possible to execute raw SQL queries during a migration with `db: Kysely<any>` object ?

I'm trying to run `CREATE EXTENSION IF NOT EXISTS "uuid-ossp"` for Postgres. Since `db: Kysely` instance does not have `create()` method, I can't make this work. Any solutions for this ?

**Comment by igalklebanov** [comment]
Hey 👋 

Try

```ts
import { sql } from 'kysely'

await sql`create extension if not exists "uuid-ossp"`.execute(db)
```
