### ISSUE TITLE
Using `join` on same table CANNOT get right result

### ISSUE THREAD

**Issue by meathill** [kysely-org/kysely#618]
Hi, all, thanks for maintaining this wonderful library!

I were trying to use `join` on one table to get results at one requests, here is my code:

```ts
export interface CategoryTable {
  id: number;
  name: string;
  slug: string;
  parent: number;
  description: string;
  image: string;
  isHomepage: boolean;
}

await db.selectFrom('category')
    .leftJoin('category as parent', 'parent.id', 'category.parent')
    .selectAll()
    .where('category.id', '=', id)
    .executeTakeFirst();
```

but I can only get the parent record, without the record pointe by `id`.

I have read documents, I think I did write the right code.
And I tried the example on: https://kysely.dev/docs/examples/JOIN/simple-inner-join , 
copied the generated SQL into my DB client, it works well.

So I have to ask you here to help me on this. Thanks all. Wish you a good day!

**Comment by koskimas** [comment]
Are you expecting the `parent` to be provided as a nested object under a `parent` property? Kysely doesn't do that since that's not what the db returns. Kysely is just a query builder and it returns what the DB returns.

If you want nested objects, see [this recipe](https://kysely.dev/docs/recipes/relations)

**Comment by meathill** [comment]
@koskimas thanks for replying.

Actually I didn't expect the `parent` to be returned as a nested object, here is what I got:

```json
{
    "id": 1,
    "name": "Special",
    "slug": "special",
    "parent": "0",
    "image": null,
    "createdAt": "2023-07-16T14:19:54.098Z",
    "updatedAt": "2023-07-16T14:19:54.098Z",
    "deletedAt": null,
    "description": "",
    "isHomepage": false
}
```

And what I expect to get is like DB returns:

<img width="1187" alt="image" src="https://github.com/kysely-org/kysely/assets/437409/03402965-b7e5-47b4-b318-f9f1f727cb6a">

so I think in JSON object, it would be like:

```json
{
  "category.id": 3,
  "category.parent": 1
  ....
  "parent.id": 1
  ....
}
```

**Comment by koskimas** [comment]
The column names you see in that tool are the combination of table and column name. That's not what the db returns. Kysely doesn't touch the result at all. It simply returns what the db returns.
