### ISSUE TITLE
How to insert and update list column?

### ISSUE THREAD

**Issue by topperspal** [kysely-org/kysely#623]
Kysely 0.26.1
Environment - **Deno** - npm:kysely@0.26.1

```prisma
model Admin {
  id String @id,
  name String
  permissions String[]
  
  @@map("admins")
}
```

Simple CRUD works correctly, but I could not figure out how wo work with Array, especially inserting and updating, Please tell me how to insert a column type Array<string> using kysely.

I tried it using this -

```ts
db
    .updateTable("admins")
      .set({
        permissions: ["CREATE_USER"], 
      })
      .where("id", "=", id);
```

but this does not work

**Comment by igalklebanov** [comment]
Hey 👋 

This is not a proper way to submit an issue and suggests a total lack of effort and respect.

1. the lack of words and directness makes it sounds like "dumb maintainers, library broken, fix now!" - this library's maintainers don't owe you anything and are not working for you.

2. it lacks any context and details. what version are you using? what does your `DB` interface look like? what doesn't work exactly?

**Comment by TechnotronicOz** [comment]
> ```ts
> db
>     .updateTable("admins")
>       .set({
>         permissions: ["CREATE_USER"],
>       })
>       .where("id", "=", "id");
> ```
> 
> this does not work

Did you try https://kysely.dev/docs/examples/UPDATE/single-row?

```typescript
const result = await db
  .updateTable('admins')
  .set({
    permissions: 'CREATE_USER',
  })
  .where('id', '=', 'your-id')
  .executeTakeFirst();
```

**Comment by topperspal** [comment]
> > ```ts
> > db
> >     .updateTable("admins")
> >       .set({
> >         permissions: ["CREATE_USER"],
> >       })
> >       .where("id", "=", "id");
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > this does not work
> 
> Did you try https://kysely.dev/docs/examples/UPDATE/single-row?
> 
> ```ts
> const result = await db
>   .updateTable('admins')
>   .set({
>     permissions: 'CREATE_USER',
>   })
>   .where('id', '=', 'your-id')
>   .executeTakeFirst();
> ```
> 
> Or, is `permissions` a `jsonb` or `array` column?

permissions is an Array of string

**Comment by topperspal** [comment]
> ```ts
> db
>     .updateTable("admins")
>       .set({
>         permissions: ["CREATE_USER"], 
>       })
>       .where("id", "=", id);
> ```

It works if I type cast permissions array as **any**

```ts
 db
     .updateTable("admins")
       .set({
         permissions: ["CREATE_USER"] as any, 
       })
       .where("id", "=", id);
```
