### ISSUE TITLE
RuntimeDriver and PostgresDriver destroy

### ISSUE THREAD

**Issue by luixo** [kysely-org/kysely#626]
Hello,

While testing my app in Jest I encountered error signaling that Pool was not destroyed successfully.
Digging down, I found that the problem is that `RuntimeDriver` doesn't run `PostgresDriver`s destroy as expected.

My code looks something like this:
```ts
// database.ts
const pool = new Pool({ connectionString: '...' });
const dialect = new PostgresDialect({ pool });
const getDatabase = (meta?: Metadata) =>
  new Kysely({ dialect, log: meta && getLogger(meta) });

// test.spec.ts
it('test', () => {
  const database = getDatabase();
  await database.insertInto(...).execute();
  // ...
});

// test-environment.ts
export const teardown = () => {
  const database = getDatabase();
  await database.destroy();
}
```

The thing is I use only one Postgres pool instance but many Kysely instances (each of them have binded logger with query-specific metadata). Whenever `RuntimeDriver`s `destroy` [method](https://github.com/kysely-org/kysely/blob/master/src/driver/runtime-driver.ts#L88-L103) is called, it checks if current instance [was initialized](https://github.com/kysely-org/kysely/blob/master/src/driver/runtime-driver.ts#L32-L42) and the teardown's instance is not (though the test one was).

A possible solution for that would be to pass the responsibilty to decide whether `destroy` should be called to the wrapped driver of the `RuntimeDriver`.

**Comment by koskimas** [comment]
You shouldn't share a dialect instance with multiple Kysely instances.

**Comment by luixo** [comment]
> You shouldn't share a dialect/pool instance with multiple Kysely instances.

Is there an option to keep logging (or other options - say plugins) distinct while benefiting from having a pg pool?

> You can either create new dialect and pool for each Kysely instance or override the dialect driver's init and destroy methods.

Why can't I use a shared pool while creating dialect / Kysely instance on every run?

Can you give an example of how overriding dialect driver's init / destroy should help?
