### ISSUE TITLE
Sqlite helpers not being published

### ISSUE THREAD

**Issue by bromanko** [kysely-org/kysely#628]
The docs reference [JSON helpers for Sqlite](https://kysely.dev/docs/recipes/relations). I see the helper file also here in the repo. However, the [NPM package for 0.26.1](https://www.npmjs.com/package/kysely/v/0.26.1?activeTab=code) does not include this helper file.

**Comment by koskimas** [comment]
Yeah, kysely.dev currently reflects the master branch and not the latest release. We are working on that.

**Comment by jlarmstrongiv** [comment]
Released in `0.26.3` 🎉 feel free to close this issue
