### ISSUE TITLE
Inconsistent MySQL docs and types

### ISSUE THREAD

**Issue by pilcrowOnPaper** [kysely-org/kysely#629]
The [docs](https://kysely.dev/docs/getting-started?dialect=mysql#instantiation) states that `mysql2` should be used instead of `mysql2/promise`.

```ts
import { createPool } from 'mysql2' // do not use 'mysql2/promises'!
import { Kysely, MysqlDialect } from 'kysely'

const dialect = new MysqlDialect({
  pool: createPool({})
})
```

Actually trying it out though, TS errors that `pool` option expects the `/promise` version.

```ts
import { createPool } from 'mysql2/promise'
import { Kysely, MysqlDialect } from 'kysely'

const dialect = new MysqlDialect({
  pool: createPool({})
})
```

**Comment by koskimas** [comment]
Simply not true.

**Comment by pilcrowOnPaper** [comment]
Yeah sorry, looks like my types were busted or something. Not really sure had to re-install and restart like a few times.

**Comment by acrodrig** [comment]
I am getting a similar error:

```
TS2322 [ERROR]: Type 'Pool' is not assignable to type 'MysqlPool | (() => Promise<MysqlPool>)'.
  Type 'Pool' is not assignable to type 'MysqlPool'.
    Types of property 'getConnection' are incompatible.
      Type '(callback: (err: any, connection: PoolConnection) => any) => void' is not assignable to type '(callback: (error: unknown, connection: MysqlPoolConnection) => void) => void'.
        Types of parameters 'callback' and 'callback' are incompatible.
          Types of parameters 'connection' and 'connection' are incompatible.
            Property 'query' is missing in type 'PoolConnection' but required in type 'MysqlPoolConnection'.
    return new MysqlDialect({ pool: createPool(config) });
```

@pilcrowonpaper could you share what you did to fix it? Thanks!

**Comment by igalklebanov** [comment]
Can't repro in the [TypeScript playground](https://tsplay.dev/NaB9ym).

Can you provide a reproduction?

**Comment by acrodrig** [comment]
@igalklebanov thanks for responding. It seems to have resolved itself. Maybe wrong cache?

**Comment by magandrez** [comment]
> Simply not true.

@koskimas do you have any insight as to why such a problem might occur other than negating its existance?

**Comment by igalklebanov** [comment]
What problem? you're responding to a thread from 2023. 🤦
