### ISSUE TITLE
Support for mutually recursive CTEs

### ISSUE THREAD

**Issue by RobinClowers** [kysely-org/kysely#632]
Materialize supports recursive CTEs that reference each other, using [`WITH MUTUALLY RECURSIVE`](https://materialize.com/docs/sql/recursive-ctes/). Other than that, I believe they are just postgres compatible CTEs. What would it look like to support this in Kysely?

I'm not using the database driver part of Kysely, so I'm mostly interested in the query building end of it, though it would be awesome to have both.

**Comment by koskimas** [comment]
Currently we have a suboptimal API for recursive CTEs. Recursiveness is determined for the whole `WITH` statement, but our API allows you to "set" it per CTE (but actually only the first call matters).

The following wouldn't create a `WITH RECURSIVE` statement.

```ts
db.with('cte1', (qb) => ...)
  .withRecursive('cte2', (qb) => ...)
```

As you can see, we'd currently have the option to create a third method `withMutuallyRecursive`. Correct me if I'm wrong, but isn't the `MUTUALLY` keyword something Materialize specific and not supported by other databases?

Another option would be to refactor the CTE API into something like this:

```ts
db.with(wb => wb
    .mutually()
    .recursive()
    .cte('cte1', (qb) => ...)
    .cte('cte2', (eb) => ...)
  )
  .selectFrom(['cte1', 'cte2'])
  ...
```

With such an API, we could add a `mutually` method even if it's rarely used. @igalklebanov thoughts?

**Comment by igalklebanov** [comment]
@koskimas looks good for regular recursive. slightly less WYSIWYG - 1 ` with`, but worth it in this case. can't we handle this issue internally without an API change?

correct me if I'm wrong, but mutually recursive CTE means all expressions can reference all expressions - so this is not a good fit, TypeScript does not work backwards. We'd need to first describe all CTE names and their output types, and only after that, allow describing the queries, to make it type-safe.

**Comment by koskimas** [comment]
I'd guess it just means that later CTEs can use the previous ones. But isn't that always the case 🤔 @RobinClowers can you explain what mutually recursive means and how's that different from normal postgres recursive CTEs that can already reference each other?

**Comment by igalklebanov** [comment]
Found [this](https://materialize.com/blog/recursive-ctes-in-materialize/), might help with our confusion.

**Comment by RobinClowers** [comment]
Thanks for the prompt responses!

Sorry for the confusion, and yes, any CTE can reference any other CTE. 

Hypothetically, if I added the feature, would you accept it? I'm honestly not sure if my typescript chops are up to the task, but I'm curious if the concern is more about doing the work or more like bundle size / maintenance?

**Comment by koskimas** [comment]
> Hypothetically, if I added the feature, would you accept it? I'm honestly not sure if my typescript chops are up to the task, but I'm curious if the concern is more about doing the work or more like bundle size / maintenance?

I don't think it makes sense to add this to the code. It's a matter of bundle size, typescript performance and maintenance. We need to weigh each feature to its usefulness. This feature would only work on Materialize and we'd need to change the whole `with` API. Not worth it.

**Comment by igalklebanov** [comment]
@koskimas Maybe we could still help by removing obstacles from the creation of a 3rd party helper function?

Currently, the biggest blocker I see is not being able to inject raw SQL right after the `with` keyword - something like a `.modifyFront` on the new builder in the first `.with` argument would be great.

Something like this could be implemented:

```ts
import { Expression, Generated, Kysely, QueryCreator, sql } from "kysely";

interface DB {
  users: {
    id: Generated<string>;
    name: string;
  };
}

export type MutuallyRecursiveCommonTableExpression<DB, CN extends keyof DB> = (
  creator: QueryCreator<DB>
) => Expression<DB[CN]>;

function withMutuallyRecursive<W, DB>(
  db: Kysely<DB>,
  ctes: { [K in keyof W]: MutuallyRecursiveCommonTableExpression<DB & W, K> }
): Kysely<DB & W> {
  const [[firstCTEName, firstCTEBody], ...otherCTEs] = Object.entries(ctes);

  const base = db.withRecursive(
    (wb) => wb(firstCTEName).modifyFront(sql`mutually`),
    firstCTEBody
  );

  return otherCTEs.reduce(
    (qb, [name, body]) => qb.with(name, body as any),
    base
  ) as any;
}

// @ts-ignore
const db = new Kysely<DB>({});

const result = await withMutuallyRecursive<
//      ^? const result: { name: string; b: number; id: string; a: string; }[]
  {
    cte1: { a: string };
    cte2: { b: number };
  },
  DB
>(db, {
  cte1: (qb) => qb.selectFrom("users").innerJoin('cte2', 'cte2.b', 'users.name').select("name as a"),
  cte2: (qb) => qb.selectFrom("users").innerJoin('cte1', 'cte1.a', 'users.name').select(sql<number>`1 + 1`.as("b")),
})
  .selectFrom("cte1")
  .innerJoin("cte2", "cte1.a", "cte2.b")
  .innerJoin('users', 'cte1.a', 'users.name')
  .selectAll()
  .execute();

```
https://tsplay.dev/wQJgZN

The DX could be worse for sure, but it's type-safe in `ctes` argument and in the downstream query.

**Comment by RobinClowers** [comment]
@igalklebanov that would still be nicer than having to define the whole thing as a template string, which is what we do right now. Though I'm not sure it would work in all cases, since I would still be limited to referencing CTEs defined before the current one, right?

**Comment by igalklebanov** [comment]
@RobinClowers 

> Though I'm not sure it would work in all cases, since I would still be limited to referencing CTEs defined before the current one, right?

iirc the implementation I provided works both ways. `cte1` references `cte2` that's only defined after it.
