### ISSUE TITLE
Is there a way to create a CTE with values in kysely/postgres?

### ISSUE THREAD

**Issue by nestarz** [kysely-org/kysely#638]
Hello ! Do you know how I can do the following using kysely ? and how to make it typed.

```
WITH cte1 (temp_var1, temp_var2) AS (
  VALUES
   (1,4),
   (2,5),
   (3,6)
)
SELECT 
    *
FROM cte1
```

**Comment by alnorris** [comment]
It's in the API docs. https://kysely-org.github.io/kysely-apidoc/classes/Kysely.html#with

**Comment by nestarz** [comment]
> It's in the API docs. https://kysely-org.github.io/kysely-apidoc/classes/Kysely.html#with

I can't find what I'm asking @alnorris, can you help me translate my SQL to Kysely if it's in the API docs ?

**Comment by koskimas** [comment]
Currently there's no built-in way to create a `values` expression, but you can always use raw sql.

https://kyse.link/?p=s&i=pedgALnEFSkPTKajsyWt
