### ISSUE TITLE
Typechecking doesn't work when insert value is instantiated outside the values function

### ISSUE THREAD

**Issue by maktouch** [kysely-org/kysely#641]
In this playground link: https://kysely.dev/docs/examples/INSERT/single-row

```ts
const result = await db
  .insertInto('person')
  .values({
    first_name: 'Jennifer',
    last_name: 'Aniston',
    age: 40,
    hello: 'world'
  })
  .executeTakeFirst()

console.log(result.insertId)
```

This gets correctly typechecked. Column `hello` doesn't exist and there's squiggly lines everywhere. 
This, however, doesn't work. 

```ts
const obj = {
    first_name: 'Jennifer',
    last_name: 'Aniston',
    age: 40,
    hello: 'world'
  }
  
const result = await db
  .insertInto('person')
  .values(obj)
  .executeTakeFirst()

console.log(result.insertId)
```

Same thing for updates. 

This is quite a footgun!

**Comment by igalklebanov** [comment]
Hey 👋 

This is a general TypeScript problem. I'll try to find the relevant issue/s later.
You can find the same shenanigans in anything that involves objects, see zod's pick/omit methods.

Lemme give you another weird behavior:

```ts
const values = {
    first_name: 'Jennifer',
    last_name: 'Aniston',
    age: 40,
    hello: 'world'
}

const result = await db
  .insertInto('person')
  .values([values, {
    first_name: 'Jennifer',
    last_name: 'Aniston',
    age: 40,
    hello: 'world'
  }])
  .executeTakeFirst()
```

no type errors.

```ts
const values = {
    first_name: 'Jennifer',
    last_name: 'Aniston',
    age: 40,
    hello: 'world'
  }

const result = await db
  .insertInto('person')
  .values([{
    first_name: 'Jennifer',
    last_name: 'Aniston',
    age: 40,
    hello: 'world'
  }, values])
  .executeTakeFirst()
```

again, no type-errors.

if you add `as const` to `values`, there are type-errors.
so you should always use `as const` when passing input "from outside" in type-safe TS libraries.

I actually had a PR that "fixes" it with a hack, but we rightfully didn't merge it as it's unhealthy. This is TypeScript's responsibility to fix.
https://github.com/kysely-org/kysely/pull/229

**Comment by maktouch** [comment]
hmm but even with `as const` it doesn't work? 

```ts
const obj = {
    first_name: 'Jennifer',
    last_name: 'Aniston',
    age: 40,
    hello: 'world'
  } as const

const result = await db
  .insertInto('person')
  .values(obj)
  .executeTakeFirst()

console.log(result.insertId)
```

**Comment by igalklebanov** [comment]
It worked on the 2 item example, haven't checked on single value example.

Here's some related text from people who are more in the know about this issue.
https://stackoverflow.com/a/57015227
https://github.com/microsoft/TypeScript/issues/12936

**Comment by cmmartin** [comment]
Okay, so typescript allows additional members, which makes sense. What doesn't make sense is why this is valid...

```
const obj = {
    first_name: 'Jennifer',
    last_name: 'Aniston',
    age: 40,
    hello: 'world'
  }
  
const result = await db
  .insertInto('person')
  .values(obj)
  .executeTakeFirst()
```

but this is not...

```
const result = await db
  .insertInto('person')
  .values({
    first_name: 'Jennifer',
    last_name: 'Aniston',
    age: 40,
    hello: 'world'
  })
  .executeTakeFirst()
```

If the explanation is that the additional members are not type errors, then both of these should be valid. Something else is going on here

**Comment by koskimas** [comment]
@cmmartin Feel free to contribute and fix the issue. Bitching about it won't make us want to help you.
