### ISSUE TITLE
Generic select function for specific column of type

### ISSUE THREAD

**Issue by scarf005** [kysely-org/kysely#642]
[original thread](https://discord.com/channels/890118421587578920/1138627093513646263)

```ts
import { SelectQueryBuilder, SqlBool } from "kysely"

type DB = {
	likes: { isDeleted: SqlBool }
	reviews: { isDeleted: SqlBool }
	users: { foo: SqlBool }
}

type Column<C extends string, Type> = { [K in C]: Type }

type TablesWithColumn<
	DB,
	C extends string,
	Type,
	Col extends Column<C, Type> = Column<C, Type>,
> = keyof {
	[K in keyof DB as DB[K] extends Col ? K : never]: never
}

type Withdeleted = TablesWithColumn<DB, "isDeleted", SqlBool>
//    ^? type withdeleted = "likes" | "reviews"

// works
const withDeleted1 = <Type, O>(
	qb: SelectQueryBuilder<DB, Withdeleted, O>,
) => qb.where("isDeleted", "=", false)

// doesn't work
const withDeleted2 = <
	TB extends TablesWithColumn<DB, "isDeleted", SqlBool>,
	O,
>(qb: SelectQueryBuilder<DB, TB, O>) => qb.where("isDeleted", "=", false)
```

[Playground Link](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgZQKYBtUGMYEUCuqUAngEL7DoAmRANCgI7qkQTpwC+cAZlBCHABEAa2IBnDMUEAoaTGJhUcACKk4AXkTSAkOmDDUYgFyI4wMcoyoYqKieRMWbTjqioAbsFQB3Y6fOWmDZ2jMys7Bw6+BJQfkjcrPaO4S6RcgpKAMJs+CAAdgA8mXCoAB42eVRicGIwUMB5AOb0ACoZAHwapgDaANJmeXCZALombYou6RMtAIYARphiAOrAMAAW2ei5hTqqtDrFZRVVNXUNzTrjqPvamyXlqJXVm9tFrR1dL-lvcFft+51NAZiBBuFptH0BnBgaCVGoZtVVH1hvdjs9nAB+OD9Ex5DxEUZwPHuIjSNLyCYrdY0IK2LqzBaGKkbHLfPZCAJWYKCegOMJsdrSAD0QrgYrgAD0sRSlN5VmsadY6ZpBHoDGJBHAAD5CNyeHwa2QiuDeaDCMTSLAQPK1E3ywJKqgARi6BSu9AA8u0ABQ6BhzexWHAEIhkCjUIgFdnMxXBT3-aQASg0nX9ADpvGsiKhvYJObSqDyhOoi9wZugJImjaKqBBDHkAOTwU1QYSW622uXrB3BABMrsuaiOjxODMWzK+hXZeYsXNsRb5TnQCe0HoB3v9gcwwcIJHIlBoUCjpFaJ7gXuT6lTcwzWbcufzjqLghL9DLFdQVaAA)

Maybe would this be due to limitation of how typescript works?

**Comment by igalklebanov** [comment]
Hey 👋 

Both variants don't work since they require to always have exactly `'likes' | 'reviews'` in query context.
So things like: `'likes' | 'users'` or `'likes' | 'reviews' | 'users'` cause a type error, which is not what you want.

Regarding issues with type errors within helper functions, it's a limitation of TypeScript, it won't narrow the generic properly when used inside the helper. You should only really focus on making sure the input and output types of a helper are correct.

```ts
type TablesWithColumn<C extends string> = {
  [TB in keyof DB]: C extends keyof DB[TB] ? TB : never;
}[keyof DB];

type TablesWithIsDeletedColumn = TablesWithColumn<"isDeleted">;

type IfIntersects<G0, G1, R> = [G0 & G1] extends [never] ? never : R;

// easiest escape is - don't bother with anything but input and output correctness and strictness.
// anything inside the helper cannot be type-safe anyway due to typescript limitations.
const withDeleted = <TB extends keyof DB, O>(
  qb: IfIntersects<TB, TablesWithIsDeletedColumn, SelectQueryBuilder<DB, TB, O>>
): SelectQueryBuilder<DB, TB, O> => qb.where("isDeleted" as any, "=", false);

// if you want better ergonomics within the helper, you could cast it as a narrower builder.
// this is still not quite as type-safe as you'd like given that the tables in `TablesWithIsDeletedColumn`
// could have very different structures, and that nothing guarantees all of them are in query context.
const withDeletedAlt = <TB extends keyof DB, O>(
  qb: IfIntersects<TB, TablesWithIsDeletedColumn, SelectQueryBuilder<DB, TB, O>>
): SelectQueryBuilder<DB, TB, O> =>
  (qb as unknown as SelectQueryBuilder<DB, TablesWithIsDeletedColumn, O>).where(
    'isDeleted',
    "=",
    false
  ) as any;
```
https://tsplay.dev/NDAG4m
