### ISSUE TITLE
Migration schema as a separate prop

### ISSUE THREAD

**Issue by luixo** [kysely-org/kysely#648]
Hi,

I'm setting up test environment with a pool of DB schemas.
I deploy my migrations for each schema.
When I tried to run it like this:
```ts
const schemaName = /* THIS IS UNIQUE */;
const database = new Kysely<ReceiptsDatabase>({
  dialect: new PostgresDialect({ ... }),
}).withSchema(schemaName);
await database.schema.createSchema(schemaName).ifNotExists().execute();
const migrator = new Migrator({
  db: database,
  provider: new FileMigrationProvider({...}),
});
await migrator.migrateToLatest();
```
I stumbled upon `"UNIQUE_SCHEMA_NAME.kysely_migration_lock" does not exist` error on the test which runs later.
It seems like schema is [taken](https://github.com/kysely-org/kysely/blob/df616ab3fe7a4b8d5e4ee3c05f982d943f3d2b7a/src/migration/migrator.ts#L233-L235) from a prop `migrationTableSchema` though schema is already passed via `withSchema` to `database` instance used.
Adding a prop `migrationTableSchema: schemaName` to `Migrator` constructor solves the issue.

Is it necessary to pass schema multiple times?

**Comment by koskimas** [comment]
Yes it is in this case. You can have your migration tables in one schema and the tables the migration creates in another.

**Comment by luixo** [comment]
Can we use the default schema for migration tables from the database itself?
If I don't pass `migrationTableSchema` I end up using `public` schema for migration table which doesn't seem obvious to me.
