### ISSUE TITLE
Typing a Postgres JSON Object Array Helper

### ISSUE THREAD

**Issue by alandotcom** [kysely-org/kysely#649]
I'm trying to extend the existing postgres helpers to be able to return rows where the `many` relations of one table are included as a JSON row in the final result.

An example schema would look like this,

```ts
  interface DB {
    acquisition: AcquisitionTable
    transaction: TransactionTable
  }

  interface AcquisitionTable {
    id: Generated<string>
  }

  interface TransactionTable {
    id: Generated<string>
    acquisitionId: string
    status: string
  }
```

And a query would look like,

```sql
SELECT
  "acquisition"."id",
  COALESCE(
    JSONB_AGG(
      JSON_BUILD_OBJECT(
        'id',
        "transaction"."id",
        'status',
        "transaction"."status"
      )
    ) FILTER (
      WHERE
        "transaction"."id" IS NOT NULL
    ),
    '[]'
  ) AS "transactions"
FROM
  "acquisition"
  LEFT JOIN "transaction" ON "transaction"."acquisitionId" = "acquisition"."id"
GROUP BY
  "acquisition"."id"
```

Example result,
```
/*
+--------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------>
| id                                   | transactions                                                                                                                                    >
|--------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------>
| d61d6e1b-d2d2-4baf-ba24-2b6ed26c7d37 | [{"id": "93366ffd-bafe-4af7-86d9-e8f557a2901c", "status": "SUCCESS"}, {"id": "d520ce18-fc0d-44f3-b237-7e8b8fc712bd", "status": "SUCCESS"}]     >
| 9492f6f6-997a-468f-b876-2185276e7040 | [{"id": "5fd801b9-a49a-4559-b686-1cd7c9ed4bd0", "status": "SUCCESS"}, {"id": "dbed09ad-99de-404e-b50e-7294bf86c06f", "status": "SUCCESS"}]     >
| dde9e851-6bb7-492f-a6fd-dc220b145060 | [{"id": "e905eae6-4431-4795-a48e-d71698832afe", "status": "SUCCESS"}, {"id": "666f0001-5122-479f-8677-08f4f95ffe4f", "status": "SUCCESS"}]     >
| 55c9c2a1-c9bd-453b-9620-8f418b03413a | []                                                                                                                                             >
| 63fd6a34-5bc4-4a65-a936-60e79a520f9c | [{"id": "9644a5e3-4ef5-4a1e-b722-4dd3bdaf8bf8", "status": "SUCCESS"}, {"id": "bc51cd66-e84c-465a-974a-7a8a3c78158b", "status": "SUCCESS"}]     
*/
```

This is about as far as I've gotten, but I'm not sure how to filter out the nulls from the result, so the result type is incorrect and looks like

```ts
const rows: {
    id: string;
    transactions: {
        id: string | null;
        status: string | null;
    }[];
}[]
```

Implementation
```ts
function jsonBuildObjectArray<
  O extends Record<string, Expression<unknown>>,
  DB,
  TBL extends keyof DB
>(
  obj: O,
  // Primary Key Column so we can filter out NULLs in the resulting array
  tablePKeyRef: ExpressionWrapper<DB, TBL, string | null>
): RawBuilder<
  Simplify<
    {
      [K in keyof O]: ExtractTypeFromReferenceExpression<DB, TBL, O[K]>
    }[]
  >
> {
  // https://stackoverflow.com/questions/24155190/postgresql-left-join-json-agg-ignore-remove-null
  return sql`
    COALESCE(
      JSONB_AGG(
        JSON_BUILD_OBJECT(
          ${sql.join(Object.keys(obj).flatMap((k) => [sql.lit(k), obj[k]]))}
        )
      )
      FILTER (WHERE ${tablePKeyRef} IS NOT NULL),'[]'
    )
  `
}
```

playground link: https://kyse.link/?p=s&i=zpiPgISS1it2HD3XXplo

**Comment by igalklebanov** [comment]
Hey 👋 

I take it you got this working. Can you post your solution for future readers?

**Comment by alandotcom** [comment]
No, I didn't get to a working solution

**Comment by koskimas** [comment]
This should now be possibe in 0.27.0 using:

```ts
import { jsonBuildObject, sql } from 'kysely/helpers/postgres'

const result = await db
  .selectFrom('acquisition')
  .leftJoin('transaction', 'transaction.acquisitionId', 'acquisition.id')
  .select((eb) => [
    'acquisition.id',
    eb.fn.coalesce(
      eb.fn.jsonAgg(
        jsonBuildObject({
          id: eb.ref('transaction.id'),
          status: eb.ref('transaction.status'),
        })
      ).filterWhere('transaction.id', 'is not', null),
      sql.lit('[]'),
    ).as('transactions'),
  ])
  .groupBy('acquisition.id')
  .executeTakeFirstOrThrow()
```

**Comment by adrienduchemin** [comment]
Hey, we are still encountering a small issue with your code @koskimas. 

Even when using `filterWhere('transaction.id', 'is not', null)`, the return type of transactions[0].id is string | null, as if the typing of filterWhere not null was not taken into account.  So we have to cast the whole query just to remove the `not null`.
Glad to hear your thoughts !

**Comment by hanssonduck** [comment]
> Hey, we are still encountering a small issue with your code @koskimas.
> 
> Even when using `filterWhere('transaction.id', 'is not', null)`, the return type of transactions[0].id is string | null, as if the typing of filterWhere not null was not taken into account. So we have to cast the whole query just to remove the `not null`. Glad to hear your thoughts !

Hey @koskimas also have this issue.

**Comment by igalklebanov** [comment]
Currently, we don't affect the return type based on SQL filtering, due to compile-time performance considerations and implementation complexity.

We do offer [`$narrowType<T>`](https://kysely-org.github.io/kysely-apidoc/interfaces/SelectQueryBuilder.html#_narrowType) and `NotNull` as a workaround.

**Comment by hanssonduck** [comment]
> We do offer [`$narrowType<T>`](https://kysely-org.github.io/kysely-apidoc/interfaces/SelectQueryBuilder.html#_narrowType) and `NotNull` as a workaround.

Thanks for the quick reply it works perfectly.

**Comment by AmrMonier** [comment]
> This should now be possible in 0.27.0 using:
> 
> ```ts
> import { sql } from 'kysely'
> import { jsonBuildObject } from 'kysely/helpers/postgres'
> 
> const result = await db
>   .selectFrom('acquisition')
>   .leftJoin('transaction', 'transaction.acquisitionId', 'acquisition.id')
>   .select(({ fn, ref }) => [
>     'acquisition.id',
>     fn.coalesce(
>       fn.jsonAgg(
>         jsonBuildObject({
>           id: ref('transaction.id'),
>           status: ref('transaction.status'),
>         })
>       ).filterWhere('transaction.id', 'is not', null),
>       sql`'[]'`
>     ).as('transactions'),
>   ])
>   .groupBy('acquisition.id')
>   .executeTakeFirstOrThrow()
> ```

why on earth there is no mention of this in the documentation?

**Comment by koskimas** [comment]
> why on earth there is no mention of this in the documentation?
@AmrMonier This is open source. We build this thing on our spare time *for free*. Things are not perfect. We're doing the best we can after our actual work and our personal life.

You haven't paid anything for this. You are not entitled to make demands or be angry if something's missing. If you asked nicely, I would've added an example right away to the docs.

**Comment by koskimas** [comment]
> And people with their thumbs up, feel free to create a PR.
You could've added a thumbs up to the example I provided. But no. You put your thumbs up for the person that demanded for more work. Just... Fuck you..,

**Comment by koskimas** [comment]
Why these morons like @Amr-Monier just never get it. It's beyond me. They somehow think they are part of some community that owes them something just by adding a rude comment to demand more work from the actual community.

**Comment by kylealwyn** [comment]
thank you @koskimas and team - kysely is incredible

**Comment by fabricioffa** [comment]
> We do offer [`$narrowType<T>`](https://kysely-org.github.io/kysely-apidoc/interfaces/SelectQueryBuilder.html#_narrowType) and `NotNull` as a workaround.

I've read the docs you pointed and tried many different approaches, but i always ends up with a type error message from $narrowType. Is it really supposed to be used on such cases or did i get it wrong?
```	ts	
const recipes = await ctx.db
			.selectFrom('recipe')
			.leftJoin('recipeComponent as comp', 'recipe.id', 'comp.recipeId')
			.selectAll('recipe')
			.select(({ fn, ref }) => [
				fn.coalesce(
					fn.jsonAgg(
						jsonBuildObject({
							id: ref('comp.id'),
							materialId: ref('comp.materialId'),
							subRecipeId: ref('comp.subRecipeId'),
							unit: ref('comp.unit'),
							quantity: ref('comp.quantity'),
							isPerUnit: ref('comp.isPerUnit'),
							createdAt: ref('comp.createdAt'),
							updatedAt: ref('comp.updatedAt'),
						})
					).filterWhere('comp.id', 'is not', null),
					sql`'[]'`
				).as('components')
			])
			.groupBy('recipe.id')
			.orderBy('recipe.name', 'asc')
			.$narrowType<{ components: RecipeComponentSchema[] }>()
			.execute();
```
