### ISSUE TITLE
Cannot call private methods of migrator

### ISSUE THREAD

**Issue by romeerez** [kysely-org/kysely#650]
Knex migrations have a richer public interface, so I'm able to specify how many migrations I want to roll back or migrate. I have a problem rewriting the existing code for Knex to Kysely. I could do the same with Kysely if only the `#migrate` method wasn't private.

Is it a desired behavior, to intentionally limit usage of the library? If yes, then all's good, and I'll have to copy-paste the source code into my script to customize it. If not, please, use private methods of TS instead, they are syntactically better, they semantically limit the responsibility of the library, and users are still able to call them if it's really needed.

IMO, `#` private methods were a bad idea and should **never** be used, it doesn't make any sense to forbid users to use the tool in a way they need for their task. Wondering, what's your opinion on this?

**Comment by koskimas** [comment]
Private interface is private for s reasons. It can change at any point without warning. It's a pretty common thing in software design.

**Comment by romeerez** [comment]
My suggestion was to use TS private methods, and my question was why use JS private methods instead. TS private methods are enough for what you're saying. JS private methods are when you really want to force users to search for workarounds rather than simply using the method that already exists.
