### ISSUE TITLE
Custom Type Converters

### ISSUE THREAD

**Issue by brett-minca** [kysely-org/kysely#652]
I'm not sure if I'm missing something, or just stumbled upon something that isn't implemented yet.

I have a postgres compound composite type:

```postgresql
create type radio_option as (
    pdf_field_name text,
    pdf_friendly_name text
);

create table form_fields as (
  "id" uuid primary key default gen_random_uuid(),
  "radio_options" radio_option[] not null
)
```

```typescript
export type FormFields = {
  id: GeneratedAlways<string>,
  radioOptions: ColumnType<
    RadioOption[],
    RadioOption[] | undefined,
    RadioOption[] | undefined
  > | null;
};

export type DB = {
  formFields: FormFields;
};
```

However, when I get this row back, the type isn't deserialized, it's just the string representation of that column (radio_options[]).

```plain
"{\"(option1,\\\"Friendly Option 1\\\")\"}"
```

I would expect it to be:

```typescript
[["option1", "Friendly Option 1"]]
```

Is it possible for me to implement a custom type handler for this?  I saw the `Expression` api, but it looks like that's not the right thing for this.  Thanks!

ps: I really like Kysely. Nice work on this!

**Comment by koskimas** [comment]
You can use https://github.com/brianc/node-pg-types.
