### ISSUE TITLE
Using introspection, can I tell if a column is primary?

### ISSUE THREAD

**Issue by dinfer** [kysely-org/kysely#653]
the method `getTables` of `DatabaseIntrospector` just return `ColumnMetadata`, which lack of some information to tell is primary or not.
By the way, is there any way to get indices using introspection?

**Comment by koskimas** [comment]
There's no constraint or index information available through the introspection API. The API is there mostly to help 3rd party type code generators.

**Comment by dinfer** [comment]
@koskimas Yes, I'm creating some code generators and I want to know which column is the primary key. Could Kysely add more information about table introspection ?

**Comment by koskimas** [comment]
Kysely table interface types don't need to know which column is the primary key. Index information is also irrelevant.

**Comment by dinfer** [comment]
Is it possible to add pk on ColumnMetadata? I can create a pull request if it's ok for Kysely.
In the file `https://github.com/kysely-org/kysely/blob/master/src/dialect/sqlite/sqlite-introspector.ts`, kysely uses `pragma_table_info` to get column info which can tell a column is primary or not.

```
sqlite> CREATE TABLE User
   ...>         -- A table comment
   ...> (
   ...>         uid INTEGER,    -- A field comment
   ...>         flags INTEGER   -- Another field comment
   ...> );
sqlite> .schema User
CREATE TABLE User
        -- A table comment
(
        uid INTEGER,    -- A field comment
        flags INTEGER   -- Another field comment
);
sqlite> select * from pragma_table_info('User');
cid|name|type|notnull|dflt_value|pk <--- is primary key or not
0|uid|INTEGER|0||0
1|flags|INTEGER|0||0
sqlite> select * from sqlite_master;
```

What's more, comment on a column can also be returned. just like what `#getTableMetadata` does, parse the sql.

Finally, I didn't check mysql and postgresql, I'll find if it's ok for them.
