### ISSUE TITLE
Is there a way to stop query execution in plugins?

### ISSUE THREAD

**Issue by alnorris** [kysely-org/kysely#654]
I'm wanting to write a lru-cache plugin, I cannot find a way to able to cancel the query all together when a cache hit is found.

**Comment by koskimas** [comment]
Not without throwing, which obviously won't work in your use case.

**Comment by alnorris** [comment]
Perhaps it would be easy to add a `skipExecution` boolean method in KyselyPlugin method? If its true transformResult will just have an null result. Am happy to create a PR for this @koskimas if you are willing to merge.

**Comment by koskimas** [comment]
We shouldn't add something like that to a query builder. Kysely should just execute the query you build. Nothing more.

If I were you, I'd build the cache outside Kysely.
