### ISSUE TITLE
Add boilerplate-reducing tools for doUpdateSet

### ISSUE THREAD

**Issue by icopp** [kysely-org/kysely#655]
It would be very useful if there was a way to handle common boilerplate cases for this with Postgres. For example, there could be `doUpdateSetAll()` (`column_name = excluded. column_name` for all columns in the query) and `doUpdateSetAllExcept(['column_name_a', 'column_name_b'])` to leave out a specific subset of column names.

**Comment by koskimas** [comment]
I understand the value of this kind of helper for DX, but I don't like it for because there's no SQL equivalent for it. We'd need to generate different code on different dialects. Kysely normally doesn't do that. I wouldn't want to start here.

You could argue that this is similar to `selectAll` but the difference is that `selectAll` is always compiled as `select *`, regardless of the dialect.

**Comment by AlexErrant** [comment]
> `doUpdateSetAllExcept(['column_name_a', 'column_name_b'])`

I created a typescript type to help enforce this, which excludes id, noteId, created, and ord from the update set. However, being just a type, you still need to write runtime-code (i.e. `updated: (x) => x.ref("excluded.updated")`).

```ts
// the point of this type is to cause an error if something is added to CardEntity
type OnConflictUpdateCardSet = {
  [K in keyof CardEntity as Exclude<K, "id" | "noteId" | "created" | "ord">]: (
    x: ExpressionBuilder<
      OnConflictDatabase<DB, "card">,
      OnConflictTables<"card">
    >
  ) => RawBuilder<CardEntity[K]>
}

// usage
      await db
        .insertInto("card")
        .values(batches[i])
        .onConflict((db) =>
          db.doUpdateSet({
            updated: (x) => x.ref("excluded.updated"),
            due: (x) => x.ref("excluded.due"),
            deckIds: (x) => x.ref("excluded.deckIds"),
            cardSettingId: (x) => x.ref("excluded.cardSettingId"),
            state: (x) => x.ref("excluded.state"),
          } satisfies OnConflictUpdateCardSet)
        )
        .execute()

```

Taken from [here](https://github.com/AlexErrant/Pentive/blob/69351e870e1bfc51b73b09101570e37d70b97718/app/src/sqlite/card.ts#L130-L136). With a bit more work I think one could create a generalized typescript function like `doUpdateSetAllExcept`, but I'm too bad at typescript x|
