### ISSUE TITLE
Cloudflare workers error with Postgres and Kysely 0.26.1

### ISSUE THREAD

**Issue by Amuleus** [kysely-org/kysely#663]
I saw a pull request for a test of Kysely + Postgres + Cloudflare:
https://github.com/kysely-org/kysely/pull/574/files
The first time SQL query is executed - all is fine, but when you call several times same query in Cloudflare it gives exceptions. 
Looks like CloudFlare uses slightly modified node event pool which breaks Postgres queries in a way I can't figure yet.

A simple Kysely query in Cloudflare workers:
```
export async function getCountry(args: { countryId: string }) {
  const dbResult = await db
    .selectFrom("country")
    .where("id", "=", args.countryId)
    .selectAll()
    .executeTakeFirst();
  return dbResult;
}
```

It runs first time without issues, next time I open a handler which runs same query cloudfalre gives exception:
```
(error) kysely:error: Error: Cannot perform I/O on behalf of a different request. I/O objects (such as streams, request/response bodies, and others) created in the context of one request handler cannot be accessed from a different request's handler. This is a limitation of Cloudflare Workers which allows us to improve overall performance.
    at CloudflareSocket.write (index.js:26521:24)
    at Connection._send (index.js:26758:28)
    at Connection.parse (index.js:26764:14)
    at Query.prepare (index.js:22850:22)
    at Query.submit (index.js:22824:16)
    at Client._pulseQueryQueue (index.js:29053:49)
    at Client.query (index.js:29133:14)
    at PostgresConnection.executeQuery (index.js:19877:45)
    at connection.executeQuery (index.js:17684:39)
    at index.js:14282:43
    at PostgresConnection.executeQuery (index.js:19892:39)
    at connection.executeQuery (index.js:17684:39)
    at index.js:14282:43
    at DefaultConnectionProvider.provideConnection (index.js:17544:24)
    at async DefaultQueryExecutor.executeQuery (index.js:14281:16)
    at async SelectQueryBuilder.execute (index.js:14793:24)
    at async listCountries (index.js:30009:20)
    at async onBeforeRender (index.js:30188:28)
    at async index.js:3444:19
```

When I wait for about 1-2 minutes and open handler - query runs fine, if you try to run same Kysely query within the next minute after same query was executed exception happens again.

That is very strange because vanilla pg query has no such issue in Cloudflare workers:

```
export const dbListCountries = async (page = 1, pageSize = 10) => {
  const client = new Client("postgres://xxx:xxx@xxx:5432/xxx");
  await client.connect();
  const offset = (page - 1) * pageSize;
  const result = await client.query(
    `SELECT * FROM country LIMIT $1 OFFSET $2`,
    [pageSize, offset]
  );
  const countries = result.rows;
  return countries;
};
```

My Kysely DB init (maybe the reason of IO error related to pg connection initialization in CloudFlare):
```

export const db = new Kysely<DB>({
  dialect: new PostgresDialect({
    pool: async () =>
      new Pool({
        connectionString:
          process.env.DATABASE_URL_KYSELY ||
          "postgres://xxx:xxx@xxx:5432/xxx",
      }),
  }),
  plugins: [
    new CamelCasePlugin({
      underscoreBeforeDigits: true,
      underscoreBetweenUppercaseLetters: true,
    }),
  ],
  log: process.env.IS_LOCAL ? ["query", "error"] : ["error"],
});
```

**Comment by koskimas** [comment]
I'd guess this has something to do with the pool. A second query on the same pooled connection fails. Once you wait a couple of minutes, the pooled connection is released and you get a new connection.

You could try disallowing pooled connection reuse. I don't really know if that's possible, but check out the options [here](https://node-postgres.com/apis/pool).

You could validate this idea by setting `idleTimeoutMillis: 1` which will release the pooled connections after 1 millisecond. That's still not a real solution since you can get another query within that time.

**Comment by Amuleus** [comment]
@koskimas thanks for a fast reply. 

I also read https://github.com/pocketbase/pocketbase/discussions/2185 where CloudFlare gave similar error. They suggest to init new instance on each request.

So I changed:
```
export const db = new Kysely<DB>({
  dialect: new PostgresDialect({
    pool: async () =>
      new Pool({
        connectionString:
          process.env.DATABASE_URL_KYSELY ||
          "postgres://xxx:xxx@xxx:5432/xxx",
      }),
  }),
  plugins: [
    new CamelCasePlugin({
      underscoreBeforeDigits: true,
      underscoreBetweenUppercaseLetters: true,
    }),
  ],
  log: process.env.IS_LOCAL ? ["query", "error"] : ["error"],
});
```

to:

```

export const dbFactory = () => {
  return new Kysely<DB>({
    dialect: new PostgresDialect({
      pool: async () =>
        new Pool({
          connectionString:
            process.env.DATABASE_URL_KYSELY ||
            "postgres://xxx:xxx@xxx:5432/xxx",
        }),
    }),
    plugins: [
      new CamelCasePlugin({
        underscoreBeforeDigits: true,
        underscoreBetweenUppercaseLetters: true,
      }),
    ],
    log: process.env.IS_LOCAL ? ["query", "error"] : ["error"],
  });
};
```

Then I create a `context` with dbFactory result and pass it down to server handler and middlewares which previously imported `db` directly from the file.

That helped so far.

@koskimas do you think Pool makes sense inside dbFactory taking into consideration the dbFactory is called one time per HTTP request?

**Comment by Amuleus** [comment]
I'm closing this issue. 

Looks like Kysely works fine with Cloudflare and server-less functions, but connection pool is redundant when using server-less functions.

If the overhead of establishing a new connection for each request becomes a performance bottleneck, you may want to explore other solutions like using a Database Proxy that maintains the connection to the PostgreSQL database and provides a single endpoint for server-less functions. This way, the proxy handles connection pooling, and functions just connect to it.

Here's a conceptual idea:

1. Serverless Function -> Sends request to Database Proxy
2. Database Proxy -> Manages connection pool and forwards request to PostgreSQL
3. PostgreSQL -> Processes request and sends response back through the chain

Solutions like AWS RDS Proxy, PgBouncer, or similar technologies might help in reducing the connection overhead in a server-less environment.

**Comment by Amuleus** [comment]
Closing as serverless environments have different requirements to connection pooling than regular application servers.

**Comment by Amuleus** [comment]
Configuring Postgres Pool like here:
https://github.com/vercel/storage/blob/main/packages/postgres/src/create-pool.ts#L115
allowed to import db and use it as usual without factory.
