### ISSUE TITLE
COLLATE NOCASE for orderby sqlite

### ISSUE THREAD

**Issue by subhanwebbee** [kysely-org/kysely#668]
Kysely does not support order by with collate nocase for sqlite which creates an issue when sorting for incase sensitive strings in sqlite

**Comment by koskimas** [comment]
Cool.

**Comment by igalklebanov** [comment]
Hey 👋 

@subhanwebbee Kysely doesn't support many things. It's a continuous work in progress.

The real issue is how you presented the problem. Very tasteless, and demanding. We are not working for you. 🤷
