### ISSUE TITLE
Insert into select with custom values

### ISSUE THREAD

**Issue by RdXDavidaz** [kysely-org/kysely#674]
I'm trying to do this sort of request : 

```
INSERT INTO table ( id, token, date) 
SELECT  table2.id, 'custom_string_token', new Date()
FROM    table2
WHERE   table2.user= 'custom_user';
```

But I can't figure out how is it possible to just select Id from an other table, and a custom string character/custom date.
My current code:
```
return await db.insertInto('client_password_reset')
 .expression(db.selectFrom('client').select('id', generateToken(10); new Date()).where(column, '=', body.username))
```
    
But generateToken (that return a string) and new Date() don't work, as there are not in client table.
Is there a way to do that, or should I do two request?

**Comment by koskimas** [comment]
Like this https://kyse.link/?p=s&i=SIDp1HnFTuzFRlcBvlQ8

**Comment by koskimas** [comment]
There's even an example of that in kysely.dev https://kysely.dev/docs/examples/INSERT/insert-subquery
