### ISSUE TITLE
Add TiDB Serverless Driver

### ISSUE THREAD

**Issue by shiyuhang0** [kysely-org/kysely#679]
Hi, I'd like to add a 3rd party dialect called [TiDB Serverless Driver](https://github.com/tidbcloud/serverless-js) and add it to the official 3rd party dialects list https://kysely.dev/docs/dialects#3rd-party-dialects

Is there some necessary process to get this done?

**Comment by koskimas** [comment]
Just create a PR and we'll merge it.

**Comment by shiyuhang0** [comment]
Thanks! I will develop the plugin then open a pr
