### ISSUE TITLE
Where clause with and and multiple or support

### ISSUE THREAD

**Issue by dhirajsonavane** [kysely-org/kysely#681]
Hi,

I am currently working on a scenario where I need to filter postgres data based on combination of multiple dates. I am using node/typescript. 

Start and End Dates are in an array object. 

Raw sql as below. 

select  * from test_schema.sample_vw
where asset in ('A1', 'A2')
and plant in ('P1, 'P2', 'P3')
and (
(task_ts >= '2023-06-01' and task_ts <= '2023-06-30')
or (task_ts >= '2023-07-01' and task_ts <= '2023-07-31')
or (task_ts >= '2023-08-01' and task_ts <= '2023-08-31')
or (task_ts >= '2023-09-01' and task_ts <= '2023-09-30')
)

I tried multiple ways but could't achieve this using kysely qbery builder. 

Any help would be highly appreciated.

**Comment by koskimas** [comment]
https://kysely.dev/docs/examples/WHERE/conditional-where-calls

**Comment by dhirajsonavane** [comment]
Thanks Got the solution in case anyone struggles with similar use case. 

let query = queryBuilder({ dbUrl: this.dbUrl, schema: dbSchema })
      .selectFrom('sample_vw')
      .selectAll();

    if (filter.filters.asset.length) {
      query = query.where('asset', 'in', filters.asset);
    }

    if (filter.filters.plantSection.length) {
      query = query.where('plant', 'in', filters.plantSection);
    }

    if (filter.filters.startAndEndDates.length) {
      query = query.where(eb => {
        const ors: Expression<SqlBool>[] = [];

        filter.filters.startAndEndDates.map(date => {
          const ands: Expression<SqlBool>[] = [];

          if (date?.startDate) ands.push(eb.cmpr('taskTs', '>=', date.startDate!));
          if (date?.endDate) ands.push(eb.cmpr('taskTs', '<=', date.endDate!));

          ors.push(eb.and(ands));
        });

        return eb.or(ors);
      });
    }

    console.log(query);
    const result = await query.execute();

**Comment by koskimas** [comment]
Umm did you look at the link I provided https://kyse.link/?p=s&i=hD4IjnC2bpoS8b8Zw5Pj. That's the solution.
