### ISSUE TITLE
Multiple column data with the same column name get overriden during join

### ISSUE THREAD

**Issue by md-redwan-hossain** [kysely-org/kysely#682]
```
SELECT *
FROM "Stuffs"
JOIN "PersonalData" ON "Stuffs"."PersonalDataId" = "PersonalData"."Id"
WHERE "Stuffs"."Id" = '5897ef27-9597-4bc7-b42c-dac688c20040';
```

If I run the upper raw query, I got the following result: 

```
{
	"Id" : "5897ef27-9597-4bc7-b42c-dac688c20040",
	"CreatedAt" : "2023-09-06T18:11:01.348Z",
	"UpdatedAt" : null,
	"PersonalDataId" : "25d5db69-5055-474b-a005-5947520d44a3",
	"Email" : "super.admin@mail.com",
	"MobileNumber" : null,
	"Id" : "25d5db69-5055-474b-a005-5947520d44a3",
	"CreatedAt" : "2023-09-06T18:11:01.348Z",
	"UpdatedAt" : null,
	"FullName" : "Super Admin",
	"Password" : "123456",
	"DateOfBirth" : "2023-09-06T18:11:01.348Z",
	"Bio" : null,
	"Role" : "SuperAdmin",
	"Gender" : "Male",
	"IsVerified" : false,
	"IsBanned" : false,
	"IsDeactivated" : false
}
```

However, in kysely, when I execute the following,

```
const data = await this.db
  .selectFrom("Stuffs")
  .innerJoin("PersonalData", "PersonalData.Id", "Stuffs.PersonalDataId")
  .selectAll()
  .where("Stuffs.Id", "=", id)
  .executeTakeFirst();
```

The result is the following. The `PersonalData.Id` is gone from the result, even using aliasing does not help, I can overcome this issue by selecting the columns manually and give different alias, but it is not practical with the table that has so many columns. 

This is the normal behavior of JS object where duplicate key will be overridden with the latest insert value. Kysely need to do something here. The most practical solution will be wrap the data of the joined table in a nested object, and the Drizzle ORM exactly follows this approach.

```
{
    "Id": "25d5db69-5055-474b-a005-5947520d44a3",
    "CreatedAt": "2023-09-06T18:11:01.348Z",
    "UpdatedAt": null,
    "PersonalDataId": "25d5db69-5055-474b-a005-5947520d44a3",
    "Email": "super.admin@mail.com",
    "MobileNumber": null,
    "FullName": "Super Admin",
    "Password": "123456",
    "DateOfBirth": "2023-09-06T18:11:01.348Z",
    "Bio": null,
    "Role": "SuperAdmin",
    "Gender": "Male",
    "IsVerified": false,
    "IsBanned": false,
    "IsDeactivated": false
}
```

**Comment by koskimas** [comment]
Using an alias DOES help. What the heck are you talking about?

```ts
const data = await this.db
  .selectFrom("Stuffs")
  .innerJoin("PersonalData", "PersonalData.Id", "Stuffs.PersonalDataId")
  .selectAll()
  .select("PersonalData.Id as PersonalDataId")
  .where("Stuffs.Id", "=", id)
  .executeTakeFirst();
```

**Comment by koskimas** [comment]
>  Kysely need to do something here.

You need to learn how SQL works.

> Drizzle ORM exactly follows this approach.

Kysely is not an ORM. We never ever add anything to the SQL that the user didn't explicitly request.

**Comment by md-redwan-hossain** [comment]
> > Kysely need to do something here.
> 
> You need to learn how SQL works.
> 
> > Drizzle ORM exactly follows this approach.
> 
> Kysely is not an ORM. We never ever add anything to the SQL the user didn't explicitly request. Wrapping things to nested objects works for trivial joins. It's completely impossible for arbitrary SQL. Especially when combined with the fact that we don't alter the SQL. Also that's an ORM feature. SQL returns a set of flat records.
> 
> I think you'd be much happier with Drizzle or some other ORM.

I have attached raw sql query and the result of the raw sql query and everything is working fine. You completely avoided the raw sql part and told me to learn sql. kysely does nothing wrong, even if the database sending the data that I am attached from raw query, JS will override that since it returns me a object where duplicate key is not allowed. What is the possible solution then? Can you give a working code for my problem? The thing I need that I want all the columns from both tables, and as I know there are columns with the same name in both of the table, I want to pass some argument in `selectAll()` that will rename the duplicate key.

**Comment by armstrong-pv** [comment]
I'm probably going to be shot down here, so I hold my hands up and surrender right now 😂But having bumped into this, it would be nice to have (an admittedly non-sql) extension to the `.selectAll(['person', 'pet'])` clause:
````
.selectAll(['person as per_', 'pet as pet4_''])
````
Which only affects the column names and would make all of the person column names be prefixed with 'per_' and all of the pet column names be prefixed with 'pet4_'. Under the hood, this could just automatically build out an appropriate `.select()` clause, so hopefully wouldn't break any existing functionality. 

This excellent library is already saving me a ton of work, so it would be the icing on the cake...

**Comment by armstrong-pv** [comment]
Hey @igalklebanov, thanks for responding to my question. I thought there might be a way of introspecting this from the schema that you give Kysely? For instance, a snippet of mine looks like:
````
export interface Database {
  user: UserTable
  authorisation: AuthProviderTable
  group: GroupTable
  userDevice: UserDeviceTable
}
````
And then for one of the tables:
````
export interface GroupTable {
  id: string
  name: string
  creatorUserId: string
  ownerUserId: string
  description: string | null
  avatarUrl: string | null
  language: string | null
  groupType: number 
  metadata: string | null
  isClosed: boolean
  edgeCount: number | null
  maxCount: number
  createdAt: Date | null
  updatedAt: Date | null
  disabledAt: Date | null
}

export class Group extends BaseModel implements Selectable<GroupTable> {
  id: string
  name: string
  creatorUserId: string
  ownerUserId: string
  description: string | null
  avatarUrl: string | null
  language: string | null
  groupType: number
  metadata: string | null
  isClosed: boolean
  edgeCount: number | null
  maxCount: number
  createdAt: Date | null
  updatedAt: Date | null
  disabledAt: Date | null

  constructor(group: Selectable<GroupTable>) {
    super()
    this.id = group.id
    this.name = group.name
    this.creatorUserId = group.creatorUserId
    this.ownerUserId = group.ownerUserId
    this.description = group.description
    this.avatarUrl = group.avatarUrl
    this.language = group.language
    this.groupType = group.groupType
    this.metadata = group.metadata
    this.isClosed = !!group.isClosed
    this.edgeCount = group.edgeCount
    this.maxCount = group.maxCount
    this.createdAt = group.createdAt
    this.updatedAt = group.updatedAt
    this.disabledAt = group.disabledAt
  }
}
````
But I'm new to both typescript and Kysely, so I'm sure there's something I'm probably missing!

**Comment by dahlia** [comment]
At least in SQLite and PostgreSQL, overlapping column names do not cause either of them to be omitted:

```
test=# create temp table foo (id int, name text);
CREATE TABLE
Time: 15.516 ms
test=# create temp table bar (id int, name text);
CREATE TABLE
Time: 5.205 ms
test=# insert into foo values (1, 'foo');
INSERT 0 1
Time: 1.642 ms
test=# insert into bar values (1, 'bar');
INSERT 0 1
Time: 1.829 ms
test=# select * from foo join bar using (id);
 id | name | name
----+------+------
  1 | foo  | bar
(1 row)

Time: 1.291 ms
```


If Kysely is supposed to transparently mirror SQL's behavior, it should follow this one as well.

**Comment by igalklebanov** [comment]
But what does the underlying driver return?
