### ISSUE TITLE
support for SELECT ... FOR UPDATE OF table_name

### ISSUE THREAD

**Issue by remvn** [kysely-org/kysely#683]
currently i can't find a way to add raw sql to SelectQueryBuilder 

suggestion: maybe we can add a new parameter for `table_name` in `SelectQueryBuilder.forUpdate()` method 

edit: my current workaround [Playground Link](https://kyse.link/?p=b&i=haFkqHBvc3RncmVzoXamMC4yNi4zoXPaAWJpbXBvcnQgeyBHZW5lcmF0ZWQgfSBmcm9tICJreXNlbHkiCgpkZWNsYXJlIGdsb2JhbCB7CiAgaW50ZXJmYWNlIERCIHsKICAgIHVzZXI6IFVzZXJUYWJsZQogICAgdXNlcl9iYWxhbmNlOiBVc2VyQmFsYW5jZVRhYmxlCiAgfQoKICBpbnRlcmZhY2UgVXNlclRhYmxlIHsKICAgIGlkOiBHZW5lcmF0ZWQ8c3RyaW5nPgogICAgZmlyc3RfbmFtZTogc3RyaW5nIHwgbnVsbAogICAgbGFzdF9uYW1lOiBzdHJpbmcKICAgIGFkZHJlc3M6IHsKICAgICAgY2l0eTogc3RyaW5nCiAgICB9CiAgfQoKICBpbnRlcmZhY2UgVXNlckJhbGFuY2VUYWJsZSB7CiAgICB1c2VyX2lkOiBudW1iZXIKICAgIGJhbGFuY2U6IG51bWJlcgogIH0KfQqhcdoBR2ltcG9ydCB7IEV4cHJlc3Npb25CdWlsZGVyLCBSYXdCdWlsZGVyLCBzcWwgfSBmcm9tICJreXNlbHkiCgpjb25zdCByb3dzID0gYXdhaXQga3lzZWx5CiAgLnNlbGVjdEZyb20oInVzZXIiKQogIC5zZWxlY3RBbGwoKQogIC5pbm5lckpvaW4oInVzZXJfYmFsYW5jZSIsICJ1c2VyX2JhbGFuY2UudXNlcl9pZCIsICJ1c2VyLmlkIikKICAuZm9yS2V5U2hhcmUoKQogIC5tb2RpZnlFbmQoc3FsYG9mICR7c3FsLnRhYmxlKCJ1c2VyIil9YCkKICAuZm9yVXBkYXRlKCkKICAubW9kaWZ5RW5kKHNxbGBvZiAke3NxbC50YWJsZSgidXNlcl9iYWxhbmNlIil9YCkKICAuZXhlY3V0ZSgpCqFjww==)

![image](https://github.com/kysely-org/kysely/assets/34063162/1e188bc9-eaee-490f-ad3a-34aa363aa5d6)

It would be nice if i can do some auto-complete and type-safe for table_name.

**Comment by koskimas** [comment]
Yep, we should add an optional argument for those methods. It can be a single table name or an array of them.

**Comment by koskimas** [comment]
Released in 0.27.1. You can now say

```ts
.forUpdate('person')
```

or

```ts
.forUpdate(['person', 'pet'])
```
