### ISSUE TITLE
Why can the numInsertedOrUpdatedRows be undefined?

### ISSUE THREAD

**Issue by pedrofrazaopacheco** [kysely-org/kysely#684]
Hi! Thanks for the library.
I am using the PostgresDialect.
Why is it that the [ InsertResult ](https://kysely-org.github.io/kysely-apidoc/classes/InsertResult.html#numInsertedOrUpdatedRows) numInsertedOrUpdatedRows has the type undefined | bigint 
The [DeleteResult](https://kysely-org.github.io/kysely-apidoc/classes/DeleteResult.html)'s numDeletedRows has the type bigint.
And the [UpdateResult](https://kysely-org.github.io/kysely-apidoc/classes/UpdateResult.html)'s numUpdatedRows has the type bigint while the numChangedRows has the type undefined | bigint?

Is there any reason why the db call in an insert would send back the numInsertedOrUpdatedRows undefined? Why isn't it 0 if it has not inserted anything? The same for the other cases
Thank you

**Comment by koskimas** [comment]
The types don't currently know anything about the used dialect. Some dialects don't return that value.
