### ISSUE TITLE
Can't create row with default values

### ISSUE THREAD

**Issue by codepunkt** [kysely-org/kysely#685]
It seems impossible to create a new row if a table has only auto-generated columns, e.g. postgres `gen_random_uuid()` id

```prisma
model Cart {
  id    String     @id @default(dbgenerated("gen_random_uuid()")) @db.Uuid
  items CartItem[] @relation

  @@map("carts")
}
```

I tried all variations of this I could think of, including using raw `sql`, but everything I tried resulted in SQL syntax errors:
```js
db.insertInto('carts').columns([]).returningAll().executeTakeFirstOrThrow()
```

The query I need to create here is
```sql
insert into "carts" default values returning *
```

Is there a way to do this?

**Comment by koskimas** [comment]
Hmm.. Maybe it'd be worth it to add a `defaultValues()` method to the insert query builder.

**Comment by koskimas** [comment]
Added in 0.27.1.

```ts
db.insertInto('person')
  .defaultValues()
```
