### ISSUE TITLE
[Question] Is it possible to support for Postgres.js as built-in PostgreSQL dialect driver?

### ISSUE THREAD

**Issue by lulunananaluna** [kysely-org/kysely#691]
My understanding is that [postgres](https://github.com/porsager/postgres) is also a decent alternative for [pg](https://github.com/brianc/node-postgres), however there is no built-in dialect / driver for it.

There is some cool work here at [igalklebanov/kysely-postgres-js](https://github.com/igalklebanov/kysely-postgres-js) and https://github.com/porsager/postgres/issues/603.

Is it possible to have it as a built-in? Or is it better to be left-out as an external dialect?

Thank you!

**Comment by koskimas** [comment]
We don't see any reason to support two Postgres drivers in the core.

**Comment by lulunananaluna** [comment]
You're right I agree, sorry for the silly suggestion :laughing: 

How about a reason to replace the existing built-in driver with a better one?

- https://github.com/porsager/postgres/discussions/627
- https://porsager.github.io/imdbench/sql.html

Could it break things?

**Comment by koskimas** [comment]
If someone writes a better driver in a significant way, we will consider it.

**Comment by igalklebanov** [comment]
Hey 👋

Postgres.js has no single connection getter. Kysely needs it. There's a PR/branch inplementing it, but porsager has been busy as of late and its not released yet.
So even if we wanted to add the dialrct to core, we can't.

I'm a Kysely member, and maintain this community dialect btw. What are you concerns with it not being in Kysely's core?
