### ISSUE TITLE
ERR_UNSUPPORTED_ESM_URL_SCHEME on Windows when running migration

### ISSUE THREAD

**Issue by Freya-Karow** [kysely-org/kysely#698]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `kysely@0.26.3` for the project I'm working on.

When trying to run a migration on Windows, I encountered the problem, that the path to the migrationfolder, which worked on Linux before, was not convertet properly. This results in the error 'ERR_UNSUPPORTED_ESM_URL_SCHEME'.

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/kysely/dist/esm/migration/file-migration-provider.js b/node_modules/kysely/dist/esm/migration/file-migration-provider.js
index 1b1fb9f..ea7da02 100644
--- a/node_modules/kysely/dist/esm/migration/file-migration-provider.js
+++ b/node_modules/kysely/dist/esm/migration/file-migration-provider.js
@@ -30,7 +30,7 @@ export class FileMigrationProvider {
                 fileName.endsWith('.mjs') ||
                 (fileName.endsWith('.mts') && !fileName.endsWith('.d.mts'))) {
                 const migration = await import(
-                /* webpackIgnore: true */ this.#props.path.join(this.#props.migrationFolder, fileName));
+                    /* webpackIgnore: true */ new URL("file://" + this.#props.path.join(this.#props.migrationFolder, fileName)));
                 const migrationKey = fileName.substring(0, fileName.lastIndexOf('.'));
                 // Handle esModuleInterop export's `default` prop...
                 if (isMigration(migration?.default)) {
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by koskimas** [comment]
This doesn't work on macos or linux. Unfortunately the `FileMigrationProvider` doesn't work on windows. It's only about 20 lines of code though, so my suggestion is that you create your own `MigrationProvider` for the time being.

**Comment by douglasg14b** [comment]
Sucks that this lands in nofix.

If the `FileMigrationProvider` doesn't support Windows, it should fail with an exception that it doesn't support that platform when ran on that platform. Preventing folks from having to hunt down threads like these :/
