### ISSUE TITLE
BUG!! Query does not work through Kysely

### ISSUE THREAD

**Issue by gurvirbaraich** [kysely-org/kysely#702]
## Problem
I have a query written that given an output when running in the console but fails to give output when executed through Kysely.

## Stack
- Node
- PlanetScale (MySQL DB)
- Prisma Schema
- Kysely

## Creating of query
![image](https://github.com/kysely-org/kysely/assets/117713832/7222e464-21ac-46e0-a1e8-c9fbb3146422)

![image](https://github.com/kysely-org/kysely/assets/117713832/69d3a511-d426-4c39-b657-947f52016c19)

## Expected Output
![image](https://github.com/kysely-org/kysely/assets/117713832/0220c41a-7fd4-4d35-92be-2332e441fd76)

**Comment by koskimas** [comment]
NOT A BUG! YOU'VE MADE A BUNCH OF MISTAKES!

**Comment by koskimas** [comment]
Here it is anyway https://kyse.link/?p=s&i=f1pafVzLnxy0ia7qzcXm

**Comment by koskimas** [comment]
By the way, that query makes very little sense. You don't join anything to `JobPosting` and you don't filter `JobPosting` in any way which will lead to a result where EVERY `JobPosting` in the db is joined to the user. You should get all job postings in the DB as the result.
