### ISSUE TITLE
Use the native node test runner and get rid of `concurrently`

### ISSUE THREAD

**Issue by koskimas** [kysely-org/kysely#703]
Node now comes with a really fast test runner built-in. We should switch to using that. It'd also allow us to parallelize the different database tests in a nice way in code instead of using the current horrible `concurrently` hackery. We'd also get rid of bunch of dev dependencies. @igalklebanov thoughts?

**Comment by igalklebanov** [comment]
I'm all for it. I never used `node:test` extensively.

**Comment by igalklebanov** [comment]
@koskimas 
> most of the slowness comes from all the build steps.

Maybe explore switching from [tsc](https://www.typescriptlang.org/docs/handbook/compiler-options.html) to [esbuild](https://esbuild.github.io) or [swc](https://swc.rs), everything or just tests?
