### ISSUE TITLE
having method not taking aliased column as type safe input

### ISSUE THREAD

**Issue by BaptisteMahe** [kysely-org/kysely#708]
Hello, firstly thank you for this amazing query builder, I've been replacing unsafe raw queries with Kysely built queries and it has been a joy to know that my backend always references valid tables and columns !

That said I'm having an issue with the `having`  methods lately.
With this simple setup:

schema.ts
``` typescript
import { Generated } from 'kysely'

declare global {
  interface DB {
    person: PersonTable
  }

  interface PersonTable {
    foo: Generated<string>
  }
}
```

query.ts
``` typescript
const persons = await db
  .selectFrom('person')
  .select('foo as bar')
  .having('bar', '=', 'test')
  .execute()
```

This should generate a valid MySQL query like so:

``` sql
SELECT
  `foo` AS `bar`
FROM
  `person`
HAVING
  `bar` = ?

-- Parameters
-- [1] test
```

But I'm having a Typescript error with the input type which is the following :

``` shell
TS2345: Argument of type  "bar"  is not assignable to parameter of type  ReferenceExpression<DB, "person"> 
```

I understand that the string `"bar"` doesn't represent any well-defined table or column inside my schema but I would expect that for that specific query where I explicitly aliased the `foo` column as `bar` I would be able to reference it safely.

Maybe there is something I didn't understand about the way the type system works, if so please show me how to make this kind of call while keeping the type safety.

Thank you in advance!

**Comment by koskimas** [comment]
Postgres doesn't support that. We decided to go with that since we don't have dialect specific types.

**Comment by igalklebanov** [comment]
@koskimas I wonder if and when we introduce dialect-specific type configuration, could we possibly allow this for some engines?
