### ISSUE TITLE
Using optimizer hints for MySQL

### ISSUE THREAD

**Issue by rurruur** [kysely-org/kysely#710]
I would like to know if there are any techniques or options for optimizer hint.
Something similar to the following:
```ts
const result = await this.db
      .selectFrom()
      .selectAll()
      .where()
      .maxExecutionTime(60_000)
      .execute();
```
Or, if theres any way to limit the execution time of query, please let me know.

**Comment by koskimas** [comment]
We won't support MySQL optimizer hints. That's a whole another language and only works on MySQL.

**Comment by koskimas** [comment]
@rurruur Actually I was wrong, you CAN already do this: https://kyse.link/?p=s&i=9M4EZLxzkCkjrUqDAhZV

**Comment by koskimas** [comment]
Here's a cleaner pattern https://kyse.link/?p=s&i=cK2ZWx8EA5lTlgXZj3Iw

**Comment by koskimas** [comment]
Here's a cleaner pattern https://kyse.link/?p=s&i=nj62YVgjRoZUSVUlZWMC

**Comment by rurruur** [comment]
Thanks! 👍
