### ISSUE TITLE
Add "NULLS NOT DISTINCT" support

### ISSUE THREAD

**Issue by cesek-navisys** [kysely-org/kysely#711]
PostgreSQL v15 supports NULLS NOT DISTINCT statement. Please add it (as optional) when creating unique constraints or indexes.

**Comment by koskimas** [comment]
We should probably add two methods `nullsNotdDistinct()` and `nullsDistinct()`.

**Comment by viraxslot** [comment]
Hi all, started researching this one. I'd like to implement it.
