### ISSUE TITLE
Several levels whereRef for nested jsonObjectFrom / jsonArrayFrom calls

### ISSUE THREAD

**Issue by Amuleus** [kysely-org/kysely#712]
Use-case: Kysely selection with nested `jsonObjectFrom`  structure like Order->Route->Carrier

Problem: `whereRef` is not aware about outer `jsonObjectFrom`

Problematic query:
```
const result = await ksldb
    .selectFrom("order")
    .select((eb) => [
      "id",
      'status',
      "createdAt",
      "routeId",
      jsonObjectFrom(
        eb
          .selectFrom("route")
          .select([
            "route.id",
            "route.name",
            jsonObjectFrom(
              eb
                .selectFrom("carrier")
                .select(["carrier.id"])
                .whereRef("carrier.id", "=", "route.carrierId"), // <-- problem here that `route` is outer `jsonObjectFrom` subquery result
            ).as("carrier"),
          ])
          .whereRef("route.id", "=", "order.routeId"),
      ).as("route"),
    ])
    .where("id", "=", id)
    .executeTakeFirst();

```

Line `.whereRef("carrier.id", "=", "route.carrierId"),` gives TypeScript error:
`Argument of type '"route.carrierId"' is not assignable to parameter of type 'ReferenceExpression<DB, "order" | "carrier">'`

1) does Kysely support or is going to support in the future nested `whereRef` aware of outer `jsonObjectFrom` scope?

2) if I need several levels deep `whereRef` now, how would I write a custom Postgres utility function to be able `inner jsonObjectFrom subquery` to reference fields from `outer jsonObjectFrom subquery`? Preferably in a type-safe way, but if no chance than any way would be fine.

3) if 1-2 not possible, how would write semi-raw multi-level nested jsonObjectFrom subquery?

I'm aware it's possible to do regular join of Order to Route to Carrier and then subquery `jsonObjectFrom` carrier on the top-level, but want to know about possibility of referencing nested `jsonObjectFrom` and later `jsonArrayFrom` as well.

**Comment by Amuleus** [comment]
As for now I stopped on join Order to Route to Carrier like:

```
const result = await ksldb
    .selectFrom("order")
    .leftJoin("route as jointRoute", "jointRoute.id", "order.routeId") // Join the 'route' table
    .leftJoin(
      "carrier as jointCarrier",
      "jointCarrier.id",
      "jointRoute.carrierId",
    )
    .select((eb) => [
      "order.id",
      "order.createdAt",
      "order.routeId",
      jsonObjectFrom(
        eb
          .selectFrom("route")
          .select(["route.id", "route.name"])
          .whereRef("route.id", "=", "order.routeId"),
      ).as("route"),
      jsonObjectFrom(
        eb
          .selectFrom("carrier")
          .select(["id", "name"])
          .whereRef("carrier.id", "=", "jointRoute.carrierId"),
      ).as("carrier"),
    ])
    .where("order.id", "=", id)
    .executeTakeFirst();
    ```
    
    but question about  nested `whereRef` is still actual.

**Comment by koskimas** [comment]
You need to use the callback version of the select function to get a new `eb` in the nested calls. The outer `eb` doesn't know about inner subqueries.

**Comment by koskimas** [comment]
Like this (wasn't on the computed before)

```ts
const result = await ksldb
  .selectFrom("order")
  .select((eb) => [
    "id",
    'status',
    "createdAt",
    "routeId",
    jsonObjectFrom(
      eb.selectFrom("route")
        .select((eb) => [
          "route.id",
          "route.name",
          jsonObjectFrom(
            eb.selectFrom("carrier")
              .select(["carrier.id"])
              .whereRef("carrier.id", "=", "route.carrierId"),
          ).as("carrier"),
        ])
        .whereRef("route.id", "=", "order.routeId"),
    ).as("route"),
  ])
  .where("id", "=", id)
  .executeTakeFirst();
```
