### ISSUE TITLE
Inconsistent behavior using 'orderBy' with jsonArrayFrom

### ISSUE THREAD

**Issue by SWatchmaker** [kysely-org/kysely#715]
Hi!

I'm having trouble orderBy inside jsonArraFrom . If  i try the code below, i can fetch the rows but in an incorrect order.

```typescript
export function withPlayers(eb: ExpressionBuilder<Database, 'ladder'>) {
  return jsonArrayFrom(
    eb
      .selectFrom('user_ladder')
      .innerJoin('user', 'user.id', 'user_ladder.user')
      .select([
        'user_ladder.position',
        'user_ladder.user',
        'user_ladder.ladder',
        'user_ladder.createdAt',
        'user.firstName',
      ])
      .whereRef('ladder.id', '=', 'user_ladder.ladder')
      .orderBy('user_ladder.position')
  ).as('players');
}
```

The weird thing is that i can fetch the rows in the correct order if i remove the 'user' table inner join (maybe that case is not implemented) but also have to remove the 'user_ladder.createdAt' column from the select.

I'm using MySql dialect with PlanetScale. I checked using the generated query for the not working cases directly on my SQL manager (DBeaver) and it works perfectly.

**Comment by koskimas** [comment]
MySql doesn't have a json function that would allow `jsonArrayFrom` implementation that'd preserve the order. When you get the order you want, it's pure luck. The `json_arrayagg` function used by `jsonArrayFrom` returns the items in undefined order. I have no idea why MySQL made that design choice 🤷

**Comment by hanssonduck** [comment]
Hi @koskimas what do you think about this solution? https://stackoverflow.com/a/63282137/10055887
Not sure about its performance but maybe this could be added to the utility function?
