### ISSUE TITLE
Limit method should accept subqueries

### ISSUE THREAD

**Issue by xbjfk** [kysely-org/kysely#719]
In PostgreSQL at least, you can pass a subquery to the `LIMIT` keyword. The `limit` method in kysely should take subqueries too.

**Comment by koskimas** [comment]
I think postgres accepts any expression that's not dependent of individual rows. So subqueries are fine as long as they are not correlated subqueries.

We can't check this on the type level so I think the best solution is to just allow any expression, even though may expressions will fail.
