### ISSUE TITLE
Possible to abstract out transaction management?

### ISSUE THREAD

**Issue by sampbarrow** [kysely-org/kysely#722]
I was wondering if it would be possible to abstract out transaction management, in a similar manner to how there's currently a "QueryExecutor" interface and a default implementation.

I've come across a number of instances where it would be useful to wrap the entire transaction in some kind of logic depending on the way the database connection is handled.

Web locks are a good use case for this when it's being used in the browser. The web locks api allows you to run a block of async code within a global lock across all tabs.

```
navigator.locks.request("my_resource", async (lock) => {
  // The lock has been acquired.
  await do_something();
  await do_something_else();
  // Now the lock will be released.
});
```

Sqlite in the browser (now officially supported by sqlite) generally requires a worker, and works off of one global connection, so transaction management is a little bit trickier to deal with than with most drivers - you have to do some kind of in-application locking. Web locks being the best way I've found.

You can work around this type of call by using the transaction related methods on the driver class, passing a new promise, storing the resolve callback in a variable, then calling it later, but it's a bit hacky and more bug prone.

So this would involve a new interface, TransactionExecutor, with one method, `async execute<T>(callback: (trx: Transaction<DB>) => Promise<T>): Promise<T>`

The Kysely class would hold an instance of this, like it currently holds a QueryExecutor, which would be passed to TransactionBuilder on creation. A call to its execute method would replace lines 554-574 of Kysely.ts (that logic would be moved to a DefaultTransactionExecutor which would hold references to the objects it needs such as QueryExecutor). 

The DefaultTransactionExecutor class would be the default implementation when creating a new Kysely, so this would be optional and wouldn't be a breaking change.

Thoughts? I can (probably) do the code but I wanted to see if this would be something you'd be willing to implement.

**Comment by koskimas** [comment]
If you need something like this, a custom dialect is the way to go.
