### ISSUE TITLE
Question: is there any documentation on how to use count?

### ISSUE THREAD

**Issue by capaj** [kysely-org/kysely#727]
as per title. I would expect such a basic feature would get mentioned in the docs with at least a few examples.

**Comment by koskimas** [comment]
https://kysely.dev/docs/examples/SELECT/function-calls
https://kysely-org.github.io/kysely-apidoc/interfaces/FunctionModule.html#count

Or just hover over the method in the IDE.

If you mean how count works in SQL, it's not our job to teach the users SQL.
