### ISSUE TITLE
Feature Request: SQL.js support

### ISSUE THREAD

**Issue by kaorun343** [kysely-org/kysely#728]
SQL.js doesn't depends on node native modules. 
Therefore, compared to other sqlite packages like better-sqlite3, there're some benefits to use this library:
- It can be used at browser.
- It can be used at Electron's main process without rebuilding native modules.

I hope that SQL.js will be supported officially.

- https://github.com/sql-js/sql.js/
- https://sql.js.org/#/

**Comment by koskimas** [comment]
This would make a great third party dialect but we won't support something like this in the core.
