### ISSUE TITLE
Feature idea: forcing `WHERE` or an alternative for writes.

### ISSUE THREAD

**Issue by Schoonology** [kysely-org/kysely#734]
I run a small team, and we hit a production issue where an innocuous-looking query erased data during an `UPDATE` because `WHERE` was missing. My intent is to update Kysely to make this less likely, and I'd like to do so by _forcing_ one of two things before `execute` will run.

- You have provide a variant of `WHERE`.
- You have _explicitly_ called some new function, e.g. `updateAll()` or what-have-you, that makes clear you _intend_ to update every row in the table.

I intend to do something like this in a fork, but I would _prefer_ to do so in a way that's useful to others and/or amenable for merging upstream.

So the real "issue" is a discussion about how best to make this happen.

- I see adding a sort of configuration alongside the connection string, "safe mode", that opts in to this behaviour.
- There's some internal, mutable state required to know if a write is "safe", which is set by, say, `where` and `updateAll`.
- I'll take any and all naming suggestions.

**Comment by koskimas** [comment]
This has come up many times. It's not a query builder's job to prevent people from doing this kind of mistakes. Kysely tries to prevent you from writing invalid queries (when possible) but any valid query is ok. If you want to guard your team from making catastrophic mistakes, you should probably use an ORM of some sort.
