### ISSUE TITLE
official integration with Zod

### ISSUE THREAD

**Issue by matthiasfeist-foodfacts** [kysely-org/kysely#737]
Hi.

I love Kysely and use it in a bunch of projects. By accident I stumbled upon Drizzle which seems similar but not quite as mature. One nice thing that project has though is a quite nice integration with Zod: https://orm.drizzle.team/docs/zod
Are there any plans to introduce something like that in Kysely as well?

**Comment by koskimas** [comment]
There's no plan to add zod integration. I think there are some users that use zod with kysely. It's worth asking around in discord.
