### ISSUE TITLE
Queries with functions confuse Webstorm

### ISSUE THREAD

**Issue by esafak** [kysely-org/kysely#738]
When I use selects with expressions Webstorm complains about unresolved variables in the response:

```typescript
const result = await db
	.selectFrom('person')
	.select(({ eb }) =>
		eb(eb.fn.count('id'), '>', 0).as('email_exists')
	).executeTakeFirst()
result?.email_exists ?? false
```

[Playground Link](https://kyse.link/?p=b&i=haFkpW15c3FsoXamMC4yNi4zoXPaAaJpbXBvcnQgeyBHZW5lcmF0ZWQgfSBmcm9tICdreXNlbHknCgpkZWNsYXJlIGdsb2JhbCB7CiAgaW50ZXJmYWNlIERCIHsKICAgIHBlcnNvbjogUGVyc29uVGFibGUKICAgIHBldDogUGV0VGFibGUKICB9CgogIGludGVyZmFjZSBQZXJzb25UYWJsZSB7CiAgICBpZDogR2VuZXJhdGVkPHN0cmluZz4KICAgIGZpcnN0X25hbWU6IHN0cmluZwogICAgbGFzdF9uYW1lOiBzdHJpbmcgfCBudWxsCiAgICBjcmVhdGVkX2F0OiBHZW5lcmF0ZWQ8RGF0ZT4KICAgIGFnZTogbnVtYmVyCiAgfQoKICBpbnRlcmZhY2UgUGV0VGFibGUgewogICAgaWQ6IEdlbmVyYXRlZDxzdHJpbmc-CiAgICBuYW1lOiBzdHJpbmcKICAgIG93bmVyX2lkOiBzdHJpbmcKICAgIHNwZWNpZXM6ICdjYXQnIHwgJ2RvZycKICAgIGlzX2Zhdm9yaXRlOiBib29sZWFuCiAgfQp9oXHZjGNvbnN0IHBlcnNvbiA9IGF3YWl0IGRiCgkuc2VsZWN0RnJvbSgncGVyc29uJykKCS5zZWxlY3QoKHsgZWIgfSkgPT4KCQllYihlYi5mbi5jb3VudCgnaWQnKSwgJz4nLCAwKS5hcygnZW1haWxfZXhpc3RzJykKCSkuZXhlY3V0ZVRha2VGaXJzdCgpoWPC)

![Screenshot 2023-10-19 at 17 08 56](https://github.com/kysely-org/kysely/assets/3928300/83748761-f870-41a3-8bf7-b00997a00d4d)

I note that the inferred type (via _Specify type explicitly_) is `any`, while the inlay hint type is correct: `{email_exists: SqlBool} | undefined`. What is causing this mismatch? See also #190.

**Comment by koskimas** [comment]
You need to wrap the selections to an array when you use the callback version

**Comment by esafak** [comment]
1. Is that documented?
2. It did not seem to make a difference, in the playground or in Webstorm.

**Comment by koskimas** [comment]
> Is that documented
Yes it is.

It works in the playground I wrote. See the previous message.
