### ISSUE TITLE
[Question] Graceful shutdown with transactions in progress

### ISSUE THREAD

**Issue by maslennikov** [kysely-org/kysely#740]
Hello! This question is possibly related to #257. 

I run a fastify server serving multiple requests which trigger transactions spanning multiple services.

Currently, for each request I have a transaction instance stored in node [async local storage](https://nodejs.org/api/async_context.html) like that
```js
    // inside service method triggered by endpoint controller
    this.db.transaction().execute(async (tx) =>
      txContext.run(tx, async () => {
        // do stuff, call services
      })
    )
```

And I have a global server hook to track `onClose` event to execute shutdown routines. From within that hook transaction objects won't be accessible because it is run in async context different from those of requests. I rely on simply calling `db.destroy()` instead.

 **Question**: is it enough to just call `db.destroy()` to rollback all running transactions or should I somehow orchestrate the shutdown to await/abort all pending tx-es?

**Comment by koskimas** [comment]
Yes, it's enough to just call `db.destroy()` on built-in dialects. We have no control over third party dialects. So if you're using one of those, open an issue in their github.

**Comment by paynecodes** [comment]
@maslennikov I'm looking to do something similar by creating an `HttpRequestContext` using `AsyncLocalStorage`. Can you share more of the code surrounding that?
