### ISSUE TITLE
Executing raw SQL requires compilation step

### ISSUE THREAD

**Issue by DarkMio** [kysely-org/kysely#741]
I have a pretty innoscent daily scheduled task that used to work in a prior version in SQLite:

```ts
const maintenanceTask = (db: Kysely<any>) => {
    sql`VACUUM`.execute(db);
}
```

which now fails with:

```log
Oct 20 13:19:14 debian-4gb-nbg1-1 bun[985596]:  8 | export class NoopQueryExecutor extends QueryExecutorBase {
Oct 20 13:19:14 debian-4gb-nbg1-1 bun[985596]:  9 |     get adapter() {
Oct 20 13:19:14 debian-4gb-nbg1-1 bun[985596]: 10 |         throw new Error('this query cannot be compiled to SQL');
Oct 20 13:19:14 debian-4gb-nbg1-1 bun[985596]: 11 |     }
Oct 20 13:19:14 debian-4gb-nbg1-1 bun[985596]: 12 |     compileQuery() {
Oct 20 13:19:14 debian-4gb-nbg1-1 bun[985596]: 13 |         throw new Error('this query cannot be compiled to SQL');
Oct 20 13:19:14 debian-4gb-nbg1-1 bun[985596]:                   ^
Oct 20 13:19:14 debian-4gb-nbg1-1 bun[985596]: error: this query cannot be compiled to SQL
Oct 20 13:19:14 debian-4gb-nbg1-1 bun[985596]:       at compileQuery (/opt/some-software/node_modules/kysely/dist/esm/query-executor/noop-query-executor.js:13:14)
Oct 20 13:19:14 debian-4gb-nbg1-1 bun[985596]:       at /opt/some-software/node_modules/kysely/dist/esm/raw-builder/raw-builder.js:41:37
Oct 20 13:19:14 debian-4gb-nbg1-1 bun[985596]:       at execute (/opt/some-software/node_modules/kysely/dist/esm/raw-builder/raw-builder.js:39:18)
Oct 20 13:19:14 debian-4gb-nbg1-1 bun[985596]:       at maintenanceTask (/opt/some-software/src/database/datastore/index.ts:8:4)
```

## Additional infos

This (possibly?) used to work (in a slightly different environment in Node) under `0.23.5`, but seems not to work with `0.26.3`. The prior environment threw no errors, but since the code base of that isn't mine, it's possible that it just silently caught errors.

Additionally I've written my own SQLite bun driver, but don't see why it wouldn't work in this case.

**Comment by wirekang** [comment]
It would be great if you provide the source code of your own driver.

**Comment by kwright02** [comment]
@wirekang please provide your code to your customer dialect / driver, otherwise please close your issue

**Comment by DarkMio** [comment]
The driver is very boring and more or less copy-paste from the sqlite driver, just with bun-specific symbols (or rather type decls) to work correctly: https://gist.github.com/DarkMio/d76e4db61fe61ce3e8d09b1228622848

**Comment by DarkMio** [comment]
Oh man, I slept on that one. The error is misleading, because the passed DB object was null:

```log
Nov 02 08:46:56 debian-4gb-nbg1-1 bun[985596]:  6 |
Nov 02 08:46:56 debian-4gb-nbg1-1 bun[985596]:  7 | const maintenanceTask = (db: Kysely<any>) => {
Nov 02 08:46:56 debian-4gb-nbg1-1 bun[985596]:  8 |     const query = CompiledQuery.raw("VACUUM");
Nov 02 08:46:56 debian-4gb-nbg1-1 bun[985596]:  9 |     db.executeQuery(query);
Nov 02 08:46:56 debian-4gb-nbg1-1 bun[985596]:         ^
Nov 02 08:46:56 debian-4gb-nbg1-1 bun[985596]: TypeError: undefined is not an object (evaluating 'db.executeQuery')
Nov 02 08:46:56 debian-4gb-nbg1-1 bun[985596]:       at maintenanceTask (/opt/some-software/src/database/datastore/index.ts:11:4)
```

This error is much clearer and then explains why the query does not pass the compile step of the DB driver. The error was caused by an innocent `setInterval(maintenanceTask, 5000);` - which obviously is missing the function parameter.

Sorry for the confusion, maybe something can be done about the thrown error tho?

**Comment by omaksi** [comment]
Same thing happened to me, and I agree that the error messages in the noop-query-executor could maybe be made clearer, indicating that a proper query executor wasn't provided. I could create a PR for this, if you think it's worthwhile.
