### ISSUE TITLE
Serverless and RDS Proxy Support

### ISSUE THREAD

**Issue by joshstrange** [kysely-org/kysely#744]
Is anyone using Kysely with RDS Proxy? I’m currently using Prisma and PlanetScale but I’d like to migrate to Kysely and then RDS Aurora (MySql Compatible) because it’s cheaper to scale and I can have multiple databases on a single cluster (my app is single tenant, right now I’m paying for 1 PlanetScale DB per customer). 

My backend is lambda so it’s my understanding that I’d overwhelm the RDS DB if I let all of them connect directly so I was looking into RDS Proxy. Prisma does not work well with RDS Proxy due to its use of "SET" calls and prepared statements which cause RDS Proxy to pin the connection to the client that used the "SET" command or prepared statement, which makes the proxy absolutely useless.

I saw [this](https://github.com/kysely-org/kysely/issues/114) issue that says Kysely does use prepared statements but it's literally the only reference I can find about this. I'm considering spinning up a test project to just figure it out myself but I was hoping someone could shed some light on this and maybe this issue could help the next person like me who is searching for this information.

I'm wondering if anyone else is using Kysely with RDS Proxy and what their experience with it is. Or using Kysely in a serverless environment with RDS at all. Kysely looks very cool and refreshingly lightweight after all we've dealt with in Prisma, we'd love to switch to it. 

Thank you!

**Comment by rcoundon** [comment]
We went in the other direction, we used to use RDS and moved to PlanetScale. 
However, when used RDS from lambda we used this library with success - https://www.npmjs.com/package/serverless-mysql
Now, I haven't used this in conjunction with Kysely but it could be possible.

**Comment by joshstrange** [comment]
@rcoundon I absolutely _love_ PlanetScale but the pricing is just too much since I have to pay for 1 DB per-customer. On RDS I can run multiple databases on one cluster and since my customer have spiky-demand that doesn't overlap I can share the cluster without issue.

The "Scalar" plan on PlanetScale is equivalent to the PS-10 (0.125 vCPU and 1 GB RAM) which is really wimpy and for ~$70/mo (using reserved 3 year, partial upfront) I can get 2 vCPU and 8 GB Ram (db.t4g.large) on RDS Aurora (16x and 8x respectively).

Again, I love PlanetScale and I started when their only options were Scalar or Enterprise and I was under the impression that since you paid for read/write/storage on Scalar that it would scale to whatever you needed. I don't know if that changed or was never the case but now my instances are having trouble keeping up with what aren't that heavy of queries.

I'm going to do a full test with prod data/load on RDS before moving but the savings and higher performance are too much to ignore completely.

**Comment by rcoundon** [comment]
I'd recommend you get in touch with their support, they've been very helpful for us for all kinds of questions from query structure to billing, PlanetScale capabilities (deploy requests, branching etc) and even custom plans.
Funnily enough, I upgraded our plan and our monthly price went down due to not having overage. 
Before you move off it, I suggest you have a chat with them about options, they might be able to come up with something cost effective for you. We found the maintenance and set up to make use of RDS _much_ higher than with PlanetScale. 
No more VPCs or NAT Gateways!!

**Comment by joshstrange** [comment]
@rcoundon That's fair and I have talked with their support and their CEO even. I've talked extensively on HackerNews about how much I like it. Trust me, I really, really don't want to go and I'll absolutely reach out to support again but last time I talked to them I mentioned this and it seemed like it wouldn't be possible, but it's worth trying. Thanks!

**Comment by rcoundon** [comment]
Fair enough, no worries. I hope you find a path and if you don't, maybe serverless-mysql might help.

**Comment by igalklebanov** [comment]
Hey 👋 

Regarding serverless-mysql, creating a custom dialect is quite straightforward. Check out the core dialects and community dialects as examples [here](https://kysely.dev/docs/dialects). Feel free to ask for help on discord if you get stuck.

**Comment by rcoundon** [comment]
I imagine this would be almost identical to that of the mysql2 driver, too.

**Comment by joshstrange** [comment]
I'm hoping to find some time this weekend to do some more testing on my RDS cluster, specifically with RDS Proxy. I'll report back here on what I find and I might implement the custom dialect for mysql-serverless as well to compare performance. Thank you both.

PS: I heard back from PlanetScale support and unfortunately they don't have a product that fits my needs which I has assumed from the start. Super nice people and I'd use them again in a heartbeat if not for my special case.

**Comment by igalklebanov** [comment]
imma close this as it's a non-issue. feel free to comment further.
