### ISSUE TITLE
fn.sum returns a string?

### ISSUE THREAD

**Issue by joshstrange** [kysely-org/kysely#749]
I'm new to Kysely and testing it out. I have a query that does:

```
...
.select(({fn}) => [
	fn.sum<number>('tableName.count').as('totalCount'),
	...
])
...
```

Now obviously I know that adding the `<number>` doesn't actually do anything but affect the type of my result after running this query but I wasn't expecting it to come back as a string. I know the default is `string | number | bigint` but I'm not quite clear on when/why it chooses the types it does. `tableName.count` is of type `int` in MySQL and is `not null`. Oddly enough I have 2 counts in this query that also say they could be `string | number | bigint` but they are coming back as numbers.

Here is the result when I dump it (column names changed but real values):

```
{ totalCount: '92521', count1: 41, count2: 11155 }
```

In Prisma I had a lot of _fun_ when my queries started randomly returning `bigint`'s when I upgraded and so I had to cast everything using `Number()` after pulling it out of the DB. Obviously I can do that here but I'd like to understand what's going on if possible instead of just papering over it. 

Thanks for any help!

**Comment by koskimas** [comment]
`sum` can produce an integer that's larger than the maximum integer a javascript number can represent (2^53-1). The result has to be a string or you might get garbage out in when summing large numbers.

Kysely doesn't touch the output types at all. Whenever you have this kind of issues, refer to the documentation of the underlying driver. If you're using the built-in `MysqlDialect` you can configure the driver's `typeCast` option: https://github.com/mysqljs/mysql#custom-type-casting

**Comment by Philipinho** [comment]
For Postgres dialect users see: https://github.com/brianc/node-postgres/issues/811

The solution is to add a type parser.
```typescript
import { Pool, types } from 'pg';
types.setTypeParser(types.builtins.INT8, (val) => Number(val));
```

Example usage:
```typescript
import { Pool, types } from 'pg'
types.setTypeParser(types.builtins.INT8, (val) => Number(val));

const dialect = new PostgresDialect({
  pool: new Pool({
    connectionString: DB_URL,
  })
})
```
