### ISSUE TITLE
Kysely Query with array of "From" with raw SQL not as documented

### ISSUE THREAD

**Issue by aviranco** [kysely-org/kysely#750]
I am using Kysely with Postgres), However applying Kysely equivalent for `FROM X, Y` does not seem to work. I would like to produce the following SQL (you can ignore the WHERE clause):
```
SELECT *
FROM
  products,
    jsonb_array_elements(products.properties#>'{someProperty}') as search_item

where cast(value as integer)=2
```

The equivalent I saw in the source code documentation (having multiple `FROM` and also raw sql is:
/node_modules/kysely/dist/esm/query-creator.d.ts:
```
import { sql } from 'kysely'

const items = await db.selectFrom([
    'person as p',
    db.selectFrom('pet').select('pet.species').as('a'),
    sql<{ one: number }>`(select 1 as one)`.as('q')
  ])
  .select(['p.id', 'a.species', 'q.one'])
  .execute()

The generated SQL (PostgreSQL):

select "p".id, "a"."species", "q"."one"
from
  "person" as "p",
  (select "pet"."species" from "pet") as a,
  (select 1 as one) as "q"
```

So I used the syntax utilizing the `sql` object like the 3rd select argument as the following:
```
const res2 = await db.selectFrom([
    'products',
    sql<{ someProperty: number }>`(jsonb_array_elements(products.properties#>'{someProperty}')`.as('search_item')
  ]).select(['products.properties', 'search_item']).execute();
```

However getting an error:
```

error: Uncaught (in promise) PostgresError: syntax error at end of input
          error = new PostgresError(parseNoticeMessage(current_message));
                  ^
    at Connection.#simpleQuery (https://deno.land/x/postgres@v0.17.0/connection/connection.ts:700:19)
    at eventLoopTick (ext:core/01_core.js:183:11)
    at async Connection.query (https://deno.land/x/postgres@v0.17.0/connection/connection.ts:949:16)
    at async PoolClient.#executeQuery (https://deno.land/x/postgres@v0.17.0/client.ts:245:12)
    at async PoolClient.queryObject (https://deno.land/x/postgres@v0.17.0/client.ts:433:12)
    at async PostgreSQLDriverDatabaseConnection.executeQuery (https://deno.land/x/kysely_deno_postgres@v0.4.0/src/PostgreSQLDriverDatabaseConnection.ts:14:12)
    at async https://esm.sh/v133/kysely@0.26.3/denonext/kysely.mjs:3:50936
    at async Or.provideConnection (https://esm.sh/v133/kysely@0.26.3/denonext/kysely.mjs:3:86791)
    at async t.executeQuery (https://esm.sh/v133/kysely@0.26.3/denonext/kysely.mjs:3:50891)
    at async t.execute (https://esm.sh/v133/kysely@0.26.3/denonext/kysely.mjs:3:58522)

```

Any idea? It seems equivalent to the docs in terms of how to have multiple terms in the `FROM` statement, also using raw sql as well. (Also if I try to add select `search_item` the type is not identified for this string.

**Comment by wirekang** [comment]
You did right except you did not close the round brackets.
`(jsonb_array_elements(products.properties#>'{someProperty}')` -> `(jsonb_array_elements(products.properties#>'{someProperty}'))`

or just `jsonb_array_elements(products.properties#>'{someProperty}')`

**Comment by aviranco** [comment]
> You did right except you did not close the round brackets. `(jsonb_array_elements(products.properties#>'{someProperty}')` -> `(jsonb_array_elements(products.properties#>'{someProperty}'))`
> 
> or just `jsonb_array_elements(products.properties#>'{someProperty}')`

Thanks, I've managed to finally find it by patching the postgres module and printing the query (if there is an easier way to print/debug kysely queries let me know:
[Thanks, I](https://stackoverflow.com/questions/77370826/kysely-query-with-array-of-from-with-raw-sql/77371100#77371100)

**Comment by wirekang** [comment]
I checked the generated sql from [playground](https://kyse.link/?p=b&i=haFkqHBvc3RncmVzoXamMC4yNi4zoXPZYWltcG9ydCB7IEdlbmVyYXRlZCB9IGZyb20gImt5c2VseSIKCmRlY2xhcmUgZ2xvYmFsIHsKICBpbnRlcmZhY2UgREIgewogICAgW3g6IHN0cmluZ106IGFueQogIH0KfQqhcdnbaW1wb3J0IHsgc3FsIH0gZnJvbSAia3lzZWx5IgoKZGIuc2VsZWN0RnJvbShbCiAgInByb2R1Y3RzIiwKICBzcWw8ewogICAgc29tZVByb3BlcnR5OiBudW1iZXIKICB9PmAoanNvbmJfYXJyYXlfZWxlbWVudHMocHJvZHVjdHMucHJvcGVydGllcyM-J3tzb21lUHJvcGVydHl9JylgLmFzKAogICAgInNlYXJjaF9pdGVtIiwKICApLApdKQogIC5zZWxlY3RBbGwoKQogIC5leGVjdXRlKCkKoWPD).

**Comment by aviranco** [comment]
> I checked the generated sql from [playground](https://kyse.link/?p=b&i=haFkqHBvc3RncmVzoXamMC4yNi4zoXPZYWltcG9ydCB7IEdlbmVyYXRlZCB9IGZyb20gImt5c2VseSIKCmRlY2xhcmUgZ2xvYmFsIHsKICBpbnRlcmZhY2UgREIgewogICAgW3g6IHN0cmluZ106IGFueQogIH0KfQqhcdnbaW1wb3J0IHsgc3FsIH0gZnJvbSAia3lzZWx5IgoKZGIuc2VsZWN0RnJvbShbCiAgInByb2R1Y3RzIiwKICBzcWw8ewogICAgc29tZVByb3BlcnR5OiBudW1iZXIKICB9PmAoanNvbmJfYXJyYXlfZWxlbWVudHMocHJvZHVjdHMucHJvcGVydGllcyM-J3tzb21lUHJvcGVydHl9JylgLmFzKAogICAgInNlYXJjaF9pdGVtIiwKICApLApdKQogIC5zZWxlY3RBbGwoKQogIC5leGVjdXRlKCkKoWPD).

Thank you. I didnt know how to import the `sql` in the playground, but I will use it from now on🤘
