### ISSUE TITLE
Better Documentation on Error Handling in Migration

### ISSUE THREAD

**Issue by jan9won** [kysely-org/kysely#752]
I had some confusions while using this library's migration feature for the first time.
I think following changes will help beginners.

1. Add Section "Error Handling" in "Migrations" Page 

    I agree on the design choice of `Migrator`'s methods not throwing error and rather returning useful informations.
However, the documentation should be explicitly emphasizing that the Migration methods won't throw.
Many people would first expect that the method will throw when query errors.

2. Add Documentation on Error Subclasses Like `SqliteError`

    I was first confused because the error object returned by `CreateTableBuilder.execute()` method did not have error message on the top level. I only saw `{ code : 'SQLITE_ERROR' }`, and there was no documentation about this Class. I suggest to add documentation on those interfaces (e.g., add link to the superclass `Error` in official NodeJS docs), or just compose custom error object using Error rather than inheriting from it.

By the way, thank you for a nice library.
It really helps me for projects with SQLite3.

**Comment by koskimas** [comment]
1. It's literally the first sentence in the documentation. How do you want us to make it more clear. https://kysely-org.github.io/kysely-apidoc/classes/Migrator.html#migrateToLatest

2. The error subclasses come from the underlying drivers. We should document that instead.

**Comment by jan9won** [comment]
1. I didn't mentioned it clearly. I meant in [readme](https://kysely.dev/docs/migrations) documentation, not in API docs. 
2. Thank you

**Comment by kwright02** [comment]
@jan9won if you have specific wording you're looking for the docs to have, fork the repo, make the edits you think should be done, then open a pull request.

Please close this issue
