### ISSUE TITLE
Missing Where Operator "->"

### ISSUE THREAD

**Issue by aviranco** [kysely-org/kysely#753]
When dynamically creating where clauses, using "->" operator to access inner jsonb field:
```
eb(columnName, '->', propertyName);
```

Eventhough it generates the correct sql query, it seems the Types don't have this operator declared in the list:
```
export declare const OPERATORS: readonly ["=", "==", "!=", "<>", ">", ">=", "<", "<=", "in", "not in", "is", "is not", "like", "not like", "ilike", "not ilike", "@>", "<@", "?", "?", "?&", "!<", "!>", "<=>", "!~", "~", "~*", "!~*", "exists", "not exists", "&&", "||", "@@", "@@@", "!!", "<->"];

```

Is it a "bug" that the type should be added, or there is a better approach?

**Comment by igalklebanov** [comment]
Hey 👋

See [JSON traversal](https://github.com/kysely-org/kysely/releases/tag/0.26.0) section and the linked pull request.

**Comment by aviranco** [comment]
Thank you!

By the way, when implemented dynamically (e.g. variable instead of a specific table) there is an error claiming cannot convert string to never:

```
function func({eb, ref, or, and} = ExpressionBuilder<DB, any>) {
// Here the types are both string, however there is an error claiming cannot convert string to never
       ref(columnName, '->').key(propertyName as never);
}
```

Therefore I see the way to use it is by converting to `never`, I guess its because it cannot match a specific key due to the "any" defined instead of a specific table.  Let me know if there is more elegant way of utilizing the kysely functionality in a generic way without adding like "as never" to where clauses etc.
