### ISSUE TITLE
Insert into select from values

### ISSUE THREAD

**Issue by entropitor** [kysely-org/kysely#755]
I don't see how one can do `select from values` which is needed for e.g. https://brunoscheufler.com/blog/2020-02-08-conditional-inserts-in-postgres. I can see how to do [the select subexpression for the insert](https://github.com/kysely-org/kysely/issues/674) but not how to select from values 

```sql
INSERT INTO "transaction" (
  "id",
  "amount",
  "from",
  "to"
)
-- Look at that! We don't have to add VALUES directly;
-- instead, we can add a SELECT statement to get the data
-- we want to insert
SELECT * FROM (
  VALUES (
    gen_random_uuid(),
    10.0,
    "89af7957-aacc-416c-8ecd-97c93150c223",
    "a64fb583-3533-4dca-a014-154dbf5d67a4"
  )
-- this is just to tell Postgres that the data types between the
-- INSERT columns and VALUES match up
) AS t (uuid, numeric, uuid, uuid)
-- And we can even filter that data to make sure
-- the balance is greater or equal the transaction
-- amount we're trying to insert. If this check
-- turns out negative, we won't insert _anything_.
WHERE (
  SELECT "balance"
  FROM "account"
  WHERE "id" = '89af7957-aacc-416c-8ecd-97c93150c223'
) >= 10.0
```

**Comment by kwright02** [comment]
How is writing it like this more useful than writing like this:

`sql

INSERT INTO "transaction" (
  "id",
  "amount",
  "from",
  "to"
)
-- Look at that! We don't have to add VALUES directly;
-- instead, we can add a SELECT statement to get the data
-- we want to insert
 VALUES (
    gen_random_uuid(),
    10.0,
    "89af7957-aacc-416c-8ecd-97c93150c223",
    "a64fb583-3533-4dca-a014-154dbf5d67a4"
)
-- And we can even filter that data to make sure
-- the balance is greater or equal the transaction
-- amount we're trying to insert. If this check
-- turns out negative, we won't insert _anything_.
WHERE (
  SELECT "balance"
  FROM "account"
  WHERE "id" = '89af7957-aacc-416c-8ecd-97c93150c223'
) >= 10.0
`

**Comment by entropitor** [comment]
AFAIK and AFAICT (*) that's not valid SQL. Or at least not in postgres: https://www.postgresql.org/docs/current/sql-insert.html

You can insert either `DEFAULT VALUES`, `VALUES (...)` or the result of a query. You cannot provide `WHERE` clauses to the insert itself. SELECT queries do support it but then you have to select from literal values instead of a table

(* I quickly tried the query above and I get `ERROR:  syntax error at or near "WHERE"`)

**Comment by koskimas** [comment]
There's no built-in `values` function, but you can do something like this https://kyse.link/?p=s&i=xVNtsu4NKPQQWCtbU4ij

Or write your own `values` helper.

**Comment by entropitor** [comment]
I was able to piece together this expression but ultimately had to abandon this idea as it causes some issues with conversion (i.e. I have uuids and the literal values are interpreted as string so the insert values with a conversion error: `error: column "id" is of type uuid but expression is of type text`)

```ts
export class FromValuesExpression<DB, TB extends keyof DB, T>
  implements Expression<T>
{
  constructor(private readonly values: Array<InsertObject<DB, TB>>) {}

  get expressionType(): T | undefined {
    return undefined;
  }

  toOperationNode(): OperationNode {
    return SelectQueryNode.cloneWithSelections(
      SelectQueryNode.createFrom([
        ParensNode.create(
          ValuesNode.create(
            this.values.map((value) => {
              return ValueListNode.create(
                Object.values(value).map((fieldValue) => {
                  return ValueNode.create(fieldValue);
                }),
              );
            }),
          ),
        ),
      ]),
      [SelectionNode.createSelectAll()],
    );
  }
}

```

**Comment by echocrow** [comment]
In case anyone searching how to express `select from (values ...)` discovers this issue:

While there is still no built-in values utility, the docs actually show off a working implementation of such a helper:
- https://kysely.dev/docs/recipes/extending-kysely#a-more-complex-example
