### ISSUE TITLE
I can't use Kysely discord anymore

### ISSUE THREAD

**Issue by cesek-navisys** [kysely-org/kysely#756]
Hi, I have just noticed I don't see Kysely in my Discord servers anymore. When I try to use the invitation link again the "Unable to accept invite" shows up. Please help

**Comment by koskimas** [comment]
What's your discord username/id?

**Comment by cesek-navisys** [comment]
mike35x95x1

**Comment by koskimas** [comment]
I don't know why that's happening. Try again later?

**Comment by koskimas** [comment]
The link hasn't expired.

**Comment by cesek-navisys** [comment]
Correct! I am back. It's really weird 🤷‍♂️
