### ISSUE TITLE
Randomly query returns empty array when using Cloudflare Hyperdrive Cache

### ISSUE THREAD

**Issue by iridiumsoft** [kysely-org/kysely#760]
Hi, I am using kysely on Cloudflare worker with Hyperdrive cache. sometimes, the query starts to return an empty array and after a few minutes, it starts to return the correct result. I have tried the same query with the pg client and it always works. 

any clue on what could be wrong?

**Comment by igalklebanov** [comment]
Hey 👋

Can you share the code that was run in both cases?

**Comment by koskimas** [comment]
Closing since there's no answer.

**Comment by a-eid** [comment]
@igalklebanov @koskimas could you guys share how kysely works with hyperdrive ?
are there any docs around it ?

**Comment by igalklebanov** [comment]
Hey 👋 

Follow https://developers.cloudflare.com/hyperdrive/configuration/connect-to-postgres/#postgresjs:

1. `npm i kysely kysely-postgres-js postgres`
2. close to the link above, do something like:

```ts
import { type GeneratedAlways, Kysely } from 'kysely'
import { PostgresJSDialect } from 'kysely-postgres-js'
import postgres from 'postgres'

export interface Env {
  HYPERDRIVE: Hyperdrive;
}

// preferably generated by `kysely-codegen` or `kanel-kysely`
interface Database {
  person: {
    id: GeneratedAlways<number>
    first_name: string | null
    last_name: string | null
    age: number
  }
}

export default {
  async fetch(request: Request, env: Env, ctx: ExecutionContext) {
    const db = new Kysely<Database>({
      dialect: new PostgresJSDialect({
        postgres: postgres(env.HYPERDRIVE.connectionString)
      })
    })

    try {
      const result = await db.selectFrom('person').selectAll().limit(10).execute()

      ctx.waitUntil(db.destroy());

      return Response.json({ result });
    } catch (e) {
      console.log(e);
      return Response.json({ error: e.message }, { status: 500 });
    }
  },
} satisfies ExportedHandler<Env>;
```

**Comment by vladshcherbin** [comment]
@igalklebanov hey 👋  curious to know why you've chosen `postgres` instead of `pg`? Seems like the are [both supported](https://developers.cloudflare.com/hyperdrive/examples/connect-to-postgres/#supported-drivers)

**Comment by igalklebanov** [comment]
Are you seriously asking me about something random 8 months ago?

**Comment by a-eid** [comment]
@vladshcherbin `pg` didn't used to work. i think support was added recently.

**Comment by vladshcherbin** [comment]
@igalklebanov of course, there's so few info about the topic in the internet. I'd better give a shot by asking, especially from someone from core team 🙌

@a-eid thanks, this might be the case

All in all, I've asked because `pg` is mentioned as recommended in cloudflare docs. I've since tried both `pg` (doesn't work, has pending issue right now) and `postgres` (worked with no questions), thank you such a valuable example

**Comment by vladshcherbin** [comment]
Here's the detailed reason why `pg` is the recommended way in `cloudflare hyperdrive` - [comment](https://github.com/cloudflare/templates/pull/679#issuecomment-3006733848)

Hopefully this helps future explorers 🫡
