### ISSUE TITLE
Jsonb path to property inside a raw sql query

### ISSUE THREAD

**Issue by aviranco** [kysely-org/kysely#765]
I think the documentation is missing regarding accessing json property e.g. `tableName.columnName -> propertyName` inside a raw sql query, where the `eb` is not available to do stuff like `eb.sql.ref(..).key()...`.

Using the raw sql query inside a raw query:

```
...
  INNER JOIN (${filterQuery}) ...
...
```

This is what I tried:
```
let selectedColumn = sql`CAST(${sql.ref('products', columnName, '->', propertyName)} as numeric) as selected_value`;
```
This way it simply ignores whatever is written after the table name, trying to convert it as a whole to numeric:
`message: "cannot cast type products to numeric",`

After I remove the table name (and I want to have it anyway):
```
let selectedColumn = sql`CAST(${sql.ref(columnName, '->', propertyName)} as numeric) as selected_value`
```
It still use generate the sql query with only the first value and ignore the '->property_name':
`message: "cannot cast jsonb object to type numeric"`

Any idea?

**Comment by koskimas** [comment]
This has nothing to do with Kysely.

**Comment by koskimas** [comment]
Sorry, read that too fast. The issue here is that `sql.ref` doesn't support JSON references.
