### ISSUE TITLE
How to reference JSONB property in Kysely in raw sql?

### ISSUE THREAD

**Issue by aviranco** [kysely-org/kysely#766]
What is the way to generate in kysley to reference a property of JSONB column **inside a raw SQL (where the eb object is not accessible)**?
As the following does not build the string correctly as expected 
```
let selectedColumn = sql.ref('products', columnName, '->', propertyName);
```
generates `products` instead of `"products"."columnName"->'propertyName'`

For those who don't know what is raw sql:
```
const sqlQuery = sql`....${filterQuery} ...`
```

The previous issue was closed as "This has nothing to do with Kysely." which is a joke, I invested the time to demonstrate that kysely generate invalid result with this input, and I went through the whole sql documentation to see this scenario documented and did not see any. 

Anyway Thanks in advance!

**Comment by koskimas** [comment]
`sql.ref` doesn't support JSON references yet.
