### ISSUE TITLE
FileMigrationProvider doesn't work on Windows in ESM package

### ISSUE THREAD

**Issue by MChartier** [kysely-org/kysely#768]
Discussed on Discord here: https://discord.com/channels/890118421587578920/1149627608175214602.

When attempting to run migrations on a Windows machine from a node project using ESM modules (as opposed to commonjs), importing the migration files will fail with a `ERR_UNSUPPORTED_ESM_URL_SCHEME` error, because the import statement is expecting a path that starts with `file:///`. But then if the caller tries to provide that instead of an absolute or relative file path, `FileMigrationProvider` will construct the path incorrectly, treating the entire URL as a relative path and concatenating it with the current path, which will also fail.

This can be fixed by updating the code in `getMigrations` in `FileMigrationProvider` to something like this:

```
const migrationPath = this.#props.path.join(this.#props.migrationFolder, fileName);
const migrationFileUrl = pathToFileURL(migrationPath);
const migration = await import(migrationFileUrl.href);
```

**Comment by koskimas** [comment]
That breaks it on all other platforms.

**Comment by dangnhdev** [comment]
> That breaks it on all other platforms. Since kysely is runtime agnostic and has zero dependencies, there's no way to detect the operating system and do that conditionally.

I'm getting this issue too. At least give us a hint on how to fix this please.

**Comment by koskimas** [comment]
> I'm getting this issue too. At least give us a hint on how to fix this please.

`FileMigrationProvider` is 20 lines of code. Just copy-paste it to your project and change the relevant lines. How is that not the obvious solution? How is writing 20 lines of code an issue?

**Comment by VincentBattu** [comment]
>  Since kysely is runtime agnostic and has zero dependencies, there's no way to detect the operating system and do that conditionally.

Naive question, but can we simply use platform from 'node:process' package to achieve this?

For example (this is quick example and, of course, the process module could be passed through the props in the constructor) :
```typescript
import { platform } from 'node:process'

export class FileMigrationProvider implements MigrationProvider {
   async getMigrations(): Promise<Record<string, Migration>> {
     // ...
          const pathParts = [
            this.#props.migrationFolder,
            fileName,
          ]
          if (platform === 'win32') {
            pathParts.unshift('file://')
          }
          const migration = await import(/* webpackIgnore: true */ this.#props.path.join(...pathParts))
    // ...
}

**Comment by igalklebanov** [comment]
@VincentBattu runtime agnostic means, no dependency on NodeJS standard libraries.

**Comment by VincentBattu** [comment]
I am a bit confused because this module already relies on the "path" and "fs" modules of NodeJS (but maybe the readdir and join functions have the same signatures across all runtimes?).

In any case, why couldn't we add a "platform" [here](https://github.com/kysely-org/kysely/blob/master/src/migration/file-migration-provider.ts#L71), typed as "win32" | "linux" | "openbsd" | whatever (which falls back to "linux" to avoir backward compatibility issues)? 
```typescript
export interface FileMigrationProviderProps {
  fs: FileMigrationProviderFS
  path: FileMigrationProviderPath
  platform?: 'win32' | 'linux' | 'openbsd'
  migrationFolder: string
}
```
It is then up to the caller to provide it (or not), depending on the runtime he is using.

**Comment by igalklebanov** [comment]
Passing https://github.com/unjs/pathe as `path` to the constructor should solve this.

**Comment by igalklebanov** [comment]
Try https://github.com/kysely-org/kysely-ctl.
