### ISSUE TITLE
getting Error: relation "myschema.kysely_migration_lock" does not exist when running migrator in an existing DB

### ISSUE THREAD

**Issue by capaj** [kysely-org/kysely#774]
I am trying to use the `migrator.migrateToLatest()` to migrate in an existing DB for me and it is failing with `Error: relation "myschema.kysely_migration_lock" does not exist.`

Do I have to create the kysely tables manually to be able to run the migrator? Is this documented anywhere?
I would have expected that the migrator creates these tables when they do not exist.

EDIT: I realised now that the db I am using is not completely fresh, it has existing tables.

**Comment by capaj** [comment]
Actually tried this with a fresh DB and there it works ok.
Would be nice if I could somehow tell migrator to ignore existing tables and just create everything from scratch.
So this is more like a feature request rather than a bug. Can you please remove the "bug" label @igalklebanov ?

**Comment by koskimas** [comment]
It's pretty clearly stated [here](https://kysely-org.github.io/kysely-apidoc/interfaces/MigratorProps.html#migrationTableSchema) that you can't change the migration table schema once the migration tables are created.

You can always just delete the migration tables if you want to start from scratch.

**Comment by capaj** [comment]
@koskimas  I haven't changed the name of the migration table.
I was just trying to run migrator in a database with existing tables. I can prepare a reproduction repo if you want.
