### ISSUE TITLE
Consider splitting `values` into `values` and `valuesMany` or something similar in insert queries

### ISSUE THREAD

**Issue by koskimas** [kysely-org/kysely#778]
Currently we've overloaded a single `values` method to take both an object (single row) and an array (multiple rows). When the type of an object a user is inserting doesn't match the object overload, typescript attempts to match it with the array overload, which obviously matches even less. Then typescript shows the last error: the failed comparison with the array. Even the error highlight is misleading, showing that the first property of the object is invalid (since array doesn't have that property)

We'd get much better error messages if we moved the array overload to a separate function.

**Comment by thelinuxlich** [comment]
making it variadic doesn't fall on the same issue?

**Comment by igalklebanov** [comment]
No overload, so might report differently. Needs checking.

**Comment by igalklebanov** [comment]
Check errors tab: https://tsplay.dev/wEYJbw

**Comment by elitan** [comment]
I just wanted to slide in and say: 

Helpful error messages are 100x more important than savings on a function name due to overloading.

**Comment by igalklebanov** [comment]
> I just wanted to slide in and say: 
> 
> Helpful error messages are 100x more important than savings on a function name due to overloading.

Why not both..

**Comment by koskimas** [comment]
One issue with `values(value, ...moreValues)` is that we don't use the same pattern elsewhere. Also you can't do this:

```ts
values(eb => [])
```

instead you'd have to do this

```ts
values(eb => {}, eb => {}, eb => {}, eb => {})
```

**Comment by igalklebanov** [comment]
It's not perfect, but what about:

```ts
values(item)
values(items[0], items.slice(1))
values(eb => items[0], eb => items.slice(1).map(...))
```

**Comment by koskimas** [comment]
That has the same original issue doesn't it? If the first overload doesn't match, it tries to compare it with the function version and you'd get an error that the object is no a function?

**Comment by igalklebanov** [comment]
Having `valuesMany` rubs me the wrong way, so exploring alternatives, that's all.

**Comment by igalklebanov** [comment]
Was last exploring moving the errors deeper to something without overloads, and forcing `values` to accept that something that has a single and many variant.

Maybe if we force usage of `ExpressionBuilder` in `values` and accept a kysely-specific `eb.toTuple` and `eb.toTupleList`. This is not as easy as using `values` and `valuesMany`.

**Comment by koskimas** [comment]
The single object input needs to be there. That's by far the most used variant. Forcing a callback is not an option.

**Comment by koskimas** [comment]
We have the same issue with the `set` method in update queries. https://kyse.link/?p=s&i=wAhuvxujKYJ16wUGdr6Q

The actual error in the link above is the wrong type for dates. The error comes from the wrong overload again.

**Comment by thelinuxlich** [comment]
Because of the callback variant?

**Comment by koskimas** [comment]
Yep

**Comment by koskimas** [comment]
I looked into this some more and if we wanted good error messages, we'd need to have a separate method for every overload. The current overloads also use union types, so we'd need to have a separate method for those as well. --> Not an option.

The correct error messages actually are shown in most cases, but they're lost in the wall of error text. There's a separate error for each overload. I moved the most common overloads to last so that, in most cases, the correct error message is the last one (the one people actually read). This isn't the perfect solution and, for example, having the wrong type for a column still shows an incomprehensible message.

**Comment by koskimas** [comment]
Shitballs, had to revert that. Caused too many issues. For example we completely lost autocompletion for insert/update object columns.

**Comment by igalklebanov** [comment]
One of many related issues about this - https://github.com/microsoft/TypeScript/issues/20139#issuecomment-345788338.

Wonder if we could simply guide how to read these errors with a recipe.

**Comment by thelinuxlich** [comment]
Do you think a VSCode extension could remove the noise or it's too specific?

**Comment by thelinuxlich** [comment]
When I see this issue I understand why many languages disallow overloads.

**Comment by igalklebanov** [comment]
@thelinuxlich 

> Do you think a VSCode extension could remove the noise or it's too specific?

Well, there is `Pretty TypeScriptErrors` that attempts to show errors in a more digestible way.

**Comment by koskimas** [comment]
I think I solved this well enough for now. I have no idea why combining the overloads to a union type worked this time. I'm sure I've tried this before.

<img width="637" alt="Screenshot 2024-01-06 at 12 20 32" src="https://github.com/kysely-org/kysely/assets/846508/bc1da693-5f11-4d09-b91c-41237179ea95">
<img width="443" alt="Screenshot 2024-01-06 at 12 19 47" src="https://github.com/kysely-org/kysely/assets/846508/bf1de7bd-e44d-45d2-a552-1c04614878e3">
