### ISSUE TITLE
`group_concat` with `ORDER BY`

### ISSUE THREAD

**Issue by twiddler** [kysely-org/kysely#779]
Hey there! :wave: 

I am trying to turn my raw SQL into kysely calls. However, I am having a hard time putting an `ORDER BY` into a `group_concat` clause.

This is the result I am looking for:

```sql
SELECT
  group_concat (
    DISTINCT CASE
      WHEN foo = "1" THEN bar
      ELSE NULL
    END
    ORDER BY
      bar
  ) AS "barsWhereFooIsOne"
FROM
  "Foo"
```

This is what I got so far:

```ts
kysely
  .selectFrom("Foo")
  .select((eb) => 
    eb.fn
      .agg("group_concat",
        [
          eb.case()
            .when("bar", "=", "1")
            .then("bar")
            .else(null)
            .end()
        ]
      )
      .distinct()
      .as("barsWhereFooIsOne")
  )
  .execute()
```

It's only missing the `ORDER BY`. However, I can't find where to put `.orderBy("bar")`. No matter where I put it, I get an error:

> Property 'orderBy' does not exist on type

Here's the [playground link](https://kyse.link/?p=b&i=haFkqHBvc3RncmVzoXamMC4yNi4zoXPZmWltcG9ydCB7IEdlbmVyYXRlZCB9IGZyb20gJ2t5c2VseScKCmRlY2xhcmUgZ2xvYmFsIHsKICBpbnRlcmZhY2UgREIgewogICAgRm9vOiBGb29UYWJsZQogIH0KCiAgaW50ZXJmYWNlIEZvb1RhYmxlIHsKICAgIGZvbzogc3RyaW5nCiAgICBiYXI6IHN0cmluZwogIH0KfaFx2gFJa3lzZWx5CiAgLnNlbGVjdEZyb20oIkZvbyIpCiAgLnNlbGVjdCgoZWIpID0-IAogICAgZWIuZm4KICAgICAgLmFnZygiZ3JvdXBfY29uY2F0IiwKICAgICAgICBbCiAgICAgICAgICBlYi5jYXNlKCkKICAgICAgICAgICAgLndoZW4oImJhciIsICI9IiwgIjEiKQogICAgICAgICAgICAudGhlbigiYmFyIikKICAgICAgICAgICAgLmVsc2UobnVsbCkKICAgICAgICAgICAgLmVuZCgpCiAgICAgICAgICAgIC5vcmRlckJ5KCJiYXIiKQogICAgICAgIF0KICAgICAgKQogICAgICAuZGlzdGluY3QoKQogICAgICAuYXMoImJhcnNXaGVyZUZvb0lzT25lIikKICApCiAgLmV4ZWN1dGUoKQqhY8M=).

I'd appreciate any help. Thank you. :pray:

**Comment by igalklebanov** [comment]
Hey 👋 

There is no built-in support for `order by` outside of `over` clause in an aggregate function's arguments.

Try the following: 

```ts
kysely
  .selectFrom("Foo")
  .select((eb) =>
    eb.fn
      .agg("group_concat", [
        sql`${eb
          .case()
          .when("bar", "=", "1")
          .then("bar")
          .else(null)
          .end()} order by ${eb.ref("bar")}`,
      ])
      .distinct()
      .as("barsWhereFooIsOne"),
  )
  .execute()
```
https://kyse.link/?p=s&i=epxzshFodVoa44dfhc18

**Comment by twiddler** [comment]
Works perfectly, thank you. :pray: 

For anyone doing something similar, you can add the types like `.agg<string | null>('group_concat',`
