### ISSUE TITLE
WITH queries lose typesafety when using $if after select

### ISSUE THREAD

**Issue by thelinuxlich** [kysely-org/kysely#785]
Don't know if this a bug or expected behavior: https://kyse.link/?p=s&i=YkGTBDBQLn5RdD2wss6P
If I swap the order of the $if and select statements, it works.

**Comment by koskimas** [comment]
Seems like a clear bug. Thanks for opening the issue!

**Comment by muhammetozendev** [comment]
It seems there's no type safety even without an `$if` call. Just wanted to point that out as well. Here's an example:

(https://kyse.link/?p=s&i=6sIdEemHECvof0S9fmIr)[https://kyse.link/?p=s&i=6sIdEemHECvof0S9fmIr]
