### ISSUE TITLE
Allow alterTable with multiple renames in Kysely

### ISSUE THREAD

**Issue by lancejpollard** [kysely-org/kysely#787]
If I want to add a prefix to 10 columns in a table, I have to create 10 `db.schema.alterTable('my_table')` statements with 1 `.renameColumn('foo_x', 'bar_x')` each, rather than just one `alterTable` statement with 10 `.renameColumn`s. It would be nice to be able to avoid the code duplication for alterTable and allow multiple `renameColumn` and such multiple times, then under the hood it creates the multiple statements as necessary. Maybe there is a philosophical reason I'm not aware of for not having this feature, if so, would be curious about that!

Cheers!

**Comment by igalklebanov** [comment]
Hey 👋 

One of Kysely's main design principles is WYSIWYG (What You See Is What You Get). Thus, this functionality does not belong in the core.
