### ISSUE TITLE
Compiled query as non-enumerable property after execute()

### ISSUE THREAD

**Issue by thelinuxlich** [kysely-org/kysely#788]
I think it would be nice for debuggability if we had a option to enable a non-enumerable property(with a Symbol as key) on Kysely results with the compiled query data.

**Comment by koskimas** [comment]
I don't think this is a good idea. You can always get the compiled query by colling `compile`.

```ts
const query = db.selectFrom('person').selectAll()
const result = await query.execute()
const compiled = query.compile()
```
