### ISSUE TITLE
Date is Incompatible with ColumnType<Date>

### ISSUE THREAD

**Issue by aq1** [kysely-org/kysely#789]
I have something like this

```typescript
import { type Generated } from "kysely"

interface User {
  id: string
  createdAt: Generated<Date> // same with  ColumnType<Date>
}

const f = (u: User) => {
  return u
}

f({id: "id", createdAt: new Date()})
```

```
tsc -V
Version 5.1.3

tsc test.ts 
test.ts:12:15 - error TS2739: Type 'Date' is missing the following properties from type 'Generated<Date>': __select__, __insert__, __update__
```
Any help will be appreciated.

**Comment by igalklebanov** [comment]
Hey 👋 

You're not supposed to use the type with the `Generated` columns in anything beyond what you provide to `Kysely`. Use `Selectable<User>` instead.

**Comment by aq1** [comment]
Thank you very much

**Comment by benheckmann** [comment]
I'm using codegen `prisma-kysely`.

Prisma schema:
```ts
model EmailProvider {
  // ...
  createdAt    DateTime @default(now())
}
```

Kysely types:
```ts
export type EmailProvider = {
    // ...
    createdAt: Generated<Timestamp>;
};
```

I need / want to use the whole EmailProvider object as a function argument and as a type in general. Is there no clean way to do this?

**Comment by igalklebanov** [comment]
Hey @benheckmann 👋 

Did you go over https://kysely.dev/docs/getting-started ?

**Comment by benheckmann** [comment]
Hi!

I probably did a while ago, but I seem to have missed this.

So I would use `Selectable<EmailProvider>` in this case?
