### ISSUE TITLE
Writing Unit Test

### ISSUE THREAD

**Issue by vnijat93** [kysely-org/kysely#801]
**This is NOT an issue but more of crying for help**

We are using Kysely for an enterprise API using AWS Lambda and AWS Aurora (Postgres). One of the requirement is having unit test coverage of at least 80%.

Kysely is AWESOME, but i have been struggling with writing unit tests. (I'm new to Typescript btw). These unit test will run on jenkins, so no Postgres database for us to connect to. I figured that I might need to mock certain calls but don't know how.

One of my functions look like this:
```
const dialect = new PostgresDialect({ pool: new Pool(databaseConfig)})
const DB = new Kysely<Database>({ dialect })
const results = await DB.withSchema("database_schema")
    .selectFrom("table")
    .where('someId', '=', queryParamSomeId)
    .where('anotherId', '=', queryParamAnotherId)
    .selectAll()
    .execute()
```

Does anyone have any example that I can learn from?

**Comment by igalklebanov** [comment]
Hey 👋 

Ideally, you'd want to do integration tests against real engines - by spinning up a docker image. See Kysely's node.js tests for reference.

**Comment by francescovenica** [comment]
Given something like:
```
export const db = new Kysely<DB>({
  dialect: new PostgresDialect({  pool: new Pool()  }),
  plugins: [new CamelCasePlugin()],
});

export const fetchAccount = () => db.selectFrom("account").executeTakeFirst()

```

I'm able to unit test the function and check that the query is correct
```
const mocks = vi.hoisted(() => ({ query: vi.fn() }));

vi.mock("@/db", () => ({
  __esModule: true,
  ownerDb: new Kysely<DB>({
    dialect: new PostgresClientDialect({  client: mocks  }),
    plugins: [new CamelCasePlugin()],
  }),
}));

it("query", async () => {
    mocks.query.mockResolvedValue({ rows: [{ .... }] });
    await fetchAccount();
    expect(mocks.query.mock.calls).toMatchInlineSnapshot("here you will see the query");
  });


```

**Comment by thelinuxlich** [comment]
But is it useful?

**Comment by francescovenica** [comment]
as unit test I would say yes....if I have a function that create a user and a subscription, something like:

```
export const createAccount = async () => {
  await db.insert("account").executeTakeFirst() 
  await db.insert("subscription").executeTakeFirst()
}
```

I want to be sure that calling this `createAccount()` will run 2 particular queries.... 

Obviously for integrations test we shouldn't mock the connection and just connect to a real db (like wrote in first comment)

**Comment by thelinuxlich** [comment]
Then why unit test if the integration test will cover the same field and more?

**Comment by francescovenica** [comment]
mmm maybe it is just a limitation for my experience...but usually I do unit test to be sure that a piece of code does what is meant to do and integration test to test the whole flow....otherwise what would be the point of unit test? but again, I never built myself an app with millions of users, I only worked for companies that do tests in this way, so I might be wrong :)

**Comment by thelinuxlich** [comment]
But what value do you gain from asserting something that will always happen(at least on the happy path, as createAccount isn't a pure function)?
At least the integration test asserts the expected data transformation.

**Comment by francescovenica** [comment]
I think the main point is to mock the client so you can run unit tests without having a db running, maybe the assertion can be skipped if you have integration tests, but if I think about a function like this:

```
const registerBusinsess = ({ db }: { db: Kysely<DB> }) => { 
  const account = await db.insert("account").executeTakeFirst() 
  const stripeSubs = await stripe.subs.create({ meta: { account: account.uuid }});
  const subscription = await db.insert("subscription").set({ stripeSubs: stripeSubs.id }).executeTakeFirst();
  await sqs.sendMessage({ event: "new-subscription", data: subscription })
}
```

I would like to have a test like:
```
it("register a businsess", () => {
   await registerBusinsess({ db });
   expect(dbMock.query).toHaveBeenCalledWith("...");
   expect(stripeSubs.create).toHaveBeenCalledWith("...");
   expect(dbMock.query).toHaveBeenCalledWith("...");
   expect(sqsMock.sendMessage).toHaveBeenCalledWith("..);
})
```

**Comment by thelinuxlich** [comment]
That test doesn't assert anything that wouldn't happen anyway

**Comment by markwitt1** [comment]
Any update on this? It is really annoying that we need to spin up a database in our CI. Isn't there a way to just mock the responses of our db queries?

**Comment by thelinuxlich** [comment]
Just use pglite

**Comment by markwitt1** [comment]
I dont want to use sth like that because our tests should run in a few milliseconds. It's unnecessarily overcomplicating it.

I managed to get this to work with vitest:

```
vi.mock("../../src/db", () => ({
		db: {
			selectFrom: vi.fn().mockReturnValue({
				where: vi.fn().mockReturnValue({
					select: vi.fn().mockReturnValue({
						executeTakeFirstOrThrow: vi
							.fn()
							.mockResolvedValue({ id:"id" }),
					}),
				}),
				selectAll: vi.fn().mockReturnValue({
					execute: vi.fn().mockResolvedValue([
						"..."
					]),
				}),
			}),
			transaction: vi.fn().mockReturnValue({
				execute: vi.fn().mockImplementation((callback) =>
					callback({
						deleteFrom: vi.fn().mockReturnValue({
							where: vi.fn().mockReturnValue({
								execute: vi.fn(),
							}),
						}),
						insertInto: vi.fn().mockReturnValue({
							values: vi.fn().mockReturnValue({
								execute: vi.fn(),
							}),
						}),
					}),
				),
			}),
		},
	}));
```

It's a bit verbose but gets the job done without any fake database shenanigans

**Comment by igalklebanov** [comment]
This is an anti-pattern. Don't.

**Comment by francescovenica** [comment]
I use this
https://github.com/kysely-org/kysely/issues/801#issuecomment-1936662422

And I take a snapshot of the query (being sure the query is correct) + integration test..in this way you don't need to mock all the methods

**Comment by markwitt1** [comment]
@igalklebanov Can you elaborate on why this is an anti-pattern? Prisma recommends doing exactly that: https://www.prisma.io/docs/orm/prisma-client/testing/unit-testing#example-unit-tests

**Comment by rebasecase** [comment]
Unit testing by mocking the inner workings of your database client, like query builders or ORM calls, is a bad idea because it ties your tests too closely to low-level details that can change often. This makes your tests fragile. A better approach is to use a repository or service layer as a simple wrapper around your database. Then you can mock that layer in your unit tests and focus on testing your actual logic. Save the real database checks for integration tests that just verify the repository does what it’s supposed to. Cleaner, simpler, much easier to maintain.

What are you /actually/ testing when you mock every database method.. that a function was called with the right arguments? Cool... but now you’ve doubled your code just to mirror the implementation. That’s not real testing. Focus on testing behaviors, not the plumbing underneath. Good tests should break when features break, not when you refactor a query or change a parameter name.
