### ISSUE TITLE
Auto intersting of table name

### ISSUE THREAD

**Issue by romeerez** [kysely-org/kysely#809]
Hi and thank you for this wonderful library!

Sometimes I'm bitten by:
```ts
.where('id', '=', 123)
```
Because joined tables also have an `id` column, this is ambiguous for the database.

It would be nice if Kysely added a table name to it automatically. It could be added always, or it could see if there are any joined tables and add it only in such a case.

The same applies to `where`, `order`, and all other methods that can accept a column name.

Then it would be one potential runtime error less.

**Comment by koskimas** [comment]
Kysely will always remain just a dumb query builder and only do things the user explicitly asks. Also, we don't have any runtime data on which column belongs to which table. We only have that information in the type level. So we couldn't do that even if we wanted to, without fetching that data from the DB.

What we could consider is not allow ambiguous columns in the type level, but that might be hard to implement. Something worth trying though.

**Comment by romeerez** [comment]
I see, it's not implementable without unwanted changes.

In one other query builder, `where` forces to provide a joined table name:
```ts
db.issues.
  .join('comments', 'comments.id', 'issues.id')
  .where({ 'comments.content': 'value' }) // allowed
  .where({ 'content': 'value' }) // not allowed on type level
```

When it's a simple column, it knows that it's for the main table:
```ts
db.issues
  .join('comments', 'comments.id', 'issues.id')
  .where({ id: 809 }) // id of the issue
```

With such behavior, it knows that it should insert the table name to avoid ambiguity.

But Kysely is designed to be closer to SQL, and in SQL we don't have such restrictions.

The feature is not possible without restricting `where('joinedColumn', '=', 'value')`, and this restriction doesn't align with philosophy.
