### ISSUE TITLE
Is there any way to write the string "tableName"."columnName"->'propertyName' inside raw sql?

### ISSUE THREAD

**Issue by aviranco** [kysely-org/kysely#813]
I know that `sql.ref` doesn't support JSON references yet, but I wonder if there is **ANY** way/walkaround to generate the following string dynamically so the following code could somehow work (just need to reference a json property dynamically inside raw query):

```
const filterQuery =  ` "${tableName}"."${columnName}"->'${propertyName}' `
const sqlQuery = sql`....${filterQuery} ...`
```

Thanks!

**Comment by igalklebanov** [comment]
Hey 👋 

You can inject strings as-is using `sql.raw`:

```ts
const filterQuery =  ` "${tableName}"."${columnName}"->'${propertyName}' `
const sqlQuery = sql`....${sql.raw(filterQuery)} ...`
```
