### ISSUE TITLE
Feature: Copy inline docs to derived table interfaces (e.g., Selectable<T>)

### ISSUE THREAD

**Issue by ekcom** [kysely-org/kysely#814]
I've written a class for Kysely with some inline JSDocs/TSDocs, which I use for IntelliSense popups:

```typescript
interface DbPerson {
  /**
   * Auto-generated id of the person
   **/
  id: Generated<number>,
  /**
   * A person's name
   * 
   * Should be at least two characters long
   **/
  name: string,
}
```

Then, to use the table, I use Kysely's types like so:

```typescript
export type Person = Selectable<DbPerson>;
export type PersonNew = Insertable<DbPerson>;
export type PersonUpdate = Updateable<DbPerson>;
```

However, now when I am trying to create a `PersonNew` object, I don't have my documentation in IntelliSense.
I see popups for the fields (e.g., `name: ValueExpression<DB, "person", string>`) but not the documentation (e.g., no `A person's name\nShould be at least two characters long` above the `name`).

I can't use the `DbPerson` type itself (e.g., because assigning a `number` to `id` gives type errors (`Type 'number' is not assignable to type 'Generated<number>'.`)), so I have to use these derived types (which are loosing the associated documentation).

I'm not sure if there is a fancy TypeScript way of inheriting comments or if this can be done some other way.
Is there another paradigm that I should use to see my documentation, e.g., when calling `db.insertInto("persons").values({/* need hints here! */})`?

**Comment by igalklebanov** [comment]
Hey 👋 

This is outside of Kysely's core scope I'm afraid. A limitation of JSDocs and your IDE, and maybe the community codegen libraries.

For top-level comments, you could use `@see` and `@link` tags, or copy the entire comment. 

For properties, there is no DRY solution that I know of.
You could, instead of using `Selectable`, `Insertable` and `Updateable`, define the object type yourself and use "column-level" type helpers and either use `@see` and `@link` tags or copy the comment itself:

```ts
import type { Generated, InsertType, SelectType, UpdateType } from 'kysely'

type DbPerson = {
  /**
   * Auto-generated id of the person
   **/
  id: Generated<number>
  /**
   * A person's name
   *
   * Should be at least two characters long
   **/
  name: string
}

export type Person = {
  /**
   * @see {@link DbPerson.id}
   */
  id: SelectType<DbPerson['id']>
  /**
   * @see {@link DbPerson.name}
   */
  name: SelectType<DbPerson['name']>
}

export type PersonNew = {
  /**
   * @see {@link DbPerson.id}
   */
  id?: InsertType<DbPerson['id']>
  /**
   * @see {@link DbPerson.name}
   */
  name: InsertType<DbPerson['name']>
}

export type PersonUpdate = Partial<{
  /**
   * @see {@link DbPerson.id}
   */
  id: UpdateType<DbPerson['id']>
  /**
   * @see {@link DbPerson.name}
   */
  name: UpdateType<DbPerson['name']>
}>
```
