### ISSUE TITLE
How to extend a database type?

### ISSUE THREAD

**Issue by stefanvanherwijnen** [kysely-org/kysely#815]
Hi,

Is it (or should it be) possible to assign a `Kysely<SecondaryDb extends PrimaryDb>` instance to a `Kysely<PrimaryDb>` type?
At the moment this result in an `The types of '...some internal kysely function...' are incompatible between these types.` Other than the typing errors, it seems to work fine.

For example, have a look at db.tsx in this forked demo:
https://codesandbox.io/s/kysely-demo-forked-c5tvfg

The use case is a library which accepts a Kysely instance as argument to perform database operations. But this Kysely instance is not limited to the database structure as is defined in the library. If extending the database is not possible, is there any other way to achieve this?

Kind regards,

Stefan

**Comment by koskimas** [comment]
You can use inheritance, interface merging, type intersections and whatnot. You can't use `{ [key: string]: any }` which says your DB has every table in the universe.

**Comment by stefanvanherwijnen** [comment]
Apologies, I accidentally saved the codesandbox while trying to find a workaround.
The problem is this:
![Screenshot from 2023-12-22 10-14-03](https://github.com/kysely-org/kysely/assets/5968971/4ee43477-babc-4733-bd5e-f339e3c197ba)
