### ISSUE TITLE
agg requires two type parameters

### ISSUE THREAD

**Issue by gudleik** [kysely-org/kysely#829]
In version <0.27 we could do this:

```ts
const person = await db
  .selectFrom('person')
  .select(eb => eb.fn.agg<string[]>('array_agg', ['last_name']).as('names'))
```

But with version 0.27, typescript gives an error `Expected 2 type arguments, but got 1.`

Working example with v0.26.3: [Playground Link](https://kyse.link/?p=b&i=haFkqHBvc3RncmVzoXamMC4yNi4zoXPaAaJpbXBvcnQgeyBHZW5lcmF0ZWQgfSBmcm9tICdreXNlbHknCgpkZWNsYXJlIGdsb2JhbCB7CiAgaW50ZXJmYWNlIERCIHsKICAgIHBlcnNvbjogUGVyc29uVGFibGUKICAgIHBldDogUGV0VGFibGUKICB9CgogIGludGVyZmFjZSBQZXJzb25UYWJsZSB7CiAgICBpZDogR2VuZXJhdGVkPHN0cmluZz4KICAgIGZpcnN0X25hbWU6IHN0cmluZwogICAgbGFzdF9uYW1lOiBzdHJpbmcgfCBudWxsCiAgICBjcmVhdGVkX2F0OiBHZW5lcmF0ZWQ8RGF0ZT4KICAgIGFnZTogbnVtYmVyCiAgfQoKICBpbnRlcmZhY2UgUGV0VGFibGUgewogICAgaWQ6IEdlbmVyYXRlZDxzdHJpbmc-CiAgICBuYW1lOiBzdHJpbmcKICAgIG93bmVyX2lkOiBzdHJpbmcKICAgIHNwZWNpZXM6ICdjYXQnIHwgJ2RvZycKICAgIGlzX2Zhdm9yaXRlOiBib29sZWFuCiAgfQp9oXHZq2NvbnN0IHBlcnNvbiA9IGF3YWl0IGRiCiAgLnNlbGVjdEZyb20oJ3BlcnNvbicpCiAgLnNlbGVjdChlYiA9PiBlYi5mbi5hZ2c8c3RyaW5nW10-KCdhcnJheV9hZ2cnLCBbJ2xhc3RfbmFtZSddKS5hcygnbmFtZXMnKSkKICAud2hlcmUoJ2lkJywgJz0nLCAnMScpCiAgLmV4ZWN1dGVUYWtlRmlyc3QoKaFjww==)

Same example with v0.27: [Playground Link](https://kyse.link/?p=b&i=haFkqHBvc3RncmVzoXamMC4yNy4woXPaAaJpbXBvcnQgeyBHZW5lcmF0ZWQgfSBmcm9tICdreXNlbHknCgpkZWNsYXJlIGdsb2JhbCB7CiAgaW50ZXJmYWNlIERCIHsKICAgIHBlcnNvbjogUGVyc29uVGFibGUKICAgIHBldDogUGV0VGFibGUKICB9CgogIGludGVyZmFjZSBQZXJzb25UYWJsZSB7CiAgICBpZDogR2VuZXJhdGVkPHN0cmluZz4KICAgIGZpcnN0X25hbWU6IHN0cmluZwogICAgbGFzdF9uYW1lOiBzdHJpbmcgfCBudWxsCiAgICBjcmVhdGVkX2F0OiBHZW5lcmF0ZWQ8RGF0ZT4KICAgIGFnZTogbnVtYmVyCiAgfQoKICBpbnRlcmZhY2UgUGV0VGFibGUgewogICAgaWQ6IEdlbmVyYXRlZDxzdHJpbmc-CiAgICBuYW1lOiBzdHJpbmcKICAgIG93bmVyX2lkOiBzdHJpbmcKICAgIHNwZWNpZXM6ICdjYXQnIHwgJ2RvZycKICAgIGlzX2Zhdm9yaXRlOiBib29sZWFuCiAgfQp9oXHZq2NvbnN0IHBlcnNvbiA9IGF3YWl0IGRiCiAgLnNlbGVjdEZyb20oJ3BlcnNvbicpCiAgLnNlbGVjdChlYiA9PiBlYi5mbi5hZ2c8c3RyaW5nW10-KCdhcnJheV9hZ2cnLCBbJ2xhc3RfbmFtZSddKS5hcygnbmFtZXMnKSkKICAud2hlcmUoJ2lkJywgJz0nLCAnMScpCiAgLmV4ZWN1dGVUYWtlRmlyc3QoKaFjww==)

**Comment by koskimas** [comment]
Fixed in 0.27.1. Thanks for reporting this!
