### ISSUE TITLE
Allow parameters in ExecuteStatement for RDS Aurora Data API

### ISSUE THREAD

**Issue by vicary** [kysely-org/kysely#834]
Currently we can use the `driver` option to supply an `RDSData` client for the mysql mode, but options are restricted to client level only.

There is a specific parameter `continueAfterTimeout` that is only available at `ExecuteStatement`, where it continues running the statement even if the timeout in Data API is reached.

This is particularly useful and necessary for DDL and long-running INSERT/UPDATE/CALL statements.

**Comment by koskimas** [comment]
You are probably talking about [this driver](https://github.com/sst/kysely-data-api) right? That's a third party driver/dialect and we have no control over it. You need to open the issue in their github.

**Comment by vicary** [comment]
@koskimas Yes, you're right. Thanks!
