### ISSUE TITLE
SelectQueryBuilder preventAwait makes it impossible to return a query from an async function.

### ISSUE THREAD

**Issue by dhatch-niv** [kysely-org/kysely#838]
## Issue

I have a database repository class that internally uses Kysely for querying. There are two methods that share a similar query, so I have a helper function to create the query. To fill where parameters this function may need to perform a query internally, so it is an async function.

The structure is roughly:

```typescript
class DatabaseRepo {
    private async makeQuery(db: Conn) -> Promise<SelectQueryBuilder> {
        const filter = await getFilterArg(db);
        return db.selectFrom("item").where("item.fkId", "=", filter);
    }

    async getOne(db: Conn) -> Promise<Item | undefined> {
        const query = await this.makeQuery(db);
        return await query.executeTakeFirst();
    }

    async getMostRecent(db: Conn) -> Promise<Item | undefined> {
        let query = await this.makeQuery(db);
        query = query.orderBy("ts", "desc");
        return await query.executeTakeFirst();
    }
}
```

This doesn't work. Running it returns an error:

```
Error: don't await SelectQueryBuilder instances directly. To execute the query you need to call `execute` or `executeTakeFirst`.
```

This is caused by [preventAwait](https://github.com/kysely-org/kysely/blob/9deb62afe60ce7778bf12504e9d53e17735eace6/src/util/prevent-await.ts#L1) which is intended to return a helpful error message if users use Query wrong.

JavaScript considers any *[thenable object](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise#thenables)* similar to a promise. Awaiting the result of `makeQuery` resolves with the result of awaiting the query, an error. The desired behavior is to resolve to the query **value**. Then the query can be subsequently executed by calling the appropriate `execute` or `executeTakeFirst` method.

## Workaround

This can be worked around by overriding the `then` property before returning the query from the async function (making it no longer a thenable object):

```typescript
Object.defineProperty(query, "then", { value: undefined });
return query;
```

## Proposed Solution

It may have been initially unclear that adding this error message prevents returning a query from an async function. The value of the error message for new users needs to be weighted against making this use case difficult. An argument could be made for leaving the error message since it helps new users. It looks me probably 30 minutes to figure out what was going on here because the error message states not to call execute which I am doing, and the stack trace is incomplete (probably an issue with my Node configuration and not Kysely). 

Consider removing `preventAwait`. It is unfortunate that JavaScript allows awaiting any object, but since Kysely targets Typescript, users should be able to identify that they are not using a query correctly if they don't call `execute()` or `executeTakeFirst()` because the type will still be a SelectQueryBuilder and not their result.

**Comment by thelinuxlich** [comment]
Or....you do:

```ts
 private async makeQuery(db: Conn) {
       const filter = await getFilterArg(db);
       return () => db.selectFrom("item").where("item.fkId", "=", filter)
}
```

**Comment by koskimas** [comment]
We know how promises work.
