### ISSUE TITLE
Add  support for Postgres bulk update statement

### ISSUE THREAD

**Issue by emishur** [kysely-org/kysely#839]
In Postgres, it is possible to bulk update table from a list of values:

```sql
CREATE TABLE "foo" (
	"col1" int,
	"col2" text
);

UPDATE "foo"
SET
 "col1" = "v".col1,
 "col2" = "v".col2
FROM (
	VALUES
	 (1, 'bar'),
	 (2, 'buz')
) AS "v" ("col1", "col2")
WHERE
	"foo"."col1" = "v"."col1";

```

Currently, it is not possible to construct such update query with Kysely.
There is a proposed solution https://kyse.link/?p=s&i=C0yoagEodj9vv4AxE3TH,
but it only works if all columns have 'text' type.

My understanding is that when Kysely tries to prepare the statement it does not
provide parameter type and Postgres defaults to 'text' (see related issue #732).

Possible solution is to inject parameter types into PREPARE statement.
Either by specifying parameter types like this:

```sql
PREPARE prep_foo (int, text, int, text) AS
	UPDATE "foo"
	SET
	 "col1" = "v".col1,
	 "col2" = "v".col2
	FROM (
		VALUES
		 ($1, $2),
		 ($3, $4)
	) AS "v" ("col1", "col2")
	WHERE
		"foo"."col1" = "v"."col1";

```

or like this

```sql
PREPARE prep_foo AS
	UPDATE "foo"
	SET
	 "col1" = "v".col1,
	 "col2" = "v".col2
	FROM (
		VALUES
		 ($1::int, $2::text),
		 ($3::int, $4::text)
	) AS "v" ("col1", "col2")
	WHERE
		"foo"."col1" = "v"."col1";

```

**Comment by koskimas** [comment]
You can modify the proposed solution to make the casts. We can't add automatic casts since they are database-dependent. We don't know what the column's data type is when you pass in a javascript `number` for example.

We can't do this automatically. We don't have the information, and never will have, since Kysely is not an ORM.

**Comment by koskimas** [comment]
Types don't exist in the runtime, so no, that's not possible.
