### ISSUE TITLE
Introspect should also fetch column comments so we can generate typescript comments

### ISSUE THREAD

**Issue by maktouch** [kysely-org/kysely#841]
Related to https://github.com/RobinBlomberg/kysely-codegen/issues/127

We need comments in the introspection, so we can generate typescript comments for the column. Would you accept a PR for this?

**Comment by koskimas** [comment]
> Would you accept a PR for this

Sure, if you provide a fully working and tested PR that implements this for __all__ built-in dialect that support the feature.
