### ISSUE TITLE
JSON select types are working incorrectly with zod passthrough object

### ISSUE THREAD

**Issue by vladshcherbin** [kysely-org/kysely#850]
Hey 👋 

I have a JSON column and [zod](https://github.com/colinhacks/zod) validated data is stored there.
Same zod schema type is used in database `JSONColumnType`.
Schema is a zod `object` type and everything works correctly.

When I add [.passthrough()](https://zod.dev/?id=passthrough) to object (_`passthrough` is used for preserving unknown keys, specified ones always exist_), Kysely loses the ability to get `ref`.`key` suggestions and result output type also has `| null` added.

**Working Reproduction:**

```ts
import { CamelCasePlugin, type GeneratedAlways, type JSONColumnType, Kysely, PostgresDialect } from 'kysely'
import pg from 'pg'
import { z } from 'zod'

const brandSchema = z.object({
  slug: z.string()
})

type Brand = z.infer<typeof brandSchema>
type SlugKey = Brand['slug']

interface BrandsTable {
  id: GeneratedAlways<number>
  details: JSONColumnType<Brand>
}

type Database = {
  brands: BrandsTable
}

const database = new Kysely<Database>({
  dialect: new PostgresDialect({
    pool: new pg.Pool({ connectionString: 'connection' })
  }),
  plugins: [
    new CamelCasePlugin()
  ]
})

const brand = await database
  .selectFrom('brands')
  .select((eb) => [
    'id',
    eb.ref('details', '->').key('slug').as('slug')
  ])
  .executeTakeFirstOrThrow()

console.log(brand.slug)
  ```

Result:

✅ `SlugKey` has correct type

<img width="579" alt="image" src="https://github.com/kysely-org/kysely/assets/6711845/e537a958-b6e0-4e7e-ba14-33e9a8622770">

✅ `ref`.`key` has correct type suggestions

<img width="662" alt="image" src="https://github.com/kysely-org/kysely/assets/6711845/895fbe2e-5be7-4454-ba2c-c919bd14c826">

✅ query result has correct type

<img width="633" alt="image" src="https://github.com/kysely-org/kysely/assets/6711845/4c4e9ae4-f655-478c-980f-ba9516f1431e">

---

**Non-working:**

Just one change to the above code:

```ts
const schema = object({
  slug: string()
}).passthrough()
```

Result

✅ `SlugKey` still has correct type

<img width="579" alt="image" src="https://github.com/kysely-org/kysely/assets/6711845/e537a958-b6e0-4e7e-ba14-33e9a8622770">

❌ `ref`.`key` has no type suggestions

<img width="626" alt="image" src="https://github.com/kysely-org/kysely/assets/6711845/32c9322c-99a2-49b3-afdf-baf012e135b6">

❌ query result has incorrect type (`slug` always exists)

<img width="669" alt="image" src="https://github.com/kysely-org/kysely/assets/6711845/038fa173-5fee-46c0-ad88-a793e5cffaae">

I've also tried using just `ColumnType` but the result is the same.

passthrough `Brand` object type:

<img width="639" alt="image" src="https://github.com/kysely-org/kysely/assets/6711845/3c09e3d6-5c9d-452d-897f-b4cc35ad98e4">

---

kysely - 0.27.2
zod - 3.22.4
typescript - 5.3.3
node - 20.10.0
vscode - 1.85.2

**Comment by koskimas** [comment]
Interoperability with zod is not our goal.

**Comment by vladshcherbin** [comment]
@koskimas same thing happens with a plain object type, I just happened to found out with a zod one.

This will create same results:

```ts
type Brand = {
  slug: string
  [key: string]: unknown
}
```

I can create a new issue without zod if needed 😅

**Comment by vladshcherbin** [comment]
@thelinuxlich thanks, will do 🙌

**Comment by vladshcherbin** [comment]
I've opened a new issue without zod with reproduction, kyse.link is insanely good 🤩
