### ISSUE TITLE
Compile time checks for empty arrays

### ISSUE THREAD

**Issue by andy-zhou** [kysely-org/kysely#851]
One of the common pitfalls I've seen developers have with Kysely revolves around empty arrays and the subsequent generation of invalid SQL.

```ts
const person = await db
  .insertInto('person')
  .values([])
  .execute()
```

generates the following invalid SQL

```sql
INSERT INTO
  "person" ()
VALUES
```

While the behavior is correct - kysely only generates what it's asked to - it's an easy gotcha to miss.

---

Does it make sense to protect against this in the type system? Basically something like

```ts
type NonEmptyArray<T> = [T, ...T[]]
export type InsertObjectOrList<DB, TB extends keyof DB> 
  = InsertObject<DB, TB> | Readonly<NonEmptyArray<InsertObject<DB, TB>>>;
```

I'm not sure what kind of downstream effect this might have, but happy to make a PR.

**Comment by koskimas** [comment]
That won't work with an non-inline array.

**Comment by KROT47** [comment]
> That won't work with an non-inline array.

@koskimas hi!
Works pretty well for me though...

And current behavior is not type safe at all when you can catch runtime error any time.

e.g.
```ts
const newAddressesData = getData() // here may be empty array
await db
    .insertInto('addresses')
    .values(newAddressesData)
    .onConflict((oc) => oc.doNothing())
    .execute() // => and this throws runtime error - game over
```

Instead like @andy-zhou proposed with this:
```ts
type NonEmptyArray<T> = [T, ...T[]]
export type InsertObjectOrList<DB, TB extends keyof DB> 
  = InsertObject<DB, TB> | Readonly<NonEmptyArray<InsertObject<DB, TB>>>;
```

will lead to compile time error instead

<img width="331" alt="Image" src="https://github.com/user-attachments/assets/b8fa51d5-f62b-4bbc-b85d-59415e8c052b" />


so we need just to use one util to finish with this:
```ts
function getNonEmptyArray<T>(arr: T[]): [T, ...T[]] | undefined {
  if (!arr.length) return undefined
  return arr as [T, ...T[]]
}

const newAddressesData = getNonEmptyArray(getData()) // always non empty array or undefined
if (newAddressesData) {
  await db
      .insertInto('addresses')
      .values(newAddressesData)
      .onConflict((oc) => oc.doNothing())
      .execute() // => no runtime error
}
```

This is breaking TS change but seems better than having runtime errors
