### ISSUE TITLE
Incorrect types and missing suggestions when using object index signature

### ISSUE THREAD

**Issue by vladshcherbin** [kysely-org/kysely#852]
When using object index signature, known properties get `| null` type and `ref`.`key` suggestions are missing. Without index signature everything is working correctly.

Example with correct `ref`.`key` suggestions and correct `brand` slug field type:

https://kyse.link/?p=s&i=MmozcfIdl4l3HrV97ncr

Same example without `ref`.`key` suggestions and with incorrect `brand` slug field type (it can't be `null`):

https://kyse.link/?p=s&i=PlNhdkgf4RggHGJnuqVX

kysely 0.27.2

related zod issue - https://github.com/kysely-org/kysely/issues/850

**Comment by koskimas** [comment]
I don't think it's possible to fix that. Just try doing this

```ts
type X = keyof Brand
const x: X = 'slug'
```

you don't get suggestions for `slug` even here.

**Comment by vladshcherbin** [comment]
@koskimas yeah, doesn't work for me too ☹️

What about the `slug` type from the second example link? It's `string | null` but from the type it can only be a `string`. Can this somehow be fixed or it's also not possible?
