### ISSUE TITLE
[Q] Reusable CTE (psql)

### ISSUE THREAD

**Issue by snowytime** [kysely-org/kysely#858]
Hey 👋 I have been using Kysely and loving it but I have been trying to create a reusable CTE but its not working as expected / the types are being messed up so I 'm wondering if anyone has managed to get this to work.

**example (simple)**

Say you have a super simple query like:

```ts
const res = await db
  .with('something', eb => eb.selectFrom('dogs').select('coat'))
  ...rest of query
```

I want to extract the .with() into a reusable function that can be used. Trying to do this I only managed it to work using the `QueryCreator<DB>` however this works only if the .with is the only CTE being used. If there are more, then it stops working, presumably since the type is now `QueryCreator<DB & { previous cte(s) }>` which breaks the type inference, etc.

Is there a way to make this work so that you can bring in your CTE's like `.with('blah', cteFn())`?

Thanks a ton :)

**Comment by koskimas** [comment]
Unfortunately that's only currently possible by either using the exact `QueryCreator` type or loosening type-safety by doing this: https://kyse.link/?p=s&i=RQ4GXkErV7QZ1ECUYVxC

Note that you can incorrectly use the `exressionBuilder` by listing tables that don't exist.

**Comment by EDjur** [comment]
Hi 👋 

Are there any plans to include this type of feature in the future? Having composable queries through re-usable CTEs is really handy when writing large queries.

Currently if you do something like this:

```
const petNames = db
  .selectFrom("pet")
  .select(["name", "id", "owner_id"]);

const cte1 = db
  .with("petNames", () => petNames)
  .selectFrom("petNames")
  .select("id");

const cte2 = await db
  .with("cte1", () => cte1)
  .selectFrom("cte1")
  .select("id")
  .execute();
  ```
  
  The query gets pretty messed up (albeit still functional), since it will nest the various CTE within each other.

**Comment by thelinuxlich** [comment]
Wrap the CTE in a function that receives the query builder as the param

**Comment by EDjur** [comment]
Right, I tried that as per above, but that gets pretty frustrating if you want to have multiple CTEs, or use CTEs within a different CTE no?

**Comment by thelinuxlich** [comment]
Your example should be something like

```ts
const cte2 = await db
  .with("cte1", cte1)
  .selectFrom("cte1")
  .select("id")
  .execute();
```

**Comment by EDjur** [comment]
I've tried that as well but that raises a type error unfortunately.
