### ISSUE TITLE
Issue with parentheses in Postgres using a conflict expression

### ISSUE THREAD

**Issue by lncrespo** [kysely-org/kysely#863]
When working with partial unique indexes in PostgreSQL you can use the "ON CONFLICT" clause together with said partial unique index, for example given the following table:

```sql
CREATE TABLE my_table
(
    id                SERIAL,
    my_identifier     VARCHAR,
    my_type           VARCHAR,
    value             TEXT
);

CREATE UNIQUE INDEX my_partial_unique_index ON my_table(my_identifier) WHERE my_type = 'foo';
```
We specify that the column `my_identifier` has to be unique if the column `my_type` is of value `foo`.
When inserting into the table, we can tell Postgres to check for this partial unique index by repeating the defining expression like this:
```sql
INSERT INTO my_table (my_identifier, my_type, value) VALUES ('123', 'foo', 'bar') ON CONFLICT (my_identifier) WHERE my_type = 'foo' DO UPDATE SET value = 'baz';
```

When trying this with the `OnConflictBuilder`, we would use the `.expression` method
```typescript
.onConflict(conflict => {
    conflict.expression(sql`(my_identifier) WHERE my_type = 'foo'`)
})
```
however the resulting SQL has parentheses around the conflict expression, resulting in a syntax error:
```sql
INSERT INTO my_table (my_identifier, my_type, value) VALUES ('123', 'foo', 'bar') ON CONFLICT ((my_identifier) WHERE my_type = 'foo') DO UPDATE SET value = 'baz';
```

I would like to see an option to either be able to remove the surrounding parentheses as a builder method, e.g. `noSurroundingParentheses()` or being able to drop a raw sql expression into the conflict clause.

If there already is a solution to my problem, please let me know.

**Comment by igalklebanov** [comment]
Hey 👋 

Try [this](https://kyse.link/JXdkc).

```ts
await db
  .insertInto("my_table")
  .onConflict((oc) =>
    oc
      .column("my_identifier")
      .where("my_type", "=", "foo")
      .doUpdateSet({ value: "baz" }),
  )
  .execute();
```
