### ISSUE TITLE
camelCase plugin is not being applied to subquery results that incorporates jsonArrayFrom

### ISSUE THREAD

**Issue by ekschro** [kysely-org/kysely#865]
# UPDATE
I have realized that this is probably due to the fact that `jsonArrayFrom` is returning a string of JSON that I have to then parse. I had to cast the type `string` to the result in order to avoid a type error. The error seems to be due to the fact that a parsed JSON result is promised by `jsonArrayFrom` yet it returns a string.

Any thoughts on resolving this?

# Example Query
```js
db
    .selectFrom('a')
    .selectAll()
    .select(
      (eb) => jsonArrayFrom(
        eb.selectFrom('b')
          .whereRef('b.aId', '=', 'a.id')
          .selectAll('b')
          .orderBy('b.id')
      )
        .$castTo<string>()
        .as('b')
    )
    .where('a.id', '=', id)
    .executeTakeFirst();
```

# Current Behavior
```js
{
  "id": "XXXXX",
  "createdBy": "YYYYY",            // camelCase working as expected
  "exampleName": "Test",
  "b": [
    {
      "id": 0,
      "a_id": "XXXXX",                 // camelCase not working as expected
      "attr_ex": 0                      // camelCase not working as expected
    },
    {
      "id": 1,
      "a_id": "XXXXX",                // camelCase not working as expected
      "attr_ex": 1                      // camelCase not working as expected
    }
  ]
}
```

# Expected Behavior
```json
{
  "id": "XXXXX",
  "createdBy": "YYYYY",   
  "exampleName": "Test",
  "b": [
    {
      "id": 0,
      "aId": "XXXXX",
      "attrEx": 0
    },
    {
      "id": 1,
      "aId": "XXXXX",
      "attrEx": 1
    }
  ]
}
```

**Comment by pringon** [comment]
Can you also share information about the type definitions and migrations you run against the database please? :)

**Comment by igalklebanov** [comment]
Hey 👋 

> Some dialects might simply return the data as a JSON string. In these cases you can use the built in ParseJSONResultsPlugin to parse the results.
https://kysely.dev/docs/examples/SELECT/nested-object
