### ISSUE TITLE
ParseJSONResultsPlugin

### ISSUE THREAD

**Issue by pizzooid** [kysely-org/kysely#868]
Hi there!

I hope this report is in the appropriate format.

I am using the ParseJSONResultsPlugin. When I store a value like "[0]" in a text field, it is returned as an array. 

What are your suggestions?

Thank you for your help

**Comment by koskimas** [comment]
Modify the plugin or change the text column to json. If it contains an array of numbers, why is it a text column?

We don't have any metadata about the actual type of the column. The plugin can only detect JSON by checking the format.
