### ISSUE TITLE
Pass client instance

### ISSUE THREAD

**Issue by francescovenica** [kysely-org/kysely#870]
Hello,

I just found out about this amazing tool, I wanted to double check if it is possible somehow to pass a client to the query builder, so instead of having something like:
```
const dialect = new PostgresDialect({
  pool: new Pool({
    database: 'test',
    host: 'localhost',
    user: 'admin',
    port: 5434,
    max: 10,
  })
})

// Database interface is passed to Kysely's constructor, and from now on, Kysely 
// knows your database structure.
// Dialect is passed to Kysely's constructor, and from now on, Kysely knows how 
// to communicate with your database.
export const db = new Kysely<Database>({
  dialect,
})
```

having something like:
```
export const db = new Kysely<Database>({
  client,
})
```

or even something like:
```
export const db = new Kysely<Database>()
db.connection(client).whatever()
```

similar to what Knex provide, many thanks

**Comment by igalklebanov** [comment]
Hey 👋 

The core PostgreSQL dialect only accepts a pool instance. You can use https://github.com/jtlapp/kysely-pg-client instead.

**Comment by francescovenica** [comment]
great, many thanks! :)

**Comment by francescovenica** [comment]
actually I don't think that library works, typescript is complaining a bit, I'll try to fork it
