### ISSUE TITLE
Set role & configs

### ISSUE THREAD

**Issue by francescovenica** [kysely-org/kysely#873]
hello,

I'm trying to set the role for a particular transaction & some local setting, I think the only way to do this is using the sql fragment but if I do something like:
```
await sql`set local role ${role}`.execute(trx);

for (const setting of Object.keys(settings)) {
  await sql`select set_config('${setting}', ${settings[setting]}, true)`.execute(
    trx,
  );
}
```

it throw this error:
```
syntax error at or near "$1"
```

these are the db logs:
```
2024-02-08 08:11:44.087 UTC [714] DETAIL:  parameters: $1 = 'FREE'
2024-02-08 08:11:44.445 UTC [715] LOG:  statement: begin
2024-02-08 08:11:44.447 UTC [715] ERROR:  syntax error at or near "$1" at character 16
2024-02-08 08:11:44.447 UTC [715] STATEMENT:  set local role $1
```

am I doing something wrong?

**Comment by koskimas** [comment]
String substitutions get turned into parameters. They aren't interpolated to the SQL string to avoid SQL injections.

See the `sql` module in the API docs.

**Comment by francescovenica** [comment]
ops, sorry, I've misunderstood the documentation (my english is not very good), using `sql.lit()` seems to work! thanks
