### ISSUE TITLE
fix bun tests hanging in CI.

### ISSUE THREAD

**Issue by igalklebanov** [kysely-org/kysely#882]
Hey 👋 

Bun tests are hanging in GitHub Actions. Durations going 3h and beyond for the bun related steps.

I have disabled bun steps until fixed @ `test.yml`.

**Comment by Jarred-Sumner** [comment]
I wonder if it's an IPv6 issue. Bun doesn't implement "happy eyeballs" yet.

**Comment by igalklebanov** [comment]
If it's of any use, this is where it started happening. https://github.com/kysely-org/kysely/actions/runs/7764564469/job/21178156254#step:13:1

**Comment by igalklebanov** [comment]
bun 1.1.2+c8d072c2a still hanging. https://github.com/kysely-org/kysely/actions/runs/8582688442/job/23521068831?pr=942
