### ISSUE TITLE
Web, Getting Started - MySQL dialect example produces type error

### ISSUE THREAD

**Issue by linas-ipxo** [kysely-org/kysely#886]
Hello.

Direct copying examples from https://kysely.dev/docs/getting-started?dialect=mysql produces a type error in createPerson():

![image](https://github.com/kysely-org/kysely/assets/11992427/809f40f0-58c0-4708-800d-46b7681d1103)

I obviously can work around this, but as a bit of a newcomer, I'm not exactly sure if this is intented, or is this a bug somewhere.

**Comment by igalklebanov** [comment]
Hey 👋 

This is a documentation issue - PR's welcome.

1. `findPersonById` should accept `bigint` or even `number | bigint`.
2. Since we're in MySQL context, you can add a non-null assertion as follows: `return await findPersonById(insertId!)`

**Comment by koskimas** [comment]
We don't know which property is the id that gets returned. All Kysely sees is the table interface and there's no indication of the primary key. Some tables don't even have it or they have a composite primary key.

You can easily cast the type using `Number(insertId!)`

**Comment by koskimas** [comment]
I fixed the getting started guide.
