### ISSUE TITLE
`sql` tag function should be available on the `Kysely` interface

### ISSUE THREAD

**Issue by alexgleason** [kysely-org/kysely#888]
I'm building a project where Kysely is only a devDependency. Functions accept `Kysely` instances, where `Kysely` is used only as a type.

But since `sql` is a separate import, I have to make Kysely a peerDependency to use it:

```ts
await sql`CREATE VIRTUAL TABLE nostr_fts USING fts5(event_id, content)`.execute(this.db);
```

What I want is the ability to do this:

```ts
await this.db.sql`CREATE VIRTUAL TABLE nostr_fts USING fts5(event_id, content)`.execute();
```

After a lot of digging this is the closest thing I've come up with... which I think works?? But is insane:

```ts
await this.db.executeQuery({
  sql: 'CREATE VIRTUAL TABLE nostr_fts USING fts5(event_id, content)',
  query: {
    kind: 'RawNode',
    sqlFragments: [],
    parameters: [],
  },
  parameters: [],
});
```

**Comment by koskimas** [comment]
We specifically removed `sql` from the Kysely instance to make it a free function.
