### ISSUE TITLE
Feature request in adding ExecuteTakeFirstOrThrow

### ISSUE THREAD

**Issue by shivan-eyespace** [kysely-org/kysely#890]
I have had a look through closed issues and wasn't able to find something like this.

So far we have `execute()`, `executeTakeFirst()` and `executeTakeFirstOrThrow()`. 

We are wondering if there is a take one and one only else throw if you SQL gets more than one row result.

This would be simliar to sqlalchemy's `.one()` (https://docs.sqlalchemy.org/en/20/core/connections.html#sqlalchemy.engine.Result.one) as opposed the `.first()` (and also `one_or_none()` - at most one result or no result else throw an error) methods.

**Comment by thelinuxlich** [comment]
I feel this is kind of feature creep

**Comment by koskimas** [comment]
> I feel this is kind of feature creep

Agreed.
