### ISSUE TITLE
Merging multiple queries 

### ISSUE THREAD

**Issue by HendrixString** [kysely-org/kysely#903]
Hi,

I wonder about the practice of the following dilemma : 

I have 2 compiled mutation queries and I want to use `db.executeQuery()` or the transaction variant `tx.executeQuery(..)`
on the two compiled queries at once. How do I do that with one invocation ?

**Comment by HendrixString** [comment]
@koskimas Any lead or tip would be very appreciated

**Comment by thelinuxlich** [comment]
The mysql driver has an option for that but it's bad practice.

**Comment by HendrixString** [comment]
bad practice to send multiple mutations in one go ?
I Never heard of such thing. This will be the only way to create mutation transactions in many databases

**Comment by thelinuxlich** [comment]
https://github.com/mysqljs/mysql#multiple-statement-queries

**Comment by HendrixString** [comment]
@thelinuxlich That's not what I meant.
I meant multiple mutation statements sent to the db at once, think like a batch write.

**Comment by thelinuxlich** [comment]
This is exactly about sending multiple statements at once, if you want a batch insert, Kysely supports it

**Comment by HendrixString** [comment]
@thelinuxlich How is it supported ?

**Comment by thelinuxlich** [comment]
You can insert an array of values

**Comment by thelinuxlich** [comment]
If it's not what you need, please provide an example.

**Comment by igalklebanov** [comment]
Hey 👋

Sending multiple SQL statements in the same request is considered a bad practice. Mostly because it opens you up for SQL injection. We don't support this pattern in Kysely core.

However, the community can definitely come up with an implementation.

I have shared a TS playground on discord in the past with a rough implementation for MySQL. Will look into generalizing it and publishing it as a separate library.

**Comment by HendrixString** [comment]
@thelinuxlich @igalklebanov  kysely is a query builder, so I should be able to create:
```sql
begin transaction
1. insert statement
2. delete statement
commit
```

I have compiled both statements already, and I will need to use it in a batch write.
This batch writes and deletes don't depend on interactive input, they are pure functions.
Why should I send a statement -> wait for something that i dont use and then send another statemment,
instead I can send everything in batch

**Comment by thelinuxlich** [comment]
Isn't that what happens inside a Kysely transaction?

**Comment by HendrixString** [comment]
@thelinuxlich Almost, in Kysely transaction, it executes each command. each execution might be a roundtrip
in the cloud. Which is problematic, because interactive transactions are discouraged because they are usually time bounded. On the other hand, pure batch mutations are excellent.

**Comment by igalklebanov** [comment]
Kysely being a query builder doesn't mean it has to support all possible queries with API methods. We provide escape hatches so you can still execute stuff that's not supported.

Have you tried `Promise.all`?

Have you tried `sql.join([query0, query1], ';').execute(trx)` ?

**Comment by HendrixString** [comment]
@igalklebanov I just asked what a good practice will be, I didn't ask features to be added because of my needs. God bless, I can program things, I just wanted an advise from the Kysely experts here.
I am leaning towards `sql.join([query0, query1], ';').execute(trx)`, I hope it will rewrite the parameters, will it ?

**Comment by HendrixString** [comment]
@igalklebanov Sababa, i will give it a go, thanks

**Comment by igalklebanov** [comment]
See last suggestion - https://kyse.link/1sFlF

**Comment by HendrixString** [comment]
@thelinuxlich @igalklebanov Thanks, I appreciate the help
