### ISSUE TITLE
Make mssql testable using apple silicon.

### ISSUE THREAD

**Issue by igalklebanov** [kysely-org/kysely#906]
Hey 👋 

The current docker setup doesn't seem to work on Apple silicon (e.g. M3 chips).

**Comment by MarkusWendorf** [comment]
I think you need to enable Rosetta emulation in Docker for this to work.

<img width="1256" alt="Screenshot 2024-03-12 at 15 01 03" src="https://github.com/kysely-org/kysely/assets/18446907/4209eea5-2817-4698-8865-3862ba94021d">

**Comment by igalklebanov** [comment]
Thanks!

They moved it to:

![image](https://github.com/kysely-org/kysely/assets/14938291/6789c366-88b7-4501-9f31-ecc6037b792e)

**Comment by koskimas** [comment]
@igalklebanov did you get a Mac? 😋

**Comment by igalklebanov** [comment]
Been using macs at work for a few years now. But only Intel chips. Now they gave me an M3. 🤓

**Comment by koskimas** [comment]
Welcome to the world of not-useless-battery-life!
