### ISSUE TITLE
Breaking change with addColumn between 0.27.2 and 0.27.3

### ISSUE THREAD

**Issue by ankane** [kysely-org/kysely#908]
Hi, thanks for this project.

Before 0.27.3, `addColumn` worked with [custom data types](https://www.postgresql.org/docs/current/sql-createtype.html) in Postgres.

```javascript
await db.schema.createTable('items').addColumn('embedding', 'vector(3)').execute();
```

However, this now throws:

```text
invalid column data type "vector(3)"
```

It looks like it's due to 3df726fd566664a1842d0fe8cfc0d79983647e39.

**Comment by igalklebanov** [comment]
Hey 👋 

Just like before, you have to use `sql` template tag if a data type is not available in the list.

```ts
import { sql } from "kysely";

await db.schema
  .createTable("items")
  .addColumn("embedding", sql`vector(3)`)
  .execute();
```
https://kyse.link/nwcuY

**Comment by ankane** [comment]
Thanks for the response. This was not the case before 0.27.3, but good to know.

**Comment by igalklebanov** [comment]
The API was designed to tell you NOT to do it the way you pasted.

![image](https://github.com/kysely-org/kysely/assets/14938291/74facdf4-31a2-48db-959c-5d8f6beaf718)
https://kyse.link/3e74S

**Comment by koskimas** [comment]
As @igalklebanov said, previously, if you ignored the type error and built the code anyway, it worked. Now there's also a runtime check. We don't consider that a breaking change as you shouldn't ignore typescript errors.
