### ISSUE TITLE
Mapping field names between database and object

### ISSUE THREAD

**Issue by philongvn99** [kysely-org/kysely#909]
Hello everyone, 
For some reason, the names of fields in the source code and my database are different. Is there anyway to map them as @map() in Prisma?
I have tried kysely-mapper but face an error about 'Kysely<Database> cannot be assigned to Kysely<unknow>', it come from a #private property of Kysely
If you have experienced any of the above problems, please help me.
Thanks

**Comment by igalklebanov** [comment]
Hey 👋 

This needs more info.
e.g. dependencies used, how you instantiate your Kysely instance, etc.

If it is related to prisma-kysely, you should ask there or on our discord.
