### ISSUE TITLE
Unable to create timetz with precision columns

### ISSUE THREAD

**Issue by dunkelbraun** [kysely-org/kysely#910]
When creating a `timetz(p)` column with the schema builder:

```ts
await db.schema
  .createTable("test")
  .addColumn("t", "timetz(4)")
  .execute();
```

`parseDataTypeExpression`throws an Error:  

> Error: invalid column data type "timetz(4)"
 ❯ Module.parseDataTypeExpression node_modules/kysely/dist/esm/parser/data-type-parser.js:14:11

**Comment by koskimas** [comment]
```ts
.addColumn("t", sql`timetz(4)`)
```

**Comment by koskimas** [comment]
Oh, that's actually a supported type. Needs fixing.

**Comment by dunkelbraun** [comment]
I forgot to mention that it was for the PostgreSQL dialect.
