### ISSUE TITLE
[BUG] Extraneous Attributes allowed on `insertInto` when using `.map` to generate an array of values

### ISSUE THREAD

**Issue by hughgardiner** [kysely-org/kysely#913]
I'm writing a migration script from Mongo to Postgres and I've really enjoyed using Kysely for it so far!

However, I discovered that when trying to do bulk inserts via `insertInto` where the input is generated using `.map` on an array, Kysely is unable to validate against the inferred type from the return value of the `.map` callback

[Playground Link](https://old.kyse.link/?p=b&i=haFkqHBvc3RncmVzoXamMC4yNy4yoXPaAaJpbXBvcnQgeyBHZW5lcmF0ZWQgfSBmcm9tICdreXNlbHknCgpkZWNsYXJlIGdsb2JhbCB7CiAgaW50ZXJmYWNlIERCIHsKICAgIHBlcnNvbjogUGVyc29uVGFibGUKICAgIHBldDogUGV0VGFibGUKICB9CgogIGludGVyZmFjZSBQZXJzb25UYWJsZSB7CiAgICBpZDogR2VuZXJhdGVkPHN0cmluZz4KICAgIGZpcnN0X25hbWU6IHN0cmluZwogICAgbGFzdF9uYW1lOiBzdHJpbmcgfCBudWxsCiAgICBjcmVhdGVkX2F0OiBHZW5lcmF0ZWQ8RGF0ZT4KICAgIGFnZTogbnVtYmVyCiAgfQoKICBpbnRlcmZhY2UgUGV0VGFibGUgewogICAgaWQ6IEdlbmVyYXRlZDxzdHJpbmc-CiAgICBuYW1lOiBzdHJpbmcKICAgIG93bmVyX2lkOiBzdHJpbmcKICAgIHNwZWNpZXM6ICdjYXQnIHwgJ2RvZycKICAgIGlzX2Zhdm9yaXRlOiBib29sZWFuCiAgfQp9oXHaArVjb25zdCBwZW9wbGUgPSBbewogIGZpcnN0TmFtZTogJ0plbm5pZmVyJywKICBsYXN0TmFtZTogJ0FuaXN0b24nLAogIGlEb250OiAnZXhpc3QnLAp9XQoKLy8gVFMgSW5mZXJyZWQgVHlwZQovLyAgIGNvbnN0IHBlb3BsZU1hcE5vRXJyb3I6IHsKLy8gICAgIGZpcnN0X25hbWU6IHN0cmluZzsKLy8gICAgIGlfZG9udDogc3RyaW5nOwovLyAgICAgbGFzdF9uYW1lOiBzdHJpbmc7Ci8vICAgICBhZ2U6IG51bWJlcjsKLy8gfVtdCmNvbnN0IHBlb3BsZU1hcE5vRXJyb3IgPSBwZW9wbGUubWFwKChwZXJzb24pID0-IHsKICByZXR1cm4gewogICAgZmlyc3RfbmFtZTogcGVyc29uLmZpcnN0TmFtZSwKICAgIGlfZG9udDogcGVyc29uLmlEb250LAogICAgbGFzdF9uYW1lOiBwZXJzb24ubGFzdE5hbWUsCiAgICBhZ2U6IDEKICB9Cn0pOwoKYXdhaXQgZGIKICAuaW5zZXJ0SW50bygncGVyc29uJykKICAudmFsdWVzKHBlb3BsZU1hcE5vRXJyb3IpIC8vIG5vIHRzIGVycm9yCiAgLmV4ZWN1dGUoKQoKYXdhaXQgZGIKICAuaW5zZXJ0SW50bygncGVyc29uJykKICAudmFsdWVzKFt7CiAgICBmaXJzdF9uYW1lOiBwZW9wbGVbMF0uZmlyc3ROYW1lLAogICAgbGFzdF9uYW1lOiBwZW9wbGVbMF0ubGFzdE5hbWUsCiAgICBhZ2U6IDEsCiAgICBpX2RvbnQ6IHBlb3BsZVswXS5pRG9udCAvLyB0cyBlcnJvcgogIH1dKQogIC5leGVjdXRlKCmhY8I=)

**Comment by koskimas** [comment]
Yep, nothing we can do about this.
