### ISSUE TITLE
UNION expression select column type can still be interpereted null despite IS NOT NULL WHERE statement

### ISSUE THREAD

**Issue by codygordon** [kysely-org/kysely#915]
Take this expression builder example:

```
` eb(
        'folderId',
        'in',
        eb
          .selectFrom('folder')
          .select(['id'])          
          .union(
            eb
              .selectFrom('contentPermission')
              .select(['folderId as id'])
              .where('contentPermission.folderId', 'is not', null)
          ),
      )
```

The `contentPermission` table definition has `folderId` as a nullable column, so TS is throwing an string as the `folderId` type does not exactly match the "parent" query `id` column type (not nullable), however I know the union result would never result in any null values due to the where statement. 

<img width="744" alt="Screen Shot 2024-03-17 at 3 32 06 PM" src="https://github.com/kysely-org/kysely/assets/13374656/9c836d16-9847-46b4-9bbf-539e9ba26d84">.     

In lieu of a fix, is there a recommended workaround for this situation?

**Comment by koskimas** [comment]
This has been answered many times. It's impossible to fix this for anything other than trivial cases, but fixing it would complicate the types a lot and basically make the library unusable. The query builder type would be changed by `where` calls, making reassignment to the same variable often impossible. All that just to fix trivial on-condition expressions. As soon as there's a more complex where statement, it wouldn't be possible anymore.

**Comment by koskimas** [comment]
I just added an example for dealing with these cases

https://kysely.dev/docs/examples/SELECT/not-null

**Comment by codygordon** [comment]
Thank you, appreciate the response!
