### ISSUE TITLE
Type errors with sql RawBuilder arbitrary where statements after updating to 0.27

### ISSUE THREAD

**Issue by codygordon** [kysely-org/kysely#920]
Passing a full arbitrary raw `sql` statement into a `where`, which had been working fine, seems to be raising a type error for me now after updating to 0.27.  

```
Argument of type 'RawBuilder<unknown>' is not assignable to parameter 
of type 'ExpressionOrFactory<DB, "myTableName", SqlBool>'
```

My use-case is a tsquery statement like this (but I get the error attempting the simple `between` [example from the docs](https://kysely-org.github.io/kysely-apidoc/functions/sql-1.html#sql) as well): 
```
where(sql`search_terms @@ to_tsquery('simple', ${searchText})`)
```

Passing `sql<undefined>` type seems to clear the error – but is this intended?

**Comment by koskimas** [comment]
Use

```ts
sql<bool>`whatever`
```

for boolean expressions.

**Comment by codygordon** [comment]
Thanks! Just noting the docs should probably be updated with this new requirement.

**Comment by koskimas** [comment]
> Thanks! Just noting the docs should probably be updated with this new requirement.

Done.

**Comment by chadselph** [comment]
There `where` statements in these docs https://kysely-org.github.io/kysely-apidoc/interfaces/Sql.html#ref don't have the type parameter and as far as I can tell don't work, should they be updated too?
