### ISSUE TITLE
support for functions in selectFrom, e.g. GENERATE_SERIES

### ISSUE THREAD

**Issue by mattkrick** [kysely-org/kysely#931]
Love this project! Thanks for all your work on it.
I wanted to see if there's any interest in supporting functions in `selectFrom`.

Here's my example query:

```sql
SELECT
  NEXTVAL('"mySequence"')
FROM
  GENERATE_SERIES(1, 1000) 
```

To achieve that today, the closest I could get without pulling too many escape hatches is

```ts
db.selectFrom(sql.raw('generate_series(1,1000)'))
.select((pg) => pg.fn<number>('NEXTVAL', [sql.lit('"mySequence"')]).as('seqId'))
.execute()
```

ideally, it'd be nice to get the function params outside of the raw sql:

```ts
// error! doesn't work
db.selectFrom((eb) => eb.fn('generate_series', [1,1000]))
```

What do you think? If this is possible today, please let me know!

**Comment by koskimas** [comment]
Already supported.
