### ISSUE TITLE
ColumnDefinitionBuilder.ifNotExists() not yet available

### ISSUE THREAD

**Issue by qvanderlinden** [kysely-org/kysely#945]
Hi there,

In the `ColumnDefinitionBuilder` [docs](https://kysely-org.github.io/kysely-apidoc/classes/ColumnDefinitionBuilder.html#ifNotExists), there is mention of the `ifNotExists` method. Unfortunately, it's not available in version 0.27.3 yet, when can we expect a new release with this functionality (that I'm very eager to use !!!) ?

Cheers,
Quentin

**Comment by igalklebanov** [comment]
Hey 👋 

We don't have a roadmap. When we decide to cut a release. You can install directly from kysely's `master` branch for now.

**Comment by koskimas** [comment]
The method shouldn't be in the docs yet though. I'll fix that.
