### ISSUE TITLE
`as` required in subquery although it does not add to type-safety

### ISSUE THREAD

**Issue by twiddler** [kysely-org/kysely#947]
The subqueries in [this playground](https://kyse.link/#cN4IgpgJglgLg9gJwM4gFyhgTwA5jSKAW20RgAJgyBxMAOzAQEMZIyBfMgMwTkLIB0QAa0xIwAG0yCA3P1pywADxIJyUWiwSdGAYzBkAIs0YAjRmIpyyZXMji1UZAAoMk9gCqnxYWbWu4YRxcYTxNvXzY5BWVSMnVNbT1nVw8vfWArOIhHGnomFggAHloAV0ITBgA+CKj6GNU4jQZE-WDQ70s-LJy6BmZIYrKKhGrMuAB3PIB9KGyyUvKGGtoQABoQAEcShkx8HXskch5xpDIAXjJGccZYMggTTIA6MW8dGAAxHkIACkFbN3kIAAlE8XmA3t9vmATEDzpUyABtTLWaHI6xkZ4ScEfL6-EABQQgrrojFgiFQkwAJlhZ3h0Mpj04tEe+xKGgAguJxN8gY9zHipoTYQB6YVkLC4U7YcynABkZHGiCESFWZBMJTUMAA5BA1fpaFAkvAyN5GAA3fRwDVkAAG-MEguBNrR1ke4wAFgwwHiAo8JtNZoJVYIzkGyNDHggwJwfSlmYHgUSSa77SBOHA4ITVrUSajiejMa8cbxYzBCS7SVjyfSaXSqYzmayOVyeXykHihWRReKcGApTLVeryDB3VBTqaIKdjQg2TAiPoGDxkI0yIRMGR9hAwBW3Z6o6W-ZMGDMIGGQ2GI1GY38448E0Ck8m23izAgszn0Xnk5Wi58Szey2BHcyRgSEazhcN6yZFkrWbbkHy7MUJT7O57C1chpSQFVLnEEcrQAc3dOJtVOJASk4ThDSgOhyHTBAe0lS5aF1CA4BQ2g4HIHRGBKCwZw0edwwQJckB3D0vQPf1jwTYMQFDNZIMjaNYzseNT0THdUzMAAvd8ugAXUfR4lHBDVvSBXwQDYdZoEYIt8DXJANnENZhFECRdnQEBkPwGBGHw1zaEYQg8FQEAAAZHkpAB2R4AGYrLYIA) should not require `as` in their `SELECT` statements, since it does not add to type-safety and is not required by MySQL.

```ts
const rows = await db
  .selectFrom("person")
  .select((eb) => [
    eb
      .selectFrom("pet")
      .select((eb2) => eb2.fn.countAll().as("_")) // types pass & works, but it'd be nice to leave out `as("_")`
      .where("pet.owner_id", "=", eb.ref("person.id"))
      .as("foo"),

    eb
      .selectFrom("pet")
      .select((eb2) => eb2.fn.countAll().as("")) // types pass, but this leads to runtime errors in my code
      .where("pet.owner_id", "=", eb.ref("person.id"))
      .as("bar"),

    eb
      .selectFrom("pet")
      .select((eb2) => eb2.fn.countAll()) // types don't pass, although it's sufficient for types and does not cause runtime errors
      .where("pet.owner_id", "=", eb.ref("person.id"))
      .as("baz"),
  ])
  .execute();
```

```ts
import { Generated } from "kysely";

export interface Database {
  person: PersonTable;
  pet: PetTable;
}

export interface PersonTable {
  id: Generated<number>;
}

export interface PetTable {
  id: Generated<number>;
  owner_id: number;
}
```

**Comment by igalklebanov** [comment]
Hey 👋 

How would you know, across multiple underlying drivers what the name of these result columns would be?

**Comment by twiddler** [comment]
In this case, it's a MySQL scalar. I don't know about how other databases handle it, so I can't answer your question.

This is really more in the "nice to have" category of things, so if there's no clear path to a solution then please close this issue and save the energy for more important stuff. :pray:

**Comment by igalklebanov** [comment]
It would require duplicating `SelectQueryBuilder` with a more lax API. And there's complexity in finding out if we're in this very specific case or not to return it or return the regular builder.

Not worth it.
