### ISSUE TITLE
Is it possible to tell from an onDuplicateKeyUpdate whether it was created or updated?

### ISSUE THREAD

**Issue by OultimoCoder** [kysely-org/kysely#950]
I am trying to minimise database queries in my application so would love the benefits of using onDuplicateKeyUpdate but its also important for me to know whether it was created or inserted. Is that possible at all?

**Comment by igalklebanov** [comment]
Hey 👋

> For INSERT ... ON DUPLICATE KEY UPDATE statements, the affected-rows value per row is 1 if the row is inserted as a new row, 2 if an existing row is updated, and 0 if an existing row is set to its current values.
https://dev.mysql.com/doc/c-api/8.3/en/mysql-affected-rows.html

> numInsertedOrUpdatedRows holds the number of (actually) inserted rows. On MySQL, updated rows are counted twice when using on duplicate key update.
https://kysely-org.github.io/kysely-apidoc/classes/InsertResult.html
