### ISSUE TITLE
Update to set boolean value to opposite value

### ISSUE THREAD

**Issue by randomGitBeing132** [kysely-org/kysely#951]
Hi, i have a boolean value isEnabled and I would like to set it to the opposite value in my update statement 

```
UPDATE table
SET is_enabled = ~is_enabled
WHERE table_id = 1
```
How do i translate this to kysely syntax? 

Thank you

**Comment by igalklebanov** [comment]
Hey 👋 

Use the `NOT` keyword.

```ts
await db
  .updateTable('table')
  .set('is_enabled', (eb) => eb.not('is_enabled'))
  .where('table_id', '=', 1)
  .execute();
```

**Comment by randomGitBeing132** [comment]
Thank you for the help, but i got this error upon using it

Error: Incorrect syntax near the keyword \'not\'.\n at RequestTokenHandler.onErrorMessage

**Comment by igalklebanov** [comment]
What dialect are you using?

**Comment by randomGitBeing132** [comment]
> What dialect are you using?

MSSQL

**Comment by igalklebanov** [comment]
There is currently no built-in support for `~` unary operator.

For now, this is the most type-safe way of doing it:

```ts
import { SqlBool, sql } from "kysely";

await db
  .updateTable("table")
  .set("is_enabled", (eb) => sql<SqlBool>`~${eb.ref("is_enabled")}`)
  .where("table_id", "=", 1)
  .execute()
```

**Comment by igalklebanov** [comment]
@randomGitBeing132 see updated answer.
