### ISSUE TITLE
ColumnType is not extracted for array data type

### ISSUE THREAD

**Issue by pavestru** [kysely-org/kysely#957]
I have used [kysely-codegen](https://github.com/RobinBlomberg/kysely-codegen) to generate the DB model. However, select statements do not return correct TS type corresponding to `int8[]` data type.

## Simplified example

[TYPESCRIPT PLAYGROUND LINK](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgaQJ4GcCmAbVAaOAYQmwFcQA7AFVTEzgF84AzKCEOAcgGsMdVOAWABQIgPQAqCSLgSiECumAATTFDgAjHBADucGAAt6AEQBCcEBFXY4Ac0wU1AQxiZlLNh0PB0cAMoAigAy+k4a2PQaqHC8WLgAtADGVpj2FABcMnIABrnoAI7YWUQASgCiAIJUZXBUFaZBNejsmAD6MGERcAAUzSBtyWSUcMAUMAAcANoAugCUANzFudlZYiLicn51JVRwEMxwZhYpNhJrwjC09ACSY+NwALzyQ9RXADzoMFCjtgSf3xRbHAAD5wCjkLTqUEaYC2UYwP5fH4gsEQtQomFwsYAPnWwkwAA9ILARmM1MwnIl6H4WlROvQEDI4H0BiRyBk4LcJjMRAw8YTifB4eTKSZzIzhHApcyWu16el-LT6byNnAygA5Yx7A5HSzWWTnEROdCoCiJFikM0wYAKOyYGA0-rGFxObrKDQKtBxVBvMzY2aIJlS5KKeBQTDoUjYeBPJw6JzAeDuoPSqUAOjimESMAAYp5upwWXLwphOLMU6mMzgszAC0XBuyyxXpWnCVnSK5uuXRJLpWIxLUjHABTW3HBwzBSFAKPortq4Nlw5Ho5MAAzTDOyhuUbLMgwQKPuLTMpGAmYEDQdkYwQucu483tSidTmdLqMwRbCPnCIA)

Consider the following schema (postgresql)
```sql
CREATE TABLE some_table (some_column int8[]);
```

Given that this is the only table, the DB model generated by [kysely-codegen](https://github.com/RobinBlomberg/kysely-codegen) would look like this (without any kysely-codegen customization):

```typescript
type Int8 = ColumnType<string, string | number | bigint, string | number | bigint>

export interface SomeTable {
  some_column: Int8[]
}

export interface DB {
    some_table: SomeTable
}
```

Now, we have a function selecting the array:

```typescript
async function getSomeData(db: Kysely<DB>) {
    const result = await db
        .selectFrom('some_table')
        .select('some_column')
        .execute()

    return result;
}
```

## Expected return type

Expected type returned by the query for column `some_column` should be  `string[]`.

Rationale: `some_column` is array of `Int8`. Type `Int8` is defined using `ColumnType`, where the first generic parameter (for SELECT) is defined as `string`. That means that the returned type for `some_column` should be `string[]`.

## Actual return type

However, the select query returns type `Int8[]` for `some_column`, because there is no support for array of `ColumnType`. In other words, ColumnType does not get "unwrapped" for array data type.

[TYPESCRIPT PLAYGROUND LINK](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgaQJ4GcCmAbVAaOAYQmwFcQA7AFVTEzgF84AzKCEOAcgGsMdVOAWABQIgPQAqCSLgSiECumAATTFDgAjHBADucGAAt6AEQBCcEBFXY4Ac0wU1AQxiZlLNh0PB0cAMoAigAy+k4a2PQaqHC8WLgAtADGVpj2FABcMnIABrnoAI7YWUQASgCiAIJUZXBUFaZBNejsmAD6MGERcAAUzSBtyWSUcMAUMAAcANoAugCUANzFudlZYiLicn51JVRwEMxwZhYpNhJrwjC09ACSY+NwALzyQ9RXADzoMFCjtgSf3xRbHAAD5wCjkLTqUEaYC2UYwP5fH4gsEQtQomFwsYAPnWwkwAA9ILARmM1MwnIl6H4WlROvQEDI4H0BiRyBk4LcJjMRAw8YTifB4eTKSZzIzhHApcyWu16el-LT6byNnAygA5Yx7A5HSzWWTnEROdCoCiJFikM0wYAKOyYGA0-rGFxObrKDQKtBxVBvMzY2aIJlS5KKeBQTDoUjYeBPJw6JzAeDuoPSqUAOjimESMAAYp5upwWXLwphOLMU6mMzgszAC0XBuyyxXpWnCVnSK5uuXRJLpWIxLUjHABTW3HBwzBSFAKPortq4Nlw5Ho5MAAzTDOyhuUbLMgwQKPuLTMpGAmYEDQdkYwQucu483tSidTmdLqMwRbCPnCIA)

**Comment by igalklebanov** [comment]
Hey 👋

We do not have conttol over `kysely-codegen`.

The column type should be `ColumnType<Int8[], ..., ...>` and not `ColumnType<...>[]`.
