### ISSUE TITLE
[FEATURE REQUEST] enum tables

### ISSUE THREAD

**Issue by carlpaten** [kysely-org/kysely#963]
Coming from a Hasura background, I'm used to being able to define [enum tables](https://hasura.io/docs/latest/schema/postgres/enums/#enums-in-the-hasura-graphql-engine).

An enum table is a table whose rows are understood to represent values in an enum type. Example:

- I have a table `color` with three rows having primary key `"red"`, `"green"` and `"blue"`.
- I have a table `teacup` whose row `color` has a foreign key to the table `color`.
- I set an "enum table" flag for the `color` table somewhere (maybe in `kysely-codegen` config).

Then I'd like Kysely to recognize that `db.selectFrom("teacup").select("color")` has type `("red" | "green" | "blue")[]`.

This is the single feature I find myself missing from Hasura.

**Comment by koskimas** [comment]
Kysely doesn't detect anything. It only operates on the types you provide it. Just provide the correct type for that column in your table interface and it already works. If you're using some type generator, note that they are all third party libraries and we don't maintain or develop them. We have no control over their features.
