### ISSUE TITLE
How to define a custom plugin using the FunctionNode?

### ISSUE THREAD

**Issue by QuentinJanuel** [kysely-org/kysely#967]
Hello!

I was writing a custom plugin and needed to import among other nodes the `FunctionNode` but I realized it was not exported. Should it be exported or am I doing something unintended? I know all nodes are marked as internal, but I see no other way to define a custom plugin and the `OperationNodeTransformer` I use isn't marked as internal while still exposing the nodes so I'm not sure.

Thank you for the excellent project by the way!

**Comment by igalklebanov** [comment]
Hey 👋 

It appears we forgot to add it to the exports. I've opened a PR that takes care of that.
