### ISSUE TITLE
what is the migration_lock ??

### ISSUE THREAD

**Issue by ikaaasra** [kysely-org/kysely#973]
what is the migration_lock ?? why we have this in the database

**Comment by koskimas** [comment]
Nice!

**Comment by koskimas** [comment]
`migration_lock` is a table that can be used by third party dialects to lock the migration table to prevent concurrent processes running migrations from interfering with each other. Not all database engines have global, or table locks. The `migration_lock` table has a single row that can be used as a lock if needed.
