### ISSUE TITLE
Invalid object name upon inserting value into temp table in mssql

### ISSUE THREAD

**Issue by benedictngjh96** [kysely-org/kysely#974]
Hi, i am using mssql and encountering this error upon inserting value into the temp table.
I am using the camel case plugin as well.

`RequestError: Invalid object name '#_temp'.`

[playground](https://kyse.link/#cN4IgpgJglgLg9gJwM4gFyhgTwA5jSEAGhAEcBXMBTfAQwHcbYACCAIwDokBjACzAFsaAHQB2TJuy4IwNGGAAqNVgBswACiEgAxPIHZNASlHj2NCBADCcZWX4iNIKBE2EmmqCLkBzSi6ZquawMmAF4APiZA5XZsBChBKgBpMEw1AyMxCTNLa1t7TREafjA-TQA3GgReSrUANgAWIyJ-KODwyOt2ETgYADkyZWU0jJMwAA8wLjI5NIBuUVF6RhgWVmMJOlgeRRUwJAAeYDdtXX59NCYjp1QmEVtWSlnborAbpBg4kS8mAF9fsLS63YHiQlBgAElPHAHDo9IYgRUbHs1FcIDcAIyuQrFG6aOTvZ7FTS-EYScaTabqAzzEQgH7EaA0VRcGD4fhIJAkZREEAAa0woOU1HQICwuHwMBoXh52LwqBAAAZ2AAmADs7AAzHSfkA)

**Comment by koskimas** [comment]
Works as expected. The table name is converted from camelCase to snake_case.

**Comment by benedictngjh96** [comment]
Yes it converts the name but how do i deal with the error?

**Comment by koskimas** [comment]
The error is caused by the invalid name that you specifically asked Kysely to use. Don't use the invalid name. See the docs here on how to implement custom snake_case --> camelCase and camelCase --> snake_case conversions https://kysely-org.github.io/kysely-apidoc/classes/CamelCasePlugin.html

**Comment by juniorUsca** [comment]
Is there something that applies only to one query and not to all?
