### ISSUE TITLE
where with sql complains about Property 'isSelectQueryBuilder' is missing 

### ISSUE THREAD

**Issue by unilynx** [kysely-org/kysely#982]
I'm running into problems with `where` & `sql` in v0.27.2 when using: ``.where('id', '=', sql`any(${['1', '2', '3']})`)`` - a syntax that worked with v0.23.5:

"Argument of type 'RawBuilder<unknown>' is not assignable to parameter of type 'ExpressionOrFactory<DB, "person", SqlBool>'.
  Property 'isSelectQueryBuilder' is missing in type 'RawBuilder<unknown>' but required in type 'SelectQueryBuilderExpression<Record<string, SqlBool>>'.(2345)

I've taking this example https://kysely-org.github.io/kysely-apidoc/interfaces/Sql.html and as far as I can tell it will now generate the same error: https://old.kyse.link/?p=s&i=IRUTxKuKdZwxKHs8snN8

Is this a Kysely issue or is the example outdated ?

**Comment by igalklebanov** [comment]
Hey 👋 

This is a documented change. You should add `<SqlBool>`.

```ts
import { SqlBool } from 'Kysely'

// ...

.where(sql<SqlBool>`birthdate between ${date1} and ${date2}`)
```
https://old.kyse.link/?p=s&i=m1mbEmpAtm7Gpgyvf1EE

Also note, we have built-in support for `between` now in `ExpressionBuilder`:

```ts
.where((eb) => eb.between('birthdate', date1, date2))
```
https://old.kyse.link/?p=s&i=rigM1aWB3lgbPBQeXQ23
