### ISSUE TITLE
Documentation for UpdateResult

### ISSUE THREAD

**Issue by mjomble** [kysely-org/kysely#988]
[InsertResult](https://github.com/kysely-org/kysely/blob/master/src/query-builder/insert-result.ts) is very well documented, with the nuances of different dialects clearly described 👍

[UpdateResult](https://github.com/kysely-org/kysely/blob/deea8e22aae3dc4e142f055b6ec4d9a50a402bda/src/query-builder/update-result.ts), however, contains only two similarly named fields (numUpdatedRows and numChangedRows) with zero comments, which can lead to some confusion 😄

It would be nice to have similarly detailed comments in both. Unfortunately, I don't have enough information to properly document this myself in a PR. I found some info [in this issue](https://github.com/kysely-org/kysely/issues/428), but I suspect there's more to it.

Maybe @wirekang, @igalklebanov or @koskimas would be up for it? Or you could post the necessary information in this thread, which I could then prepare into a PR.

**Comment by wirekang** [comment]
Comments on `QueryResult` will be enough information to make a PR. Good luck.
https://github.com/kysely-org/kysely/blob/deea8e22aae3dc4e142f055b6ec4d9a50a402bda/src/driver/database-connection.ts#L23-L35
