### ISSUE TITLE
OnConflict update all Fields

### ISSUE THREAD

**Issue by ctaity-treinta** [kysely-org/kysely#989]
Hi, i would like to kown if exists a way to do something like this:
```
const result = await db
  .insertInto('person')
  .values({
    first_name: 'Jennifer',
    last_name: 'Aniston',
    age: 40
  })
  .onConflict( (oc) => {
    oc.column("id").doMerge()
  }).execute()
```

and in doMerge, add all table fields, like doing an upsert, like knex merge, without need specify each field?

**Comment by koskimas** [comment]
`on conflict do merge` is not valid SQL.

**Comment by AlexErrant** [comment]
You might find this interesting/useful, where I add a type `OnConflictUpdateCardSet` so I get a type error if I add and don't handle a column.

**Comment by ctaity-treinta** [comment]
I think would be very useful have the columns to update all columns of the table, is a  use case vert common.

**Comment by AlexErrant** [comment]
You can't update a PK, and kysely doesn't know what the PK is. There's no general solution for this so you'll need to write it yourself. Also, you probably won't want to update a `createdAt` column.

**Comment by ctaity-treinta** [comment]
but if i sent to insert { a, b, c ,d } and the conflict is on field a, you could merge b, c, d, you have a point with  createdAt, also createdAt and updateAt columns usually are implement as default values.

**Comment by AlexErrant** [comment]
Let me emphasize: _kysely doesn't know what the PK is_.

> and the conflict is on field a

That error occurs at _runtime_, which is _not_ kysely's domain.
