### ISSUE TITLE
Question about a generic getById

### ISSUE THREAD

**Issue by Guid75** [kysely-org/kysely#995]
Brand new user of this fantastic library, I'm searching a way to write a generic function to handle the getById classic usecase, here is my naive approach:

```typescript
import { Kysely, Selectable } from "kysely";

export type FooTable = {
  id: string;
  name: string;
  fromFoo: boolean;
};

export type BarTable = {
  id: string;
  name: string;
  fromBar: string;
}

type Tables = {
  foo: FooTable;
  bar: BarTable;
};


export async function getById<TableName extends keyof Tables>(
  dataSource: Kysely<Tables>,
  tableName: TableName,
  id: string
) {
  const query = dataSource
    .selectFrom(tableName)
    .selectAll()
    .where("id", "=", id);

  return await query.execute();
}
```

[Here is the playground link](https://www.typescriptlang.org/play/?#code/JYWwDg9gTgLgBAbzgaQJ4GcCmAbVAaOAZR0wGMYBDAI20zgF84AzKCEOAIgGsMdUOA3ACghmAB6RYcGKjB0AYhAgAVarTgBeRELhxgAEwBccdDCjAAdgHNhuixRCZjp89dvNWIRRGNUltCgthemFRCWh4GTk4ACEKKFUaOi0EHT0jEzNLGzT7R2cstzSWNjioAtcc+hEoukTadE1tXSYlY296zHcqeOMyzuDQsMl4CnRUC1JmAFdJmGAICzgrTBgY1ABJfQAeToA5BzpxGEwLfUauTFQIJjhO9AA+AAo0-QpKQghpqFInFF5cLs1JhHng0pQkgd8ndgVDMGDdAYKtkhABKZpwUiLUxwACO00wUFQTTeHy+P0waV0ADosLRyPJPE8IbQ4aiqXBaSRyABBbDYJ7s3Q0gDuAAtCZgnhwDBwCBwNHL0qjQrooKtvksKCKKMB4PjCahqeIyNMToLgkIgA)

I don't really get why I cannot pass the id parameter into the where clause :(
What did I miss?

**Comment by koskimas** [comment]
Works if you [simplify it](https://www.typescriptlang.org/play/?ts=5.2.2#code/JYWwDg9gTgLgBAbzgaQJ4GcCmAbVcC+cAZlBCHAEQDWGOqFA3AFBOYAekscMqYmcAMQgQAKgEMARtn4BeREzhxgAEwBccdDCjAAdgHNminWJCZ1m7fsPFSIIRHUTh0sTub5mrDtHg8+cACExKHEpWXlFFXMtXQMFOGNTaMs4xRIyIKhk2PcWP35Q6XQ4OQR4omF1e0LMawlg9Uya9092TngxdFQdAGNiAFdemGAIHTg9TBgA1ABJZQAKeOUxGDEAZQh+qB6zFFpcAB4a9AA+ABp41bCAORNdqkxUCCI4Y4vItQ0Y-SYASgi4D1Rpo4ABHfqYKB4OTLVYbLY7eKKAB0WGkPRgAls8yu0lupl+SLgqJwmAxAEFsNh5oTFCiAO4AC0hmHmFBUFDOlBknKUyl+nkUUEmWzGYnpYmA8HBkNQyPYZP6MFZAqY+CYQA)

But in general you shouldn't try to write generic code like this with Kysely. Kysely's types are extremely strict and it's hard to combine strict and generic.

**Comment by Guid75** [comment]
Ok, thank you very much, I can live with some little repetitions
