### ISSUE TITLE
May anyone help me with the short version of selectAll type?

### ISSUE THREAD

**Issue by iceleo-com** [kysely-org/kysely#997]
I'm writing the function "findMany" in a Abstract Class. But the final result type seem to be mismatch.
I tried tracing the type, but no luck. May anyone take a look and give me some advice? I appreciate everything!

![ksnip_20240521-192931](https://github.com/kysely-org/kysely/assets/15703671/904b0fb0-6cdb-4a0e-9dcc-40ddd2628b43)

**Comment by koskimas** [comment]
There is no short version. If there were, we'd use it.

You should avoid trying to create generic helpers like this. Super strict (Kysely) and generic don't work well together.
