### ISSUE TITLE
`SELECT` in SQL template tag has parens around it, making it invalid in some contexts in SQLite

### ISSUE THREAD

**Issue by AlexErrant** [kysely-org/kysely#999]
Hi, I'm trying to convert this to kysley:

```sql
INSERT INTO "cardTag"
SELECT
  KEY AS cardId,
  value AS tag
FROM json_tree(blah)
EXCEPT
  SELECT *
  FROM "cardTag"
  WHERE "cardId" IN (?, ?, ?)
```

It uses the sqlite specific [`json_tree`](https://www.sqlite.org/json1.html#jtree), a table-valued function, so I elect to use a SQL template string:

```ts
await db
  .insertInto('cardTag')
  .expression(
    (qb) => sql<CardTag>`
SELECT key   AS cardId,
       value AS tag
FROM json_tree(blah)
EXCEPT
${qb.selectFrom('cardTag').selectAll().where('cardId', 'in', cardIds)}`, // the problem is here
  )
  .execute()
```

Unfortunately, the injected `select` statement has parens around it, which makes it invalid in sqlite (as noted [here](https://github.com/kysely-org/kysely/issues/285#issuecomment-1631890614)):

```sql
INSERT INTO "cardTag"
SELECT
  KEY AS cardId,
  value AS tag
FROM json_tree(blah)
EXCEPT
( --this parens breaks sqlite
  SELECT *
  FROM "cardTag"
  WHERE "cardId" IN (?, ?, ?)
)  --this paren breaks sqlite
```

I tried to work around this by parameterizing just `cardIds`, the array, but it doesn't handle the array of ids properly:

```sql
await db
  .insertInto('cardTag')
  .expression(
    (qb) => sql<CardTag>`
SELECT key   AS cardId,
       value AS tag
FROM json_tree(blah)
EXCEPT
SELECT * FROM cardTag where cardId in ${cardIds}`,
  )
  .execute()
```
```sql
INSERT INTO "cardTag"
SELECT
  KEY AS cardId,
  value AS tag
FROM json_tree(blah)
EXCEPT
SELECT *
FROM cardTag
WHERE cardId IN ? -- not correct
```

How can I fix this? Here's [the playground](https://kyse.link/#cN4IgpgJglgLg9gJwM4gFyhgTwA5jeAD20RgAIoA7GMBAMwEMBjMUgEXpnoCN6kXgAOhVKlG9BBAAq9AOapSAYXFTZAbiEBfIULBES5KjQbNFy6TNKDhpBHADuUCPIoBXALZca665zmkkMAiUMt4iYhIAkk7+gcHeWhQgADQgAI4uNJj4UG7ECGTA-qkANqQapLS2bqQCIADWmHzFmLXeOXkFphLmZRVVNSBYuAC0kLCIrdoUxWBk4RBRSKQAvKQA2rVwFGC1SQMwdnC7+wAWCGA7IAC63kL0dvSwpBBcQiIAdJR8+RFUcAAUtXm5lqAEo3qR3rpsOckEgoFtAdYRP9UlxQSsAHxFYoAHiU3VkmIABkIAMoAUQAMhSFJJSHUwJgRKQAIJk0TKKJJCEskQAN3oxQybI5viEADEAEoAeQAsqQAFZILYAfUCF3+XGK9BO4IoAHUABIUqUU0hDFirADk1AIMGtQgpAA0FBSAAqSIQAEmAaPeTTAjBgEqqgJAwNkYIDYBmwdZxWK-1B7zsJxoYHD8yix1qlGO2YgSFBGmJPOs+o+uiDLmoyduFHujzILwhnwo3xgv3gWbMUZAlch0Nh8MRvNIqPRWJx+L7MhJ5OptPpjOZInZnMiEHLfJZguFLA34oo0vlSpVFHV50z2t1+uNpvNlpWpFtugdTtdHq9FEpNLppAAFSkKeCqRhYaYZpuCwQAYpC+oWSCljupCDlCBA1nWoLeCAGgpNAQpBjA+BICUsB4CkDRNFk6CDDgeCoIMsjJCAjZuAxIAAAzvAATAA7O8ADMuEaEAA). Thanks!

**Comment by alenap93** [comment]
i think that we have to override visitSelectQuery in sqlite query compiler, removing wrapInParens ... https://github.com/kysely-org/kysely/blob/deea8e22aae3dc4e142f055b6ec4d9a50a402bda/src/query-compiler/default-query-compiler.ts#L143-L150

**Comment by AlexErrant** [comment]
After rubbing some braincells together I realized I could fix my workaround using [`sql.join`](https://kysely-org.github.io/kysely-apidoc/interfaces/Sql.html#join):

```ts
await db
  .insertInto('cardTag')
  .expression(
    (qb) => sql<CardTag>`
SELECT key   AS cardId,
       value AS tag
FROM json_tree(blah)
EXCEPT
SELECT * FROM cardTag where cardId in (${sql.join(cardIds)})`, // duh
  )
  .execute()
```

Gonna leave this issue open though because it's still a workaround.

**Comment by koskimas** [comment]
You can build the whole query without any raw SQL https://kyse.link/w9kuZ
